### ISSUE TITLE
Add custom allure test attributes for Xunit in .Net 

### ISSUE THREAD

**Issue by dnbr2002** [allure-framework/allure2#1001]
**Is your feature request related to a problem? Please describe.**
When viewing the [docs](https://docs.qameta.io/allure/#__net), it appears there are options in NUnit that do not exist with Xunit for .NET.  Specifically the NUnit.Allure package allows for lots of attributes on the tests so you customize your reports quite a bit.  Things like
``` 
    [AllureTag("Regression")]
    [AllureSeverity(SeverityLevel.critical)]
    [AllureIssue("ISSUE-1")]
    [AllureTms("TMS-12")]
    [AllureOwner("User")]
    [AllureSuite("PassedSuite")]
    [AllureSubSuite("NoAssert")]
```

**Describe the solution you'd like**
I'd like the ability to integrate more custom information from my tests into the Allure report using attributes like this but in Xunit.  Is this possible?  

**Describe alternatives you've considered**
I've searched high and low across the internet but haven't found anything for Xunit with Allure that will do this yet.  I'm really hoping Im missing something easy.  There are not alot of alternatives for cross platform linux based html report generation tools for .NET out there.  And I like Allure.  The reports are pretty nice.  

**Additional context**
We are really looking for ways to inject more information in the report about the features that are being tested.  Possibly adding links to the agile stories and featues themselves so testers can follow what the automated tests are doing more easily.

**Comment by dnbr2002** [comment]
Any chance of this happening in the future?  :)

**Comment by dnbr2002** [comment]
For anyone who comes across this.  We for now have been mixing xUnit with the more comprehensive NUnit attributes to get better reporting.  It's just more depends in the test project.  Makes little more complicated have nunit attributes with xunit facts and asserts.  

Sample from class

```
   
using System;
using System.Net.Http;
using System.Threading.Tasks;
using Xunit;
using Allure.Commons;
using NUnit.Allure.Attributes;
using NUnit.Allure.Core;
using NUnit.Framework;
using Assert = Xunit.Assert;

namespace MFDAPI.integrate
{
[TestFixture]
    [AllureNUnit]
    [AllureDisplayIgnored]
    public class ApiHealthTest : IDisposable
    {

        public HttpClient client { get; }

        public void Dispose()
        {
            client.Dispose();
        }

        public ApiHealthTest()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri(Environment.GetEnvironmentVariable("SERVICE_HOST_URL"));
        }

        [Fact]
        [Test(Description = "ping test")]
        [AllureTag("Integration", ".NetCore", "WebApi", "PROJID.MFDAPI")]
        [AllureSeverity(SeverityLevel.trivial)]
        [AllureTms("PCOMX-172", "https://jira.mycompany.com/browse/PROJID-172")]
        [AllureOwner("Devs")]
        [AllureSuite("Integration Tests")]
        [AllureSubSuite("Health Tests")]
        public async Task TestHelloWorld() { ... }

   }
}

```

**Comment by wkisielewicz** [comment]
Hi @dnbr2002 , when you generate a report in XML format from the above class, do you get all this info visible in Allure? I have similar situation in my project, we are using Xunit as the main test framework and to use allure attributes I combined with NUnit, but it seems to be not reflected in my test report.

**Comment by IvanWR1995** [comment]
To display xUnit tests on .NET Core in allure reports, you can use this Open Source library: https://github.com/TinkoffCreditSystems/Allure.XUnit . [Reference to nuget package](  https://www.nuget.org/packages/NUnit.Allure/). It's custom adapter. This library based on Allure.Commons. It's project with examples using this library: https://github.com/TinkoffCreditSystems/Allure.XUnit/tree/master/src/Examples

**Comment by dnbr2002** [comment]
@IvanWR1995  that looks very cool.  Thanks!  Will definitely check that out.

**Comment by baev** [comment]
fixed in https://github.com/allure-framework/allure-csharp
