### ISSUE TITLE
No space between test data and duration

### ISSUE THREAD

**Issue by marvelfrozen** [allure-framework/allure2#1003]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
There is no space between test data and duration.
![image](https://user-images.githubusercontent.com/29943195/61026121-ce40da00-a3dc-11e9-9fc3-1eba4cb2e64e.png)

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Create a TestNG test method using DataProvider.
```java
    @Test(dataProvider = "test1")
    public void testMethod(String n1, Integer n2) {
        Assert.assertTrue(true);
    }

    @DataProvider(name = "test1")
    public Object[][] createData1() {
        return new Object[][] {
                { "Cedric", new Integer(36) },
                { "Anne", new Integer(37)},
        };
```

#### What is the expected behavior?
Give space between test data and duration to make reading it easier

#### What is the motivation / use case for changing the behavior?
Report readibility

#### Please tell us about your environment:

| Allure version | 2.12.1 |
| Test framework | testng@7.0.0-beta3 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
already fixed
