### ISSUE TITLE
nose parameterized  testing, In allure report only one

### ISSUE THREAD

**Issue by landhu** [allure-framework/allure2#1008]
**nose parameterized  testing, In allure report only one**
parameterzied:https://pypi.org/project/parameterized/

**Steps**
1. my testcase like this:
  from nose.tools import assert_equal
from parameterized import parameterized, parameterized_class

import unittest
import math

@parameterized([
    (2, 2, 4),
    (2, 3, 8),
    (1, 9, 1),
    (0, 9, 0),
])
def test_pow(base, exponent, expected):
   assert_equal(math.pow(base, exponent), expected)

def qq(d):
    print d

def test_aa():
    aa=['a','b','c']
    bb=['d','f']
    for a in aa:
        for b in bb:
            print a
            yield qq,b
2. the i use python nose,like this
   nosetests -v test_math.py --with-allure --logdir=aa
3. print log is OK
  test_math.test_aa('d',) ... ok
test_math.test_aa('f',) ... ok
test_math.test_aa('d',) ... ok
test_math.test_aa('f',) ... ok
test_math.test_aa('d',) ... ok
test_math.test_aa('f',) ... ok
test_math.test_pow(2, 2, 4, {}) ... ok
test_math.test_pow(2, 3, 8, {}) ... ok
test_math.test_pow(1, 9, 1, {}) ... ok
test_math.test_pow(0, 9, 0, {}) ... ok

----------------------------------------------------------------------
Ran 10 tests in 0.006s

OK
4. then i use allure 2.6.0
 allure server f:\xx
  
But only two tests
![TIM截图20190920140432](https://user-images.githubusercontent.com/22722402/65303339-5814dc80-dbb0-11e9-9088-52a3a9b9ff32.png)
![QQ截图20190920141053](https://user-images.githubusercontent.com/22722402/65303386-84305d80-dbb0-11e9-850f-7232b9072645.png)

**Comment by rafaelcs** [comment]
I have the same issue using Pytest. Bug reported here: https://github.com/allure-framework/allure-python/issues/430

**Comment by baev** [comment]
It should be fixed already
