### ISSUE TITLE
Allure report with XCtest is displayig UNKOWN name and time

### ISSUE THREAD

**Issue by moatazeldebsy** [allure-framework/allure2#1010]
**Describe the bug**
Allure report with XCtest is displaying UNKOWN name and time
**To Reproduce**
1. run `run XCUITest from command line` and generate the results in a specific folder in the project
2. run on 'allure serve TestResults'
3. Allure copy the result files to temp folder with this output `Generating a report to a tmp directory...
Parse file TestResults_1/TestSummaries.plist
Parse file TestResults_1/Info.plist
Report successfully generated to /var/folders/allure-report
Starting web server...`

**attachment**

<img width="1260" alt="Screenshot 2019-09-21 at 17 22 43" src="https://user-images.githubusercontent.com/45570191/65375419-b071da00-dc95-11e9-99c1-04593d9fa561.png">

**Environment (please complete the following information):**

| Allure version | 2.13.0 |
| --- | --- |
| Test framework | XCUITest |

**Comment by Bidonus** [comment]
+1 same issue

**Comment by moatazeldebsy** [comment]
@Bidonus not yet.
