### ISSUE TITLE
Bad TMS and issue links in Allure Ruby Cucumber

### ISSUE THREAD

**Issue by Rangiferus** [allure-framework/allure2#1013]
**Describe the bug**
AllureCucumber.configure is missing settings for issue and tms URL patterns. We can only set tms_prefix and issue_prefix that are recognized but generated links are bad.

**To Reproduce**

1. Set up prefixes:
AllureCucumber.configure do |c|
  c.tms_prefix      = 'JIRA:'
  c.issue_prefix    = 'JIRA:'
end

2. Add @JIRA:XXX as test tag to a scenario
3. Run test with Allure formatter
4. Generate Allure report

**Expected behavior**
A way to set link_tms_pattern and link_issue_pattern for proper tms and issue link generation.

| Test framework | Ruby@2.5.3 (allure-ruby-adaptor-api@0.7.2) |
| Allure adaptor | allure-cucumber@0.6.1 |
| Generate report using | allure commandline @2.9.0 |

**Comment by baev** [comment]
please update to latest version of Allure Cucumber (2.13.2 at the moment)

in case of any problems please report an issue here https://github.com/allure-framework/allure-ruby

**Comment by Rangiferus** [comment]
I already tried to do that but due to unknown reason I cannot.
`bundle update allure-cucumber` returns
"Bundler attempted to update allure-cucumber but its version stayed the
same".

There must be some other unknown requirements for newer allure version...

Tomasz
