### ISSUE TITLE
Allow useJavaDoc in Allure.description

### ISSUE THREAD

**Issue by oliversundell** [allure-framework/allure2#1024]
**Is your feature request related to a problem? Please describe.**
When using the annotation @Description in Allure, you can pass on the parameter "useJavaDoc = true" to automatically parse the javadoc above the method as the description picked up by Allure as well. When instead using the "Allure.description()" it isn't allowed to pass the "useJavaDoc", why? Would really want to be able to use it since we call these methods inside our listener in the test framework.

**Describe the solution you'd like**
The possibility to pass on "useJavaDoc" in Allure.description() as it is possible by using @Description(useJavaDoc = true)

Thanks!

**Comment by baev** [comment]
you can't access JavaDoc during test runtime as it omitted from byte code and available only in test sources. So we are using annotation processor that generates resources with JavaDoc content for methods annotated with `@Description(useJavadoc = true)` methods during compilation.

If you wan't to customise our solution you can follow the code from `allure-descriptions-javadoc` module. Also there is a `ResultsUtils.getJavadocDescription` util method that can be used to access generated resources (it will only return javadoc string for methods annotated by `@Description(useJavaDoc=true)` annotation)
