### ISSUE TITLE
URGENT - Screenshot generated in allure-results; however not available in report when generating report via commandline - Windows/TestNG/Maven

### ISSUE THREAD

**Issue by NaveeSabares** [allure-framework/allure2#1026]
Hi All,
I am using TestNG/Maven in my automation project and trying out allure report via allure commandline. and generating report after automation run using commandline commands as below in the bin folder of allure commandline. 
Can you please check if there is any issue in POM file.
**Command to generate report-** 	
String winCMD = "cmd /c allure generate -c ../../allure-results -o ../../target/allure-report";
Path - "user.dir" + "\\allure-2.13.0\\bin"

**Below is my POM file-** 
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.omnimobile.app</groupId>
	<artifactId>omnimobile-app</artifactId>
	<packaging>jar</packaging>
	<version>1.0-SNAPSHOT</version>
	<name>omnimobile-app</name>
	<url>http://maven.apache.org</url>
	
	<properties>
		<aspectj.version>1.9.4</aspectj.version>
		<allure.version>2.13.0</allure.version>
	</properties>
	
	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>2.22.2</version>
					<configuration>
						<systemPropertyVariables>
							<parameter name="appenvironment" value="${appenvironment}" />
							<parameter name="appplatform" value="${appplatform}" />
							<parameter name="applocale" value="${applocale}" />
						</systemPropertyVariables>
					   	<argLine>
        					-javaagent:"${settings.localRepository}\org\aspectj\aspectjweaver\${aspectj.version}\aspectjweaver-${aspectj.version}.jar"
        				 </argLine>
            	</configuration>
        		<dependencies>
            		<dependency>
                		<groupId>org.aspectj</groupId>
                		<artifactId>aspectjweaver</artifactId>
                		<version>${aspectj.version}</version>
                	</dependency>
        		</dependencies>
				</plugin>
				<plugin>
					<artifactId>maven-compiler-plugin</artifactId>
					<configuration>
						<source>1.8</source>
						<target>1.8</target>
						<encoding>UTF-8</encoding>
					</configuration>
				</plugin>

				
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>
											org.apache.maven.plugins
										</groupId>
										<artifactId>
											maven-resources-plugin
										</artifactId>
										<versionRange>
											[2.6,)
										</versionRange>
										<goals>
											<goal>resources</goal>
											<goal>testResources</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore></ignore>
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
				
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-dependency-plugin</artifactId>
					<version>3.1.1</version>
					<executions>
						<execution>
							<id>allure-commandline</id>
							<phase>clean</phase>
							<goals>
								<goal>unpack-dependencies</goal>
							</goals>
							<configuration>
								<includeGroupIds>io.qameta.allure</includeGroupIds>
								<includeArtifactIds>allure-commandline</includeArtifactIds>

								<outputDirectory>
									${project.basedir}/
									
								</outputDirectory>
							</configuration>
						</execution>
					</executions>
				</plugin>
				
				<plugin>
					<artifactId>maven-assembly-plugin</artifactId>
					<version>2.6</version>
					<configuration>
						<descriptors>
							<descriptor>zipreport.xml</descriptor>
						</descriptors>
					</configuration>
					<executions>
						<execution>
							<id>make-assembly</id> 
							<phase>test</phase> 
							<goals>
								<goal>single</goal> 
							</goals>
						</execution>
					</executions>
				</plugin>

			</plugins>
		</pluginManagement>
	</build>
	<dependencies>
		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-server</artifactId>
			<version>3.14.0</version>
		</dependency>
		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-api</artifactId>
			<version>3.14.0</version>
		</dependency>
		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-iphone-driver</artifactId>
			<version>2.39.0</version>
		</dependency>
		
		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>6.1.0</version>
		</dependency>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.8</version>
		</dependency>
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest-core</artifactId>
			<version>1.3</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.7</version>
		</dependency>
	
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.13</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-scratchpad</artifactId>
			<version>3.13</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.13</version>
		</dependency>
		<dependency>
			<groupId>com.relevantcodes</groupId>
			<artifactId>extentreports</artifactId>
			<version>2.41.2</version>
		</dependency>
		
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.2</version>
			<scope>provided</scope>
		</dependency>
		
		
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.9.4</version>
		</dependency>
		
		<dependency>
			<groupId>org.jsoup</groupId>
			<artifactId>jsoup</artifactId>
			<version>1.11.3</version>
		</dependency>
		<dependency>
			<groupId>com.mashape.unirest</groupId>
			<artifactId>unirest-java</artifactId>
			<version>1.4.9</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1</version>
		</dependency>
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20160810</version>
		</dependency>
		<dependency>
			<groupId>org.uncommons</groupId>
			<artifactId>reportng</artifactId>
			<version>1.1.4</version>
			<exclusions>
				<exclusion>
					<groupId>org.testng</groupId>
					<artifactId>testng</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.google.inject</groupId>
			<artifactId>guice</artifactId>
			<version>3.0</version>
		</dependency>
		<dependency>
			<groupId>velocity</groupId>
			<artifactId>velocity-dep</artifactId>
			<version>1.4</version>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>
		<dependency>
			<groupId>net.sf.sociaal</groupId>
			<artifactId>freetts</artifactId>
			<version>1.2.2</version>
		</dependency>
		<dependency>
			<groupId>javazoom</groupId>
			<artifactId>jlayer</artifactId>
			<version>1.0.1</version>
		</dependency>
	<dependency>
		<groupId>net.sf.sociaal</groupId>
		<artifactId>freetts</artifactId>
		<version>1.2.2</version>
	</dependency>
	
	<dependency>
    	<groupId>ru.yandex.qatools.allure</groupId>
    	<artifactId>allure-testng-adaptor</artifactId>
    	<version>1.5.4</version>
	</dependency>
	
	<dependency>
   		<groupId>io.qameta.allure</groupId>
   		<artifactId>allure-testng</artifactId>
	    <version>2.13.0</version>
	     <scope>test</scope>
	</dependency>
	<dependency>
  		<groupId>io.qameta.allure</groupId>
  		<artifactId>allure-commandline</artifactId>
  		<version>2.13.0</version>
  		<type>pom</type>
	</dependency>
	</dependencies>
	<reporting>
      <excludeDefaults>true</excludeDefaults>
        <plugins>
            <plugin>
                <groupId>ru.yandex.qatools.allure</groupId>
                <artifactId>allure-maven</artifactId>
                <version>2.8</version>
                  <configuration>
                    <reportVersion>${allure.version}</reportVersion>
                </configuration>
            </plugin>
        </plugins>
    </reporting>
</project>

**Comment by NaveeSabares** [comment]
@baev - Can you please help me with this. Am working in a windows web-desktop for mobile automation via see-test cloud portal.

**Comment by baev** [comment]
looks like support ticket. In order to get help with report configuration please use our gitter chat https://gitter.im/allure-framework/allure-core

**Comment by NaveeSabares** [comment]
@baev - Okay. Posted the query there. Can you please assign someone to help on this?

**Comment by baev** [comment]
> Can you please assign someone to help on this?

I can't. Allure is open source project, our community are group of enthusiasts that help others for free because they are awesome people. For urgent help from core maintainers you can buy paid support.

**Comment by fescobar** [comment]
I have no idea about your complete project. But I think you could have a problem with directories.

This is an example project when you can see the screenshots/videos attached. Follow the README to execute the tests and ignore the docker-compose part. It's just to show you how the allure-results are properly generated
https://github.com/fescobar/allure-docker-service/tree/master/allure-docker-java-testng-example
This is the right way to attach it
![image](https://user-images.githubusercontent.com/1236418/69055865-b8849680-0a06-11ea-8cbf-7d3f1d66170b.png)
https://github.com/fescobar/allure-docker-service/blob/master/allure-docker-java-testng-example/src/test/java/com/allure/docker/FirstTest.java#L35

**Comment by NaveeSabares** [comment]
@fescobar  - The screenshots captured are available in allure-results folder. However, my query is related to the screenshots not attached to the report. As i checked in few references, it seems that the issue is with aspectj java agent path . Can you please validate my pom.xml if i have provided it right?
