### ISSUE TITLE
Unknown Hook is existed in report

### ISSUE THREAD

**Issue by ledaivuong** [allure-framework/allure2#1030]
In my report, it exists an Unknown Hook which I'm not sure what it is and how can skip it
![2019-12-02_00h01_20](https://user-images.githubusercontent.com/22213252/69917304-fff33400-1496-11ea-8bf1-9faa996ecd3a.png)

**Comment by baev** [comment]
duplicate of https://github.com/webdriverio-boneyard/wdio-allure-reporter/issues/164
