### ISSUE TITLE
There is no way to exclude Skipped test cases in allure report

### ISSUE THREAD

**Issue by sbhatta2018** [allure-framework/allure2#1037]
I am using allure 2.10.0 with Java & TestNG. I have around 1000 test cases of which some gets skipped if there mismatch in some parameters. Because of this my pass percentage gets affected as it includes SKIPPED test cases in the count.

I need a way to not include SKIPPED test cases in the count.

Current Behavior -
Total - 3 (Pass + Failed + Skipped)
Pass - 1, Failed - 1, Skipped - 1
Pass Percentage - 33.33% 

Expected behavior -
Total - 2 (Include only Pass and Fail)
Pass Percentage - 50%

Please let me know if there is already a way to implement it

**Comment by sridharreddysuram123** [comment]
Any update on this?

**Comment by storenth** [comment]
python users want this feat too!

**Comment by ShuoHuangTesting** [comment]
any update so far? Also struggling in this issue.

**Comment by Nisim761** [comment]
Assuming I have 1 pass, 1 fail, 1 skip.
I want to have 33.3% pass rate and not 50%.

In my case I prefer the previous behavior.
What can I do?
