### ISSUE TITLE
Several run of the same test but under several suites  - distinct into one

### ISSUE THREAD

**Issue by maxski** [allure-framework/allure2#1046]
**Issue **
There is one test that could be run several times but with other start-up condition (no data providers or test params). Each one run is from different test suite. Report shows only one with retry and most critical is one failed it could be hidden by re-run

1. One test with @Test annotation
2. Two suites included the test, but each suite has different run condition
Actual: Final report contains one test.

**Comment by baev** [comment]
you can add start-up condition as test parameter, that will fix the issue

**Comment by maxski** [comment]
You mean in test method or in xml test?

`@Test 
public void someTest (T param);`

`<test name="name">
        <parameter name="param" value="value"/>`

**Comment by baev** [comment]
both ways should be ok

**Comment by maxski** [comment]
Yep, suite level variable helps
Thanks
