### ISSUE TITLE
All bintray downloads for allure libraries are failing

### ISSUE THREAD

**Issue by brishin** [allure-framework/allure2#1049]
**Describe the bug**
All bintray downloads for allure libraries are failing. Otherwise bintray seems to be up for other libraries.

**To Reproduce**
Try to download from https://dl.bintray.com/qameta/maven/io/qameta/allure/allure-android-commons/2.0.0-beta1/allure-android-commons-2.0.0-beta1.jar — see that it fails with 403 status code.

**Comment by Jian-Min-Huang** [comment]
yes, brew install allure also fail

**Comment by Nikitron** [comment]
Are there public mirrors?

**Comment by baev** [comment]
our Bintray account has been rate-limited once again. You can download command line installation directly from github releases https://github.com/allure-framework/allure2/releases

more details available at https://github.com/allure-framework/allure2/issues/832

**Comment by Nikitron** [comment]
@baev But on this page there is only a link on dl.bintray.com (which does not work) and not compiled sources....

**Comment by baev** [comment]
https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/

**Comment by baev** [comment]
> But on this page there is only a link on dl.bintray.com (which does not work) and not compiled sources....

fixed, now distributions are available for last release https://github.com/allure-framework/allure2/releases/tag/2.13.1

**Comment by rickschubert** [comment]
I am having the same problem, unsure how to solve the problem.

**Comment by baev** [comment]
the issue should be fixed by now
