### ISSUE TITLE
Have option to provide multiple allure-results directories to combine

### ISSUE THREAD

**Issue by nishantvas** [allure-framework/allure2#1051]
**Is your feature request related to a problem? Please describe.**
In a multi module maven / gradle project the **allure-results** directories are created module wise and this leads to problems when trying to generate a report with all those results

**Describe the solution you'd like**
Much like the -o option, it'll be pretty great to have an option to provide multiple allure-results folder paths
`allure serve --result-dir /path/to/one --result-dir /path/to/two --report-dir /path/report`

**Describe alternatives you've considered**

We can tweak the system properties to force allure to put all results in a certain folder but it requires hackish ways to generate directory for multi module projects

**Comment by menezes-ssz** [comment]
@nishantvas you can! Just send parameters with space, looks like code below

`$ allure serve reports/ios/allure/ reports/android/allure/`

My reports folder structure

![image](https://user-images.githubusercontent.com/35569098/79644551-0fda8e80-8180-11ea-886a-499d29e03134.png)

Allure result 

<img width="1505" alt="Captura de Tela 2020-04-18 às 14 31 53" src="https://user-images.githubusercontent.com/35569098/79644763-714f2d00-8181-11ea-9b0b-8df255a37d72.png">

OS : macOS Mojave 10.14.5 (18F203)

Hope this can help you!

**Comment by nikhilwaichal96** [comment]
I have folder structure like  this 
 D:\Allurereport\
         -AWS-May15
         -AWS-May16
         -AWS-May17   ....
I am trying to generate consolidate report but  No luck getting this
ALLURE REPORT UNKNOWN
unknown - unknown (Unknown)
0
test cases

**allure serve D:\Allurereport\AWS-May15 D:\Allurereport\AWS-May16 D:\Allurereport\AWS-May17 D:\Allurereport\AWS-May18**


when I use **allure generate allure-results1 allure-results2** its showing incorect execution time in days

**Comment by fescobar** [comment]
@nishantvas try with this https://github.com/fescobar/allure-docker-service#MULTIPLE-PROJECTS---REMOTE-REPORTS

**Comment by menezes-ssz** [comment]
@fescobar this allure-docker is too good!

**Comment by Tonicku** [comment]
Can we have an example how to setup correctly multi project ? I don't understand how to bind results X to the allure project X, result Y to allure project Y, result Z to allure project Z and so on. Thanks a lot

**Comment by fescobar** [comment]
@Tonicku 
https://github.com/fescobar/allure-docker-service-examples/blob/master/allure-docker-multi-project-example/docker-compose.yml
https://github.com/fescobar/allure-docker-service#creating-our-first-project
https://github.com/fescobar/allure-docker-service#send-results-through-api

**Comment by deadshot674gam** [comment]
@leomenezessz i have a Jenkins Build which generates Multiple OS*Browser Combinations results , these combinations i am not sure how many it can vary or may increase in Future . 

My directory Structure - 
```
|----- results
|            |-->OS1+Browser1
|                    |--><Session-id-1>
|                              |-->allure-results
|                     |--><Session-id-1>
|                              |-->allure-results
|            |-->OS1+Browser2
|                    |--><Session-id-1>
|                              |-->allure-results
|                     |--><Session-id-2>
|                              |-->allure-results
|
```

Can i provide like - 
`allure serve reports/*/*/allure-results`
