### ISSUE TITLE
Some failed test cases not shown in report

### ISSUE THREAD

**Issue by rameshnatesan** [allure-framework/allure2#1058]
**Describe the bug**
Some Geb tests failed due to DriverCreationException in setupSpec() or cleanupSpec(). In such cases Allure is not showing those failed tests in its report

**To Reproduce**
1. Run a Geb Spock test and create an exception in setupSpec()/setup() or cleanupSpec()/cleanup() method
2. Open Allure report
3. You will notice that the failed test is not in the report

**Expected behavior**
 failed test should be shown in the report

**Screenshots**
N/A

**Environment (please complete the following information):**

| Allure plugin| ru.d10xa:gradle-allure-plugin:0.5.5 |
| --- | --- |
| Test framework | Geb/Spock|
| Allure adaptor | allure-spock-geb:0.2.1 |

**Comment by diroussel** [comment]
I have the same issue.  In the results I have one xml file with 4 failing tests, and one passing test...

<img width="682" alt="image" src="https://user-images.githubusercontent.com/2374/97978975-4f886100-1dc6-11eb-8089-217e63fb0ff8.png">

When I generate the reports with allure-command line npm package, only the passing test shows up:
<img width="561" alt="image" src="https://user-images.githubusercontent.com/2374/97979065-75156a80-1dc6-11eb-9f9a-bc27caa6d510.png">

It was using allure 2.13.0.  I tried building the HEAD of allure-commandline from the allure2 repo, and use that instead, but get the same problem.

**Comment by diroussel** [comment]
The problem seems to be that the generated suites.json and suites.csv only contain the passing test suite.

Could it be because the suite name is the same for all the tests, because it's generated from a cucumber scenario outline?

**Comment by baev** [comment]
yeah, such results considered as retries due to same name. In order to fix that you need to provide parameters to Allure.
