### ISSUE TITLE
Add allure plugin for Karate framework

### ISSUE THREAD

**Issue by zhulanov-an** [allure-framework/allure2#1061]
Add ability to generate allure report using Karate framework https://github.com/intuit/karate
Current json report plugin doesnt't work

**Comment by ashokkumarg** [comment]
any update on the feature?

**Comment by dhoanglong91** [comment]
any update?

**Comment by auto110** [comment]
any update?

**Comment by felipecrs** [comment]
I wonder how this works:

https://www.linkedin.com/pulse/karate-integration-allure-reporting-kushan-shalindra-amarasiri-/

**Comment by vikram3005** [comment]
@baev Adding this ability will be really good. Any update on the feature completion(due date) will help. Thank you.

**Comment by vhristov5555** [comment]
Do we have some plans to add such plugin? It would help lots of people have better Allure reports.

**Comment by QATew** [comment]
I see this has been merged. Any input on how to use it? @baev

**Comment by baev** [comment]
https://mvnrepository.com/artifact/io.qameta.allure/allure-karate

To configure it, add `AllureKarate` Runtime Hook to `com.intuit.karate.Runner`:

```java
Runner.path("...").hook(new AllureKarate())...;
```
