### ISSUE TITLE
How to generate report with Xcode 11 XCUITest

### ISSUE THREAD

**Issue by DonnieLi** [allure-framework/allure2#1062]
Apple changed the format of xcresult starting in Xcode 11.
Allure reports are empty when run with Xcode 11 result bundles.
Have you handled this situation?
Thanks!

**Comment by eroshenkoam** [comment]
Hello, just follow this instruction: 
https://github.com/eroshenkoam/xcresults

**Comment by eroshenkoam** [comment]
Let me know if you have problems with that)
