### ISSUE TITLE
Add option to sort the test cases in the report by the cases chronological execution order

### ISSUE THREAD

**Issue by tomerbr1** [allure-framework/allure2#1064]
**Is your feature request related to a problem? Please describe.**
I use Allure for pytest to test a product. Sometimes I find a relationship between failures of cases with the actions done in previous cases. It is hard to see this by the current sorting options as there is no option to view the cases in the report by their actual chronological execution order.

**Describe the solution you'd like**
Add a sort option in the report to sort the test cases under the suites by their execution chronological order.

**Describe alternatives you've considered**
The only alternative i currently see is looking at the actual pytest output and look for relation between failed cases.

**Comment by zoykhan** [comment]
when will this be fixed?

**Comment by eastdenchik1** [comment]
Will this feature be fixed?

**Comment by pamarntharajan** [comment]
Facing the same issue. Can this be fixed please?

**Comment by baev** [comment]
sort by oder available for a while as far as I know

**Comment by korund** [comment]
Hi!
Issue is still relevant. Requests are sorted inside of folders correctly, but folders between themselves are not, however they are represented correctly in the suites file.
Can folders also respect the chronological order?

**Comment by mourav2222** [comment]
it works here, sorting the chronological execution order

![image](https://github.com/allure-framework/allure2/assets/76436807/f5e67d28-e385-4c69-ac6e-c62212481c79)
