### ISSUE TITLE
Reports are not updating properly when only some of the examples are re executed

### ISSUE THREAD

**Issue by prakashshetty90** [allure-framework/allure2#1065]
Details : 
I have created the scenario outline with multiple examples data.
First time when executed report is getting generated without any issues
Later when we re-execute the scenario outline with all the examples data the results are generated as exepcted.

But the issue is if we re-execute only some of the examples data the allure report is getting updated in place of different test data set.

| Allure version | 2.9.0 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.9.0 |
| Generate report using | allure-maven@2.18 |

Detailed Information with screenshots : 
1) Below screenshot is when i execute single scenario outline with multiple examples.
  In the name of the scenario I have added code to have the unique name iwth below code
Allure.getLifecycle().updateTestCase(testResult -> {
            String name = testResult.getName();
            testResult.setName(arg1 +  " " +name);
        });
![allure all examples execution](https://user-images.githubusercontent.com/58566125/75669698-758ebc00-5ca1-11ea-9dc2-8ee47681327b.PNG)

2)  Next time when we re-execute only some of the examples data by commenting others. 
The same test case status is not getting updated.

In this example i re-executed only failed examples data that is TEST_EX_S0005_16, TEST_EX_S0005_18, TEST_EX_S0005_22, TEST_EX_S0005_24

but allure report is not updated for those test cases instead it replaced the  TEST_EX_S0005_01,TEST_EX_S0005_02,TEST_EX_S0005_03,TEST_EX_S0005_04

Please find the screenshot below 
![allure 4 examples  data execution](https://user-images.githubusercontent.com/58566125/75675051-59444c80-5cac-11ea-8288-0c05f0095482.PNG)

Please help us with this issue

**Comment by prakashshetty90** [comment]
Can anyone please help me with this issue

**Comment by prakashshetty90** [comment]
Did anyone had a chance to look into this issue

**Comment by fescobar** [comment]
@prakashshetty90 instead to change the name, did you try just adding arguments?. Just left the name of the test as it is. The arguments differentiate the tests.
