### ISSUE TITLE
Buggy display of the identical screenshots attached to different steps

### ISSUE THREAD

**Issue by remorhaz** [allure-framework/allure2#1069]
**Describe the bug**
Generated report shows screenshots from different steps incorrectly if they address the same file.

**To Reproduce**
I attach two identical screenshots (in same file) to two different steps like this:
```xml
<!-- In step 1 -->
<attachment title="GDPR accepted" source="62f92a7008ae196a9fe1640d699c9b49edf3412c-attachment.png" type="image/png"/>
<!-- In step 2 -->
<attachment title="Logo clicked" source="62f92a7008ae196a9fe1640d699c9b49edf3412c-attachment.png" type="image/png"/>
```
And then I see the following in generated report:

- Step 1 contains "Logo clicked" attachment  entry and the click on it folds/unfolds correctly.
- Step 2 contains "Logo clicked" attachment entry and the click on it folds/unfolds the attachment in step 1.

**Expected behavior**
- Step 1 contains "GDPR accepted" attachment entry and the click on it folds/unfolds correctly.
- Step 2 contains "Logo clicked" attachment entry and the click on it folds/unfolds correctly.

**Environment:**

| Allure version | 2.13.2 (and same behavior on 2.7.0) |
| --- | --- |
| Test framework | PHPUnit@9.0.1 |
| Allure adaptor | Custom adapter over allure-framework/allure-php-api@1.1.7 |
| Generate report using | Allure CLI@2.13.2 |

**Comment by baev** [comment]
Reusing the same files in different attachments is not supported, and support is not planned.
