### ISSUE TITLE
miss encoding when build report with newman allure reporter

### ISSUE THREAD

**Issue by Pavel-max176** [allure-framework/allure2#1071]
i'm using Postman to craft integrated api test for my web-application.
I build reports with newman and allure reporter, but when i start allure web interface and see generated report i found missing Cyrillic encoding in test description. What i doing wrong?
![allure](https://user-images.githubusercontent.com/62247686/76762220-e8b82800-67a1-11ea-9840-5e7ac11188ad.png)

**Comment by baev** [comment]
please check [newman-reporter-allure](https://www.npmjs.com/package/newman-reporter-allure) ([docs](https://allurereport.org/docs/newman/))
