### ISSUE TITLE
Ignoring CDATA tags in report

### ISSUE THREAD

**Issue by ognif** [allure-framework/allure2#1073]
**Describe the bug**
If I use allure to compile a bug report out of my reporter, it looks like allure do not recognize the CDATA Tag inside a XML Node. All content of the node is compiled as text and CDATA is complete ignored. If I use  `<strong>`, it is ignored. If I use a link inside a` <a>` tag, it is ignored. But it is definitely allowed to use a link or a `<strong>` or `<I>` tag inside `<pre><code>` formatted text.

This is a sample XML. The stack contain a `<strong>` part and also a link. In allure it is just Text. Because it is inside the CDATA tag, allure must have recognized it as html not as text only.

Sample XML:
````
<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1584727575012" stop="1584727575055">
    <name>Clipcafe 20-3-2020</name>
    <title>Clipcafe 20-3-2020</title>
    <test-cases>
        <test-case start="1584727575012" status="failed" stop="1584727618818">
            <name>L5</name>
            <title>L5</title>
            <labels>
                <label name="severity" value="undefined"/>
            </labels>
            <parameters>
                <parameter kind="argument" name="User Agent" value="Chrome 80.0.3987.149 / macOS 10.15.3"/>
            </parameters>
            <steps/>
            <attachments>
                <attachment title="Screenshot" source="06bc1a92-101c-411a-b68f-b98744064e3d-attachment.png" type="image/png" size="418553"/>
            </attachments>
            <failure>
                <message>AssertionError: XML Vergleich fehlgeschlagen: expected [ Array(101) ] to deeply equal []</message>
                <stack-trace><![CDATA[<a href="/diff?id=5ccb5830-6ad5-11ea-8484-afdba76c5235">Compare</a> <strong>Hans</strong> 
]]></stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>
````

**To Reproduce**
To reproduce just use the XML and compile it. You will see that the CDATA is ignored. 

**Expected behavior**
I expect that allure will use the CDATA info as it is, so that text is bold and link is shown and working.

**Environment (please complete the following information):**
"allure-commandline": "^2.13.0",
"nodejs" v13.9.0
"MacOS" 13.0.5
"jdk" 130.2

**Comment by baev** [comment]
Closed as stale. However, it is already fixed in Allure 3.
