### ISSUE TITLE
Not able to install allure in mac

### ISSUE THREAD

**Issue by skmonjurul** [allure-framework/allure2#1079]
I am not able to install allure manually in MAC. 

I am referring 2.1.4 in this below link:
https://docs.qameta.io/allure/#_installing_a_commandline
but this is not working. 

so I downloaded from this below link:
https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.9.0/
both the .zip and .tgz file. 

but still, it is not working.

**Comment by fescobar** [comment]
@skmonjurul  the docker container, it's easiest.
https://github.com/fescobar/allure-docker-service

**Comment by baev** [comment]
https://allurereport.org/docs/gettingstarted-installation/
