### ISSUE TITLE
Report unable to fetch data from artefacts of CircleCI

### ISSUE THREAD

**Issue by techhemant** [allure-framework/allure2#1085]
**Describe the bug**
We upload the generated Allure report components to CircleCI artefacts. Since Chrome version 80.0.3987.149, we're unable to see report data stored as CircleCI artefacts due to CORS policy. 
I believe, CircleCI store all of its artefacts on AWS S3.

**Console error logs**

`Access to XMLHttpRequest at 'https://circle-production-customer-artifacts.s3.amazonaws.com/....' (redirected from 'https://......-gh.circle-artifacts.com/0/Test_Report/widgets/executors.json') from origin 'https://.......-gh.circle-artifacts.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**To Reproduce**
1. Generate report in CircleCI container
2. Upload whole report as artefacts.
3. Open the report

**Expected behavior**
I should be able to see report data on browser.

**Screenshots**
<img width="1674" alt="Screen Shot 2020-05-01 at 6 02 46 am" src="https://user-images.githubusercontent.com/41311719/80771944-9b85ef00-8b72-11ea-89ae-db04f450bb4d.png">

**Environment (please complete the following information):**

| Allure version | 2.13.2 |
| Test framework | phpunit |
| Allure adaptor | "allure-framework/allure-php-api": "1.1.8",|
| Generate report using | allure generate allure-results --clean |

**Comment by Ljancek** [comment]
I have some issue ... root cost is probably https://support.circleci.com/hc/en-us/articles/360046342233-Artifact-Redirects-Changes

**Comment by techhemant** [comment]
On asking CircleCI they have applied a flag to opt out of redirects until they consider handling AJAX requests a different way. That solves the issue I was facing.
