### ISSUE TITLE
Allow adding attachments in set up and tear down methods

### ISSUE THREAD

**Issue by Kremliovskyi** [allure-framework/allure2#1087]
I am using TestNG TestListenerAdapter and log4j2. I have created custom log4j2 appender to be able to retrieve logs and add them as attachments in Allure. These are various kind of logs from different sources and it is not possible to use any existing Allure integration.

The issue is when I am trying to add text/plain attachments anywhere besides test method scope for example in onConfigurationSuccess method of TestListenerAdapter or even onFinish the attachment is stored in allure-results folder but it is not added to the report. Thus part of the log is lost. It is crucial to see what happened in BeforeSuite, BeforeTest, BeforeClass, BeforeMethod and all after TestNG methods. 

**Describe the solution you'd like**
Please allow adding attachments to the report in set up and tear down methods to be able to see full custom log.

**Comment by fescobar** [comment]
@Kremliovskyi did you try using the helper `Allure.addAttachment(...)` you can call that method from any part from your code like a @BeforeMethod @AfterMethod @Before @After, etc

https://github.com/fescobar/allure-docker-service/blob/master/allure-docker-java-testng-example/src/test/java/com/allure/docker/listeners/MyListener.java#L38

https://github.com/fescobar/allure-docker-service/blob/master/allure-docker-java-testng-example/src/test/java/com/allure/docker/listeners/MyListener.java#L38

**Comment by baev** [comment]
we support attachments and steps in majority of configuration methods, for your appender you can check that current allure context exists by invoking `Allure.getLifecycle().getCurrentTestCaseOrStep()` method (in case of empty optional there is no context present) before adding attachments. 

We do not support hooks from custom listeners (as there is no guarantee of listeners order, and AllureTestNG integration uses this hooks, so your custom listener can be invoked before Allure context started/after Allure context closed).

**Comment by Kremliovskyi** [comment]
@fescobar I did tried Allure.addAttachment and annotated method from @BeforeMethod, etc. and nothing appears in report, I mean web version. Do you support adding attachments from  @BeforeMethod ?

**Comment by Kremliovskyi** [comment]
@baev I see. Optional is empty in this listener. It did work directly from @BeforeMethod and after methods. Thank you, will try to add attachments directly from configuration methods.

**Comment by fescobar** [comment]
> @fescobar I did try Allure.addAttachment and annotated method from @BeforeMethod, etc. and nothing appears in report, I mean web version. Do you support adding attachments from @BeforeMethod ?

@Kremliovskyi maybe you have a problem with your file
Download this example project and execute just the next class `mvn test -Dtest=FirstTest`
[allure-docker-java-testng-example.zip](https://github.com/allure-framework/allure2/files/4582313/allure-docker-java-testng-example.zip)
This class contains the `@BeforeMethod` with the attach method
<img width="1204" alt="Screen Shot 2020-05-05 at 5 52 03 PM" src="https://user-images.githubusercontent.com/1236418/81093045-6e7e6700-8ef9-11ea-8128-d362752ea857.png">

You will see in the report the log files attached in the Set Up section

![Screen Shot 2020-05-05 at 5 52 13 PM](https://user-images.githubusercontent.com/1236418/81093125-8a820880-8ef9-11ea-9ecf-54c35508cd30.png)
