### ISSUE TITLE
Allure report do not show failed test cases

### ISSUE THREAD

**Issue by ElenaAlejo** [allure-framework/allure2#1090]
**Describe the bug**
Failed test cases are not shown.
At data folder, there are 37 test cases instead of expected 43 test cases (6 failed test cases are missing)

**Expected behavior**
Expected that the 6 failed test cases appear at the report

**Screenshots**
<img width="684" alt="Screen Shot 2020-05-13 at 19 34 04" src="https://user-images.githubusercontent.com/16277679/81802325-d0ba1600-9550-11ea-8c3d-057edd8ad49e.png">

This image shows the failed test cases for that build.
As we are retrying 4 times: 6 failed test x 4 = 24 failed executions

<img width="1322" alt="Screen Shot 2020-05-13 at 19 29 07" src="https://user-images.githubusercontent.com/16277679/81802283-bc761900-9550-11ea-92ee-95461ab09152.png">

**Environment (please complete the following information):**

| Allure version | 2.13.3 |
| --- | --- |
| Test framework | JUnit5 |
| Allure adaptor | allure-junit5@2.13.3 |
| Generate report using | Gradle@2.8.1 |

**Additional context**
Jenkins plugin environment, test results generated using Gradle.

**Comment by baev** [comment]
should be fixed by now. If the issue still reproduces, please make sure you're using the latest available versions. If the update didn't help either, please create a new [support request](https://github.com/orgs/allure-framework/discussions/new?category=questions-support).
