### ISSUE TITLE
The 'allure.report.directory' property in 'allure.properties' file is not being considered

### ISSUE THREAD

**Issue by s4ik4t** [allure-framework/allure2#1092]
**Describe the bug**
The `allure.report.directory` property in `allure.properties` file is not being considered.

**To Reproduce**
1. Create `allure.properties` file in your project
2. Add `allure.report.directory=target/allure-report`
3. Run test with `mvn clean test site` (e.g. https://github.com/allure-examples/allure-testng-example)

**Expected behavior**
Report should be generated in the given directory i.e. `target/allure-report` not in default one i.e. `target/site/allure-maven-plugin`

**Screenshots**

**Environment (please complete the following information):**

| Allure version | 2.13.2 |
| --- | --- |
| Test framework | testng@7.1.0 |
| Allure adaptor | allure-testng@2.13.2 |
| Generate report using | allure-maven@2.10 |

**Additional context**
When I add the following configuration for `allure-maven` in the `pom.xml` then it works:
```
<configuration>
  <reportDirectory>${basedir}/target/allure-report</reportDirectory>
</configuration>
```

**Comment by focbenz** [comment]
The same problem with the allure-maven Version 2.10.0

Is the property named `allure.results.directory` or `allure.report.directory`?

The allure.properties file in src/test/resource contains the default value for both versions:
```
allure.results.directory=target/allure-results
allure.result.directory=target/allure-results
```

Trying to use system property in surefire-plugin did not work either:
```
<systemProperties>
	<property>
		<name>allure.results.directory</name>
		<value>${project.build.directory}/allure-results</value>
	</property>
	<property>
		<name>allure.result.directory</name>
		<value>${project.build.directory}/allure-results</value>
	</property>
</systemProperties>
```

In any case results are directly written into the working folder.

**Comment by s4ik4t** [comment]
> The property is named `allure.results.directory` not `allure.report.directory`.
> 
> A sample allure.properties file can be found here:
> https://github.com/allure-examples/allure-junit5-example/blob/master/src/test/resources/allure.properties
> 
> You could also use to stay flexible in case of a changed Maven output directory:
> `allure.results.directory=${project.build.directory}/allure-results`
> 
> but then you might need to enable resource filtering for testResources:
> 
> ```
> <project>
> 	<build>
> (...)
> 		<testResources>
> 			<testResource>
> 				<directory>src/test/resources</directory>
> 				<filtering>true</filtering>
> 			</testResource>
> 		</testResources>
> 	</build>
> </project>
> ```

These 2 are different properties, result is generated first then comes report :)

**Comment by abzaman7** [comment]
> **Describe the bug** The `allure.report.directory` property in `allure.properties` file is not being considered.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Create `allure.properties` file in your project
> 2. Add `allure.report.directory=target/allure-report`
> 3. Run test with `mvn clean test site` (e.g. https://github.com/allure-examples/allure-testng-example)
> 
> **Expected behavior** Report should be generated in the given directory i.e. `target/allure-report` not in default one i.e. `target/site/allure-maven-plugin`
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Environment (please complete the following information):**
> 
> Allure version	2.13.2
> Test framework	testng@7.1.0
> Allure adaptor	allure-testng@2.13.2
> Generate report using	allure-maven@2.10
> **Additional context** When I add the following configuration for `allure-maven` in the `pom.xml` then it works:
> 
> ```
> <configuration>
>   <reportDirectory>${basedir}/target/allure-report</reportDirectory>
> </configuration>
> ```

Where did you add the configuration?

**Comment by Vigneshwaran4495** [comment]
> **Describe the bug** The `allure.report.directory` property in `allure.properties` file is not being considered.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Create `allure.properties` file in your project
> 2. Add `allure.report.directory=target/allure-report`
> 3. Run test with `mvn clean test site` (e.g. https://github.com/allure-examples/allure-testng-example)
> 
> **Expected behavior** Report should be generated in the given directory i.e. `target/allure-report` not in default one i.e. `target/site/allure-maven-plugin`
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Environment (please complete the following information):**
> 
> Allure version	2.13.2
> Test framework	testng@7.1.0
> Allure adaptor	allure-testng@2.13.2
> Generate report using	allure-maven@2.10
> **Additional context** When I add the following configuration for `allure-maven` in the `pom.xml` then it works:
> 
> ```
> <configuration>
>   <reportDirectory>${basedir}/target/allure-report</reportDirectory>
> </configuration>
> ```

Where was this configuration added? I tried adding it in allure-maven plug in but it doesn't seem to work.

I tried adding `allure.report.directory` in pom.xml. But still no luck.
