### ISSUE TITLE
Allure report do not attach screenshot with robot framework + jenkins.

### ISSUE THREAD

**Issue by tuyenlq** [allure-framework/allure2#1096]
Hi, 

I was installed allure report on jenkins + robot framework => Allure report was successfully generated.
But on test case fail not attach screenshot https://imgur.com/a/6ufKjHq
Config allure in job : https://imgur.com/a/3Q9KZxo
Log console job : https://imgur.com/a/c5ZCdK4
What should I do in testcase attach sreenshot ?

Thanks.

**Comment by skhomuti** [comment]
@tuyenlq please see example of selenium plugin in https://github.com/allure-framework/allure-python/issues/476
by default selenium screenshots not attached

**Comment by xianglongfei-8888** [comment]
I have the same problem
```
robot -i 'test' --listener allure_robotframework --outputdir ./robot applications/test_desktop.robot
```
Allure report was successfully generated => like this : allure-report/data/screenshots/xxxx.jpg
But without screenshots/xxxx.jpg 

I can copy screenshots floder to allure-report/data/
But jenkins: How to add screenshots floder save location  allure-report/data/

eg:
```
Library           Screenshot    screenshots    screenshot_module=scrot
Library           DateTime

Keyword Screenshot
    Create Directory    ./screenshots
    ${ctime}    Get Current Date
    Take Screenshot    ${ctime}.jpg
```

**Comment by tuyenlq** [comment]
@skhomuti 
Hi,
I tried but it not work and allure support robotframework appium ?

Thanks

**Comment by skhomuti** [comment]
@xianglongfei-8888 you can use the approach with an additional library, see this example https://github.com/allure-framework/allure-python/blob/master/allure-robotframework/examples/attach/foreign_library_helper.py

**Comment by fengnex** [comment]
The bug still exists in v2.8.19, the latest version of allure-robotframework!

I wonder how to fix it, and can anyone help out?

**Comment by SystemCL** [comment]
Hi all. I tried to implement the above solution but screenshots still not present in allure reports. 
Allure version: 2.13.6
Python: 3.8.2
robotframework-allurereport: 1.1.1
allure-robotframework: 2.8.19
![image](https://user-images.githubusercontent.com/8817204/99563964-84093900-29d2-11eb-9e05-6567b62a12f1.png)

Looking forward to your support :)
