### ISSUE TITLE
Incompatibility between allure-junit5 and log4j2

### ISSUE THREAD

**Issue by bentley-chapman** [allure-framework/allure2#1098]
**Describe the bug**
It seems that allure-junit5 is incompatible with the dependencies log4j-core and log4j-api.

When you log something with log4j2 the logs are not printed to the console but this warning instead:

`[WARNING] Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /Users/xyz/IdeaProjects/allure-junit5-example/target/surefire-reports/2020-06-05T15-14-54_958-jvmRun1.dumpstream`

The dumpstream file contains this text:

```
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '15:14:57.039 [main] FATAL io.qameta.junit5.AllureListener - Starting step: firstStep'.
java.lang.IllegalArgumentException: Stream stdin corrupted. Expected comma after third character in command '15:14:57.039 [main] FATAL io.qameta.junit5.AllureListener - Starting step: firstStep'.
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient$OperationalData.<init>(ForkClient.java:507)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.processLine(ForkClient.java:210)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:177)
	at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:88)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

1. Is there a bug in allure-junit5? If yes, can it be fixed please?
2. What would be a workaround to this issue?

**To Reproduce**
1. Clone fork: https://github.com/bentley-chapman/allure-junit5-example
2. mvn clean verify
3. See warning and the missing log message on console output.

**Expected behavior**
Logging with log4j2 should work correctly, meaning that log messages are printed to the console output and that no warning like "Corrupted STDOUT by directly writing to native stream in forked JVM 1" appears.

**Environment (please complete the following information):**

| Allure version | 2.13.3 |
| --- | --- |
| Test framework | JUnit 5.6.2 |
| Allure adaptor | allure-junit5 |

**Comment by baev** [comment]
Allure uses `slf4j-api`, so if you want to use log4j2 you'll need to configure a binding for it https://logging.apache.org/log4j/2.0/log4j-slf4j-impl/index.html

**Comment by bentley-chapman** [comment]
I tried it with theses dependencies and with only log4j-slf4j-impl, but the "Corrupted STDOUT" still appeared and no log messages were logged. What is wrong?

```
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.30</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <version>2.13.3</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.13.3</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.13.3</version>
        </dependency>

```

**Comment by baev** [comment]
looks like Maven Surefire issue (probably this one https://issues.apache.org/jira/browse/SUREFIRE-1614)
By using Gradle everything works just fine

**Comment by bentley-chapman** [comment]
That was what I first assumed that it is a Surefire issue. But then I read that it was fixed and thought it maybe is an Allure issue. Anyway, I think I might change the project setup to Gradle. Thank you.
