### ISSUE TITLE
Plugin for Cloud Instances

### ISSUE THREAD

**Issue by grndvl1** [allure-framework/allure2#1103]
**Is your feature request related to a problem? Please describe.**
Want to have the plugin also work for the cloud.

**Describe the solution you'd like**
Most of our clients use the cloud instance of Jira now and we would like a plugin for the cloud and not just server instances.  We need this for our mobile app automation testing.  Please make this happen it would be much appreciated!

**Comment by baev** [comment]
Duplicate of #1075
