### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by baev** [allure-framework/allure2#111]

**Comment by thasherwin** [comment]
Is it a good idea to have a color for flaky tests in the graph section? We do see that a test is marked as flaky with the icon. But looking on the graph, you will not know many failed as flaky.

**Comment by baev** [comment]
sounds good 

https://github.com/allure-framework/allure2/issues/171

**Comment by just-boris** [comment]
How do you see this, guys?

Currently we have 4 statues with four different colors. How should we do to display flacky test? It can also be either passed or not passed. Threoretically, it means that we need to create a color for flacky-passed and flacky-failed and flacky-broken tests. It will make the chart unreadable.

I'd suggest to add an extra chart that displays only pure statistics, excluding tests, that we considered flacky. Aslo it's possible to add a checkbox like "Show flacky tests", that will switch the mode for the graph.

**Comment by sseliverstov** [comment]
How about dashes? white(transparent) + color of current status?

**Comment by baev** [comment]
Note that we have `flaky`, `muted` and `known` errors now. And I agree with @just-boris that different color for every case will make charts unreadable.

Also we are going to introduce a categories in forthcoming release. So every error may have (or have not) a category such as `infrastructure`, `network` and so on. And every category will have its own color as well.

I propose to discuss how we gonna achieve this in https://github.com/allure-framework/allure2/issues/171
