### ISSUE TITLE
Do not show history block if there is no history.json provided

### ISSUE THREAD

**Issue by baev** [allure-framework/allure2#112]

**Comment by thasherwin** [comment]
Does this means that allure 2.0 will support history? User will be able to see the history of previous results and compare it with the latest results?

**Comment by baev** [comment]
@thasherwin yep, Allure 2 supports history. You can try it out using Allure Jenkins Plugin 2.11 and Allure 2 Beta-3

**Comment by thasherwin** [comment]
oh great. i will definitely try it out.
