### ISSUE TITLE
Allure screenshots, steps are not visible during parallel run

### ISSUE THREAD

**Issue by arturmkr** [allure-framework/allure2#1125]
Using gradle-6.4, JDK 11, Allure, Selenide 5.13, Junit 5.

If executing tests not in parallel mode - everything works Ok!
But if run tests in parallel mode - screenshots are not attached, steps are not visible.

Screenshots are attached with 'junit.jupiter.execution.parallel.enabled' true and false:
http://i.piccy.info/i9/45803f25c4bb6a3853d05796c51a8ff3/1598796112/195620/1394194/disabled_parallel.png
http://i.piccy.info/i9/900313b301d5316efda45360f7a91e1b/1598796132/148661/1394194/enabled_parallel.png

**Junit5 config:**
    systemProperties += [
            'junit.jupiter.execution.parallel.enabled'                 : true,
            'junit.jupiter.extensions.autodetection.enabled'           : true,
            'junit.jupiter.execution.parallel.mode.default'            : 'concurrent',
            'junit.jupiter.execution.parallel.mode.classes.default'    : 'concurrent',
            'junit.jupiter.execution.parallel.config.strategy'         : 'fixed',
            'junit.jupiter.execution.parallel.config.fixed.parallelism': 19
    ]

@baev , could you please help.

Source code:
https://github.com/arturmkr/myReportProblem

**Comment by baev** [comment]
I guess it requires `same_thread` mode in order to support steps, as Allure uses `InheritableThreadLocal` to store execution context

**Comment by arturmkr** [comment]
Thanks!
