### ISSUE TITLE
How to add Issues Links to autotest?

### ISSUE THREAD

**Issue by Diokuz** [allure-framework/allure2#1126]
Hi there!

I use allure-js-common to generate xml testcases from tests, like that

```xml
<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1599028213221' stop='1599028213401'>
    <name>AddressDadata manual</name>
    <title>AddressDadata manual</title>
    <test-cases>
        <test-case start='1599028213221' status='passed' stop='1599028213385'>
            <name>foo</name>
            <title>bar</title>
            <labels>
                <label name='issue' value='PFPCORE-1535'/>
                <label name='tag' value='chrome'/>
                <label name='tag' value='puppeteer'/>
            </labels>
            <parameters/>
            <steps>
...
```

Then I use https://dl.bintray.com/qameta/generic/allurectl/1.8.1/allurectl_linux_amd64 to upload xml to Allure ee.

The problem here, I dont know how properly set label with jira issues. The only result I achieved is `Links` by adding `<label name='issue' value='PFPCORE-153'/>`, but it is not the same as `Issues Links`.

Could you please tell where to find the information about labels format for Issue Links?

<img width="851" alt="Снимок экрана 2020-09-02 в 10 02 18" src="https://user-images.githubusercontent.com/2929442/91942396-875e2400-ed03-11ea-8bb4-18bc0228a1e5.png">

**Comment by Diokuz** [comment]
Not sure why type of issue is invalid. I chose question.

**Comment by sskorol** [comment]
Is there any reason for not using Allure2?

**Comment by Diokuz** [comment]
We could use it, but we still need to generate xml first, right? The question is about xml format.

**Comment by Diokuz** [comment]
More general question: how to get testcase format from testcase in allure ui? I could fill it manually, and then just check what field is what. Export to CSV does not provide the whole information about the format.

**Comment by baev** [comment]
> Not sure why type of issue is invalid. I chose question.

that's because we ask users to not create issues for questions, there is a community on Gitter (and you can also use StackOverflow for that) is available for questions related to Allure Report, and we have a separate support channel for Allure EE users.

Answering your question: Allure EE has 2 different types of links - Links and Issues links. 

Links are simply a pair of name and url, when Issue Links are synced with Issue trackers and enriched with additional information such as issue status and summary.

When you are using `issue` label it goes to simple links to provide compatibility with Allure Report. 

To add Issue Link you need to configure Issue Tracker integration and then specify a mapping for it. For more details please see https://docs.qameta.io/allure-ee/test-cases/issues/

**Comment by baev** [comment]
> We could use it, but we still need to generate xml first, right?

there is new version of JS integrations available https://github.com/allure-framework/allure-js , it uses JSON instead of XML. The question was why to not use the new integration instead old one

**Comment by baev** [comment]
> More general question: how to get testcase format from testcase in allure ui? I could fill it manually, and then just check what field is what. Export to CSV does not provide the whole information about the format.

Don't get it. Please DM me on Gitter

**Comment by baev** [comment]
At this point such request should be processed via Allure EE support channel, so I'm closing the issue

**Comment by Diokuz** [comment]
> To add Issue Link you need to configure Issue Tracker integration and then specify a mapping for it. For more details please see https://docs.qameta.io/allure-ee/test-cases/issues/

We already have that, and it works when you add jira key in the Issues Links in allure ui. The question is about automatization: how to create Issues Links in xml / json (when generating report during auto tests run).

> there is new version of JS integrations available https://github.com/allure-framework/allure-js , it uses JSON instead of XML. The question was why to not use the new integration instead old one

Is 2.0.0-beta6 version stable? We use 1.3.1 now.


Mkay) asked in https://gitter.im/allure-framework/allure-ru

**Comment by baev** [comment]
> Is 2.0.0-beta6 version stable?

yes, it has beta status only because not all features that should be provided in 2.0 implemented yet. But overall it already much more stable than 1.3.1
