### ISSUE TITLE
Introduce new status KNOWNISSUE

### ISSUE THREAD

**Issue by vitamotus** [allure-framework/allure2#1131]
**Is your feature request related to a problem? Please describe.**
I would like to have possibility mark tests which were failed as Known Issue if the QA team already reported defect.

**Describe the solution you'd like**
Add new status to 'Status enum' and display in HTML in a different color. 
```java
public enum Status {
    FAILED("failed"),
    BROKEN("broken"),
    PASSED("passed"),
    SKIPPED("skipped"),
    KNOWN("known");
}
```

Also, would be nice if you can add method something like this: 
```java
public TestResult markAsKnownIssue() {
        super.setStatus(Status.KNOWN);
        return this;
}
```

**Describe alternatives you've considered**
Now I'm adding information about known issues in the failure message and add a link to the defect in the Bug tracker. But to see that it is already a known failure, I need to expend the test cases.

**Comment by msharmadaon** [comment]
Will this be in the next release? If so, can you please tell the ETA?
