### ISSUE TITLE
allure+testNG+gradle: Allure lifecycle: No test is running in onTestFailure invocation

### ISSUE THREAD

**Issue by sankouski-dzmitry** [allure-framework/allure2#1136]
**Describe the bug**
When trying to add attachment to allure in TestListener.onTestFailure() method, allure may complain "No test is running"(`Allure.getLifecycle().getCurrentTestCase()` is empty), hence no attachment in report.

**To Reproduce**
1. Clone [minimal example repo](https://github.com/sankouski-dzmitry/allure-attachment-problem)
2. Run `MyTest` 
3. Search log for `Empty allure current test case`, this will indicate, that test run is over, and you cannot add attachments to this test

**Expected behavior**
`Allure.getLifecycle().getCurrentTestCase()` should return case id in all test listener method invocations

**Environment (please complete the following information):**

| Allure version | 2.13.5 |
| --- | --- |
| Test framework | testng@7.3.0 |
| Allure adaptor | allure-testng@2.13.5 |
| Generate report using | allure-gradle@2.8.1 |

**Additional context**
heisenbug

**Comment by sankouski-dzmitry** [comment]
The problem is, that allure-testng has `io.qameta.allure.testng.AllureTestNg` listener, and it may be invoked after user's listener, because listener order not guaranteed in testng

**Comment by baev** [comment]
see https://github.com/biczomate/allure-testng7.5-attachment-example
