### ISSUE TITLE
Allure2 all supported properties

### ISSUE THREAD

**Issue by rromanik** [allure-framework/allure2#1150]
Hi, Allure2 team

What are all the properties that are supported by Allure2 framework?
How can I find the list of all properties that can be put into 'allure.properties' file?

I found some places where I saw examples, e.g.
https://github.com/allure-examples/allure-junit5-example/blob/master/src/test/resources/allure.properties
https://github.com/allure-examples/allure-testng-example/blob/master/src/test/resources/allure.properties
but how to know other supported properties?

**Comment by baev** [comment]
there are actually few properties supported:

1. `allure.results.directory` - the path to allure-results
1. `allure.label.X=Y` - will add label (X, Y) to all the tests, for example `allure.label.module=UI tests` will set label `module=UI tests`
1. `allure.link.X.pattern` (`allure.link.issue.pattern`, `allure.link.tms.pattern`) - link templates

**Comment by rromanik** [comment]
Thanks, @baev

**Comment by rromanik** [comment]
@baev, is it correct that the `allure.max.title.length` property is not supported anymore?
Is there something like that in allure2?

**Comment by baev** [comment]
> @baev, is it correct that the `allure.max.title.length` property is not supported anymore?

yep.

> Is there something like that in allure2?

What are the uses cases for that? I legit can't remember why it was added in the first place

**Comment by rromanik** [comment]
In order to restrict the maximum number of characters to be displayed in the Steps in Allure report.
For example, if 'allure-assertj' is used, and the JSON objects to be compared are large, there is no way to restrict how they are displayed in the resport.
On the following sample screenshot there are more than 2000 characters:
![image](https://user-images.githubusercontent.com/13782827/98821686-8b5f9e00-2438-11eb-8f40-85663f313aed.png)

and in the whole JSON object about 6000 characters, all displayed in the step.

I remember previously there was possible to restrict the displayed number of characters, and in my case 1000 was enough.

**Comment by baev** [comment]
@rromanik thanks, I got it. Could you please create an issue for that in allure-java repository?

As workaround you can use `StepLifecycleListener#beforeStepStop` and trim step names to required length.

**Comment by rromanik** [comment]
Created the following issue in the allure-java repository: https://github.com/allure-framework/allure-java/issues/490
