### ISSUE TITLE
[TestNG-PoolService-12] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running

### ISSUE THREAD

**Issue by deepakguna** [allure-framework/allure2#1155]
**Describe the bug**
Cucumber tests ran with TestNG runner produces lot of Allure life cycle errors: - [TestNG-PoolService-12] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
** Version**
        <aspectj.version>1.8.10</aspectj.version>
        <cucumber.version>6.9.0</cucumber.version> 
        <allure.version>2.13.6</allure.version> with allure cucumber jvm 6 artifact
**To Reproduce**
1.   I have several cucumber features  which are ran via testNG runner in mvn command line

This produces lot of log lines as below : 

 produces lot of Allure life cycle errors: - [TestNG-PoolService-12] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running

Is there something i am missing here 

 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

| Allure version | 2.9.0 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.9.0 |
| Generate report using | allure-maven@2.18 |

**Additional context**

**Comment by baev** [comment]
could you please check against https://github.com/allure-framework/allure-java/pull/493 , in order to make sure it solves the problem?

**Comment by MetallFoX** [comment]
@deepakguna could you tell when will you have time to check?

**Comment by deepakguna** [comment]
@MetallFoX i moved to another gig. I will test this over this weekend and report here.

**Comment by deepakguna** [comment]
@MetallFoX I am unable to build the project . Gradlew build fails due to -- Checkstyle rule violations . PFA attached build output
[gradlew build.txt](https://github.com/allure-framework/allure2/files/5687171/gradlew.build.txt)
