### ISSUE TITLE
behaviors view  404

### ISSUE THREAD

**Issue by liuchengxu11** [allure-framework/allure2#1174]
I would like to ask why the report output by allure suddenly fails to display the data 404 in the behaviors section? It was good before
Everything else is normal
What do I need to do to get back to normal

![image](https://user-images.githubusercontent.com/33363646/104280062-4f06f780-54e6-11eb-85a5-627f5e68b9dd.png)

![image](https://user-images.githubusercontent.com/33363646/104280134-67771200-54e6-11eb-9f25-605226838349.png)

![image](https://user-images.githubusercontent.com/33363646/104280155-71991080-54e6-11eb-9cb8-699b7853a8cc.png)

**Comment by pangxie1987** [comment]
出现了跟你一样的问题，排查了下，是因为执行了部分无效的case，造成了一部分垃圾数据，behaviors 出现了404.
删除无效case后，恢复正常

**Comment by baev** [comment]
fixed long time ago, please update to the latest version
