### ISSUE TITLE
How to disable open browser in allure-report?

### ISSUE THREAD

**Issue by Askarov5** [allure-framework/allure2#1175]
Hi,
I was working on custom automation framework and wanted to integrate with allure-report. Is there a way to stop allure-report command from automatically opening a browser? I wanted to listen to the server but open it inside of my electronJs app like a webpage.

**Comment by Phincle** [comment]
allure generate

**Comment by Askarov5** [comment]
> allure generate
it's just generates the report from result. But it doesn't invoke the server. 
For example:  When I run allure open, it opens the result in server like http://192.168.1.205:49915/index.html.

I wanted to have the same result without opening the browser. Let's say if I run allure open -no-browser it runs the server(and shows the address where it's running) but won't open any browser. [something like here](https://github.com/facebook/create-react-app/issues/3070)

**Comment by hmq2018** [comment]
I'm looking for the same feature, too.

**Comment by hmq2018** [comment]
[allure-commandline-2.17.3.jar.zip](https://github.com/allure-framework/allure2/files/8600488/allure-commandline-2.17.3.jar.zip)

Attached is a recompiled version with the openbrowser implementation removed, based on version 2.17.3. 
However, because it was my first time compiling a java program, the compiled file size is particularly large.

**Comment by harmin-parra** [comment]
I would also like to deploy a HTTP server Docker container to host the Allure report.

But I also get the message `Can not open browser because this capability is not supported on your platform. You can use the link below to open the report manually.`

**Comment by baev** [comment]
Please do not use `allure serve` & `allure open` commands to host Allure Reports somewhere. Those commands should be only used to open reports on the local machine. 

Even on a local machine, the best option today is to use the `--single-file` option, generate a single file report, and open it without a web server. 

`allure generate` command produces a static website. There is no need to have an additional Java process serving it for you.

For the docker environment, you can start with the following file.

```dockerfile
FROM nginx
COPY /path/to/allure-report /var/share/nginx/html
```

(you can even use `nginx:alpine`)

For the electron — google "serve static files", you'll find plenty of the options available.
