### ISSUE TITLE
Can you support modifying the title?

### ISSUE THREAD

**Issue by liutianping0326** [allure-framework/allure2#1176]
Can you support modifying the title? Thank！<br>
![image](https://user-images.githubusercontent.com/40854706/104844802-33985400-590d-11eb-8b30-e9815da5a691.png)

**Comment by Phincle** [comment]
you can just modifie the css file.

**Comment by jamesmortensen** [comment]
Can one of the maintainers please provide some insight into what components might need to be modified to achieve this?  I assume the CLI module, or the module that generates the report, and I assume there would need to be an addTitle method for use in the codebase.  The language-specific reporters would also need to be modified to consume the new API, I think.

I'm not 100% sure yet, but we may be interested in attempting a pull request, and we would be interested in doing this for the @wdio/allure-reporter for WebdriverIO.  Thank you!

**Comment by aleksandr-kotlyar** [comment]
You want to remove the name of the product from the product. What for? Somebody asking how to change allure logo, somebody asking to change the title. That is a trademark. I think that is unfair to the developers. 

@Kevin-liutianping @jamesmortensen 
May be you need some additional info on the second line of title? Or some info-block? Or custom widget? Please tell your story. What is the real use-case behind your will to change the title?

**Comment by jamesmortensen** [comment]
@aleksandr-kotlyar 

Allure is the name of the platform. The platform is used to generate various reports. The title could reflect what the report is about.  Is it the end to end tests, the API tests, performance tests, or regression tests.  Also, since we have various products, is this the e2e test report for product A or product Z?   When they have a different look and feel, it becomes much easier to get the context.

**Comment by Kevin-liutianping** [comment]
> @ aleksandr-kotlyar
> 
> 魅力是平台的名称。该平台用于生成各种报告。标题可以反映报告的内容。是端到端测试，API测试，性能测试还是回归测试。另外，由于我们拥有多种产品，因此这是产品A或产品Z的e2e测试报告吗？当它们具有不同的外观和感觉时，变得更容易获得上下文。

+1@aleksandr-kotlyar

**Comment by Kevin-liutianping** [comment]
> @aleksandr-kotlyar
> 
> Allure is the name of the platform. The platform is used to generate various reports. The title could reflect what the report is about. Is it the end to end tests, the API tests, performance tests, or regression tests. Also, since we have various products, is this the e2e test report for product A or product Z? When they have a different look and feel, it becomes much easier to get the context.

@aleksandr-kotlyar
Yes i think so too！

**Comment by baev** [comment]
Since release 2.26.0, you can specify the report name using the --name command line option:

```bash
$ allure serve allure-results --name "Custom report name"
$ allure generate allure-results --name "Custom report name"
```

See https://github.com/allure-framework/allure2/pull/2229
