### ISSUE TITLE
Question : Why do the test results in JIRA not appear as links to my Allure report in Jenkins

### ISSUE THREAD

**Issue by pkievit86** [allure-framework/allure2#1185]
I am using Jenkins with Allure plugin, Cucumber along with Allure 2. Version 2.13.8.

I am using Allure for Jira i.c.w. plugin to export Test Launch and Test Results to Jira.

This all works fine. But the results don't appear in Jira as links to the Allure report. Does anybody know why?

The executor.json file generated in the allure-results directory 
{"buildName":"test-xxx-xxxx #175","buildOrder":"175","reportName":"AllureReport","name":"Jenkins","buildUrl":"https://jenkins.xxx.xxx:xxxx/job/test-xxx-xxxx/175/","reportUrl":"https://jenkins.xxx.xxx:xxxx/job/test-xxx-xxxx/175/allure","type":"jenkins","url":"https://jenkins.xxx.xxx:xxxx/"}

This info in this JSON seems enough to me to create the links. Could it be a Jira setting?

Thank you in advance,
Patrick

**Comment by pkievit86** [comment]
@eroshenkoam you would be my superman if you are able to answer this?

Adding a little bit of info next to my first problem discription. This is what my console says in jenkins:

Allure launch '[PRTL-4530]' synced with issues  successfully

Results of launch export 
 [JiraExportResult(issueKey=PRTL-4530, externalId=Testing, status=ok, message=null)]
All Test Results have been successfully exported to Jira

In Jira: 
I do see a generated id [OK],
name is the scenario name from my feature file [OK],
Launch is my project name form pom.xml [NOT OK, would rather see feature file name which is nice to have],
Date and status pass or fail are present [OK]

These are not backlinks, which doesn not allow me to open the report from JIRA. This I find super usefull.

**Comment by pkievit86** [comment]
allure.properties
allure.results.directory=target/allure-results
allure.link.issue.pattern=https:///jira.xxx.xxx.xxx.nl/browse/{}
allure.link.tms.pattern=https:///jenkins.xxx.xxx:xxxx/view/Testing/job/{}
allure.model.indentOutput=true
allure.label.epic=project.description

**Comment by pkievit86** [comment]
allure.yml
plugins:
  - junit-xml-plugin
  - xunit-xml-plugin
  - trx-plugin
  - behaviors-plugin
  - packages-plugin
  - screen-diff-plugin
  - xctest-plugin
  - jira-plugin
  - xray-plugin

**Comment by pkievit86** [comment]
Feature file (This might be different from any one else, I am point to features from a feature file, not on top of a method.)

@FeatureTag
@tmsLink=test-xx-xxxx
@issue=PRTL-4530
@Link=https://example.org
@Severity=Blocker
Feature: WS xxxxxxx
  Description: Contains all kinds of tests related to WS xxxxx used by xx xxx

  Scenario: TC01 Happy flow minimum set with only required fields

    Given xxxxxxx request headers are set

**Comment by pkievit86** [comment]
pipeline {
    agent {label 'xxxx'}
    
    environment {
        ALLURE_JIRA_LAUNCH_ISSUES = 'PRTL-4530'
        ALLURE_JIRA_ENABLED = 'true'
        ALLURE_JIRA_ENDPOINT = 'https://jira.xxx.xxx.xxx.nl/rest/'
        ALLURE_JIRA_USERNAME = 'xxxx'
        ALLURE_JIRA_PASSWORD = 'xxxxx'
    }

    stages {
        stage ('Checkout Test Sources') {
            steps {
                git branch: 'master',
                credentialsId: 'Git Credentials',
                url: 'git@xxxxxx.git'
            }

        }
        
        stage('Test Execution') {
             steps {
             
             withMaven(options: [artifactsPublisher(disabled: true)],
                 maven: 'MAVEN_HOME')  {
                 sh "mvn clean test -Dtest=xxxxxx,_FailedTests* -Denv=test allure:report"
                 }
            }

**Comment by pkievit86** [comment]
I have an execution.json generated but it looks like I need an executor.json.

**Comment by pkievit86** [comment]
It is also difficult to debug, perhaps it is possible to support proxy configuration to intercept http traffic to jira.

**Comment by pkievit86** [comment]
I installed Jenkins and Jira and set it up to run my test.

As you can see above I am calling allure:report with my mvn test command. this makes the executor.json contain Maven build info. Not the Jira build info necessary for the backlinks.

The allure plugin in Jira creates the executor.json with jenkins build info. 

Perhaps I can find a way to configure allure jenkins plugin to trigger the exportTestResult to jira. 

Any tips are welcome.

**Comment by pkievit86** [comment]
I am now using the allure cli to export test results to jira. This makes it possible to use the executor.json with backlink information.

**Comment by hotdog666** [comment]
@pkievit86 , Hi, can you tell us in more detail how you solved the problem?Please)

**Comment by pkievit86** [comment]
@hotdog666 I will post my solution for you tomorrow. Happy Easter!

**Comment by hotdog666** [comment]
@pkievit86 Hi, is everything okay?

**Comment by pkievit86** [comment]
@hotdog666 all is fine thanks. I hope you are too.

The solution was to trigger the allure jira-plugin (generate the report) after the test was executed by maven. 

Initially I had maven generate the report, see below stage test execution:
    stage('Test Execution') {
         steps {
         
         withMaven(options: [artifactsPublisher(disabled: true)],
             maven: 'MAVEN_HOME')  {
             sh "mvn clean test -Dtest=xxxxxx,_FailedTests* -Denv=test **allure:report**"
             }
        }

I decided to remove the allure:report command from the mvn command. And I added an extra stage after the test were finished. And let Jenkins generate a report. Because jenkins puts the right information for the backlinks in the executor.json and maven does not. To do this, I am using the allure cli. Here is how it looks now.

    stage('Test Execution') {
         steps {
         
         withMaven(options: [artifactsPublisher(disabled: true)],
             maven: 'MAVEN_HOME')  {
             sh "mvn clean test -Dtest=xxxxxx,_FailedTests* -Denv=test"
             }
        }
    }

    stage('Generate Test Report') {
        environment {
                ALLURE_JIRA_LAUNCH_ISSUES = 'PRTL-4529'
                ALLURE_JIRA_ENABLED = 'true'
                ALLURE_JIRA_ENDPOINT = 'https://jira.xxx.xxx.xxxx.xx/rest/'
                ALLURE_JIRA_CREDS = credentials('jira-user-xxxx')
                ALLURE_JIRA_USERNAME = "$ALLURE_JIRA_CREDS_USR"
                ALLURE_JIRA_PASSWORD = "$ALLURE_JIRA_CREDS_PSW"
            }

            steps {

                script {
                    allure([
                        includeProperties: true,
                        jdk: '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.e17_7.x86_64',
                        commandline: 'allure',
                        configPath: '/var/lib/jenkins/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/allure/config/allure.yml',
                        properties: [],
                        reportBuildPolicy: 'ALWAYS',
                        results: [[path: 'target/allure-results']]
                    ])
                }
                sh "/var/lib/jenkins/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/allure/bin/allure generate --configDirectory /var/lib/jenkins/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/allure/config /var/lib/jenkins/workspace/test-xxx/target/allure-results -c -o /var/lib/jenkins/workspace/test-xxx/allure-report"
                cleanWs()
            }
         }
         
I hope this helps.

**Comment by pkievit86** [comment]
@hotdog666 did my solution answer your question?

**Comment by hotdog666** [comment]
@pkievit86 Hello, unfortunately no
