### ISSUE TITLE
SAAS Offer

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [allure-framework/allure2#1206]
**Is your feature request related to a problem? Please describe.**

Not related to any particular Problem

**Describe the solution you'd like**

That you provide a SAAS Offer for Allure, with Off the shelf Github OAuth2 n integration with Public Circle CI for example

**Describe alternatives you've considered**

Not found yet, but will look for any SAAS Offer for a  Reporting Solution with Web ui, and customizable dashaboard, according custom metrics

**Additional context**

I love the work you have done the last 3 years. At the company I work for, We need  a SAAS Offer for a product with Allure Framework Feature: Exactly what they need, but if we have to manage a server (the infrastructure under there, then it probably will be a no (99% percent sure). Not that we do not do infrastructure, but the thing is we have so many infrastructure to deal in so many projects, ...

And I am sure you will get tons a pof ne w users if you offer SAAS, and stay open source

Maybe I did not look around enough : do you have any partner who can provide support to manage the infra under allure ? Cloud providers market places ? My company willing to pay to get rid of  infrastructure management under allure

**Comment by baev** [comment]
Allure TestOps looks like a solution you are looking for. Currently only on-premise installations are available, Cloud installation is in beta (ETA within 2 month) 
See https://qameta.io for details.

**Comment by baev** [comment]
btw, limited time offer: you can check out demo at https://heisenbug.allure.aws.qameta.in/

**Comment by Jean-Baptiste-Lasselle** [comment]
@baev thank you so much for this quick answer : can I be added to a notification list / wait list for SAAS offer ? my company is https://github.com/gravitee-io https://gravitee.io . 2 months we work with on premise to validate all our needs, and if we can be sure in 2 month we get full solid SAAS, It might fit in

**Comment by baev** [comment]
@Jean-Baptiste-Lasselle could you please fill the form https://qameta.io/we-need-bespoke-solution/ and comment that you are looking for SAAS offer? 

PS I'll remove your comment with private data
