### ISSUE TITLE
Allure Report after upgrading started to show wrong Rest Assured filter logs (instead of showing 400/500 it shows 200)

### ISSUE THREAD

**Issue by abayibrayev1** [allure-framework/allure2#1208]
**Describe the bug**
Allure report shows 200 http in log header, even if status of response 400 or 500
as on screenshot: 
![image](https://user-images.githubusercontent.com/72020645/115019181-a7310980-9eda-11eb-953e-d8e11e11c8e5.png)

Error started occuring after upgrading dependencies versions: 
1. Allure 2.13.6 -> 2.13.9
2. Rest assured 4.3.1 -> 4.3.3 

**To Reproduce**
1. Run tests with failed cases 400 or 500 
2. Check rest assured response logs (filter) 

**Expected behavior**
It should show 400 or 500 on response header

**Screenshots**
![image](https://user-images.githubusercontent.com/72020645/115019181-a7310980-9eda-11eb-953e-d8e11e11c8e5.png)

**Environment (please complete the following information):**

| Allure version | 2.13.9 |
| Test framework | testng@7.4.0 & cucumber@6.10.2 |
| Allure adaptor | allure-cucumber6-jvm@2.13.9 & allure-rest-assured@2.13.9 |
| Generate report using | allure-gradle@2.8.1 | plugin

**Comment by lesnik0909** [comment]
Solved in [#679](https://github.com/allure-framework/allure-java/pull/679)
