### ISSUE TITLE
Allure 2.0 beta documentation

### ISSUE THREAD

**Issue by rab2215** [allure-framework/allure2#122]
I see there is a beta3 version of allure 2.0, but I'm confused on how it's expected to be implemented.  I see several features on the roadmap show as completed, so is there any documentation of their use?

**Comment by baev** [comment]
> so is there any documentation of their use?

Not yet. We are working on it.

**Comment by baev** [comment]
Will be available here 

https://github.com/allure-framework/allure-docs
https://docs.qameta.io/allure/2.0/

**Comment by baev** [comment]
In general documentation is available. You can help us to improve it by sending PR to https://github.com/allure-framework/allure-docs
