### ISSUE TITLE
【bug】Pytest-check is not compatible with allure

### ISSUE THREAD

**Issue by jamesz2011** [allure-framework/allure2#1243]
![image](https://user-images.githubusercontent.com/16397200/116810331-cb951300-ab75-11eb-9ee3-f811517c5c29.png)

**Comment by jamesz2011** [comment]
【example-code】
`# coding=utf-8

import allure
import pytest
import pytest_check as check


@allure.feature("演示demo")
def test_jisuan1():
    # assert 1 == 1
    check.equal(1, 1)

def test_jisuan2():
    # assert 1 == 11
    check.equal(1, 11)


def test_hello2():
    # assert 12 == 12
    check.equal(12, 12)


if __name__ == '__main__':
    #pytest.main(['-sv', "testCase/test_branch.py"])
    pass`

----------------------------
【the version of library】

- pytest ： v6.2,4
- pytest-check ： 1.0.1
- allure -pytest: v2.9.42
- allureFramework : v2.13.9

**Comment by aleksandr-kotlyar** [comment]
@jamesz2011 thank you for details! Had you seen the link I have sent above?
> Seems to be fixed in pytest-check library [okken/pytest-check#66](https://github.com/okken/pytest-check/pull/66)
> and can be closed here.

It tells that fix was at 12 august and if you look at pytest-check releases - 12 august they made a 1.0.2 version of pytest-check with this fix. So you need to check 1.0.2 version or 1.0.4 latest. - They have resolved this issue in their library.
![image](https://user-images.githubusercontent.com/17043964/134948742-be2fcfa4-6404-4d3f-8d84-1fad737bdee3.png)

**Comment by jamesz2011** [comment]
@aleksandr-kotlyar  bug fixed,thanks
![image](https://user-images.githubusercontent.com/16397200/135003318-68aba9be-bb99-40bb-9816-ee8658f85b4e.png)
