### ISSUE TITLE
Download Allure task failing

### ISSUE THREAD

**Issue by AshwaniPratap8** [allure-framework/allure2#1245]
Hi Team,

In our Jenkins pipeline, we are getting the following error which is causing the task failure.

Execution failed for task ':downloadAllure'.
> Can't get https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.7.0/allure-2.7.0.zip to /home/jenkins/workspace/plugins_cdd-msteams-plugin_1.2-3/build/allure-2.7.0.zip

Please look into this and suggest the resolution.

Thanks!
Ashwani

**Comment by davidfordaus** [comment]
Still failing 5 days later.  Can this be resolved URGENTLY please?

**Comment by azakordonets** [comment]
Check this [out](https://qameta.io/blog/03-30-2021_allure_migration/)

**Comment by davidfordaus** [comment]
Thanks @azakordonets  - and I've managed to resolve it and install Allure via the binary downloads, however it seems bizarre that the main website below still refers to bintray as does the Scoop installer.    If allure has shifted to Artifactory then the site page should be updated and the Scoop URL's should also be modified.  The URL below is still incorrect:
https://github.com/allure-framework/allure2
