### ISSUE TITLE
URGENT : Bintray download is failing. Scoop installer is failing (even 5 days later)

### ISSUE THREAD

**Issue by davidfordaus** [allure-framework/allure2#1250]
The bintray resource is 404'ing

**To Reproduce**
* Use scoop - fails with "The remote server returned an error: (403) Forbidden.
URL https://dl.bintray.com/qameta/maven/io/qameta/allure/allure-commandline/2.13.9/allure-commandline-2.13.9.zip is n
ot valid"

**Expected behavior**
That qameta would have institued monitoring in normal devops fashion to ensure that they'd know immediately the link was failing

**Comment by baev** [comment]
@davidfordaus you can download Allure from Maven Central https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline or from Github Releases https://github.com/allure-framework/allure2/releases/tag/2.13.10

Scoop related issue https://github.com/ScoopInstaller/Main/pull/354/files
