### ISSUE TITLE
After migrating from 2.13.9 to 2.13.10 generated report is empty

### ISSUE THREAD

**Issue by andrzejpitala** [allure-framework/allure2#1284]
**Describe the bug**

**To Reproduce**
I'm using a gradle task to run my tests (junit5+Fluentlenium) and than generate allure report using a graddle task provided by allure-gradle plugin. After I megrated from version 2.13.9 to 2.13.10 the generated index.html file is displayed as white blank page. There is also js error in console while opening this file pointing to some error in app.js file. Attached screenshot with error.

**Expected behavior**
Report looks the same as for previous version

**Screenshots**
Attached screenshot with errors in cosole
![Allure_2 13 10_console_error](https://user-images.githubusercontent.com/48099286/118653939-561d7980-b7e8-11eb-87e1-232915201e32.png)

**Environment (please complete the following information):**

| Allure version | 2.13.10 |
| --- | --- |
| Test framework | junit5@5.7.2 |
| Allure adaptor | allure-junit5@2.13.10 |
| Generate report using | allure-gradle@2.8.1 |

**Additional context**

**Comment by baev** [comment]
2.13.10 is completely broken, the issue already fixed to date via https://github.com/allure-framework/allure2/pull/1276 , release scheduled for today

**Comment by baev** [comment]
fixed in https://github.com/allure-framework/allure2/releases/tag/2.14.0
