### ISSUE TITLE
open report url by used phantomjs throw error

### ISSUE THREAD

**Issue by Linhan-Shenzhen** [allure-framework/allure2#1291]
1. jenkins + allure generated report
2. use phantomjs openpage report url to get screenshot
3. phantomjs getscreen.js  
var page=require('webpage').create();
page.open("http://10.0.*.*:8099/job/heyUITest/20/allure/",function(status){
	if(status!=='success'){
		console.log('Unabletoloadtheaddress!');
		phantom.exit();
	}else{
		window.setTimeout(function(){
			page.clipRect={top:0, left:0, height: 500, width: 990};  // 设置页边距，从而获取想要的图片，需要慢慢调整
			page.render(output);  // 保存图片
			phantom.exit();
		},20000);
	}
});

4. throw error:

ReferenceError: Can't find variable: Promise

  http://10.0.*.*:8099/job/heyUITest/20/allure/app.js:39 in value
  http://10.0.*.*:8099/job/heyUITest/20/allure/app.js:39 in getGlobalSettings
  http://10.0.*.*:8099/job/heyUITest/20/allure/app.js:39
  http://10.0.*.*:8099/job/heyUITest/20/allure/app.js:1 in __webpack_require__
  http://10.0.*.*:8099/job/heyUITest/20/allure/app.js:39
  http://10.0.*.*:8099/job/heyUITest/20/allure/app.js:1 in __webpack_require__
  http://10.0.*.*:8099/job/heyUITest/20/allure/app.js:1
  http://10.0.*.*:8099/job/heyUITest/20/allure/app.js:1 in __webpack_require__
  http://10.0.*.*:8099/job/heyUITest/20/allure/app.js:39
  http://10.0.*.*:8099/job/heyUITest/20/allure/app.js:1 in __webpack_require__
  http://10.0.*.*:8099/job/heyUITest/20/allure/app.js:60
  http://10.0.*.*:8099/job/heyUITest/20/allure/app.js:1 in __webpack_require__
  http://10.0.*.*:8099/job/heyUITest/20/allure/app.js:1
ReferenceError: Can't find variable: allure

  http://10.0.*.*:8099/job/heyUITest/20/allure/plugins/behaviors/index.js:3 in global code
ReferenceError: Can't find variable: allure

  http://10.0.*.*:8099/job/heyUITest/20/allure/plugins/packages/index.js:3 in global code

**Comment by baev** [comment]
phantomjs has been deprecated in favor of headless chrome
