### ISSUE TITLE
uncaught typeerror:p.a.registerlanguage is not a function

### ISSUE THREAD

**Issue by jingling900226** [allure-framework/allure2#1294]
**Describe the bug**

**To Reproduce**
1. run pytest case;
2. allure generate xml -o html
3. allure open html
4. page is empty, step F12,console display:uncaught typeerror:p.a.registerlanugage is not a function     and    uncaught referenceerror:allure is not defined

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

| Allure version | 2.9.0 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.9.0 |
| Generate report using | allure-maven@2.18 |

**Additional context**

**Comment by baev** [comment]
fixed in 2.14.0
