### ISSUE TITLE
Unexpected information which should not be sorted

### ISSUE THREAD

**Issue by IssacH** [allure-framework/allure2#1308]
Hi @vlsi @robot-c0der @cakeinpanic @simple-elf @lukaville 

I have some information in my generated xml file, e.g. 

`<parameter kind='argument' name='Step' value='Z'/>`
`<parameter kind='argument' name='Step' value='Y'/>`
`<parameter kind='argument' name='Step' value='A'/>`

After executing the allure command line, I found the content is sorted by ASC code in the data json file
`"parameters" : [ {`
    `"name" : "Step",`
   ` "value" : "A"`
  `}, {`
    `"name" : "Step",`
    `"value" : "Y"`
`  }, {`
   ` "name" : "Step",`
   ` "value" : "Z"`
 `}].`

So in the final html report, the information will be displayed as "A", "Y", "Z", while the expected behavior should be "Z","Y","A".

Is it possible to set some configuration to allure command line so that the content will not be sorted? Or is there any workaround  to change java code?(e.g. where the xml is analyzed in java code)

**Comment by baev** [comment]
Allure doesn't preserve parameters order. I can't see the way to bypass it somehow
