### ISSUE TITLE
Demo report

### ISSUE THREAD

**Issue by Bakanych** [allure-framework/allure2#131]
Hi all,
where can I find Allure 2 demo report to check this out?

**Comment by baev** [comment]
https://ci.qameta.in/job/allure2_deploy/Allure/

**Comment by sskorol** [comment]
@baev there're no permissions to view

**Comment by irushah** [comment]
+1

**Comment by baev** [comment]
https://qameta.io/allure/demo/

**Comment by thakar27** [comment]
Hi,
I am using allure version 1.4.23 and i am trying to integrate with Jenkins 
When in build the job, i am getting this issue
Invalid ALLURE_HOME: /E:\jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\Allure-Commandline-1.4.23 is not a valid allure commandline directory 

Can somone please help with this issue

**Comment by eroshenkoam** [comment]
will be fixed in next release: https://github.com/jenkinsci/allure-plugin/issues/108
