### ISSUE TITLE
pytest + allure Generate the report and open local. JS reports an error

### ISSUE THREAD

**Issue by 000xiaoxiao000** [allure-framework/allure2#1339]
allure version 2.14.0
![image](https://user-images.githubusercontent.com/39261902/124568043-1df4f780-de77-11eb-8209-6ae3c1783a54.png)
After the test case is executed, there are JSON files in the directory, and then execute 'allure generate the JSON file directory    -o ./report --clean', allure generates the test report, opens the page blank, and JS reports an error, 
![111](https://user-images.githubusercontent.com/39261902/124568991-1eda5900-de78-11eb-856c-79286fd36427.png)
![222](https://user-images.githubusercontent.com/39261902/124569003-21d54980-de78-11eb-95a4-a74993a8fedc.png)

**Comment by baev** [comment]
https://stackoverflow.com/questions/23997449/allure-report-nothing-shown-in-chrome/24002146#24002146
