### ISSUE TITLE
Needs method for adding clickable links to allure report (js|wdio)

### ISSUE THREAD

**Issue by nikaswoon** [allure-framework/allure2#1347]
Like in python
<img width="1027" alt="Screenshot 2021-07-13 at 11 48 45" src="https://user-images.githubusercontent.com/55055584/125421875-4d44d83b-1024-4290-9b5f-a9edfbe8f7d3.png">

**Comment by baev** [comment]
fixed in new WDIO integration, see https://allurereport.org/docs/webdriverio-reference/#link
