### ISSUE TITLE
Flaky bomb icon missing from flaky tests

### ISSUE THREAD

**Issue by eldbud** [allure-framework/allure2#1369]
When using the pytest-rerunfailures plugin, either by cli parameter or by the @pytest.mark.flaky(reruns=some_int), flaky tests are rerun, their previous failed runs are displayed in the "Retries" tab (except for the current run), but no Flaky-Bomb icon is anywhere to be seen. 
Also when toggling the bomb filter, the flaky tests are not filtered into the filtered view (it is empty).
Seems that the flaky test is not marked as flaky, thus the icon does not appear?

![flaky](https://user-images.githubusercontent.com/76731410/127848713-98563d13-7621-4ae7-9bf6-1713562fe428.png)

Environment :
Python 3.8.1
Allure version: 2.14.0 
Test framework: pytest@6.0.1; pytest-rerunfailures@10.1
Allure adaptor: allure-pytest@2.9.43

**Comment by baev** [comment]
since 2.16 Allure has a new test mark called "Status changed after retry". It does exactly what you're looking for.

**Comment by eldbud** [comment]
thanks. where can i see docs/usage example of this test mark, so i can understand what is its proper name and how to use it? (googling "Status changed after retry" allure mark did not yield any relevant info)

**Comment by baev** [comment]
There is no docs available yet. You can find some info in related pull request tho https://github.com/allure-framework/allure2/pull/1467
