### ISSUE TITLE
[Allure+AWS Device Farm+Python]: Empty allure report is generated under downloaded 'Customer Artifacts' when automated test are run under AWS device farm

### ISSUE THREAD

**Issue by dish25** [allure-framework/allure2#1376]
**Describe the bug**
[Allure+AWS Device Farm+Python]: Empty allure report is generated under downloaded 'Customer Artifacts' when automated test are run under AWS device farm

**To Reproduce**
1. Go to AWS device farm
2.  Create a automated testrun
3. Upload .apk file(Android)
4.  Select Test type as: Appium Python
5. Uploaded zip file containing( requirements.txt file, the tests folder and the pages folder)
5.1 "requirements.txt" contains details of packages(Packages related to allure: allure-pytest==2.8.40, allure-python-commons==2.8.40)
6. Uploaded a custom .yml configuration file(Command used under "tests"
python3 -m pytest tests/ --alluredir=$DEVICEFARM_LOG_DIR/allure-results [Attached .yml file for reference
[custom_ConfigFile_YML.txt](https://github.com/allure-framework/allure2/files/6962221/custom_ConfigFile_YML.txt)
]
7. Completed other details and executed the run
8. Access "Customer Artifacts" generated under "Test suite" section
9. Download, extract and generated the allure report(from .json files)
10. On allure serve. Empty allure report is generated.

**Expected behavior**
Allure report should get generated.

**Screenshots**
![allure_ISSUE](https://user-images.githubusercontent.com/69243634/128881945-f84d7992-9d8f-4dac-9ca9-c0e23a40c690.jpg)

NOTE: Is there any step that I might be missing in order to generate allure reports. Please take a look and let me know if any other information is required on this. Thank you so much for your help!

**Comment by dish25** [comment]
Hi Team,

Is there any update on this? Thank you!

**Comment by baev** [comment]
That's definitely not an issue in Allure. From your description:

- Step 9, you generate the report from json files
- Step 10, you are using `serve` command. That's could be an issue. Serve command expects directory with Allure Results (json files), it generates the report into temp directory and then serves it using Jetty. If you already have a generated report, you may want to use `open` command instead (`serve` = `generate` + `open`)
