### ISSUE TITLE
AspectJ Internal Error: unable to add stackmap attributes. Unsupported class file major version 58

### ISSUE THREAD

**Issue by Vijay0207** [allure-framework/allure2#1378]
How to attach "Steps" and "Screenshots" in to allure ?

Requirement:

Ability to add "@Step" and "@Attachment" to the report. If my understanding is correct, it works with the presence of AspectJ added as a VM argument.
Currently, these are not getting logged into the report.

What do I have in POM?

<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M5</version>
                <configuration>
                    <trimStackTrace>false</trimStackTrace>
                    <suiteXmlFiles>
                        <suiteXmlFile>${suiteFile}</suiteXmlFile>
                    </suiteXmlFiles>
                    <testFailureIgnore>true</testFailureIgnore>
                    <skipTests>${skipTests}</skipTests>

                    <argLine>
                        -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"

                    </argLine>
                    <systemProperties>
                        <property>
                            <name>listener</name>
                            <value>io.qameta.allure.testng.AllureTestNg</value>
                        </property>
                        <property>
                            
                            <name>allure.results.directory</name>
                            <value>${project.build.directory}/target/allure-results</value>
                        </property>
                    </systemProperties>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.apache.maven.surefire</groupId>
                        <artifactId>surefire-testng</artifactId>
                        <version>3.0.0-M5</version>
                    </dependency>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                </dependencies>
            </plugin>

Aspect Jversion: 

        <aspectj.version>1.9.7</aspectj.version>

Error:

AspectJ Internal Error: unable to add stackmap attributes. Unsupported class file major version 58
[ERROR] Expecting a stackmap frame at branch target 113

Environment:

JAVA : 14
Maven: Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
and others....
   <maven.compiler.release>14</maven.compiler.release>
        
        <jdk.source.version>14</jdk.source.version>
        <jdk.target.version>14</jdk.target.version>
        <skipTests>false</skipTests>
        <allure.version>2.13.2</allure.version>
        <testng.version>7.1.0</testng.version>
        <selenium.version>4.0.0-beta-2</selenium.version>

**Comment by baev** [comment]
the issue isn't related to Allure. Most likely you misconfigured your aspectj version. According to https://htmlpreview.github.io/?https://github.com/eclipse/org.aspectj/blob/master/docs/dist/doc/README-197.html AspectJ `1.9.7` supports Java `14`.
