### ISSUE TITLE
[Adaptors] xUnit

### ISSUE THREAD

**Issue by arpit-nagar** [allure-framework/allure2#139]
Sample xUnit File : [test-report.txt](https://github.com/allure-framework/allure-core/files/272782/test-report.txt)

**Comment by baev** [comment]
https://xunit.github.io/docs/format-xml-v2.html

**Comment by arpit-nagar** [comment]
Any updates on this ??

**Comment by arpit-nagar** [comment]
Any updates on this ??

**Comment by arpit-nagar** [comment]
Do you have any timelines on this ??

**Comment by baev** [comment]
Our community are working on this, but I don't think that this gonna be fixed in next few months

**Comment by arpit-nagar** [comment]
Can you please suggest... How to use generate report for Xunit result file.

**Comment by baev** [comment]
> Can you please provide compiled version of this to test?

Change available in 2.1.1. To use it with Jenkins make sure you have directory with xunit.xml files. All files names should have `.xml` suffix. Then configure Allure Jenkins Plugin according to documentation https://docs.qameta.io/allure/2.0/#_jenkins . Then use Allure Report publisher to generate the report (and specify the directory with xunit.xml results)

**Comment by arpit-nagar** [comment]
Thanks baev for quick response.

**Comment by baev** [comment]
@arpit-nagar is it works for you?

**Comment by DITLPANW** [comment]
Hi All,
Can you please explain how to use allure2 to generate report for Xunit result file in teamcity? 
10x!

**Comment by eroshenkoam** [comment]
First of all you need to run your tests. 
After that you need to find directory with xunit `*.xml` file, for example `target/surefire-reports` (maven)
In teamcity just configure build step with *Results path* value `target/surefire-reports`

**Comment by DITLPANW** [comment]
![image](https://user-images.githubusercontent.com/29203401/29523956-3933d2f0-8697-11e7-964d-988157f30e1a.png)
Can you tell me how to install the "allure-commandline" on TeamCity agent ?

**Comment by baev** [comment]
@DITLPANW please use our Gitter https://gitter.im/allure-framework/allure-core / StackOverflow tag allure for such questions
