### ISSUE TITLE
In Azure Dev ops certain pipelines that are run produce allure reports but some of our pipelines don't produce allure reports 

### ISSUE THREAD

**Issue by Seantracey** [allure-framework/allure2#1396]
When we are running are pipelines in Azure Dev Ops Cloud. Some pipelines are producing allure reports while others do not produce allure reports. We are trying to figure what the reason for this may be...

**Comment by baev** [comment]
please use one of our support channels for such type of questions

**Comment by Seantracey** [comment]
Can you share the link for any of these support channels ?

**Comment by baev** [comment]
https://github.com/allure-framework/allure2/discussions
stackoverflow tag `allure`
https://gitter.im/allure-framework/allure-core
