### ISSUE TITLE
Polish translation bugs

### ISSUE THREAD

**Issue by wookieJ** [allure-framework/allure2#1461]
**Describe the bug**
Found some bugs in polish translations

**To Reproduce**
1. Go to server GUI

**Expected behavior**
Correctly translated words

**Screenshots**

![Zrzut ekranu 2021-10-18 o 23 13 19](https://user-images.githubusercontent.com/34069409/137807684-99a37e29-210c-4cf9-8de5-c317f226fb53.png)

**Environment (please complete the following information):**

| Allure version | 2.9.0 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.9.0 |
| Generate report using | allure-maven@2.18 |

**Comment by baev** [comment]
@wookieJ thanks for all the contributions ❤️
