### ISSUE TITLE
Substep name and duration is not aligned due to SCSS rule removal in 2.17.2

### ISSUE THREAD

**Issue by dmg0345** [allure-framework/allure2#1533]
**Describe the bug**
The time field in a substep is no longer aligned with the title of the substep.

**To Reproduce**
Execute a test that has a step with a substep, serve the report and expand the step.

**Expected behavior**
It should be aligned.

**Screenshots**
![image](https://user-images.githubusercontent.com/95141959/146676990-0e23c112-7c50-45fd-8d30-68d807647cb3.png)

**Environment (please complete the following information):**

| Allure version | 2.17.2 |

**Additional context**
Replacing the div with a span makes it to be aligned again: 

![image](https://user-images.githubusercontent.com/95141959/146677072-ff8c8d59-3b0f-4ce8-8a8a-dab056a865b4.png)

I think it might be related to changes in, specifically the SCSS in this commit:

https://github.com/allure-framework/allure2/commit/c78d0b32f604a5c1536a8625deb34b2ea783c5b9#diff-9203e3ad102b245357a92d25dfada06fc29b52e5c1d3d5c0b69cb1afef3d8872

**Comment by baev** [comment]
should be fixed by now
