### ISSUE TITLE
Typo in POM on documentation page

### ISSUE THREAD

**Issue by mpaasternak** [allure-framework/allure2#1549]
Started using your framework recently however on your page: https://docs.qameta.io/allure-report/frameworks/java/junit5 and in your POM you missed closing sign in dependency. Tried using button 'Edit on Github' however it leads to 404 page.
![typo](https://user-images.githubusercontent.com/58792624/148807961-3ee4c723-1536-45b6-bddd-b25d267b34d5.png)

**Comment by baev** [comment]
fixed in new doc https://allurereport.org/docs/junit5/
