### ISSUE TITLE
Add method in getLifecycle() new method to update description of last sub-step

### ISSUE THREAD

**Issue by stru4OK** [allure-framework/allure2#1559]
Good afternoon!
In my project I used following stack technology: Java, Junit4, Maven, Selenide (dependency allure-selenide), Allure report, Selenoid.

**Is your feature request related to a problem? Please describe.**
Main purpose: hide sensitive data in Allure Report such as the password. For example:

Selenide element

`$x("//div[@class='t-Form-itemWrapper']/input[contains(@id,'PASSWORD')]").as("Password input").sendKeys(password);`

reflects in Allure reports as follows:

`$("Password input") send keys(<my_password>)
`

![allure](https://user-images.githubusercontent.com/71832617/149924016-9917281e-2b61-40f1-9eba-963012442534.jpg)

**Describe the solution you'd like**
It will be very helpful sometimes to get rid of such sensitive data from the eyes of others.

**Describe alternatives you've considered**
I tried to change directly in allure report json file string contains my password automatically, but allure report is created straight after test execution hence I can't find json report file.

Thank you for help and suggestion!

**Comment by baev** [comment]
you can use `io.qameta.allure.listener.StepLifecycleListener` or `io.qameta.allure.listener.TestLifecycleListener` to do so. This listeners is configured via SPI and can be used to modify the test data in runtime.

## An example of using `TestLifecycleListener`

the following listener can be used to prettify test names.

So for method `org.example.DbUtilsTest.shouldTrimAfterSubstring` instead of 
`shouldTrimAfterSubstring`  will be displayed `Db utils should trim after substring` in the report `: 

```java
public class AllureNaming implements TestLifecycleListener {

    @Override
    public void afterTestSchedule(final TestResult result) {
        if (Objects.isNull(result.getLabels())) {
            return;
        }

        result.getLabels().stream()
                .filter(l -> ResultsUtils.TEST_CLASS_LABEL_NAME.equals(l.getName()))
                .map(Label::getValue)
                .filter(Objects::nonNull)
                .findFirst()
                .ifPresent(testClass -> {
                    final String[] split = testClass.split("\\.");
                    final String shortClassName = split[split.length - 1];

                    final String i1 = StringUtils.removeEnd(shortClassName, "Test");
                    final String i2 = Arrays.stream(StringUtils.splitByCharacterTypeCamelCase(i1))
                            .filter(StringUtils::isNotBlank)
                            .collect(Collectors.joining(" "));
                    final String i3 = StringUtils.lowerCase(i2);
                    final String classPart = StringUtils.capitalize(i3);


                    final String s1 = result.getLabels().stream()
                            .filter(l -> ResultsUtils.TEST_METHOD_LABEL_NAME.equals(l.getName()))
                            .map(Label::getValue)
                            .filter(Objects::nonNull)
                            .findFirst()
                            .orElseGet(result::getName);

                    final String s2 = Arrays.stream(StringUtils.splitByCharacterTypeCamelCase(s1))
                            .filter(StringUtils::isNotBlank)
                            .collect(Collectors.joining(" "));

                    final String methodPart = StringUtils.lowerCase(s2);

                    result.setName(classPart + " " + methodPart);
                });
    }
}

```

**Comment by stru4OK** [comment]
Thank you very much!
But could you give me a short tip how the listener could be added in project based on Junit4 because I'm not completely understand?
Thank you!
