### ISSUE TITLE
Fix status graph tooltip

### ISSUE THREAD

**Issue by baev** [allure-framework/allure2#156]
<img width="185" alt="screen shot 2017-02-14 at 19 06 59" src="https://cloud.githubusercontent.com/assets/2149631/22937172/e44008d2-f2e8-11e6-88b3-d8f9e4f58fd7.png">

**Comment by baev** [comment]
Also tooltip for `unknown` is not shown

**Comment by sseliverstov** [comment]
<img width="157" alt="2017-02-14 21 32 53" src="https://cloud.githubusercontent.com/assets/19683904/22942935/fe93db3e-f304-11e6-8203-c07d61e7e107.png">

in my case is ok with tooltip for unknown
