### ISSUE TITLE
Documentation: broken links

### ISSUE THREAD

**Issue by MorskeOko** [allure-framework/allure2#1580]
Documentation has broken anchor links in text with 404 responce

1. Go to (https://docs.qameta.io/allure/)
2. Go to "1.3. How to Proceed"
3. Click on [Get started](https://docs.qameta.io/allure/latest/#_get_started) 
5. Click on [report structure and features](https://docs.qameta.io/allure/latest/#_report_structure).
6. See error

**Expected behavior**
On click on the link the relevant doc opens

**Screenshots**
![404](https://user-images.githubusercontent.com/52323501/153166609-bc253c20-daf7-4022-b7dc-c320f657a6a5.png)

**Environment (please complete the following information):**

Allure documentation web site

**Comment by baev** [comment]
thanks, fixed
