### ISSUE TITLE
Duable test case name in parameterized tests

### ISSUE THREAD

**Issue by andrgn** [allure-framework/allure2#1600]
**Describe the bug**
After upgrade allure dependency to 2.17.X version there is duable test case name in parameterized tests in report

**To Reproduce**
1. Clone [allure-kotlin-junit5-gradle-kts](https://github.com/allure-examples/allure-kotlin-junit5-gradle-kts)
2. Upgrade `allureVersion` variable to `2.17.3` in `build.gradle.kts` file
3. Run `gradle clean test` command
4. Generate allure report via `gradle allureReport` command
5. Open generated report
6. Find `allureParameterizedTest displayName` results
7. See double test case name `allureParameterizedTest displayName allureParameterizedTest displayName [Second Name]` (I suppose, first part `allureParameterizedTest displayName` from `@DisplayName` and second part `allureParameterizedTest displayName [Second Name]` from `@ParameterizedTest`)

**Expected behavior**
Only one test name `allureParameterizedTest displayName [Second Name]` like in `2.16.1` version (it was last version where correct behavior appears)

**Screenshots**
```
class AllureParameterizedTest {

    @ParameterizedTest(name = "{displayName} [{argumentsWithNames}]")
    @ValueSource(strings = ["First Name", "Second Name"])
    @DisplayName("allureParameterizedTest displayName")
    @Description("allureParameterizedTest description")
    fun allureParameterizedTest(testParam: String) {
        Allure.parameter("testParam", testParam)
        Allure.step("Step inside parameterized test")
        Allure.step("Test parameter: $testParam")
    }

    @Test
    fun allureFakeParameterizedTest() {
        Allure.parameter("fakeParam", "fakeValue")
        Allure.step("Step inside fake parameterized test")
    }

}
```
![allure](https://user-images.githubusercontent.com/23133790/155845470-039bad52-e8ea-44c4-b923-6d5c6f81d98a.png)

**Environment (please complete the following information):**
I describe the environment of my working project (where I encountered the problem for the first time), but the behavior is the same

| Allure version | 2.17.3 |
| --- | --- |
| Test framework | junit5@5.8.1 |
| Allure adaptor | allure-junit5@2.17.3 |
| Generate report using | gradle@7.4 |

**Comment by shilko2013** [comment]
@andrgn You can just remove `{displayName}` and the report will be correct
```
class AllureParameterizedTest {

    @ParameterizedTest(name = " [{argumentsWithNames}]")
    @ValueSource(strings = ["First Name", "Second Name"])
    @DisplayName("allureParameterizedTest displayName")
    @Description("allureParameterizedTest description")
    fun allureParameterizedTest(testParam: String) {
        Allure.parameter("testParam", testParam)
        Allure.step("Step inside parameterized test")
        Allure.step("Test parameter: $testParam")
    }

    @Test
    fun allureFakeParameterizedTest() {
        Allure.parameter("fakeParam", "fakeValue")
        Allure.step("Step inside fake parameterized test")
    }

}
```

**Comment by baev** [comment]
the default behaviour changed so now the correct name is shown if no custom `@DisplayName` or `@ ParameterizedTest(name)` provided. Before 2.17 it was required to specify `{displayName}` for each `@ParameterizedTest`.

The solution is omit `{displayName}`  as @shilko2013 mentioned above
