### ISSUE TITLE
What Can Go in allure-config.yml?

### ISSUE THREAD

**Issue by coofercat** [allure-framework/allure2#1607]
**Pre-check**
- [X] I'm aware that I can [edit the docs](https://github.com/allure-framework/allure-docs/) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [X] Missing documentation
- [ ] Other

**Description of the improvement / report**
I'm trying to configure Allure 2.17.3 to work with some junit output we're getting from a dotnet application. When running with the `-v` option, I noticed that `allure -v generate -c -o reports junit/unit` would say:

```
Parsing file junit/unit/unit.xml
Parsing file junit/unit/unit.xml
junit/unit/unit.xml is not a valid XUnit xml file. Unknown root element testsuites
```
To resolve this, I started trying to use `--config allure-config.yml`, but couldn't get it to say any more than:

```
Could not load config file allure-config.yml. Using the empty configuration
```
I have since resolved this issue and am getting reports, but there are still issues with them that I would like to resolve.

The point I'm making here is that the software doesn't give you any clues of where the config parsing issue, missing parameter or other problem might be. As a result, I started to look for documentation. The only examples I can find that actually work are to set plugins - is that all that's available on a `--config` file, or are there other options? If so, what are they and can we document them, please?

**Comment by Dima-Diachenko** [comment]
Any update, guys? Does exist any ways how to parse allure.json configuration for allure CLI tool?

**Comment by baev** [comment]
The JUnit.xml parsing is enabled by default — no need to provide additional configuration. 

If there are parsing issues, make sure to update to the latest version, and if the update didn't help, create a new [support request](https://github.com/orgs/allure-framework/discussions/new?category=questions-support).
