### ISSUE TITLE
Failed to install, requires jre-8 while jdk-17 installed

### ISSUE THREAD

**Issue by roman4e** [allure-framework/allure2#1682]
**Describe the bug**
Requires <any>jre-8 when installing v2.18.1 while oracle jdk-17 is installed.

**To Reproduce**
1. Install oracle jdk-17
2. Download deb package v2.18.1 from https://github.com/allure-framework/allure2/releases
3. Try to install it using dpkg

**Expected behavior**
Expected the dependency to be met while installing

**Screenshots**
Error while installation process
![screenshot-20220608-154449](https://user-images.githubusercontent.com/10156713/172619836-06aa6747-7eb3-4845-9f3f-b39924798b88.png)

Get java version
![screenshot-20220608-154534](https://user-images.githubusercontent.com/10156713/172619844-4780c105-7d7b-4060-a7dc-fd097b23f9d5.png)

**Environment (please complete the following information):**
| Allure version | 2.18.1 |
| --- | --- |
| Test framework | cucumber |
| Allure adaptor | -- |
| Generate report using | gradle 7.4.2 |

**Additional context**
Problem occured while install in docker container

**Comment by Kamveno** [comment]
hii @roman4e  i would like to contribute to the issue  with your guidance for the newcomer to the platform
