### ISSUE TITLE
Issue with Credentials / Issue/Bug/TMS integrations on Cloud

### ISSUE THREAD

**Issue by itz4blitz** [allure-framework/allure2#1707]
**Describe the bug**
When adding in a valid API key (for example, Jira Cloud), I'm receiving a "400 invalid response" after testing the integration. I've tried several keys, several Jira issue tracker URLs, all to no avail.

**To Reproduce**
1. Go to "Credentials" inside admin panel
2. Click on "Create"
3. Add in valid API key
4. Configure appropriate service (ex. Issue Tracker)
5. Click on "Test" 

**Expected behavior**
Receive a response indicating the integration was successful

**Screenshots**
![image](https://user-images.githubusercontent.com/60281870/181263993-6092de2e-97a5-428f-9442-a1c14105795b.png)

**Environment (please complete the following information):**

| Allure version | 3.193.1|

**Comment by what1s1ove** [comment]
+, have the same issues

Also, some things are not clear in the documentation. For example, where to get the Jira username...

Could you provide some examples of what the values should look like? 🙏

https://docs.qameta.io/allure-testops/integrations/issue-trackers/jira/c-creds-tracker/#add-credentials

**Comment by cheshi-mantu** [comment]
hi @itz4blitz 
such requests require providing of some details you don't want to provide in a place with the public access. 

The proper way to handle the requests related to Allure TestOps is doing it via dedicated support portal for Allure TestOps https://help.qameta.io.

Could you please register future tickets there?

As of this particular issue, you need to upgrade to the most recent release of Allure TestOps: https://docs.qameta.io/allure-testops/release-notes/ (spoiler: 4.4.3 is the most recent, but it's advised to read all the descriptions related to the release 4).
You also need to read through the changes we've made for the 4th release: https://docs.qameta.io/allure-testops/ext-integrations/integrations/ (there is a lot of changes related to your issue).
And last but not least you need to update your config files to use proper images, see for your deployment type here: https://docs.qameta.io/allure-testops/getstarted/installation/#deployment-types all of the deployment types have new configs starting from 3.193.1.

**Comment by cheshi-mantu** [comment]
@what1s1ove 
for username for jira server / DC you need to go to your profile: `URL/secure/ViewProfile.jspa`

![image](https://user-images.githubusercontent.com/8607348/182352889-02f8af74-63e1-43b7-96d0-7a5403158df1.png)
