### ISSUE TITLE
Plugin failed to upload results since 3.17.2

### ISSUE THREAD

**Issue by a-rebizov-elamateam** [allure-framework/allure2#1709]
**Describe the bug**
Allure upload results failure using plugin 3.17.2

**To Reproduce**
1. Go to 'allure-results' package (mustn't be empty) and right click on it
2. Click on 'Allure: Upload results'
3. See error (please check **Additional context**)

**Expected behavior**
Expected modal window appearing with existing allure test ops projects\environments
Able to set launch name and choose project

**Screenshots**
Please see attachments

**Environment (please complete the following information):**

| Windows 10 21H1 | IntellijIDEA 2022.2 |
| Allure version | 4.4.2 |
| Test framework | junit@5.8.2 |
| Allure adaptor | allure-junit5@2.18.1 |
| Allure Plugin 3.17.2 | 

**Additional context**
Everything worked fine until i upgraded to Allure Plugin 3.17.2 version

Error message:

java.lang.reflect.UndeclaredThrowableException at jdk.proxy13/jdk.proxy13.$Proxy243.getProjectsWrapper(Unknown Source) at io.qameta.allure.idea.ui.dialog.UploadDialog.createCenterPanel(UploadDialog.java:72) at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1308) at io.qameta.allure.idea.ui.dialog.UploadDialog.init(UploadDialog.java:63) at io.qameta.allure.idea.ui.dialog.UploadDialog. (UploadDialog.java:57) at io.qameta.allure.idea.action.UploadAction.actionPerformed(UploadAction.java:44) at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:315) at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:294) at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:337) at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:294) at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$4(ActionMenuItem.java:293) at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:224) at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:286) at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:67) at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$3(ActionMenuItem.java:109) at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105) at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94) at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109) at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:546) at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:578) at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648) at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392) at java.desktop/java.awt.Component.processEvent(Component.java:6413) at java.desktop/java.awt.Container.processEvent(Container.java:2266) at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022) at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324) at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854) at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310) at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802) at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854) at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724) at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97) at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754) at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752) at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751) at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898) at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820) at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743) at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439) at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791) at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438) at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113) at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604) at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436) at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881) at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484) at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207) at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128) at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105) at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92) Caused by: java.lang.NoSuchMethodException: java.lang.invoke.MethodHandles$Lookup. (java.lang.Class,int) at java.base/java.lang.Class.getConstructor0(Class.java:3585) at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754) at retrofit2.Platform.invokeDefaultMethod(Platform.java:90) at retrofit2.Retrofit$1.invoke(Retrofit.java:147) ... 62 more
![Снимок экрана (1)](https://user-images.githubusercontent.com/93599279/182154629-e948fb8a-7ac0-4f79-876b-484aa2411246.png)

**Comment by a-rebizov-elamateam** [comment]
The error is reproduced in many

https://plugins.jetbrains.com/plugin/12513-allure-testops-support/reviews#review=70221

**Comment by cheshi-mantu** [comment]
@a-rebizov-elamateam 
Hi there!
this plug-in is a part of Allure TestOps ecosystem (not the part of this open-source project) and it's supported via https://help.qameta.io.

Could you please register at the Allure TestOps support portal using your corporate email (email of the company having the licence for Allure TestOps) and submit this error there?

thanks
