### ISSUE TITLE
Rework cucumber plugin with official parser

### ISSUE THREAD

**Issue by baev** [allure-framework/allure2#179]
Current plugin size is about 7M of size because of parser implementation (it uses lots of different dependencies and contains fonts and styles for report). We should use `info.cukes:gherkin` instead. 

https://github.com/jenkinsci/cucumber-testresult-plugin/blob/master/src/main/java/org/jenkinsci/plugins/cucumber/jsontestsupport/CucumberJSONParser.java
https://github.com/cucumber/gherkin-java

**Comment by clicman** [comment]
It is implemented in gherkin2 project: https://github.com/cucumber/gherkin2
