### ISSUE TITLE
Cypress screenshots not successfully generated

### ISSUE THREAD

**Issue by sjyzheng** [allure-framework/allure2#1799]
Hi Team,

We have an issue displaying the screenshots in the Allure report. This is a GitLab CI integration. The allure-results folder has the screenshots, and the result.json file has the images' information in it.

![Screen Shot 2022-10-27 at 09 40 58](https://user-images.githubusercontent.com/59863441/198349586-ce0f69d6-4649-4d7c-883f-a436db488d8b.png)

![Screen Shot 2022-10-27 at 09 41 38](https://user-images.githubusercontent.com/59863441/198349643-eecc3f87-660e-470b-a538-8321e79d93fe.png)

Allure is not able to create the data/attachments folder and load the screenshots to it.

![Screen Shot 2022-10-27 at 09 46 53](https://user-images.githubusercontent.com/59863441/198350569-c21fee57-0fd6-4fe9-be2b-dea03b66da74.png)

In the Allure report, the screenshots are listed with 0 B file size, they are not clickable, and cannot be opened:

![Screen Shot 2022-10-27 at 09 48 05](https://user-images.githubusercontent.com/59863441/198350957-7339a46a-a3e8-482e-84e6-34834acca0cf.png)

We are using Allure v2.17.2

**Comment by sjyzheng** [comment]
Hello, can I follow up on this issue? We have updated the allure and cypress-allure-plugin to the latest version, but the issue persists.

**Comment by baev** [comment]
We're currently working on official Cypress integration. Please follow https://github.com/allure-framework/allure-js/pull/815
