### ISSUE TITLE
Uncaught ReferenceError: allure is not defined

### ISSUE THREAD

**Issue by louisliusz** [allure-framework/allure2#1818]
jenkin+allure

allure report offen loading error ,the error message is "Uncaught ReferenceError: allure is not defined at index.js:3:1","index.js:2 Uncaught ReferenceError: allure is not defined
    at index.js:2:20
    at index.js:200:3"；but if you refresh the pages many times ,maybe it will be successful.
![image](https://user-images.githubusercontent.com/117816771/200795239-3a00e40e-6192-4997-9411-93fd1230780d.png)

**Comment by baev** [comment]
Do you have some custom plugins?

**Comment by louisliusz** [comment]
I don't kown,I just use jenkins integrate pytest and allure to do automated testing.After testing when I click allure report link ,it will be arise this issue,but if I refresh the web continuous,it will work at some time
| |
刘乾辉
|
|
***@***.***
|
---- Replied Message ----
| From | Dmitry ***@***.***> |
| Date | 11/10/2022 15:30 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [allure-framework/allure2] Uncaught ReferenceError: allure is not defined (Issue #1818) |

Do you have some custom plugins?

**Comment by louisliusz** [comment]
> Do you have some custom plugins?

Thank you for your reply.For same reason,we can't use  Jenkins 2.375 or newer ,I think ,that should be the cause of the problem

**Comment by baev** [comment]
make sure you are using the latest Allure commandline (2.20.1 at the moment). You can update it in Jenkins->Manage->Global Tool Configuration in the Allure Commandline section.
