### ISSUE TITLE
Close the current open window by Esc key

### ISSUE THREAD

**Issue by monolithed** [allure-framework/allure2#183]
It would be nice to support closing the current (not all) open window by pressing the Esc key.

**Comment by just-boris** [comment]
What do you mean? Do you want to have <kbd>esc</kbd> to be handled as a click on the "Close" icon here?

![image](https://cloud.githubusercontent.com/assets/812240/23366187/21cd8770-fd06-11e6-8030-9668ba1e9bad.png)

**Comment by monolithed** [comment]
Nope, I'd like to press the Esc key.

**Comment by just-boris** [comment]
Yes, that was my question. Do you want to press <kbd>esc<kbd> do the same thing as well as the mentioned button, or something different?

I guess the answer is yes.

**Comment by baev** [comment]
see #269
