### ISSUE TITLE
Attachments are not being added to Allure reports when I upgraded to TestNG v7.7.0

### ISSUE THREAD

**Issue by georgescaria** [allure-framework/allure2#1865]

**Comment by Faizan-Mamji** [comment]
@georgescaria I am facing the same issue with Testng version 7.6.1

**Comment by Krzysztof-Bednarczyk** [comment]
@georgescaria - same thing for me
[Issue#875](https://github.com/allure-framework/allure-java/issues/875)

**Comment by baev** [comment]
https://github.com/allure-framework/allure-java/issues/707#issuecomment-1083340458
