### ISSUE TITLE
Test duplication in the report when dynamically applying the same title or story multiple times

### ISSUE THREAD

**Issue by acqa** [allure-framework/allure2#1883]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x ] bug report

#### What is the current behavior?
При использовании динамических story и title, title-ы не группируются по имени - появляется большое кол-во title-ов с одинаковым названием и временем выполнения.
![1](https://user-images.githubusercontent.com/47945113/102243122-de32e680-3f0b-11eb-804a-dda598b2c5c0.png)

При использовании статического story - группировка производится ожидаемо. Как видно - дублирующих тестов (title-ов) - нет.
![2](https://user-images.githubusercontent.com/47945113/102243247-fe62a580-3f0b-11eb-97b7-4f66e51f09e2.png)

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Можно выполнить следующий код в pytest
```python
import schemathesis
import allure

schema = schemathesis.from_uri("https://petstore.swagger.io/v2/swagger.json")

#@allure.story("Static story")
@schema.parametrize()
def test_api(case):

    allure.dynamic.title(case.method)
    allure.dynamic.story(case.endpoint.path)
    #allure.dynamic.title(str(case.method) + ": " + str(case.endpoint.path))

    with allure.step("Endpoint: " + str(case.formatted_path)
                  + "; Query: " + str(case.query)
                  + "; Body: " + str(case.body)
                  ):

        resp = case.call()

        resp_to_attach = resp.request.method \
                         + "\n" + resp.request.url \
                         + "\n" + str(resp.status_code) \
                         + "\n" + resp.text

        allure.attach(resp_to_attach, name="output",
                          attachment_type=allure.attachment_type.TEXT)

        case.validate_response(resp)
```
Для получения результата со статическим story, можно убрать # у закомментированных строк и закомментировать
```python
    allure.dynamic.title(case.method)
    allure.dynamic.story(case.endpoint.path)
```

#### What is the expected behavior?
При использовании динамического story, группировка title-ов должна сохраняться.

#### What is the motivation / use case for changing the behavior?
Хотелось бы добавить поддержку allure в schemathesis

#### Please tell us about your environment:

- Allure version:        2.13.6
- Test framework:        pytest@3.7.2
- Allure adaptor:        allure-pytest-2.7.1

#### Other information 
Обновил информацию, добавил скрины с отчетами.
[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
closed as stale.

Please create a new [support request](https://github.com/orgs/allure-framework/discussions/new?category=questions-support) if the issue isn't fixed yet
