### ISSUE TITLE
Muted tests

### ISSUE THREAD

**Issue by baev** [allure-framework/allure2#193]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

There is no mark for muted tests. 

#### What is the expected behavior?

Muted tests is displayed in the report. We have an API to get all the muted tests and to mark tests as muted during report generation. Also muted tests should be excluded from overall report statistics.

#### Please tell us about your environment:

- Allure version:        2.0+
- Test framework:     any
- Allure adaptor:       any
- Generate report using: any

**Comment by kshepitko** [comment]
Can you please elaborate the effect of test being muted?
This label is mentioned in documentation, but without any real explanation.
I want to understand: if test is marked as muted, and failed in execution, will report contain an effective error (shown in overview, making Allure Jenkins plugin to mark build as unstable, etc.)?

**Comment by aleksandr-kotlyar** [comment]
"Muted" here is equal "skipped", "unknown", or this is something else?
If they are not skipped - then they will fail build AND if they doesn't appear in Overall statistic - it will be unfair.
So, muted tests should be skipped but not in overall statistic? And where we should see them in the allure report?
