### ISSUE TITLE
Gradle 'dev' task does not clean up node process on exit

### ISSUE THREAD

**Issue by ehborisov** [allure-framework/allure2#194]
start a dev server via **./gradlew dev**
then end gradle process and run **pgrep node** - there will be an orphaned process.

**Comment by just-boris** [comment]
this is basically an issue to `com.moowork.node`. That it does not clean up children processes upon master ends

**Comment by ehborisov** [comment]
there it is, indeed
https://github.com/srs/gradle-node-plugin/issues/143

Do we close this and just wait for the fix?

**Comment by baev** [comment]
yeah, lets close then
