### ISSUE TITLE
JUnit repeated tests are shown as separate tests in the report (not as retries)

### ISSUE THREAD

**Issue by vvyushmanov** [allure-framework/allure2#1947]
**Describe the bug**
We have a buch of unstabe tests that we execute with a re-run.
For that, we use @RepeatedTest (org.junit.jupiter.api) or @RetryingTest (org.junitpioneer.jupiter) (the latter re-runs a test for n times only if the test is failing).

But whenever a re-run of the same test is done, the report shows it not as a retry, but as n separate tests.

**Screenshots**
![image](https://user-images.githubusercontent.com/111231219/226092958-9a4809d5-7b15-47f7-90da-72f59e514c05.png)
![image](https://user-images.githubusercontent.com/111231219/226092999-4b636856-85a6-44ee-ba61-49ce1ebac877.png)

![image](https://user-images.githubusercontent.com/111231219/226093030-cbd50119-d8a7-4d5d-b87e-a980b033b3cb.png)
![image](https://user-images.githubusercontent.com/111231219/226093074-2e1e66cb-0bcc-48ed-a224-dfc488f314d2.png)

**Environment (please complete the following information):**

| Allure version | 2.21.0 |
| --- | --- |
| Test framework | junit5@5.8.2 |
| Allure adaptor | allure-selenide@2.17.3, allure-junit5@2.17.3 |
| Generate report using | allure-gradle@2.11.2 |

**Comment by baev** [comment]
It is implemented this way because Allure always shows the last result, hiding the previous as retries. Still, for repeated tests, users usually need to highlight any failures in any repetition. So disabling the retries for repeated tests is the best we can do. Otherwise, there is no point in using such tests at all

**Comment by anatolimironau** [comment]
Please note, the problem described above is also reproducing via the Wedriver.IO [Retry Flaky Tests](https://webdriver.io/docs/retry) functionality. Allure considers retried tests as separate tests.

**Comment by baev** [comment]
`@RepeatedTest` implemented this way intentionally. Otherwise, Allure will only show the latest result, removing any point to use repeated tests.

> the problem described above is also reproducing via the Wedriver.IO [Retry Flaky Tests](https://webdriver.io/docs/retry) functionality. Allure considers retried tests as separate tests.

Please create a separate discussion for that (https://github.com/orgs/allure-framework/discussions)

**Comment by vvyushmanov** [comment]
I understand why `@RepeatedTest` should be considered as separate tests (this annotation makes explicit retries with no regard to the result).
But what about `@RetryingTest (org.junitpioneer.jupiter)` ?
I think this is a good annotation to use with flaky tests, and can be considered when grouping tests in the report as retries of the same test.

https://junit-pioneer.org/docs/retrying-test/
