### ISSUE TITLE
add a tag on a cucumber scenario adds a new scenario in the report

### ISSUE THREAD

**Issue by ghost** [allure-framework/allure2#1949]
**Describe the bug**
Adding a tag on a cucumber scenario should not create a new scenario in the report

**To Reproduce**
Generate a first report after a cucumber feature run. (mvn allure:report)
You should have in your report the feature with its scenarios. (here there is only one scenario in only one feature)
![image](https://user-images.githubusercontent.com/116872349/226426241-609ed82d-dad6-4cc5-80ad-037bbfa91137.png)

update your feature, add a tag on the scenario
relaunch your cucumber tests
generate a report using maven (mvn allure:report)

**Expected behavior**
you should still see that there is only one scenario in the feature, and in the detail of the scenario you should see the newly added tag

**Screenshots**
you can see 2 scenarios, the first one is the one run in the first run (without the newly added tag in its details), the second correspond to the same scenario but with in its details the newly created tag.
![image](https://user-images.githubusercontent.com/116872349/226428481-cc08225d-eaf9-4f05-ad2c-8d88a1921b4d.png)

**Environment (please complete the following information):**
allure-cucumber7-jvm.version 2.21.0
allure-maven.version 2.12.0

**Comment by baev** [comment]
fixed in https://github.com/allure-framework/allure-java/pull/947 , released in 2.24.0
