### ISSUE TITLE
Report is not coming properly for allure report

### ISSUE THREAD

**Issue by Sheth90** [allure-framework/allure2#1964]
Hello team,
I have configured the allure report successfully with my setup. I used version conf as below.
Cypress: 12.5.1
After executing my test case. I am getting results for 2nd method, not for the first method. 
TestBody of the first method is overridden by the second method's tc. Please help to resolve this issue with the allure report.

![Screenshot_6](https://user-images.githubusercontent.com/125349115/229422089-2dfa03a6-6e92-4609-90d0-9d9bfc379d15.png)
![Screenshot_7](https://user-images.githubusercontent.com/125349115/229422098-3ca622ac-3c70-4442-9f71-eb2e720d6a12.png)
![Screenshot_8](https://user-images.githubusercontent.com/125349115/229422100-9ceea9aa-07bb-4797-b44a-dc4fbcf42710.png)
![image](https://user-images.githubusercontent.com/125349115/229422180-b765e1c5-3f65-4962-be18-5c81c7305163.png)

**Comment by cheshi-mantu** [comment]
hi @Sheth90 
Cypress is not officially supported by Allure Framework. My guess would be you are using this plug-in: https://github.com/Shelex/cypress-allure-plugin/issues
if so, please create an issue in the respective project.
Allure Report only shows what the plug-in has generated.

**Comment by Sheth90** [comment]
Thanks for correcting me. I am closing this @cheshi-mantu
