### ISSUE TITLE
Add ability to define base path for Freemarker templates

### ISSUE THREAD

**Issue by valfirst** [allure-framework/allure2#2021]
**Is your feature request related to a problem? Please describe.**
No way to define custom base path for Freemarker templates, it's needed for cases like this one: https://github.com/vividus-framework/vividus/blob/eb1d4e67f8769940b23a3736b41319ab33bead22/vividus-allure-adaptor/src/main/java/org/vividus/report/allure/AllureReportGenerator.java#L279-L281

**Describe the solution you'd like**
PR #2011

**Describe alternatives you've considered**
See link above

**Additional context**
\-

**Comment by baev** [comment]
Allure 2 is slowly getting into maintenance mode since we're moving towards the Allure 3 release. We've passed the point where Allure 2 is fully implemented using the new platform (rewritten in TypeScript), so I don't see any reason to add additional extensions to the current codebase.
