### ISSUE TITLE
No screenshot attached to Allure report

### ISSUE THREAD

**Issue by leductho911** [allure-framework/allure2#2058]
### Describe the Bug

Hi, I'm coding Selenium Java with Maven (IntelliJ). 
I run "allure serve allure-results" and there's "1b8fa271-7586-417c-833a-59274cd262ad-attachment" appears in the allure-results folder.

but, in the report, there's no screenshot attached.
![screenshot_09](https://github.com/allure-framework/allure2/assets/120003355/986aac9a-4e76-44ed-9e51-63967f5b4164)
![screenshot_10](https://github.com/allure-framework/allure2/assets/120003355/7aef2852-90c8-4f27-8eae-89e55c1eaa64)

### Steps to Reproduce

1. Run the test
2. Run allure serve allure-results in Terminal
3. Check the report for a screenshot

### Expected Behaviour

Screenshot attached

### What Language are you using?

Java

### What Framework/Allure Integration you are using?

allure-testng

### What version of Allure Integration you are using?

2.23.0

### What version of Allure Report you are using?

2.23.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leductho911** [comment]
This bug happens on allure-2.13.5 and allure-2.23.0

**Comment by leductho911** [comment]
my pom https://gist.github.com/leductho911/d64fb9ae7124e5ab6d01aeb78646c6a7

**Comment by leductho911** [comment]
Update: This bug happens randomly, sometimes it have, sometime no

**Comment by sethvanwykJET** [comment]
I've experienced the same using CodeceptJS

I haven't been able to identify a root cause either, just that some failed tests have screenshots, then others don't. The logic is likely consistent as retries on the same test also won't have screenshots at the same place, where other tests that only failed once could have a screenshot attached.

**Comment by turnitin-rshanker** [comment]
works for me using java

**Comment by baev** [comment]
See https://github.com/testng-team/testng/issues/2791

**Comment by deyvisPedrosa** [comment]
I have the same issue in a WebdriverIO (>8.14.0) project.

**Comment by baev** [comment]
All the issue details & working examples can be found here https://github.com/biczomate/allure-testng7.5-attachment-example
