### ISSUE TITLE
Dev mode requires run build first

### ISSUE THREAD

**Issue by aosheter** [allure-framework/allure2#206]
Tested on a clean-install Ubuntu machine. Only other thing I did was install the JDK to simulate our machines running allure1.

I ran ```$ ./gradlew dev``` out-of-the-box.  -> Build failed.

Installed npm -> ```apt-get install npm``` -> Build failed.

Navigated to allure-web folder -> ```npm install``` -> Build stuck at 95% but working.

Is npm listed as a requirement somewhere? Are there any other dependencies that need to be installed?

**Comment by baev** [comment]
> I ran $ ./gradlew dev out-of-the-box. -> Build failed.

This should work. Only JDK 1.8 or above is required. Could you please provide more details on the error?

**Comment by aosheter** [comment]
Here's the output with --debug flag
[report.txt](https://github.com/allure-framework/allure2/files/842363/report.txt)

**Comment by baev** [comment]
is `./gradlew clean build` works for you?

**Comment by aosheter** [comment]
Yes! But it was incredibly slow.

Also, could it be related to the fact I installed npm?

**Comment by baev** [comment]
Could you please try `./gradle dev` again?

> Yes! But it was incredibly slow.

For the first time build takes about 9mins, thats fine. 

> Also, could it be related to the fact I installed npm?

Nope. And build uses `yarn`, not `npm`

**Comment by aosheter** [comment]
>For the first time build takes about 9mins, thats fine.

It took over 15 minutes for me, is that ok?

Tried it again, and it failed again.

```
$ webpack-dev-server --inline --hot --env.development 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at Server._listen2 (net.js:1252:14)
    at listen (net.js:1288:10)
    at net.js:1398:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:65:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:84:10)
error Command failed with exit code 1.
:allure-web:yarn_start FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':allure-web:yarn_start'.
> Process 'command '/home/test/allure2-master/allure-web/.gradle/yarn/yarn-v0.21.3/bin/yarn'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 22.454 secs

```

**Comment by baev** [comment]
Remove `node_modules` folder and try one more time

**Comment by aosheter** [comment]
Removed ```node_modules```

Still fails.

```
$ webpack-dev-server --inline --hot --env.development 
module.js:442
    throw err;
    ^

Error: Cannot find module 'extract-text-webpack-plugin'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/test/allure2-master/allure-web/webpack.config.js:3:27)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
error Command failed with exit code 1.
:allure-web:yarn_start FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':allure-web:yarn_start'.
> Process 'command '/home/test/allure2-master/allure-web/.gradle/yarn/yarn-v0.21.3/bin/yarn'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 48.217 secs
```

**Comment by just-boris** [comment]
I confirm the problem. Steps to reproduce

1. Clone the clean repo
2. Run `./gradlew dev`
3. You will the the mentioned error.

**Comment by baev** [comment]
seems like not an issue. Simply run `./gradlew build` first
