### ISSUE TITLE
Allure 2.24.0 always enables analytics

### ISSUE THREAD

**Issue by arnulfojr** [allure-framework/allure2#2123]
### Describe the Bug

On the 2.24.0 release the support for generating single file reports introduced a bug that completely ignores the environment variable to disable analytics on the generated html report.

The usage in the template is
https://github.com/allure-framework/allure2/blob/b856621694a185a3681ede00b77e141ba645ade1/allure-generator/src/main/resources/tpl/index.html.ftl#L28-L30

To the extend of my understanding (rather limited) the configuration is later overwritten by the hard coded values here:

https://github.com/allure-framework/allure2/blob/8d41e9da4e8a0a5975c6be5e96976796198f2150/allure-generator/src/main/java/io/qameta/allure/core/ReportWebGenerator.java#L141-L148

ignoring the config set by

https://github.com/allure-framework/allure2/blob/b856621694a185a3681ede00b77e141ba645ade1/allure-generator/src/main/java/io/qameta/allure/core/ReportWebPlugin.java#L88
https://github.com/allure-framework/allure2/blob/b856621694a185a3681ede00b77e141ba645ade1/allure-generator/src/main/java/io/qameta/allure/core/ReportWebPlugin.java#L91

### Steps to Reproduce

Generate the report with the env variable `ALLURE_NO_ANALYTICS=true` the generated report will still have analytics.

Snapshot from a report:

```
<script src="app.js"></script>
    <script src="plugin/behaviors/index.js"></script>
    <script src="plugin/screen-diff/index.js"></script>
    <script src="plugin/packages/index.js"></script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-FVWC4GKEYS"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-FVWC4GKEYS');
        gtag('allureVersion', 'dev')
        gtag('reportUuid', 'uuid-like');
```

### Expected Behaviour

it does not include the analytics

### Screenshots or Additional Context

```
<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
    <meta charset="utf-8">
    <title>Allure Report</title>
    <link rel="favicon" href="favicon.ico">
    <link rel="stylesheet" type="text/css" href="styles.css">
    <link rel="stylesheet" type="text/css" href="plugin/screen-diff/styles.css">
</head>
<body>
    <div id="alert"></div>
    <div id="content">
        <span class="spinner">
            <span class="spinner__circle"></span>
        </span>
    </div>
    <div id="popup"></div>
    <script src="app.js"></script>
    <script src="plugin/behaviors/index.js"></script>
    <script src="plugin/screen-diff/index.js"></script>
    <script src="plugin/packages/index.js"></script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-FVWC4GKEYS"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-FVWC4GKEYS');
        gtag('allureVersion', 'dev')
        gtag('reportUuid', 'uuid-like-string')
    </script>
</body>
</html>
```

### What Language are you using?

JavaScript, TypeScript

### What Framework/Allure Integration you are using?

allure-commandline

### What version of Allure Integration you are using?

2.24.0

### What version of Allure Report you are using?

2.24.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment]
Thanks for the report, I'll look at this as soon as possible

**Comment by arnulfojr** [comment]
(for cross referencing only) related ticket https://github.com/allure-framework/allure2/pull/2018

**Comment by pwaldon** [comment]
I confirm it's ignoring the env var, the analytics references are additionally breaking https://github.com/MihanEntalpo/allure-single-html-file (current allure generate --single-file doesn't generate correctly single report with request/response attachements)
