### ISSUE TITLE
Before Suite and AfterSuite steps not appearing in allure report anymore after version 2.21

### ISSUE THREAD

**Issue by zanoon2020** [allure-framework/allure2#2133]
### Describe the Bug

before and after suite methods not shown in allure report since version 2.22

### Steps to Reproduce

after suite method not shown in allure report since version 2.22
for example below code

```java
package allure;

import org.testng.annotations.AfterMethod;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.Test;

import io.qameta.allure.Attachment;
import io.qameta.allure.Step;

public class TestClass {

       @BeforeSuite
	public void beforeSuite() {
		stepHasNestedSteps();
	}
	
	@BeforeMethod
	public void beforeMethod() {
		stepHasNestedSteps();
	}
	
	@Step("step has nested steps")
	public void stepHasNestedSteps() {
		callAttachment();
		callAttachment2();
	}
	
	@Attachment("attachment - nested ")
	public void callAttachment() {
		System.out.println("attachment");
	}
	
	@Step("another nested step")
	public void callAttachment2() {
		callAttachment();
	}
	

	
	@Test(description="description")
	public void test() {
	stepHasNestedSteps();
		
	}
	
	
	@AfterMethod(description ="after test")
	public void after(){
		stepHasNestedSteps();
	}
	
	
	@AfterSuite(description ="after Suit")
	public void afterSuit() {
		stepHasNestedSteps();
	}
	

}
```

### Expected Behaviour

version 2.24 output to be same as 2.21

![263937712-6a73f48a-f186-4f55-868e-89423f620d3c](https://github.com/allure-framework/allure2/assets/65794900/7bb40e17-7c0c-44e3-9df6-eba1e79495d8)

### Screenshots or Additional Context

2.24
![263938632-53594a34-3483-4d69-a6fd-1feab6889713](https://github.com/allure-framework/allure2/assets/65794900/498826f6-f7bc-47ff-a05c-ad705c25c739)

2.21
![263937712-6a73f48a-f186-4f55-868e-89423f620d3c](https://github.com/allure-framework/allure2/assets/65794900/5f90c1ba-a486-4674-b38f-7ffc2c6dfcc8)

https://github.com/allure-framework/allure-java/issues/953

### What Language are you using?

Java

### What Framework/Allure Integration you are using?

allure-testng

### What version of Allure Integration you are using?

2.24.0

### What version of Allure Report you are using?

2.24.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment]
Due to performance issues, we dropped support for recursive containers in Allure Report (and it was never supported in Allure TestOps). Apparently, Allure TestNG is the only integration that relies on that. 

We will not reintroduce it in the report. Instead, we need to update Allure TestNG to use separate containers for all the test fixtures. 

Closing this issue, the progress can be traced in [in allure-java repository https://github.com/allure-framework/allure-java/issues/953](https://github.com/allure-framework/allure-java/issues/953)
