### ISSUE TITLE
@Issue does not open the link set as value

### ISSUE THREAD

**Issue by nitaandreea** [allure-framework/allure2#2135]
### Describe the Bug

Link provided in the @Issue value does not open

### Steps to Reproduce

1. Annotate your test with @Issue and provide a value linking it to the corresponding Jira bug. Ex:     @Issue("https://www.myJira.com/Bug-123")
2. Generate the report and click the link displayed in the Link section
3. The page is redirected to itself

### Expected Behaviour

Clicking the issue link should open the Jira link.

### Screenshots or Additional Context

<img width="583" alt="html" src="https://github.com/allure-framework/allure2/assets/28338747/b4060517-08e9-4223-a3e2-4be40d6ef953">

<img width="417" alt="config" src="https://github.com/allure-framework/allure2/assets/28338747/25fa8269-8579-4c98-9fe2-2beb446b7ec3">

### What Language are you using?

Java

### What Framework/Allure Integration you are using?

allure-maven

### What version of Allure Integration you are using?

2.12.0

### What version of Allure Report you are using?

2.24.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nitaandreea** [comment]
<dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-junit5</artifactId>
            <version>2.12.0</version>
        </dependency>
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-rest-assured</artifactId>
            <version>2.12.0</version>
        </dependency>

**Comment by baev** [comment]
@nitaandreea allure-junit5:2.12.0 release date May 21, 2019, could you please check the latest versions to ensure the problem still exists?

**Comment by nitaandreea** [comment]
Yes, the problem still reproduces with version 2.24.0.      

      <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-junit5</artifactId>
            <version>2.24.0</version>
        </dependency>
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-rest-assured</artifactId>
            <version>2.24.0</version>
        </dependency>
