### ISSUE TITLE
Cannot install RPM on Fedora

### ISSUE THREAD

**Issue by harmin-parra** [allure-framework/allure2#2183]
### Describe the Bug

after installing `java-1.8.0-openjdk` and `java-1.8.0-openjdk-headless` fedora packages, I still get this error when installing Allure

```
rpm -i https://github.com/allure-framework/allure2/releases/download/2.24.1/allure_2.24.1-1.noarch.rpm
error: Failed dependencies:
	java8-runtime | java8-runtime-headless | openjdk8-jre-headless | openjdk-8-jre | openjdk-8-jdk | oracle-java8-installer | oracle-java8-installer is needed by allure-0:2.24.1-1.noarch
```

### Steps to Reproduce

```
dnf install java-1.8.0-openjdk java-1.8.0-openjdk-headless
rpm -i https://github.com/allure-framework/allure2/releases/download/2.24.1/allure_2.24.1-1.noarch.rpm
```

### Expected Behaviour

Allure framework installed

### What Language are you using?

TypeScript

### What Framework/Allure Integration you are using?

Pytest

### What version of Allure Integration you are using?

2.24.1

### What version of Allure Report you are using?

2.24.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by davidcarvalho** [comment]
This is not yet resolved in version 2.27
