### ISSUE TITLE
Timeline is broken in IE11

### ISSUE THREAD

**Issue by baev** [allure-framework/allure2#219]
![](https://files.gitter.im/allure-framework/allure-core/jpXd/Citrix-Full-Desktop---Desktop-Viewer-2017-03-21-17.21.56.png)

![](https://files.gitter.im/allure-framework/allure-core/jpXd/Citrix-Full-Desktop---Desktop-Viewer-2017-03-21-17.22.20.png)

![](https://files.gitter.im/allure-framework/allure-core/jpXd/Citrix-Full-Desktop---Desktop-Viewer-2017-03-21-17.21.23.png)

**Comment by baev** [comment]
Also there is some problems in Firefox 

![](https://files.gitter.im/allure-framework/allure-core/GvBv/Citrix-Full-Desktop---Desktop-Viewer-2017-03-21-17.30.31.png)

**Comment by AlexanderPoleschuk** [comment]
More issues with IE11 timeline:
![ie](https://cloud.githubusercontent.com/assets/9446141/24204498/c386a0b2-0f29-11e7-964d-54e16b5b0994.png)
The suite is executed in 15 threads, but only top part (half) of them are visible in IE11.
Same timeline in Chrome:
![chrome](https://cloud.githubusercontent.com/assets/9446141/24204492/c147c3d0-0f29-11e7-9332-41bfc3b43f46.png)
