### ISSUE TITLE
Do we have here a server reporting feature where we can see previous run result?

### ISSUE THREAD

**Issue by prasanta-biswas** [allure-framework/allure2#227]

**Comment by baev** [comment]
You can get some kind of history using latest allure jenkins plugin and BETA6. Now it only shows history for test and success rate. We will improve the history feature during next releases, so you will be able to watch previous results, test trend, new tests in report, and status changes for tests

**Comment by prasanta-biswas** [comment]
@baev Is this feature released?

**Comment by baev** [comment]
yep. You need to use Allure Jenkins plugin together with Allure 2.0.1 to get history feature. Demo report available here https://ci.qameta.io/job/allure2_build/job/master/Demo_Report/

**Comment by prasanta-biswas** [comment]
your link is not working

**Comment by just-boris** [comment]
New link would be:
https://ci.qameta.io/job/allure2/job/master/Demo_Report/

**Comment by prasanta-biswas** [comment]
Thanks for the help. It would be helpful if it can maintain a list of all execution records and anyone clicking on any item of the list will take to the complete report.
