### ISSUE TITLE
Return sorting by errors

### ISSUE THREAD

**Issue by monolithed** [allure-framework/allure2#231]
The current lists are sorted in Inverse alphabetical order. Please, return sorting by errors.

![img-2017-03-24-12-16-41](https://cloud.githubusercontent.com/assets/803674/24291570/8a48b4f8-109a-11e7-92c7-32f28f5bf973.png)

**Comment by eroshenkoam** [comment]
#79 - it's just not implemented yet

**Comment by monolithed** [comment]
Thanks!
