### ISSUE TITLE
Testcase history tab showing same date time for different runs

### ISSUE THREAD

**Issue by SohanTirpude** [allure-framework/allure2#2402]
### Describe the Bug

Hello all,

I am seeing same date time for different test case runs. Can anyone please help me out on how to fix this?

I am running this job in every 5 minute interval from Jenkins and some times I am seeing this abnormalities. BTW this is the demo test file I am using: https://github.com/fescobar/allure-docker-service-examples/blob/master/allure-docker-python-pytest-example/tests/demo_test.py

### Steps to Reproduce

1. Click on "Suite" tab.
2. Click on test case
3. Click on particular test
4. Click on "History" tab
5. For different runs, the date time is showing exact same.

### Expected Behaviour

For separate suite runs, the date time for the testcase should be different.

### Screenshots or Additional Context

<img width="1792" alt="Screenshot 2024-03-05 at 5 25 49 PM" src="https://github.com/allure-framework/allure2/assets/13250447/197b6c3d-9087-4591-bcd2-f9e247a80966">

### What Language are you using?

Python 3.8

### What Framework/Allure Integration you are using?

allure-python 2.13.2

### What version of Allure Integration you are using?

2.13.2

### What version of Allure Report you are using?

2.21

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment]
closed as duplicate https://github.com/orgs/allure-framework/discussions/2407
