### ISSUE TITLE
The majority of TC's are shown under 'Root Suite'

### ISSUE THREAD

**Issue by Mohammad-Abohasan** [allure-framework/allure2#2534]
### Describe the Bug

The majority of TC's are shown under **Root Suite**

<img width="858" alt="Screenshot 2024-05-01 at 4 05 14 PM" src="https://github.com/allure-framework/allure2/assets/74917940/5ddef540-5468-4a78-95fc-b05c2b442bce">

### Steps to Reproduce

Generate an Allure report through Jenkins.

### Expected Behaviour

Each test case appears in its own describe.

### What Language are you using?

TypeScript

### What Framework/Allure Integration you are using?

Jenkins/Allure/Cypress

### What version of Allure Integration you are using?

-

### What version of Allure Report you are using?

2.27.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mattias-clearroute** [comment]
Hi @Mohammad-Abohasan what was the reason the defect was set as completed? I cant see any code commit and have this issue myself
