### ISSUE TITLE
latest version (2.29.0) is not available in maven repo

### ISSUE THREAD

**Issue by uthark** [allure-framework/allure2#2557]
### Describe the Bug

According to https://github.com/allure-framework/allure2/releases, latest version is 2.29.0 

But when I try to use it I get this error:

```
#4 215.4 FAILURE: Build failed with an exception.
#4 215.4 
#4 215.4 * What went wrong:
#4 215.4 Could not determine the dependencies of task ':e2e-test:test'.
#4 215.4 > Could not resolve all task dependencies for configuration ':e2e-test:testRuntimeClasspath'.
#4 215.4    > Could not find io.qameta.allure:allure-bom:2.29.0.
#4 215.4      Required by:
#4 215.4          project :e2e-test
#4 215.4    > Could not find io.qameta.allure:allure-junit5:.
#4 215.4      Required by:
#4 215.4          project :e2e-test
#4 215.4 
```

After looking into maven central https://central.sonatype.com/artifact/io.qameta.allure/allure-bom I see that the latest version is 2.27.0

### Steps to Reproduce

1. try to use 2.29.0

### Expected Behaviour

dependency downloaded

### Screenshots or Additional Context

N/A

### What Language are you using?

Java

### What Framework/Allure Integration you are using?

allure-junit5

### What version of Allure Integration you are using?

2.29.0

### What version of Allure Report you are using?

2.29.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment]
as for today, the latest version of allure-java integrations is 2.27.0, see https://github.com/allure-framework/allure-java/releases
