### ISSUE TITLE
Html tags not rendered in allure.step

### ISSUE THREAD

**Issue by akila0791** [allure-framework/allure2#2592]
### Describe the Bug

Html effects with `Bold tag <b> , New Line Break <br>, Font tags<font>` not rendered in allure.step

### Steps to Reproduce

`Allure.step("<b>Sample Text</b>")`

### Expected Behaviour

Sample Text should be displayed in allure report. but` <b>Sample Text</b>` is displayed.

> 

### What Language are you using?

Java

### What Framework/Allure Integration you are using?

TestNG

### What version of Allure Integration you are using?

2.27.0

### What version of Allure Report you are using?

2.27.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment]
Allure never had such a feature, so you may want to create a [feature request](https://github.com/orgs/allure-framework/discussions/categories/ideas-feedback) instead of raising a bug.

**Comment by baev** [comment]
See https://github.com/orgs/allure-framework/discussions/2593

**Comment by akila0791** [comment]
okay thank you for the reply.
