### ISSUE TITLE
Failed or broken fixtures always have `passed` status

### ISSUE THREAD

**Issue by epszaw** [allure-framework/allure2#2600]
### Describe the Bug

When I have broken or failed fixture in my test results, it displays as passed one in a generated report:

<img width="822" alt="image" src="https://github.com/allure-framework/allure2/assets/13414205/01a1bf80-100c-452a-8a68-2cf8228d1eb7">

The result:

<img width="1399" alt="image" src="https://github.com/allure-framework/allure2/assets/13414205/2f400972-a04a-4468-b17c-61ae6c25c542">

### Steps to Reproduce

1. Create scope
2. Create a broken or a failed fixture in a context of the scope
3. Write the fixture and close the scope
4. Generate a report

### Expected Behaviour

The fixture has a correct status

### What Language are you using?

JavaScript

### What Framework/Allure Integration you are using?

-

### What version of Allure Integration you are using?

3.0.0-alpha.3

### What version of Allure Report you are using?

2.27.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MSlaski** [comment]
Hello,
Using Allure 2.29.0 I found same issue
One of the testStages is broken, but overall test status is passed

![image](https://github.com/user-attachments/assets/b26748b0-0cc2-4ae6-953e-aa8dd9afde75)

Part of json file:
![image](https://github.com/user-attachments/assets/b7dfb2a9-c578-4647-8e1d-36bd041a1644)
![image](https://github.com/user-attachments/assets/34ddc051-6ab0-4a0b-a7d1-08300e1a6047)

@baev any plans to fix that?

**Comment by baev** [comment]
@MSlaski Allure displays the status provided by the test framework. For example, if you catch the exception during test execution, the test will pass; however, some of the steps may be broken or failed.

**Comment by MSlaski** [comment]
@baev but at some stage (marked as broken) Im explicitly using `fail()` method which is throwing `AssertionError`- Im pretty sure this exception was not matched during the test. So why overall score of test case was PASSED?

**Comment by baev** [comment]
@MSlaski could you please specify the test framework you're using and the versions?

**Comment by MSlaski** [comment]
Cucumber 7 via SerenityBDD

Parts of POM file related to Allure and Serenity/Cucumber:
```
<properties>
<allure.version>2.28.0</allure.version>
<allure.maven.version>2.12.0</allure.maven.version>
<serenity.version>4.1.20</serenity.version>
</properties>
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-bom</artifactId>
                <version>${allure.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!--            Serenity and Allure are using different versions of that package that's why its necessary to force version -->
            <dependency>
                <groupId>io.cucumber</groupId>
                <artifactId>messages</artifactId>
                <version>24.1.0</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
...
<dependencies>
        <!--        Necessary to trigger tests via Cucumber Runner -->
        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <version>5.8.2</version>
            <scope>test</scope>
        </dependency>

        <!--        Serenity Package -->
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-screenplay</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-screenplay-webdriver</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>io.cucumber</groupId>
                    <artifactId>messages</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!--        Allure package -->
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-cucumber7-jvm</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-junit4</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-maven</artifactId>
            <!-- It's not the same version like rest Allure modules -->
            <version>${allure.maven.version}</version>
        </dependency>
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-awaitility</artifactId>
        </dependency>
...
```

**Comment by baev** [comment]
@MSlaski, please create a separate issue in the [allure-java](https://github.com/allure-framework/allure-java) repository. If possible, provide a sample repo to reproduce the problem (that will speed up things a lot; you can use this example: https://github.com/allure-examples/allure-cucumber7-junit-platform-maven as a baseline)

**Comment by MSlaski** [comment]
https://github.com/allure-framework/allure-java/issues/1100
