### ISSUE TITLE
Wrong counts in feature by stories widget

### ISSUE THREAD

**Issue by baev** [allure-framework/allure2#261]

**Comment by krzprz** [comment]
Hello, 
Is this problem fixed? I use version 2.11.0 and still the problem exist.

thanks,
Krzysztof

**Comment by baev** [comment]
@krzprz at the moment it is not wrong, it's more like misleading  - it shows statistic by stories per feature, not by tests. So if you have 

```
Feature1
   Story1
      tc1 passed
   Story2
      tc2 passed
      tc3 failed
```

it will show `Feature1: 1 passed and 1 failed`

**Comment by krzprz** [comment]
you mean that for Feature1 there is one story which passed all tests and one story which doesn't pass all test?

**Comment by baev** [comment]
yep

**Comment by krzprz** [comment]
thanks
