### ISSUE TITLE
Add ability to provide custom translations

### ISSUE THREAD

**Issue by valfirst** [allure-framework/allure2#2731]
### Describe the Bug

Sometimes users are not ok (or even confused) with embedded translations.

Please provide a mechanism to feed custom translations to report.

### What version of Allure Report you are using?

2.30.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment]
Could you please elaborate on what confuses users? Are you saying that there are some mistakes in the existing translations, or do you need to add support for the new languages?

**Comment by valfirst** [comment]
> Are you saying that there are some mistakes in the existing translations

no, I would provide PR for this case

> or do you need to add support for the new languages?

not exactly

> Could you please elaborate on what confuses users?

For example, we use [Behaviors plugin](https://github.com/allure-framework/allure2/tree/main/plugins/behaviors-plugin), it adds tab with name [Behaviors](https://github.com/allure-framework/allure2/blob/main/plugins/behaviors-plugin/src/dist/static/index.js#L6) in English. Users (people who review test execution reports) say: "What is 'Behaviors? I don't understand. I would name it 'Features by stories' or 'Features'". I can't say the current naming is not correct, that's a matter of perception. 

So my idea is to implement mechanism that will provide the ability to provide full custom translation (e.g. full `en_xyz.json` file) or to override certain custom translations (e.g. `tab.behaviors.name=Features`)

**Comment by baev** [comment]
Thanks! We are currently reworking the UI and will make sure to note your comments. I don't like the current tab names, either.

It would be super helpful if you provided all the feedback you have in discussions (I read them all).

Regarding the custom translation request:

You can add the custom translations as well as modify the existing ones by executing the following script:

```js
allure.api.addTranslation('en', {
    tab: {
        behaviors: {
            name: 'Features'
        }
    },
});
```

The scripts can be injected via custom plugins.

**Comment by valfirst** [comment]
It works, thanks! I'll share the feedback/alternate options once I collect them.
