### ISSUE TITLE
Dynamic Categories being assigned to all cases 

### ISSUE THREAD

**Issue by shah095** [allure-framework/allure2#2762]
### Describe the Bug

In python (3.9) when I try and assign categories with dynamic labels it's assigning them to all cases.
I used allure.dynamic.label("category", "Specific Category") and then in the categories.json use "matchedLabels": ["category=Specific Category"] but it doesn't seem to be assigning them to specified cases. every cases if left under the all the categories.  

### Steps to Reproduce

1. create multiple test cases with dynamic label for "category"
2. assign unique categories to each cases
3. run the cases
4. generate the report

### Expected Behaviour

in the categories section the cases with the associated category should only have that specific category.

### What Language are you using?

Ruby

### What Framework/Allure Integration you are using?

pytest

### What version of Allure Integration you are using?

2.30.0

### What version of Allure Report you are using?

2.30.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment]
> the categories.json use "matchedLabels"

`matchedLabels` was never a part of the `categories.json`, see the docs: https://allurereport.org/docs/how-it-works-categories-file/

The recommended approach is to extend errors/add custom error messages and then create a match based on the failure reason or trace.
