### ISSUE TITLE
Return the `allure.properties` file 

### ISSUE THREAD

**Issue by monolithed** [allure-framework/allure2#277]
It would be nice to return the `allure.properties` file to set `allure.issues.tracker.pattern` and other properties.

**Comment by just-boris** [comment]
There is already an issue about that: https://github.com/allure-framework/allure-java/issues/44.

@baev are you going to implement it exclusively for Java? How about other platforms?

**Comment by monolithed** [comment]
> @baev are you going to implement it exclusively for Java? How about other platforms?

The same question.

**Comment by eroshenkoam** [comment]
we are thinking about it today :)

**Comment by eroshenkoam** [comment]
#290

**Comment by baev** [comment]
now you can put `allure.properties` file to results folder (fixed via #290)

**Comment by baev** [comment]
> There is already an issue about that: allure-framework/allure-java#44.

Nope, that is another one. Since Allure 2 all the properties should be processed via adapters, so for Allure 2 Java adapters this can be done via `allure.properties` file. Other languages will have their own way to configure adapters
