### ISSUE TITLE
Behave JUNIT support

### ISSUE THREAD

**Issue by prayagvakharia** [allure-framework/allure2#283]
Hi,

I am using behave for automation testing. I have create JUnit xml file using behave.
ex:
```
behave --junit test.feature 
```

Can i use this xml file to create allure2 reports

Thanks,
Prayag

**Comment by sseliverstov** [comment]
hi
do you mean http://pythonhosted.org/behave/?

**Comment by prayagvakharia** [comment]
Yes.

We can create Junit XML report file using --junit param.
So need to know this XML is supported with allure2.

https://pythonhosted.org/behave/behave.html

Thanks,
Prayag

**Comment by baev** [comment]
For allure2 beta7 and above you can use

```bash
$ allure serve --profile junit junit/results/path
```

and

```bash
$ allure generate --profile junit junit/results/path
```

**Comment by psharmaop5** [comment]
@prayagvakharia : 
Hi 
I also wanted to apply same approach related to Behave and have a question here:
Were you able to generate reports by the solution provided by @baev ?

Thanks.

**Comment by sseliverstov** [comment]
@prayagvakharia, do you mean https://github.com/behave ?

**Comment by psharmaop5** [comment]
@sseliverstov  yes, I guess he means the same. Behave BDD with Python (Scripting).

**Comment by sseliverstov** [comment]
One or two weeks and we will have beta.

**Comment by prayagvakharia** [comment]
@psharmaop5 : no I am not able to generate report. It always display blank dashboard. I switch to cucumber report.

**Comment by prayagvakharia** [comment]
@sseliverstov as you said one or two weeks you have beta release so is it support python behave .xml or Json file right? Curious about beta release if it support python behave report.

I am using --JUnit or --format=json.pretty option for my test reports.

**Comment by sseliverstov** [comment]
No. I am about behave formatter that produce results in native allure2 format. Just install from pypi and use with common line like this: behave -f allure_behave.formatter:AllureFormatter -o ./allrue-result. PR here: https://github.com/allure-framework/allure-python/pull/61

**Comment by sseliverstov** [comment]
@prayagvakharia just released https://pypi.python.org/pypi/allure-behave/2.0.0b2. Will be great if you try it and give some feedback.
