### ISSUE TITLE
Sidebar gaps

### ISSUE THREAD

**Issue by baev** [allure-framework/allure2#309]
<img width="88" alt="screen shot 2017-05-02 at 12 23 46" src="https://cloud.githubusercontent.com/assets/2149631/25612148/45c49732-2f32-11e7-9672-07ae8111daf0.png">
<img width="212" alt="screen shot 2017-05-02 at 12 24 43" src="https://cloud.githubusercontent.com/assets/2149631/25612169/5ab2fe9a-2f32-11e7-97bf-3240b439525e.png">

**Comment by just-boris** [comment]
The fastest solution 

```css
white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;
```
