### ISSUE TITLE
Allow empty allure results

### ISSUE THREAD

**Issue by i-feofilaktov** [allure-framework/allure2#312]
Use-case:
I've got template jenkins task with allure report post-build action.

In some cases there is no tests and rest run produces no output in alluredir. In that case allure commandline fails and raises an Exception, and whole jenkins task is marked as failed.

Unfortunately it's hardly possible to turn off post-build action for some input parameters in jenkins, so I need allure-commandline not to fail in case of empty results.

**Comment by dzieciou** [comment]
In which release it will be released?
