### ISSUE TITLE
Cannot find allure-command line in 2.0 release notes

### ISSUE THREAD

**Issue by tk8817** [allure-framework/allure2#327]
Hey guys, 
I noticed after the 2.0-BETA1 that you stopped posting the allure-commandline.zip in the release notes. Are you planning to bring it back? I ask primarily as I would like to keep my library up to date with your most recent releases https://github.com/automation-wizards/docker_allure

**Comment by sskorol** [comment]
@tk8817 you can find latest artifacts here: https://bintray.com/qameta/generic/allure2

**Comment by baev** [comment]
we kind of like to have single place to store all the artifacts, and our team decided to use bintray

**Comment by tk8817** [comment]
Thanks @sskorol & @baev, and congrats on the release!
