### ISSUE TITLE
Allow Step titles to render html

### ISSUE THREAD

**Issue by BabyRoot** [allure-framework/allure2#331]
In some instances our test highlight actions by bolding the step title, for example

`<b>Typed</b> foo on By.cssSelector: #user`

When this is rendered for the report, the step name is exactly as shown above; the html tags are displayed in all their glory. It would be good to allow html to be rendered in the step names so that it appears like this

`Typed foo on By.cssSelector: #user`

To be more specific on the use case, here is a snippet of code

```
public void someMethod(){
   String stepName = "<b>Typed</b> foo on By.cssSelector: #user";
   logStep(stepName);
}

@Step("{0}")
  private void logStep(String stepName) {
}
```

Copy issue https://github.com/allure-framework/allure1/issues/708

**Comment by BabyRoot** [comment]
Copy issue https://github.com/allure-framework/allure1/issues/708

**Comment by baev** [comment]
Am I right that you need to display some html on test case page instead of our execution block?

**Comment by BabyRoot** [comment]
For me - this is the ability to display step text in a few lines, set the color and style of the text

**Comment by baev** [comment]
The problem is that currently steps block is pretty much complicated, so adding some styles can break it down. But there are an ability to create custom view of steps/attachments etc: 

<img width="629" alt="screen shot 2017-05-10 at 17 45 19" src="https://cloud.githubusercontent.com/assets/2149631/25904681/9b96bf7e-35a8-11e7-82ad-40374bf1eee6.png">

**Comment by lararojasmr** [comment]
Hi, has there been no implementation to add HTML tags or Markdown formatting to step names?

**Comment by Reasunta** [comment]
Hi! Join to the question above. What's the final solution for the issue?

**Comment by lararojasmr** [comment]
This solution was implemented?

**Comment by ohlori** [comment]
Any workaround @baev ?

**Comment by baev** [comment]
Please [create a new discussion](https://github.com/orgs/allure-framework/discussions/new/choose) instead of commenting on closed issues, and I'll be happy to share the update.
