### ISSUE TITLE
[Suggestion] Add a value field to Flaky annotation.

### ISSUE THREAD

**Issue by L-Evg** [allure-framework/allure2#338]
### Issue. 
Currently it is possible to mark a test as unstable (flaky) but there is no way to put a note on why it is considered as such.

### Suggestion
Alter the `@Flaky` annotation to provide an option to put notes/thoughts (similar to `@Step` etc), i.e.:
```java
@Flaky("Supposedly it fails on Mondays, early in the morning only. Need to gather statistics.")
public void aTestWhichFailsFromTimeToTime {
...
}
```
The note provided should be than displayed in the report as a part of test title.

**Comment by baev** [comment]
moved to allure-java https://github.com/allure-framework/allure-java/issues/81
