### ISSUE TITLE
Opportunity to exclude test parameter from history matching

### ISSUE THREAD

**Issue by rovner** [allure-framework/allure2#342]
I have several test parameters that differs from launch to launch and I want them to be shown in parameters block. Right now this blocks history feature, because test with different parameters have different id's in history.json.

**Comment by baev** [comment]
Could you please suggest us how the problem can be solved?

**Comment by rovner** [comment]
Probably, you could introduce additional ParameterKind that wouldn't be taken into account when building test id for history json.

**Comment by baev** [comment]
Related issues

Allure1 https://github.com/allure-framework/allure1/issues/959
Allure2 https://github.com/allure-framework/allure-java/issues/80

**Comment by DudaGod** [comment]
@baev @just-boris guys tell me please will you implement this feature? Or you are waiting a PR from someone?

**Comment by dr29bart** [comment]
Is it TestNG specific?

**Comment by sridharUpputuri** [comment]
@baev Any update on this? 
We also struck with the kind of same issue, where our test will pick-up the random user from pool of available users for specific role as part of test in the param (VO). And the same test is showing twice when the test picked up another user with same role (but ideally it's same test being run with different username same role)
![image](https://user-images.githubusercontent.com/52928428/123734693-c8fc2480-d86b-11eb-9952-042ebe1c5d97.png)

@baev  Can you please let us know if there is any work-around to overcome this issue.

**Comment by sridharUpputuri** [comment]
@baev Need your input here.

**Comment by baev** [comment]
I already introduced model changes in allure-java ( https://github.com/allure-framework/allure-java/pull/615 )

**Comment by sridharUpputuri** [comment]
Is there any ETA when this change will be release? Is there way to use it in the meantime?
