### ISSUE TITLE
 Invalid ALLURE_HOME

### ISSUE THREAD

**Issue by thakar27** [allure-framework/allure2#343]
Hi,
I am using allure version 1.4.23 and i am trying to integrate with Jenkins 
When in build the job, i am getting this issue
Invalid ALLURE_HOME: /E:\jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\Allure-Commandline-1.4.23 is not a valid allure commandline directory 

Can somone please help with this issue ?

**Comment by eroshenkoam** [comment]
will be fixed in next release https://github.com/jenkinsci/allure-plugin/issues/108

**Comment by thakar27** [comment]
I am using windows not linux

**Comment by eroshenkoam** [comment]
it's both os problem: 
https://github.com/jenkinsci/allure-plugin/pull/111/files

**Comment by thakar27** [comment]
When can we expect the next release?

**Comment by eroshenkoam** [comment]
in the end of week
