### ISSUE TITLE
Keep selected item after closing

### ISSUE THREAD

**Issue by monolithed** [allure-framework/allure2#344]
![img-2017-05-16-18-59-49](https://cloud.githubusercontent.com/assets/803674/26115873/f5b2cd98-3a69-11e7-8770-bb24cde9fdfc.png)

**Comment by baev** [comment]
Do you mind to use Allure 2 instead of 1.5 ?

**Comment by monolithed** [comment]
Allure Jenkins Plugin@2.15, Allure@2.0.0

**Comment by monolithed** [comment]
Oops, something wen wrong...
