### ISSUE TITLE
Report doesn't diplay multiple data from @DataProvider set

### ISSUE THREAD

**Issue by ASaunin** [allure-framework/allure2#346]
**For more than one element from `test-ng` `@DataProvider` set, Allure2 report shows only the last one.**

See the shot:
![image](https://cloud.githubusercontent.com/assets/19559375/26157015/b4b152a8-3b20-11e7-83a8-68b0f612949b.png)

To reproduce the bug you can use source code from (https://github.com/sskorol/allure2-testng-report/issues/1)
Just add one more element to the data provider `io.github.sskorol.testcases.common.CommonTests` class:
```
@DataProvider
public static Iterator<Object[]> getData() {
   final List<User> users = Arrays.asList(
           new User("dummyUsername", "dummyPassword"),
           new User("John Doe", "dummyPassword"));
   return users.stream()
                .map(user -> new Object[]{user})
                .iterator();
}

```

**Comment by sskorol** [comment]
@ASaunin already answered in the original issue. You can find second test result in the `Retries` section.

![image](https://cloud.githubusercontent.com/assets/6638780/26161715/59000bea-3b2d-11e7-8fb3-2f47f68dd895.png)

Click it and you'll be redirected to the second test with another dataset.

**Comment by sskorol** [comment]
@baev I believe we need to update docs with this info. As for me it was a surprise as well to be honest. `DataProvider` iterations are not quite similar to `Retries` mechanism in TestNG. These 2 have different intentions. So maybe would be better to revise it a bit (at least section naming).

**Comment by ASaunin** [comment]
I had a deeper look, and I think it is not the normal behavior, when multiple test execution combines with history. These are completely different things.

**Comment by baev** [comment]
fixed via https://github.com/allure-framework/allure-java/commit/a192e6d31f5a3b45802577f815ae918ce1658678

**Comment by baev** [comment]
fix released in 2.0-BETA7

**Comment by mashish** [comment]
Hello,
I am facing similar issue, Here is my test structure
- Test Class
    @Test method
     DataProvider runs through multiple rows

My Allure report contains only last set of dataprovider.

Am I doing anything wrong over here

**Comment by mashish** [comment]
@asaunin @baev Please suggest
