### ISSUE TITLE
Skin with infinite scroll like mochawesome

### ISSUE THREAD

**Issue by lanwen** [allure-framework/allure2#354]
http://adamgruber.github.io/mochawesome/

Allure has great model to represent very cool report. But sometimes developers only want to SCROLL this report quickly. So probably it will be cool to have one page representation with status sort, nested objects (classes, methods, steps) and infinite, lazy-loadable scroll. Very similar to example.

**Comment by baev** [comment]
Allure have no skins. We have some ideas about infinite scroll in the report, but it is only an ideas at this point.
