### ISSUE TITLE
Allure link on main jenkins build page shows report from old build

### ISSUE THREAD

**Issue by netmajor** [allure-framework/allure2#363]
When I click on Allure Report on main page of jenkins build it navigates me to page with old report.
![main](https://cloud.githubusercontent.com/assets/649986/26543432/39c52406-445e-11e7-884c-bae950dd6338.PNG)
![history](https://cloud.githubusercontent.com/assets/649986/26543447/47be7594-445e-11e7-8c37-e6845ab1323e.PNG)
![empty trend](https://cloud.githubusercontent.com/assets/649986/26543482/6c67f32a-445e-11e7-960e-3a260d577c3d.PNG)

**Comment by baev** [comment]
duplicate https://github.com/jenkinsci/allure-plugin/issues/113

**Comment by sbhatta2018** [comment]
@baev It sill pulls old report. Can you please provide the steps?

**Comment by baev** [comment]
@sbhatta2018 please do not comment on old issues, create a new one instead
