### ISSUE TITLE
Allure link on main jenkins build page shows empty report with errors

### ISSUE THREAD

**Issue by netmajor** [allure-framework/allure2#364]
When I click on Allure Report on main page of jenkins build it navigates me to empty page.
I have attached error from chrome console
![chromeerror](https://cloud.githubusercontent.com/assets/649986/26543832/c1a55fac-445f-11e7-978b-ac3126a14eb3.PNG)
![empty](https://cloud.githubusercontent.com/assets/649986/26543868/dfe675aa-445f-11e7-8de7-1576f002b45e.PNG)

**Comment by baev** [comment]
seems like the same problem https://github.com/jenkinsci/allure-plugin/issues/113

**Comment by sbhatta2018** [comment]
It is not working yet. Facing the same issue
