### ISSUE TITLE
Dynamic tests

### ISSUE THREAD

**Issue by baev** [allure-framework/allure2#366]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

There is no mark for dynamic tests. 

#### What is the expected behavior?

Dynamic tests displayed in the report. We have an API to get all the dynamic tests and to mark tests as dynamic during report generation.

#### What is the motivation / use case for changing the behavior?

Such tests have no history, so currently having dynamic tests in the report breaks history trend

#### Please tell us about your environment:

- Allure version:        2.0+
- Test framework:     any
- Allure adaptor:       any
- Generate report using: any

**Comment by netmajor** [comment]
How these test should be execute?
I am thinking about functionality to rerun failed tests, but as i know you will not implement it in allure. So we thinking to create own page where we can list failed tests from allure report and run from them failed tests using jenkins job. 

It will be great if you add showing dynamic tests and it will be not consider in history of normal build so TREND will be not broken

**Comment by baev** [comment]
> I am thinking about functionality to rerun failed tests

Allure already supports retries. So when you retry failed tests Allure hides retries and display only last status for each test.

> It will be great if you add showing dynamic tests and it will be not consider in history of normal build so TREND will be not broken

Yep, exactly. And also we need to know is test dynamic or new one for this feature #367

**Comment by netmajor** [comment]
> Allure already supports retries. So when you retry failed tests Allure hides retries and display only last status for each test.
Do you mean retries like in mocha api ? [mocha](https://mochajs.org/#retry-tests)

**Comment by baev** [comment]
I guess so

**Comment by fdPoornima** [comment]
I have my tests running in parallel using selenium grid. I am using cucumber-maven and selenium. So when I run one test case parallel on 2 devices, allure treats the execution on one of the devices as retries, instead of a seperate thread. How can this be solved
