### ISSUE TITLE
allure plugin --profile how set

### ISSUE THREAD

**Issue by hotred** [allure-framework/allure2#370]
### allure plugin --profile how set

"allure plugin --profile ./config/allure.yml"  but is wrong

I can customize self plugin

**Comment by eroshenkoam** [comment]
config/allure-{profile}.yml
allure plugin --profile {profile}

**Comment by baev** [comment]
yep, by default allure uses `config/allure.yml` configuration file. You can create your own configuration (for example to disable some default plugins). So create file

`config/allure-someprofilename.yaml`

and then you can use this configuration using the following command:

```bash
$ allure --profile someprofilename <command>
```

**Comment by hotred** [comment]
If I can put the config and pugins move to other places，
this is my project: 
project/config/allure.yml
`//allure.yml
plugins:
  - behaviors-plugin
  - packages-plugin
  - screen-diff-plugin
  - custom-logo-plugin`
project/plugins


now i run : allure generate --profile ./config/alluer -c allure-results -o allure-report && allure open

open website: No plugins are introduced

**Comment by hotred** [comment]
we use npm intall allure-commandline , my want add new plugin, if add to /config/, Not easy management，so we want to add other dir

**Comment by baev** [comment]
created an issue https://github.com/allure-framework/allure2/issues/378
