### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by GVAGVA** [allure-framework/allure2#372]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
 
#### What is the current behavior?

Currently Right-To-Left languages is not supported by Allure. 

#### What is the expected behavior?

Allure supports Right-To-Left languages.

#### What is the motivation / use case for changing the behavior?

I want to add Hebrew translation to Allure.

#### Please tell us about your environment:

- Allure version: any

#### Other information 

We can use [postcss-rtl](https://github.com/vkalinichev/postcss-rtl) module for base support for RTL languages.

**Comment by TpSr52** [comment]
I am working on it. Please assign it to me.
