### ISSUE TITLE
Allure android adapter

### ISSUE THREAD

**Issue by Badya** [allure-framework/allure2#377]
Can you add a link to it in your docs? 

https://github.com/TinkoffCreditSystems/allure-android - generates output according to Allure TestNG format

**Comment by baev** [comment]
Sure. You can add it by yourself sending a pull request to allure-docs repository https://github.com/allure-framework/allure-docs

**Comment by baev** [comment]
@kurau can you handle this issue?

**Comment by Badya** [comment]
I'll gonna do it as soon as finish docs in project's readme, upload to bintray and provide an example

**Comment by baev** [comment]
cool. You can use our Gitter in case of any problems or questions

**Comment by FruNoman** [comment]
Hi ! I created allure-android adapter , so you can use it , and pls feedback 
https://github.com/FruNoman/allure-android
