### ISSUE TITLE
No "Back to jenkins project" link in report

### ISSUE THREAD

**Issue by lohokiller** [allure-framework/allure2#379]
Current environment:

- Allure version:        2.1.1
- Test framework:  Python 2.6.6, pytest-3.0.7
- Allure Jenkins Plugin:  2.18
- Generate report using: allure-command line

Problem Description:

In upper left corner https://ci.qameta.io/job/allure2/job/335-nan-piechart/Demo2_Report/ I see link, than I need, but no idea how to add it to my Jenkins/Allure.
In my case that link is located only on Overview page in Executors section.

Other information 
I had the same problem for all previous versions.

**Comment by sskorol** [comment]
This link appears when you publish reports via `HtmlPublisher` plugin. With common Allure2 Jenkins plugin a link for getting back to job is usually located in `Executors` section on `Overview` tab.

**Comment by lohokiller** [comment]
Thanks, that's all I need. But it is funny, that vendor does not use Jenkins-Allure-Plugin on Demo Page. So, they'd better to do that feature-request.
