### ISSUE TITLE
Missing section "Defects" on Overview page

### ISSUE THREAD

**Issue by lohokiller** [allure-framework/allure2#383]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Missing section "Defects" on Overview page with direct link to related tests

#### What is the expected behavior?
Section "Defects" appear on Overview page

#### What is the motivation / use case for changing the behavior?
There no any links to defects on OverView page. А lot of extra clicks.

#### Please tell us about your environment:
- Allure version:             2.1.1
- Test framework:          Python 2.6.6, pytest-3.0.7
- Allure Jenkins Plugin:  2.18
- Generate report using: allure-command line

**Comment by sskorol** [comment]
@lohokiller Defects tab was replaced with Categories. And it's an Allure 2 feature. See https://docs.qameta.io/allure/latest/#_overview_page

**Comment by lohokiller** [comment]
Thanks. It is not about tab. No ANY direct links to tests on OverView page. Terrible degradation of usability.

**Comment by lohokiller** [comment]
Create common issue for usability degradation https://github.com/allure-framework/allure2/issues/390
