### ISSUE TITLE
Allure report only shows the last test run report

### ISSUE THREAD

**Issue by karanbajaj2209** [allure-framework/allure2#389]
Although my allure results folder contains the test results of more than 5 test runs. But the allure report only shows the last test run report. 

How can I view all the previous launches in the dashboard if I have all the data in the allure-results folder already?

**Comment by baev** [comment]
Could you please specify more details, how do you get Allure results and how do you generate the report?

**Comment by baev** [comment]
closed due to no response. Feel free to reopen
