### ISSUE TITLE
Add annotation to hide sensitive data in attaches and report

### ISSUE THREAD

**Issue by LeshaVasya** [allure-framework/allure2#392]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
All sensitive data like passwords and access keys is shown as plain text in report and attaches.

#### What is the expected behavior?

Introduce allure annotation to hide sensitive data for step. Annotation could have string parameter for regex to explain what to hide in this particular step. 
Such "what to hide regex" parameter could be introduced for attachment annotation as well.
Default regex parameter could involve some symbols following passwords and keys for instance.

#### What is the motivation / use case for changing the behavior?

Possible security hole if you demo production test report to other teams.

#### Please tell us about your environment:

- Allure version:        2.1.0
- Test framework:        testng@6.10
- Allure adaptor:        allure-testng@2.0-BETA10
- Generate report using: allure-maven@2.8

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by cpjust** [comment]
@baev I have this PR to add this feature request, but it says "Pending — Contributor License Agreement is not signed yet." even though when I click on the CLA it says I've signed it.  I'm not sure if that's normal or if I need to do something to get it unblocked?

https://github.com/allure-framework/allure-java/pull/465
