### ISSUE TITLE
Add an ability to copy test case start-end timings to clipboard

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [allure-framework/allure2#395]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 

  - [x] feature request

#### What is the current behavior?
Test case details view has only an ability to view test case start-end values as a tooltip

#### What is the expected behavior?
It'd be nice to have an ability to copy info(start-end) from the tooltip to clipboard

#### What is the motivation / use case for changing the behavior?
Usability reasons

#### Please tell us about your environment:
- Allure version:        2.1.1
- Test framework:        testng@6.10
- Allure adaptor:        allure-testng@2.0-BETA8

#### Other information 

![2017-06-12_16-29-50](https://user-images.githubusercontent.com/9446141/27036152-96794568-4f8c-11e7-81fc-8f53e9963084.png)

**Comment by jk816vu** [comment]
@baev Hi i was looking on this issue but i see that its been discused in https://github.com/allure-framework/allure2/pull/733. Is it still open ?

**Comment by baev** [comment]
yes as far as I know

**Comment by jk816vu** [comment]
@baev so can i work on it? And how it should look? something like this ? 
![image](https://user-images.githubusercontent.com/37405331/143584482-e51765e5-cf43-4af8-b94b-9ee49ebed67b.png)

**Comment by jk816vu** [comment]
And what should be in clipboard after pressing button: 
data-tooltip a.k.a. "10/25/2021 17:55:12-17:55:13" ?

**Comment by jk816vu** [comment]
Hi @baev and @just-boris i just made it work like clickable span like baev said. Can you check it ?

**Comment by just-boris** [comment]
I am wondering why is this important to make the time copyable. You can always select the text and press ctrl+c on any content. Test suite and case name make sense, because they are the most used. But what about time?

Also timestamps are stored in the different formats in different tools. Copying the current human readable option will not help looking it up with any logs. Especially the implementation from @jk816vu with `&nbsp;&ndash;&nbsp;` in the middle of copyable text

**Comment by jk816vu** [comment]
Ok, noted but why is it open issue again?
