### ISSUE TITLE
Hard to distinguish data-drive tests/Provide placeholders support @Title

### ISSUE THREAD

**Issue by L-Evg** [allure-framework/allure2#397]
#### I'm submitting a ... 
  - [x] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behaviour?
Allure 2 report shows data-driven tests by method name/or fixed title only:
No `@Title`
![2_ _ _](https://user-images.githubusercontent.com/16156565/27123268-0a80c7c8-50f6-11e7-8b73-b29f689fda3c.png)

Using `@Title` 
![2_ _ _](https://user-images.githubusercontent.com/16156565/27122874-afa8471e-50f4-11e7-9f93-c36a570ebf87.png)

So, there is no quick way to distinguish data cases, one need to go through the list and click each case to see the difference.

#### If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
1. Develop a data-drive test;
2. Ensure you have two and more data-cases for the test;
3. Run the test and generate report;
4. Have a look at the report.

#### What is the expected behaviour?

1. If there is no `@Title` then test method name + a short excerpt of the arguments' #toString() is shown in the list;
2. If there is `@Title` then the title's value is shown (current behaviour);
3. `@Title` supports placeholders in the same way as `@Step`:
`  @Title("Check user {data.name }'s data.")`
or
`  @Title("Check user's data - {0}.")`

#### What is the motivation / use case for changing the behaviour?
A quick way to distinguish data-drive test executions in the report, no need to go through the list of executions  to see the difference.

#### Please tell us about your environment:

- Allure version: 2.1.1
- Test framework: testng@6.10
- Allure adaptor: allure-testng@2.0-BETA10
- Generate report using: allure-maven@2.8

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
we can display test parameters in tree. Will it fix the problem?

**Comment by L-Evg** [comment]
>>we can display test parameters in tree. Will it fix the problem?
Do you mean the approach used in Allure 1.* (methodName/Title + Paramaters[].toString())? If yes then it should work.
