### ISSUE TITLE
Massive click overhead

### ISSUE THREAD

**Issue by Exzo** [allure-framework/allure2#399]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request

#### What is the current behavior?

In this version to open a failed test I have to make **4** clicks;
To open a stacktrace: **+1** clicks;
To open a screenshot: **+2** clicks;

#### What is the expected behavior?

Reduce clicks count to make it more user friendly.
At least make "Categories > Defects" expanded when opening

#### What is the motivation / use case for changing the behavior?

Usability should never be sacrificed for design and fancy layout.

#### Please tell us about your environment:

- Allure version:        2.1.0
- Test framework:        testng@6.8
- Allure adaptor:        allure-testng@2.0-BETA8
- Generate report using: allure-maven@2.18

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
closed as duplicate https://github.com/allure-framework/allure2/issues/390
