### ISSUE TITLE
Lost test sequence numbers in xUnit

### ISSUE THREAD

**Issue by dimkin-eu** [allure-framework/allure2#403]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request

#### What is the current behavior?
Sequence of tests is unknown

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
![image](https://user-images.githubusercontent.com/7899764/27141094-f3a896ea-512f-11e7-9c5d-5ef09c21b7c6.png)

#### What is the expected behavior?
some sequence nr. near test ( also adding extra sorting to existing name/duration/status)

#### Please tell us about your environment:

- Allure version:        2.1.1
- Test framework:        testng@6.8
- Allure adaptor:        allure-testng@2.0-BETA8
- Generate report using: allure-maven@2.18

**Comment by just-boris** [comment]
This is actually a severe item for Cucumber specs.  All my steps are messed up and I do not know what goes after each other.

![image](https://user-images.githubusercontent.com/812240/27888251-5dc38cfe-61e5-11e7-91fc-ea2388a3bb06.png)

**Comment by dimkin-eu** [comment]
It kicks everything, not only cucumber, debugging of which failed after what not possible anyhow

**Comment by slipwalker** [comment]
Agreed. It is really challenging to get from the report what was going on and what the initial test sequence was, particularly for those people who might not have access to the source code.
