### ISSUE TITLE
Add an ability to export failure results 

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [allure-framework/allure2#405]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
- [x] feature request

#### What is the current behavior?
User had to navigate to TC info tab to view TmsLink info

#### What is the expected behavior?
As a user I'd like to have 1-click action feature to export all failed/broken/_skipped_ test cases to some readable format representation.
The information in this representation should contain failed/broken sections, TmsLink value, method name(ideally) and fail reason. TestCaseID pattern should support TmsLink pattern, therefore be clickable.

E.g. 
- Failed test cases

-- TestCaseID-111
---      testCaseMethodName1
----          failureReason1
-- TestCaseID-123
---      testCaseMethodName2
----           failureReason2

* Broken test cases

--  TestCaseID-222
---       testCaseMethodName3
----            failureReason3
--  TestCaseID-234
---       testCaseMethodName4
----            failureReason4

#### What is the motivation / use case for changing the behavior?
Better(faster) failed/broken test cases handling

#### Please tell us about your environment:

- Allure version:        2.1.1
- Test framework:        testng@6.10
- Allure adaptor:        allure-testng@2.0-BETA8

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
related to #273

**Comment by baev** [comment]
should be fixed via https://github.com/allure-framework/allure2/issues/273
