### ISSUE TITLE
Make host labels configurable

### ISSUE THREAD

**Issue by dimkin-eu** [allure-framework/allure2#415]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request 

#### What is the current behavior?
only hostnames as labels for matrix runs

#### What is the expected behavior?
Create possibility override/append info to "host" label

#### What is the motivation / use case for changing the behavior?
as tests are separated not only by hosts, but also by tests themselve, could be nice to have their names in labels (or some other userdefined info)

#### Please tell us about your environment:

- Allure version:        2.1.1
- Test framework:        testng@6.8
- Allure adaptor:        allure-testng@2.0-BETA8
- Generate report using: allure-maven@2.18

#### Other information 
![image](https://user-images.githubusercontent.com/7899764/27229878-f64e1bcc-52b5-11e7-8236-2161376d1949.png)

**Comment by baev** [comment]
To change the host name you can use the `ALLURE_HOST_NAME ` and `ALLURE_THREAD_NAME ` environment variables or `allure.hostName` and `allure.threadName` system properties
