### ISSUE TITLE
Descriptions for steps

### ISSUE THREAD

**Issue by nicegirlannet** [allure-framework/allure2#422]
I setted properties description and descriptionHtml for StepResult object using .withDescription() and .withDescriptionHtml() methods (fraimwork version 2.0-BETA10). The test was performed and json file in allure-results directory contains that description and descriptionHtml attributes. But when generating report using comandline lib (2.1.1 version) this attributes are not displayed in the report. I expect that this attributes are displayed in the correspondent step result.

**Comment by tnimni** [comment]
Hi,

this doesn't work on java as well version BETA-19, the description annotation doesn't produce the info in the html report
