### ISSUE TITLE
Add support for test results in .TRX format

### ISSUE THREAD

**Issue by baev** [allure-framework/allure2#424]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

Currently you can not build the report from TRX test results.

#### What is the expected behavior?

An ability to build Allure report from TRX files

#### What is the motivation / use case for changing the behavior?

Test results file created by Visual Studio, a Microsoft application used to develop Windows software; contains test results stored in an XML format; used to display test results in Visual Studio as well as save historical test case results.

There are a lot of Visual Studio users, so it would be nice to provide an ability to generate Allure report for them out of the box

#### Other information 

Sample TRX file https://gist.github.com/baev/a815edbb988bf94336dc26a49613feca

**Comment by arpit-nagar** [comment]
Can you please let me know.. How to configure it in Jenkins.
I have a test with generate .trx output. 
What are the next steps I follow to get Allure report.

Thanks
Arpit

**Comment by baev** [comment]
You need to install latest Allure Jenkins plugin, and configure it to generate a report from the folder, that contains trx files

**Comment by arpit-nagar** [comment]
I need help... how to generate report...

I used below settings
![allure](https://user-images.githubusercontent.com/16220515/29077328-78fae62a-7c75-11e7-8ea3-978055adf8ad.JPG)


Jenkins output log.
```
Unpacking https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.3/allure-2.3.zip to /var/lib/jenkins/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/Allure on Jenkins

[test-project] $ /var/lib/jenkins/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/Allure/bin/allure generate -o /var/lib/jenkins/workspace/test-project/allure-report

allure-results does not exists

send analytics

Report successfully generated to /var/lib/jenkins/workspace/test-project/allure-report
Allure report was successfully generated.
```
Allure report is empty with 0 suite

Can you please help ?

**Comment by eroshenkoam** [comment]
Hi @arpit-nagar
In your case result path should be `testReport` (without TestResults.trx)

**Comment by arpit-nagar** [comment]
Thanks it worked...
My folder name was testReports 
I changed it to testReports/*.trx and it worked.
Thanks a lot for your immediate support.

**Comment by eroshenkoam** [comment]
@arpit-nagar `testReports` is enough (without any suffix)

**Comment by arpit-nagar** [comment]
@eroshenkoam Thanks for information.
Just have one query/issue. 
On test failure logs do not have any stackTrace(reason of failure - errorInfo) while my trx file has this info.
Am I missing anything ??

**Comment by baev** [comment]
@arpit-nagar it is not parsed yet. You can create an issue

**Comment by arpit-nagar** [comment]
Yeah I will create.
Thanks for your quick response.
Very nice product and community.

**Comment by premaram** [comment]
I am trying to generate allure reports for the VsTest results which are in .TRX format.
I tried the command $C:\allure-command-line\allure generate <TRX folder> -c -o <Allure-report-Path>

It says report generated successfully with 1 KB size index.html and it is just blank. No allure_log generated as well. Appreciate your help!! 
@arpit-nagar @eroshenkoam

**Comment by baev** [comment]
@premaram try `$ C:\allure-command-line\allure serve <TRX folder>` instead

**Comment by premaram** [comment]
@baev Awesome! Serve command works. Thank you so much.
But, from Jenkins, Allure2.5 report uses generate command by default. Is it possible to change that?

**Comment by baev** [comment]
> Allure2.5 report uses generate command by default. Is it possible to change that?

`serve` command is shortcut for `generate & open`. Allure uses AJAX to load report data, so you can't view the report without starting web server (what `open` command did) due to security issues. Using Jenkins there is no need to serve the report, Jenkins serves it for you
