### ISSUE TITLE
Add sorting options for xUnit test cases 

### ISSUE THREAD

**Issue by slipwalker** [allure-framework/allure2#431]
Currently (Allure version 2.0.1), there is no possibility to sort xUnit test cases when I'm viewing specific test. See attach below:

<img width="489" alt="sorting options" src="https://user-images.githubusercontent.com/720677/27592260-b5b8c1de-5b5c-11e7-8870-9eef30a9b719.png">

Would be very helpful to have some sorting options for xUnit test cases, e.g by name, duration, status as it is now for xUnit tests and as it was on the previous version of Allure report (1.5.4).

**Comment by baev** [comment]
![screen shot 2017-06-27 at 17 26 37](https://user-images.githubusercontent.com/2149631/27592733-d57fb2f6-5b5d-11e7-8635-8df8159438ce.png)

You can sort nodes in tree using controls at the top of the tree

**Comment by slipwalker** [comment]
I wanna sort inner test cases of the test. Currently, sorting works only for tests. In your case for example, I'd like to have possibility to sort test case "Test what do nothing and always passed ... " of test my.company.AllureMigrationTest.

**Comment by baev** [comment]
I feel like this is gonna be hard to implement (should we save the sorting for each node? Should we sort all nodes at same level, or just one node? etc)

Also I haven't see any tree with such feature. We are trying to keep the report as clear as possible (that is the reason why we had to remove nested panes and replace it with tree)

**Comment by slipwalker** [comment]
@baev Ok got it. But could you please at least add to each test case order number it was running by? 
I mean for example when opening some xUnit test the following view expected: 

1. userShouldHavePossibilityToLogin
2. userShouldHaveRightPermission
3. ...

Because now, it is really hard to understand what the orders of test cases were initially. I could add another ticket issue for this if you wish. Would it be possible to implement? In the previous version of Allure (1.5.4) this feature is present and it is quite useful.
