### ISSUE TITLE
IE11: Copy to clipboard function doesn't work

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [allure-framework/allure2#442]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Copy to clipboard functionality doesn't work, there is an error in console, that prevent it from working correctly:
**SCRIPT5009: 'Promise' is undefined**
File: app.js, Line: 25, Column: 3792
![2017-06-29_15-40-06](https://user-images.githubusercontent.com/9446141/27688097-0c6b2e8c-5ce2-11e7-9fea-587ff132b8fd.png)
![2017-06-29_15-43-58](https://user-images.githubusercontent.com/9446141/27688101-0df7edc6-5ce2-11e7-99d3-253d5a0a4aa0.png)

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | testng@6.10 |
| Allure adaptor | allure-testng@2.0-BETA11 |
| Generate report using | maven@3.5.0 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by just-boris** [comment]
@baev the simplest solution would be switching to this copying library
https://github.com/sindresorhus/copy-text-to-clipboard
