### ISSUE TITLE
Installation in Ubuntu 16.04 failed: Error: No available formula with the name "homebrew/dupes/unzip" (dependency of allure)

### ISSUE THREAD

**Issue by TimurNurlygayanov** [allure-framework/allure2#445]
qawizard@qawizard-ub14:~$ brew tap qameta/allure

========================================================================
You may want to update following environments after installed linuxbrew.

  PATH, MANPATH, INFOPATH 

(example: /usr/share/doc/linuxbrew-wrapper/examples/profile)
========================================================================
==> This script will install:
/home/qawizard/.linuxbrew/bin/brew
/home/qawizard/.linuxbrew/Library/...
/home/qawizard/.linuxbrew/share/man/man1/brew.1

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
remote: Counting objects: 353405, done.
remote: Total 353405 (delta 0), reused 0 (delta 0), pack-reused 353405
Receiving objects: 100% (353405/353405), 67.85 MiB | 1.29 MiB/s, done.
Resolving deltas: 100% (267196/267196), done.

From https://github.com/Homebrew/linuxbrew
 * [new branch]      master     -> origin/master
HEAD is now at eec5059 Merge branch homebrew/master into linuxbrew/master
Warning: /home/qawizard/.linuxbrew/bin is not in your PATH.
==> Installation successful!
==> Next steps
Install the Linuxbrew dependencies:

Debian, Ubuntu, etc.:
  `sudo apt-get install build-essential`

Fedora, Red Hat, CentOS, etc.:
  `sudo yum groupinstall 'Development Tools'`

See http://brew.sh/linuxbrew/#dependencies for more information.

Run `brew doctor` before you install anything
Run `brew help` to get started
==> Tapping qameta/allure
Cloning into '/home/qawizard/.linuxbrew/Library/Taps/qameta/homebrew-allure'...
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
Checking connectivity... done.
Tapped 1 formula (30 files, 118.6K)

qawizard@qawizard-ub14:~$ brew install allure
==> Tapping homebrew/dupes
Cloning into '/home/qawizard/.linuxbrew/Library/Taps/homebrew/homebrew-dupes'...
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
Checking connectivity... done.
Tapped 0 formulae (29 files, 111.9K)
Error: No available formula with the name "homebrew/dupes/unzip" (dependency of allure)
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
qawizard@qawizard-ub14:~$

**Comment by eroshenkoam** [comment]
@TimurNurlygayanov allure already in homebrew central repository: 
 https://github.com/Homebrew/homebrew-core/blob/master/Formula/allure.rb

```
brew untap allure
brew update
brew install allure
```

**Comment by TimurNurlygayanov** [comment]
eroshenkoam, Thank you!

Need to update readme in the repository :)

**Comment by baev** [comment]
> Need to update readme in the repository :)

could you please a pull request?

**Comment by iozeen** [comment]
`brew update` resolved problem for me
