### ISSUE TITLE
Add execution order numbers of xUnit test cases

### ISSUE THREAD

**Issue by slipwalker** [allure-framework/allure2#453]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

Currently, it is really difficult to understand what the orders of test cases initially were, especially when we apply some sorting to them. It's due to we have just test methods names without its orders. 

<img width="601" alt="xunit test" src="https://user-images.githubusercontent.com/720677/27786871-8cd2c02e-5feb-11e7-98f4-7a0520598b04.png">

So, it would be very helpful to have order numbers, I mean for example when opening some xUnit test the following view would expect for test methods:

1. addNewGroupOnlyUserTest
2. checkDataSourcesTab
3. ... etc

Would be possible to implement it? In the previous version of Allure (1.5.4) this feature is present and it is quite useful.

**Comment by baev** [comment]
duplicate #403
