### ISSUE TITLE
It is unclear from UI what step is actually failed because all executed steps are marked with green icon

### ISSUE THREAD

**Issue by Matamune** [allure-framework/allure2#456]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request

#### What is the current behavior?
 Current version:
1) All executed steps are marked with green icon
2) Failed steps are unclear
![new](https://user-images.githubusercontent.com/528577/27826262-1721e078-60bb-11e7-8ec0-40139e8f4d3d.PNG)

#### What is the expected behavior?
1) Passed steps are displayed as plain text
2) Unsuccessful steps are marked with an appropriate icon  (failed/broken/canceled)
See https://ci.qameta.io/job/allure1/job/master/Allure_Report/index.html#xUnit/7e9e06eb4dbfce8b/f934021d85627941
![old](https://user-images.githubusercontent.com/528577/27826261-170f5c78-60bb-11e7-91bc-1e1117687d52.PNG)

#### What is the motivation / use case for changing the behavior?
1) Green icons are not helpful but are informational noise, especially when you have many steps in your scenario.
2) Actually, all executed steps are "green" but there is no possibility to see the failed one

I propose to return the solution of previous versions, where only failed steps have the information icon.

#### Please tell us about your environment:

| Allure version | 2.19 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@1.5.2 |
| Generate report using | allure-maven@2.5 |

**Comment by ScorpDS** [comment]
Hi, @Matamune !
As I see now there are two different ways to arrange steps which lead to different results in report UI.
If you get assertions in method annotated with @Test and only get results from steps - you will get what you get now.
But, if you have assertions inside steps, and one of assertions has failed - you will see it in report UI as "red" step. 
Try it out.
