### ISSUE TITLE
allure 2 not available on maven central

### ISSUE THREAD

**Issue by tnimni** [allure-framework/allure2#461]
the package is not available on maven central, can you please provide a repository to download it from? the command line tool for mac is up to date

**Comment by baev** [comment]
all Allure artifacts are available on Maven Central, see https://repo.maven.apache.org/maven2/io/qameta/allure/

**Comment by tnimni** [comment]
@baev that's cool, but https://mvnrepository.com/artifact/ru.yandex.qatools.allure/allure-junit-adaptor
the latest there is 1.5.4

**Comment by tnimni** [comment]
@baev on junit adaptor the latest is 1.5.4, i followed the instructions from allure 2 web site and it won't work https://mvnrepository.com/artifact/ru.yandex.qatools.allure/allure-junit-adaptor
