### ISSUE TITLE
Allure2 incorrect behavior

### ISSUE THREAD

**Issue by alexanderyellow** [allure-framework/allure2#462]
Hello, would you mind to help me?
I try to use allure2 but it doesn't work.

Pom example:
`
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>lalala</groupId>
        <artifactId>lalala</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <groupId>lalala.ui</groupId>
    <artifactId>lalala.ui</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>       
        <allure.version>2.0-BETA14</allure.version>
        <aspectj.version>1.8.10</aspectj.version>
        <allure.results.directory>${project.build.directory}/allure-results</allure.results.directory>
        <tms>https://github.com/allure-framework/allure-docs/issues/{}</tms>
        <issues.tracker>https://github.com/allure-framework/allure-docs/issues/{}</issues.tracker>
        <spring.version>3.2.16.RELEASE</spring.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide</artifactId>
            <version>4.4.3</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.8.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.8.2</version>
        </dependency>      
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.8.0</version>
        </dependency>
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-testng</artifactId>
            <version>${allure.version}</version>           
        </dependency>     
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-aop</artifactId>
            <version>${spring.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <testFailureIgnore>true</testFailureIgnore>
                    <suiteXmlFiles>
                        <xmlFile>suites/${suite.file}</xmlFile>
                    </suiteXmlFiles>
                    <workingDirectory>./</workingDirectory>
                    <properties>
                        <property>
                            <name>usedefaultlisteners</name>
                            <value>false</value>
                        </property>                   
                    </properties>
                    <systemPropertyVariables>
                        <threadCount>${thread.count}</threadCount>
                        <env.name>${env.name}</env.name>
                        <selenide.browser>${selenide.browser}</selenide.browser>
                        <selenide.reports>${selenide.reports}</selenide.reports>
                        <webdriver.chrome.driver>${webdriver.chrome.driver}</webdriver.chrome.driver>
                        <selenide.timeout>${selenide.timeout}</selenide.timeout>
                    </systemPropertyVariables>
                    <systemProperties>
                        <property>
                            <name>allure.results.directory</name>
                            <value>${allure.results.directory}</value>
                        </property>
                        <property>
                            <name>allure.link.issue.pattern</name>
                            <value>${issues.tracker}</value>
                        </property>
                        <property>
                            <name>allure.link.tms.pattern</name>
                            <value>${tms}</value>
                        </property>
                    </systemProperties>
                    <argLine>
                        -javaagent:${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar
                    </argLine>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-maven</artifactId>
                <version>2.8</version>
            </plugin>
        </plugins>
    </build>

    <reporting>
        <excludeDefaults>true</excludeDefaults>
        <plugins>
            <plugin>
                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-maven</artifactId>
                <version>2.8</version>
                <configuration>
                    <resultsDirectory>${project.build.directory}/allure-results</resultsDirectory>
                </configuration>
            </plugin>
        </plugins>
    </reporting>

</project>`

@Step, @Attachment - doesn't work.

If you need more information i'll provide it.

**Comment by baev** [comment]
Please use our Gitter or Stackoverflow for questions/support requests 

PS you need to add quotes to escape spaces in path to java agent, see https://github.com/allure-examples/allure-junit-example/blob/master/pom.xml#L62
