### ISSUE TITLE
Allure/TestNG: Report test execution page shows unrelated @BeforeClass/@AfterClass methods

### ISSUE THREAD

**Issue by chibux** [allure-framework/allure2#463]
#### I'm submitting a ... 
  - [x] bug report

#### What is the current behavior?
@BeforeClass/@AfterClass/ methods show up for all tests, even for the ones they are not related to.

#### Prerequisites:
Two test classes: one of them has @BeforeClass/@AfterClass/ methods and the other one doesn't.

#### Steps:
1. mvn clean test
2. allure serve target/allure-results

#### What is the expected behavior?
@BeforeClass/@AfterClass/ methods should show up in Report only for the tests they belong to.

#### Environment:

| Allure version | ? |
| --- | --- |
| Test framework | testng@6.11 |
| Allure adaptor | allure-testng@2.0-BETA14 |
| Generate report using | maven-surefire@2.19.1 |

#### Other information 
https://github.com/chibux/allure2-testng
![2017-07-08 04_36_14-allure report](https://user-images.githubusercontent.com/8534108/27984973-94103b8c-6397-11e7-9d4f-2ef28c1ee736.png)

**Comment by baev** [comment]
@chibux thanks! The issue moved to https://github.com/allure-framework/allure-java/issues/99
