### ISSUE TITLE
please add support for Jbehave

### ISSUE THREAD

**Issue by braghome** [allure-framework/allure2#464]
only see support for cucumber is it possible for adding support for [Jbehave ](http://jbehave.org/reference/stable/parametrised-scenarios.html)
`
Given a stock of <symbol> and a <threshold>
When the stock is traded at <price>
Then the alert status should be <status>
 
Examples:     
|symbol|threshold|price|status|
|STK1|10.0|5.0|OFF|
|STK1|10.0|11.0|ON|
`

**Comment by baev** [comment]
just added first draft of jbehave integration https://github.com/allure-framework/allure-java/tree/master/allure-jbehave . Will be available after next allure-java release (ETA next week)

Feel free to send us pull requests with improvements
