### ISSUE TITLE
Unusable test-result links

### ISSUE THREAD

**Issue by sseliverstov** [allure-framework/allure2#473]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

## 1
html:
<img width="281" alt="2017-07-14 3 16 46" src="https://user-images.githubusercontent.com/19683904/28193099-038ef2e6-6843-11e7-8916-f811debb7d2e.png">

browser:
<img width="397" alt="2017-07-14 3 17 02" src="https://user-images.githubusercontent.com/19683904/28193091-fb7bf3ec-6842-11e7-8f5b-0532527f27fd.png">

json:
```json
 "links": [
        {
            "type": "link", 
            "url": "http://qameta.io"
        }
    ], 
```
## 2
browser:
<img width="339" alt="2017-07-14 3 21 43" src="https://user-images.githubusercontent.com/19683904/28193199-99d1ebbe-6843-11e7-99fb-a4af04efcb39.png">

json:
```json
    "links": [
        {
            "type": "issue", 
            "url": "https://github.com/qameta/allure-integrations/issues/8"
        }
    ], 
```

**NB!** icon is not clickable it is outside 'a' tag
| Allure version | 2.2.1 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by zlorb** [comment]
ETA?
