### ISSUE TITLE
Add padding for tags line

### ISSUE THREAD

**Issue by sseliverstov** [allure-framework/allure2#474]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
<img width="238" alt="2017-07-14 3 26 43" src="https://user-images.githubusercontent.com/19683904/28193338-7a47c682-6844-11e7-91e1-6357709d1988.png">

| Allure version | 2.2.1 |

**Comment by ansuman-satapathy** [comment]
Hello! I am interested to work on this. Can you guide me how to get started? I am new to contributing.
