### ISSUE TITLE
TestNG, all BeforeClass methods are listed under "Set up".

### ISSUE THREAD

**Issue by L-Evg** [allure-framework/allure2#478]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behaviour?
Concrete test result page shows all existing @BeforeClass methods not only related to the test one. 

![default](https://user-images.githubusercontent.com/16156565/28361103-4db49f2e-6c80-11e7-9406-edaea71a966f.png)

#### If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
1. There are three test classes (Java/TestNG). Each class contains a @BeforeClass annotated method and 1-2 test method(s):
`  
  @BeforeClass
  public void beforeClassMethodInClass1() {
  }
...
  @BeforeClass
  public void beforeClassMethodInClass2() {
  }
...
@BeforeClass
  public void beforeClassMethodInClass3() {
  }
`
 
The classes are isolated from i.e. no inheritance etc;

2. Run all three test classes.

#### What is the expected behaviour?
"Set up" section on test result page for Test21 from Class2 shows only #beforeClassMethodInClass2()

#### What is the motivation / use case for changing the behaviour?
Motivation - Provide exact data test run picture, avoid misleading.

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | testng@6.10 |
| Allure adaptor | allure-testng@2.0-BETA15 |
| Generate report using | allure-maven@2.8 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
duplicate https://github.com/allure-framework/allure-java/issues/99 . Fixed in `allure-testng@2.0-BETA15` (gonna be available in next few hours)
