### ISSUE TITLE
Add possibility to download HAR file attached to Allure report 

### ISSUE THREAD

**Issue by slipwalker** [allure-framework/allure2#491]
Currently, there is possibility to view HAR file attached to Allure report either within this report or in a new browser tab. But, sometimes it is not convenient. Sometimes there is a need to download this file and open it in some specific tools for sake of profiling the requests. Yeah, you can view this HAR file in a browser tab and then download it, but it is not an option in case large files (e.g. 20 MB) when you need first of all wait for file processing for view finished and only then download the file. 
It would be great to have the special button, clicking on it would trigger downloading the file.

**Comment by baev** [comment]
`Open in new browser tab` is direct link to attachment. So open the attachment in a new tab, and then save it using `ctrl` + `s`

**Comment by slipwalker** [comment]
@baev thanks. I know about it. I just wanna to have it more user friendly. Someone may want to download file right away, no need to wait until your file processing finished in a new tab cause only after that you can save it using ctrl + s or right button/save or any other. It is actual for large files.

**Comment by baev** [comment]
You can download it without opening in new window using browser menu:

![screen shot 2017-07-26 at 17 26 46](https://user-images.githubusercontent.com/2149631/28626463-b8852984-7227-11e7-9385-369c3681f532.png)

**Comment by just-boris** [comment]
@baev you may want to add [there](https://github.com/allure-framework/allure2/blob/master/allure-generator/src/main/javascript/blocks/attachment-row/attachment-row.hbs#L15) something like this

```
<a {{#if size gt 20000}}download{{/if}} href="data/attachments/{{source}}" target="_blank">
```

[Download attribute](http://devdocs.io/html/attributes#download-attribute) will tell browser that file should be downloaded instead of being open.

**Comment by baev** [comment]
@just-boris I know, but don't like it anyway. In some cases size attribute may be missed, also such behavior may be unclear for users

**Comment by slipwalker** [comment]
@baev got it. Thanks anyway.
