### ISSUE TITLE
Cann't create @Step tag file

### ISSUE THREAD

**Issue by feiyuediy** [allure-framework/allure2#497]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
In my pox.xml.If I add this parameter (<argLine> -Dfile.encoding = UTF-8 </ argLine>) , I can not create a file with the @step tag in the allure-results folder.
but If i did not add this parameter (<argLine> -Dfile.encoding = UTF-8 </ argLine>),user mvn test is fail

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | testng@6.9.10 |
| Allure adaptor | allure-testng1.5.4 |
| Generate report using | allure-maven@2.18 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
@feiyuediy could you please describe the problem in more details? I didn't get what is the problem

**Comment by feiyuediy** [comment]
@baev sorry, my english in poor,In my project. If I run directly with TestNG, my test case can be pass，but if I run with pom.xml，it fail。I consulted a lot of information and found that there was UTF-8 encoding.so，I add  <argLine>)-Dfile.encoding = UTF-8 </ argLine>) in pom.xml.but my @Step and @Attachmentit don't work ,but @Feature,@Stories is work

**Comment by baev** [comment]
here you can find working testng example https://github.com/allure-examples/allure-testng-example

**Comment by thasherwin** [comment]
@baev i had simular probleem with cucumber-jvm beta version beta version.16. Let me double check today. I will get back on this. I remember mention this in the chat. 

When using allure-cucumber-jvm.version 2.0-BETA16 and have the Steps("") annotation on top of a method the test fails with error [ERROR] Errors:
[ERROR] io.qameta.allure.aspects.StepsAspects.aspectOf()Lio/qameta/allure/aspects/StepsAspects;
If i downgrade to 2.0-BETA15 the test does not fail

**Comment by thasherwin** [comment]
it does fail.. I will create a separate bug because i am not sure whether it's related to this issue..

**Comment by feiyuediy** [comment]
@thasherwin I using allure-cucumber-jvm.version 2.0-BETA15,the test still fail。
java.lang.NoSuchMethodError: io.qameta.allure.aspects.StepsAspects.aspectOf()Lio/qameta/allure/aspects/StepsAspects;

**Comment by ham1** [comment]
Do you have a `resources/META-INF/aop.xml` file which may be not including (or excluding) packages?
I had the same error when the file looked like:
```xml
<aspectj>
  <weaver options="">
    <include within="ru.yandex.qatools.allure.*" />
    <include within="com..*" />
  </weaver>
</aspectj>
```
I removed the file and things now work as expected. I would gues you could also make sure to explicitly include the correct Allure/Allure 2 packages e.g. `io.qameta.allure`.
