### ISSUE TITLE
Duplicated info on Overview pane

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [allure-framework/allure2#502]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Information about error is displayed right under Overview label and in Test Body section(which is uncollapsed by default). Therefore, the user sees duplicated info on the screen.

#### What is the expected behavior?
There should be the only container that displays the error info

#### Please tell us about your environment:

| Allure version | 2.3 |
| --- | --- |
| Test framework | testng@6.10 |
| Allure adaptor | allure-testng@2.0-BETA15 |
| Generate report using | allure-maven@2.18 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
That is feature, not a bug ;) No need to scroll up and down in case of huge amount of steps, also in the future that feature gonna be useful for tests with multiply failures. The behaviour is copied from Allure 1
