### ISSUE TITLE
Allure report missing test details when viewed on chrome browser version 43.0.2357.134

### ISSUE THREAD

**Issue by braimanm** [allure-framework/allure2#507]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Allure report missing test details when viewed on chrome browser version 43.0.2357.134 but on latest chrome browser versions report is showing correctly

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal
1) Generate report using Allure version 2.3 for the test results with test details
2) View report using chrome browser version 43.0...

#### What is the expected behavior?
Report should show the report details

#### Please tell us about your environment:

| Allure version | 2.3 |
| --- | --- |
| Test framework | testng@6.11 |
| Allure adaptor | allure-testng@2.0-BETA16 |
| Generate report using | allure-maven@2.18 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)
![image](https://user-images.githubusercontent.com/7651167/28676851-d010a028-72b9-11e7-97d0-7da765a62633.png)

**Comment by baev** [comment]
fixed via https://github.com/allure-framework/allure2/pull/510
