### ISSUE TITLE
Safari 8 layout issues

### ISSUE THREAD

**Issue by baev** [allure-framework/allure2#508]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

![macyos_safari_8 0](https://user-images.githubusercontent.com/2149631/28678690-aed095cc-72f9-11e7-919c-222983d00094.png)

#### Please tell us about your environment:

| Allure version | 2.3 |
| --- | --- |
| OS | OS X Yosemite |
| Browser | safari 8 |
| Test framework | any |
| Allure adaptor | any |
| Generate report using | any |

**Comment by just-boris** [comment]
[autoprefixer](https://github.com/allure-framework/allure2/blob/master/allure-generator/webpack.config.js#L10) by default support only [2 latest browser versions](https://github.com/ai/browserslist/blob/master/index.js#L306). Latest Safari is 10, so 8th is out of scope.

You would be very much insane to support old 💩 (browsers).
