### ISSUE TITLE
Invisible attachment row

### ISSUE THREAD

**Issue by baev** [allure-framework/allure2#511]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

<img width="409" alt="screen shot 2017-07-27 at 20 18 56" src="https://user-images.githubusercontent.com/2149631/28683346-eaecaa14-7308-11e7-9be6-672c8f02a20e.png">

Attachments appear after removing `position: sticky` style:

<img width="409" alt="screen shot 2017-07-27 at 20 19 05" src="https://user-images.githubusercontent.com/2149631/28683347-eb182da6-7308-11e7-990f-b1769ab14dac.png">

#### Please tell us about your environment:

| Allure version | 2.3 |
| --- | --- |
| Test framework | any |
| Allure adaptor | any |
| Generate report using | any |

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by akansjain** [comment]
Hi @baev, I would like to work on this issue.

It would be great if you could please guide me to the documentation where I would find relevant information regarding this, or you may also point me to the code that requires the necessary amendments for this issue to be resolved successfully.
