### ISSUE TITLE
Steps annotation in the cucumber-jvm-2.BETA16 does not work

### ISSUE THREAD

**Issue by thasherwin** [allure-framework/allure2#513]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
When adding Steps annotation on top of a method in allure-cucumber-jvm.version 2.0-BETA16 I get error message:
io.qameta.allure.aspects.StepsAspects.aspectOf()Lio/qameta/allure/aspects/StepsAspects
This error message is also visable in the report
If i downgrade to BETA version 15 i don't see these errors in my console

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Add Steps annotation on top of a method

 ```java
 @Step("")
    public SelenideTest loop(String value){
        $(By.name("q")).setValue(value).pressEnter();
        return page(SelenideTest.class);
    }
```
Upgrade to BETA version 16 and run a mvn clean test

#### What is the expected behavior?
No errors in the console and steps should show up in the report. 
One note is that the Camel case of method name was not translated properly.. If the method name is SelenideTest, the name is not shown as Selenide test.. But as SelenideTest… This is another issue.. 

#### What is the motivation / use case for changing the behavior?
I can use steps again to see more details on what is being tested below a Cucumber step

#### Please tell us about your environment:

| Allure version | 2.3.0 |
| --- | --- |
| Test framework | cucumber.version 1.2.4 |
| Test framework | junit.version 4.12|
| Allure adaptor | allure-testng@2.0-BETA16 |
| Generate report using | allure-maven@2.18 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

```
[ERROR] Errors: 
[ERROR]   io.qameta.allure.aspects.StepsAspects.aspectOf()Lio/qameta/allure/aspects/StepsAspects;
[ERROR]   io.qameta.allure.aspects.StepsAspects.aspectOf()Lio/qameta/allure/aspects/StepsAspects;
[ERROR]   io.qameta.allure.aspects.StepsAspects.aspectOf()Lio/qameta/allure/aspects/StepsAspects;
[ERROR]   io.qameta.allure.aspects.StepsAspects.aspectOf()Lio/qameta/allure/aspects/StepsAspects;
[ERROR]   io.qameta.allure.aspects.StepsAspects.aspectOf()Lio/qameta/allure/aspects/StepsAspects;
[ERROR]   io.qameta.allure.aspects.StepsAspects.aspectOf()Lio/qameta/allure/aspects/StepsAspects;
[INFO]
[ERROR] Tests run: 11, Failures: 0, Errors: 6, Skipped: 2
[INFO]

```
![image](https://user-images.githubusercontent.com/17144752/28684751-d2e5668e-7305-11e7-87d9-a7d5cca896ed.png)

**Comment by ksuzu** [comment]
I have the same problem on JUnit4.12 .
Generate report using: allure-gradle:2.3

**Comment by symonk** [comment]
Hi, I am having the same issue here with any version greater than 2.0-BETA15, I'm running off 2.0-BETA15 but I'd like to get the newer stuff, especially the new logo and searching capabilities. p.s thanks for the great tool I hope to start contributing soon

**Comment by baev** [comment]
should be fixed in last allure versions
