### ISSUE TITLE
Surfire plugin error in the forked process

### ISSUE THREAD

**Issue by mytalala** [allure-framework/allure2#515]
#### I'm submitting a ...
  - [x] bug report;
  - [ ] feature request;
  - [ ] support request.

#### What is the current behavior?

This is not a Allure bug, but as long as this issue isn't mentioned somewhere this ticket mus be in google.
Surfire plugin with [recommended](https://docs.qameta.io/allure/2.0/#_junit_4) configuration thrown NullPointerException if at least one test outside any package. Exception looks like:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project tests: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: There was an error in the forked process`

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

1. Create new project.
1. Use official [documentation](https://docs.qameta.io/allure/2.0/#_junit_4) for junit.
1. Create ant test without any package.
1. Run `mvn clean test`.

#### What is the expected behavior?

Reports are generated.

#### What is the actual behavior?

Surfire exception (details in the end).

#### What is the motivation / use case for changing the behavior?

If someone want to try allure and create new fast project to touch it by himself and get this error - he will find reason here.

#### Please tell us about your environment:

| Allure version | 2.8.0 |
| --- | --- |
| Test framework | JUnit@4.12 |
| Allure adaptor | allure-testng@2.0-BETA15 |
| Generate report using | allure-maven@2.18 |

#### Other information 

Exception:
``Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.172 sec <<< FAILURE! - in SimpleTest
Test mechanism  Time elapsed: 0.056 sec  <<< ERROR!
java.lang.NullPointerException``

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
@mytalala I don't really understand what I supposed to do with that issue

**Comment by mytalala** [comment]
@baev, close. This is only information for google in case, when someone will get same error.
