### ISSUE TITLE
Report test case page Links are not working 

### ISSUE THREAD

**Issue by jaheikki** [allure-framework/allure2#530]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
The Links (e.g. @issue and @tmsLink) in the Allure2 test case page do not work. The links refer now to report itseself (e.g. having this hyperlink: http://localhost:63342/hus-ci-tests/target/site/allure-maven-plugin/index.html?_ijt=v52s8klq7i2s0stos0c2m80coq) and not to hyperlinks defined in allure.properties.

![image](https://user-images.githubusercontent.com/8567508/29004450-dccc826e-7acf-11e7-917e-a3688d746047.png)

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
- mvn clean install
- mvn allure:report

#### What is the expected behavior?
The @issue and @tmsLink in Allure2 report should point to web addresses defined in allure.properties.

#### What is the motivation / use case for changing the behavior?
Bug.

#### Please tell us about your environment:

| Allure version | 2.3.1 |
| --- | --- |
| Test framework | cucumber-jvm |
| Allure adaptor | allure-cucumber-jvm@2.0-BETA16 |
| Generate report using | allure-maven@2.8 |

#### Other information
Notice when running  mvn allure:report the allure.properties will be copied to allure-results folder, so I believe the allure finds the properties file but somehow will not use that file information.

In my cucumber .feature file:
@tmsLink=MY-100
@issue=MYBUG-1000

I have configured allure.properties like this:
allure.issues.tracker.pattern=https://www.yle.fi
allure.tests.management.pattern=https://www.mtv.fi

Tried also like this (/%s added in allure.properties), but no difference:
allure.issues.tracker.pattern=https://www.yle.fi/%s
allure.tests.management.pattern=https://www.mtv.fi/%s
 
I tried to set  propertiesFilePath both from maven command line and in allure-maven plugin in pom.xml but makes no difference:                 Users/heikmjar/git/tietoallas/citest/src/test/resources/allure.properties

I also generated report with allure-cli where allure.properties was in the same folder than the json result file, but problem remains the same, links still not working.

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
The problem is that you are using old properties. From the docs:

> In order to specify the link pattern you can use the system property in the following format: allure.link.my-link-type.pattern=https://example.org/custom/{}/path. Allure will replace {} placeholders with value specified in annotation. For example:
allure.link.mylink.pattern=https://example.org/mylink/{}
allure.link.issue.pattern=https://example.org/issue/{}
allure.link.tms.pattern=https://example.org/tms/{}

**Comment by jaheikki** [comment]
@baev, thanks for clarification! Notice that there's outdated information in allure2 docs: https://docs.qameta.io/allure/2.0/

13. Reporting
13.1.2. Configuration
Properties file

To configure the Allure report you should create allure.properties file

allure.properties
allure.issues.tracker.pattern=https://tms/testcase-%s
allure.tests.management.pattern=https://bugtracker/issue-%s
and simply generate the report. By default command line tool looking for config in directory you run the command. You can use ALLURE_CONFIG environment variable to specify the path to configuration.

**Comment by baev** [comment]
@jaheikki could you please send us a PR with the fix? https://github.com/allure-framework/allure-docs

**Comment by jaheikki** [comment]
@baev https://github.com/allure-framework/allure-docs/pull/68
