### ISSUE TITLE
Documentation might need updates

### ISSUE THREAD

**Issue by Youchen** [allure-framework/allure2#543]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)
### Note
This is my very first time for submit an issue, please correct me if anything wrong. Thanks!

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Documentation might need updates
1. https://docs.qameta.io/allure/latest/#_windows
Better to add in the end: "Add allure to system PATH."
2. https://docs.qameta.io/allure/latest/#_gradle
Following is not working on my machine
```
$ ./gradlew allureServe build/allure-results

FAILURE: Build failed with an exception.

* What went wrong:
Task './build/allure-results/' not found in root project 'ABC'
```
but rather the following works
```
$ allure serve ./build/allure-results/
Generating report to temp directory...
Report successfully generated to C:\Users\<myName>\AppData\Local\Temp\<numbers-here>\allure-report
Starting web server...
2017-08-08 17:00:24.748:INFO::main: Logging initialized @2529ms
Server started at <http://<myLocalIP>:62655/>. Press <Ctrl+C> to exit
```
3. https://docs.qameta.io/allure/latest/#_gradle
```
allureJavaVersion = LATEST_VERSION
```
if we run with line above, we will have
```
$ ./gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\path\to\the\project\root\dir\build.gradle' line: 33

* What went wrong:
A problem occurred evaluating root project 'ABC'.
> Could not get unknown property 'LATEST_VERSION' for object of type io.qameta.allure.gradle.AllureExtension.
```
But the following works
```
allureJavaVersion = '2.0-BETA9'
```
I just searched others' code from Github, not sure if '2.0-BETA9' is the latest version.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
1. By using Scoop to install, if not add allure /bin to PATH, allure will be recognized as unknown command.
2. Just followed the step on Doc, it's not working with gradle wrapper.
3. same as above as number 2 

#### What is the expected behavior?
User should able to run without any issue.

#### What is the motivation / use case for changing the behavior?
To save time for future users.

#### Please tell us about your environment:

| Allure version | 2.3.3 |
| --- | --- |
| Test framework | Junit-4.12 |
| Allure adaptor | \<not sure\> |
| Generate report using | \<not sure\> |

#### Other information 
my build.gradle as 
```
buildscript {
    repositories {
        mavenCentral()
        jcenter()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "com.github.jengelman.gradle.plugins:shadow:2.0.1"
        classpath "gradle.plugin.org.jetbrains.intellij.plugins:gradle-intellij-plugin:0.2.0"
        classpath 'de.sebastianboegl.gradle.plugins:shadow-log4j-transformer:2.1.1'
        classpath 'io.qameta.allure:allure-gradle:2.3'
    }
}

apply plugin: "io.qameta.allure"
apply plugin: "org.gradle.java"
apply plugin: "application"
apply plugin: "idea"
apply plugin: "com.github.johnrengelman.shadow"
apply plugin: "org.jetbrains.intellij"
allure {
    version = '2.2.1'
    autoconfigure = true
    aspectjweaver = true
    allureJavaVersion = '2.0-BETA9'
}

repositories {
    mavenCentral()
}

configurations.all{
    exclude module: 'log4j-slf4j-impl'
}

mainClassName = 'my.project.App'

idea {
    project {
        jdkName = '1.8'
        languageLevel = '1.8'
        vcs = 'Git'
    }
}

dependencies {
    testCompile 'junit:junit:4.12'
    compile 'org.slf4j:slf4j-api:1.7.25'
    compile 'org.apache.logging.log4j:log4j-slf4j-impl:2.8.2'
    compile 'org.apache.logging.log4j:log4j-api:2.8.2'
    compile 'org.apache.logging.log4j:log4j-core:2.8.2'
}

version = '1.0.0'

shadowJar{
    transform(de.sebastianboegl.gradle.plugins.shadow.transformers.Log4j2PluginsFileTransformer)
    zip64 true
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.0.1'
}
```

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
@Youchen could you please provide fixes by sending a pull request to https://github.com/allure-framework/allure-docs ?

**Comment by Youchen** [comment]
@baev will do, thanks!
