### ISSUE TITLE
Display skipped test cases on Categories tab

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [allure-framework/allure2#552]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
No info about skipped test cases is displayed on Categories tab.

#### What is the expected behavior?
Display info about skipped test cases on Categories tab. 
It might have a separate category with its own name (e.g. System issues)

#### Please tell us about your environment:

| Allure version | 2.3.3 |
| --- | --- |
| Test framework | testng@6.10 |
| Allure adaptor | allure-testng@2.0-BETA16 |
| Generate report using | allure-maven@2.18 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by dimkin-eu** [comment]
for sure it could be handled by `categories.json`, but even such json, doesn't do magic
```
[
  {
    "name": "Skipped tests",
    "messageRegex": ".*",
    "matchedStatuses": [ "skipped" ]
  }
]
```
