### ISSUE TITLE
Display setup/teardown timings on a timeline

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [allure-framework/allure2#554]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the motivation / use case for changing the behavior?
It'll allow to distinguish how much time was spent for setup/teardown against the time that is spent to initialize new driver session. 
It'll be nice to display both setup/teardown with colors that are differs from defined statuses.

#### Please tell us about your environment:

| Allure version | 2.3.3 |
| --- | --- |
| Test framework | testng@6.10 |
| Allure adaptor | allure-testng@2.0-BETA16 |
| Generate report using | allure-maven@2.18 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by X-NoNAME** [comment]
that would be very helpful. Are there any plans?

this graph makes me feel that something is wrong with the configuration of the threads
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/1393799/235253237-d4b5ebc8-814d-43d0-a3ce-1618dd06c7cf.png">
