### ISSUE TITLE
Sort behaviours/packages by success rate

### ISSUE THREAD

**Issue by andreybehalf** [allure-framework/allure2#560]
#### I'm submitting a ... 
  - [x] feature request

#### What is the current behavior?
In behaviours/packages tabs - no option to sort by success rate of the test

#### What is the expected behavior?
Sorting by success rate. (ascending/descending) 

#### What is the motivation / use case for changing the behavior?
It would be cool to have option to sort the tests by success rate. 
This will allow following stable/unstable tests (for example tests with lower than 90% success rate have to be removed from part-regression tests). 
Just sort by descending and... Vualá! - Pick the unstable tests from bottom of the list!

#### Please tell us about your environment:
| Allure version | 2.2.1 |
| ---- | ---- |
| Test framework | behave@1.2.5 |
| Allure adaptor | allure-python-commons=@2.2.1b1 |
| Generate report using | Allure Jenkins Plugin@2.22 |

**Comment by vbaibus** [comment]
Hi, I second Andrey request. I think this would be great feature at least for two reasons:
1) Help QA teams to prioritize their maintenance efforts by focusing on the most flaky tests first
2) Create automated quality control post script in CI\CD pipeline that could analyse success rates and automatically exclude tests if it falls below certain threshold (> 98% for example).

...Just realized that this ticket has been open for 3 years now. @baev any chances this would be added anytime soon?

**Comment by storenth** [comment]
I think this feat should be framework/adapter-independent because we don't see any visual under Graphs, except the next one under tests History:
<img width="949" alt="success-rate" src="https://github.com/allure-framework/allure2/assets/18244131/54c1dc20-fe36-46c3-b401-d9f8be0c3f49">
