### ISSUE TITLE
Categories tab displays "404 Not Found"

### ISSUE THREAD

**Issue by mailtosoma** [allure-framework/allure2#564]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Issue is pretty straight forward

I have been using sample test project from allure and just changed the reportVersion to 2.3 and noted the categories tab is displaying "404 Not Found".

PS: overview categories is displaying correctly.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Steps: 
Download https://github.com/allure-examples/allure-testng-example and change the reportversion in pom.xml to latest (2.3)
Executed "mvn clean test site"

Expected behaviour: Categories should display properly

Actual Behaviour: Thrown "404 Not found"

#### Please tell us about your environment:
we are using sample project from allure (allure-testng-example) 

| Allure version | 2 |
| --- | --- |
| Test framework | testng@6.8.7 |
| Allure adaptor | allure-testng@2.0-BETA16 |
| Generate report using | allure-maven@2.3 / 2.3.3|

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
should be fixed in 2.3.3
