### ISSUE TITLE
There is no way to attach log/document file for test file.

### ISSUE THREAD

**Issue by sppavilion** [allure-framework/allure2#570]
Framework Used 
--------------------------------------
[**Allure-Pytest**](https://github.com/allure-framework/allure-pytest)

Description
--------------------------------------
Currently there is way to attach a file for particular test-case only.
`allure.attach.file('looger.log', 'LOG')`

Step followed
--------------------------------------
Declared the above mentioned line to top of test-case file, tried to run, test but it gave me lot of errors.

ERRORS
-----------------------
```
shubham@shubham-ThinkPad-E460:~/allure.pytest/test1$ py.test -vv --alluredir allure_report/
================================================ test session starts =================================================
platform linux2 -- Python 2.7.13, pytest-3.2.1, py-1.4.34, pluggy-0.4.0 -- /usr/bin/python
cachedir: .cache
rootdir: /home/shubham/allure.pytest/test1, inifile:
plugins: allure-pytest-2.2.1b1
collected 0 items / 1 errors                                                                                          

======================================================= ERRORS =======================================================
____________________________________________ ERROR collecting test_ut.py _____________________________________________
test_ut.py:4: in <module>
    allure.attach.file('lib.py', 'Hello, World')
/usr/local/lib/python2.7/dist-packages/allure_commons/_allure.py:130: in file
    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)
/usr/local/lib/python2.7/dist-packages/pluggy.py:745: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/local/lib/python2.7/dist-packages/pluggy.py:339: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/local/lib/python2.7/dist-packages/pluggy.py:334: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/local/lib/python2.7/dist-packages/pluggy.py:614: in execute
    res = hook_impl.function(*args)
/usr/local/lib/python2.7/dist-packages/allure_pytest/listener.py:174: in attach_file
    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)
/usr/local/lib/python2.7/dist-packages/allure_commons/reporter.py:94: in attach_file
    file_name = self._attach(uuid, name=name, attachment_type=attachment_type, extension=extension)
/usr/local/lib/python2.7/dist-packages/allure_commons/reporter.py:89: in _attach
    self._items[last_uuid].attachments.append(attachment)
E   KeyError: None
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================== 1 error in 0.14 seconds ===============================================
```

Expected result
-------------------------------
Should able to attach log file, after completion of all test-cases run mentioned in test case file.

>
> Shubham Pardeshi

**Comment by sseliverstov** [comment]
There are no way to attach something for python module. This feature is available only for for tests, fixtures and steps. You can make module scope fixture and attach data inside it.

**Comment by baev** [comment]
As @sseliverstov mentioned above, this is not supported by design. But I guess Allure should not throw an error in such case, only log warning (issue https://github.com/allure-framework/allure-python/issues/143)

**Comment by IgorZn** [comment]
> There are no way to attach something data for python module. This feature is available only for tests, fixtures and steps. You can make module scope fixture and attach data inside it.

Is there any way to see somewhere "how to" or "tutorial"?

**Comment by sseliverstov** [comment]
> > There are no way to attach something data for python module. This feature is available only for tests, fixtures and steps. You can make module scope fixture and attach data inside it.
> 
> Is there any way to see somewhere "how to" or "tutorial"?
https://docs.qameta.io/allure/#_python
https://github.com/allure-framework/allure-python/blob/master/allure-pytest/examples/attachment/attachment.rst

**Comment by IgorZn** [comment]
> > Is there any way to see somewhere "how to" or "tutorial"?
> 
> https://docs.qameta.io/allure/#_python
> https://github.com/allure-framework/allure-python/blob/master/allure-pytest/examples/attachment/attachment.rst

OK, I see. But does it work for behave as well as for pytest?

`from allure_commons._allure import attach
from allure_commons.types import AttachmentType`

and here is result

`Traceback (most recent call last):
  File "D:\Users\<username>\PycharmProjects\myproject\venv\lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "D:\Users\<username>\PycharmProjects\myproject\venv\lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features\steps\demo.py", line 24, in step_impl
    attach.file('error_screenie.png', name='Demo attach', attachment_type=AttachmentType.PNG)
  File "D:\Users\<username>\PycharmProjects\myproject\venv\lib\site-packages\allure_commons\_allure.py", line 167, in file
    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)
  File "D:\Users\<username>\PycharmProjects\myproject\venv\lib\site-packages\pluggy\hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "D:\Users\<username>\PycharmProjects\myproject\venv\lib\site-packages\pluggy\manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "D:\Users\<username>\PycharmProjects\myproject\venv\lib\site-packages\pluggy\manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "D:\Users\<username>\PycharmProjects\myproject\venv\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "D:\Users\<username>\PycharmProjects\myproject\venv\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "D:\Users\<username>\PycharmProjects\myproject\venv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "D:\Users\<username>\PycharmProjects\myproject\venv\lib\site-packages\allure_behave\listener.py", line 185, in attach_file
    self.logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)
  File "D:\Users\<username>\PycharmProjects\myproject\venv\lib\site-packages\allure_commons\reporter.py", line 112, in attach_file
    file_name = self._attach(uuid, name=name, attachment_type=attachment_type, extension=extension)
  File "D:\Users\<username>\PycharmProjects\myproject\venv\lib\site-packages\allure_commons\reporter.py", line 107, in _attach
    self._items[last_uuid].attachments.append(attachment)
KeyError: None`

**Comment by sseliverstov** [comment]
@IgorZn can you open issue in https://github.com/allure-framework/allure-python ?

**Comment by IgorZn** [comment]
> @IgorZn can you open issue in https://github.com/allure-framework/allure-python ?

Done #431
