### ISSUE TITLE
Wrong sequence of tests in Suites and Behaviors

### ISSUE THREAD

**Issue by dimkin-eu** [allure-framework/allure2#572]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
test sequence in timeline and Suites not matched one from timeline  
- test `#1` from suites was executed last (correct in timeline)
- test `#2` from suites was executed 2nd (correct in timeline)
- test `#3` from suites was executed 1st (correct in timeline)
- test `#4` from suites was executed 3rd (correct in timeline)

![image](https://user-images.githubusercontent.com/7899764/29520362-6e389dcc-8689-11e7-89da-3407916e3993.png)

#### Please tell us about your environment:

| Allure version | 2.3.4 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.0-BETA16 |
| Generate report using | allure-maven@2.18 |

**Comment by dimkin-eu** [comment]
Also Behaviors showing tests in random sequence

**Comment by baev** [comment]
fixed via #592
