### ISSUE TITLE
Error "Exception in thread "main" java.lang.NoClassDefFoundError: io/qameta/allure/tree/AbstractTreeAggregator" when generating report using command-line

### ISSUE THREAD

**Issue by gavrilfb** [allure-framework/allure2#573]
#### I'm submitting a ... 
  - [x] bug report

#### What is the current behavior?
Error "Exception in thread "main" java.lang.NoClassDefFoundError: io/qameta/allure/tree/AbstractTreeAggregator" when generating report using command-line

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
run "allure generate" or "allure serve" on command-line
![image](https://user-images.githubusercontent.com/29943195/29549414-64c673be-8732-11e7-910c-fbfa8b807063.png)

#### What is the expected behavior?
allure report successfully generated

#### Please tell us about your environment:

| Allure version | 2.3.4 |
| Windows 10 | --- |

**Comment by baev** [comment]
duplicate https://github.com/allure-framework/allure2/issues/561

You need to reinstall allure-commandline (uninstall allure via scoop, remove `~\scoop\apps\allure` folder, install latest version again)

**Comment by gavrilfb** [comment]
Okay, it works now.

Should probably add that you need to delete the allure folder in \scoop\persist\, the one in the scoop\apps\ folder got deleted automatically when you uninstall using scoop.

Thanks.
