### ISSUE TITLE
Summary widget is broken

### ISSUE THREAD

**Issue by sseliverstov** [allure-framework/allure2#579]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

![image](https://user-images.githubusercontent.com/19683904/29773404-07cb2b72-8c06-11e7-934f-da6237f97465.png)

| Allure version | 2.3.4|

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by sseliverstov** [comment]
Reproduced only if use browser zoom, also graph had worked fine before this fix: https://github.com/allure-framework/allure2/pull/518/files

**Comment by NayanPatidar** [comment]
Hey can you assign me this ?
