### ISSUE TITLE
Supporting @Step annotation on class level

### ISSUE THREAD

**Issue by admizh** [allure-framework/allure2#580]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request

#### What is the current behavior?
We suggest to create `@Step` annotation on class level. It will be provide collecting steps from all calss methods (without toString() equals() and etc.)

#### What is the expected behavior?
This feature will provide more faster Allure integration into existing projects

**Comment by LiorElb** [comment]
+1, this would help a greate deal with my project
