### ISSUE TITLE
Alassian Marketplace - Allure2

### ISSUE THREAD

**Issue by billc-atlassian** [allure-framework/allure2#581]
I'd like to request Allure2 be offered on the Atlassian Marketplace. Please let me know if I can be of assistance in this process.

**Comment by eroshenkoam** [comment]
@billc-atlassian, we already have [allure bamboo](https://github.com/allure-framework/allure-bamboo) integration

**Comment by eroshenkoam** [comment]
https://marketplace.atlassian.com/plugins/io.qameta.allure.allure-bamboo/server/overview

**Comment by billc-atlassian** [comment]
Wonderful, thank you very much!
