### ISSUE TITLE
Bug with markdown description

### ISSUE THREAD

**Issue by DudaGod** [allure-framework/allure2#582]
#### I'm submitting a ... 
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
My markdown description not correctly converted to html. Moreover it is wrapped to `<pre><code>my md</code></pre>` html tags. And it's strange because at the output I see:
```
<pre>
    <code>            
            * do: something
            * assert: something
            * do: another thing
            * assert: another thing
    </code>
</pre>
```
How you know in pre tag the spaces at the beginning of the line do not collapse and in each line I have a huge amount of spaces and can't control it.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
I use [allure-js-commons](https://github.com/allure-framework/allure-js-commons) plugin, which has method [setDescription](https://github.com/allure-framework/allure-js-commons/blob/master/beans/test.js#L15). I used it this way - `myAllureTest.setDescription('* do: something\n* assert: something\n* do: another thing\n* assert: another thing', 'markdown')`

As a result of running my test I have next xml report:
```xml
<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1503988440713' stop='1503988457513'>
    <name>Default name</name>
    <title>Default name</title>
    <test-cases>
        <test-case start='1503988440715' status='passed' stop='1503988457511'>
            <name>Test</name>
            <title>Test</title>
            <labels/>
            <steps/>
            <attachments/>
            <description type='markdown'>
                * do: something
                * assert: something
                * do: another thing
                * assert: another thing
            </description>
        </test-case>
    </test-cases>
</ns2:test-suite>
```

In allure I see next result:
![allure report 2017-08-29 13-14-53](https://user-images.githubusercontent.com/5900697/29816434-ad6b8a5c-8cbc-11e7-8b82-c75b3ed19c68.png)

#### What is the expected behavior?
Expected beharvior in html:
```
<ul>
    <li>do: something</li>
    <li>assert: something</li>
    <li>do: another thing</li>
    <li>assert: another thing</li>
</ul>
```

#### Please tell us about your environment:

| Allure version | 2.3.3 |
| --- | --- |
| Test framework | allure-js-commons@1.3.0 |
| Generate report using | allure-npm@2.3.3 |

**Comment by just-boris** [comment]
Hello!

Well, I am aware about this limitation. Unfortunately, this is a problem in underlying package [js2xmlparser](https://github.com/michaelkourlas/node-js2xmlparser). I have reported an issue there https://github.com/michaelkourlas/node-js2xmlparser/issues/60, hope the author will do something about that.

**Comment by DudaGod** [comment]
Hello.

Thank you. Okay, I've understood about extra indentation, but why my markdown is wrapped to `<pre><code></code></pre>`? My markdown list should be wrapped to `<ul><li>1</li></ul>`.

**Comment by just-boris** [comment]
Because indentation is treated as code block. Same thing is working on Github, for example:

     indented block

**Comment by DudaGod** [comment]
Yeah, you are right.
But it's strange that there was no such problem in Allure1. You have used a different package for parsing to xml?

**Comment by baev** [comment]
yep, Allure 2 uses flexmark instead of pegdown

**Comment by DudaGod** [comment]
I think I found the reason for this behavior and write about it in issue mentioned above - https://github.com/michaelkourlas/node-js2xmlparser/issues/60.

But I can't find where this package is used in Allure2. It seems that this dependency of flexmark. Am I right?

**Comment by just-boris** [comment]
js2xmlparser is a dependency for allure-js-commons. Actually, this bug report should be filed there. But as soon as that repo is maintained by the same people, it is fine to have a conversation there.

Regarding the actual issue: I will look at this at weekend and will come up with some solution. Stay tuned.

**Comment by DudaGod** [comment]
Thank you.

**Comment by baev** [comment]
I guess this one fixed already
