### ISSUE TITLE
Ability to specify which parameters should participate in determining the identity of the test

### ISSUE THREAD

**Issue by DudaGod** [allure-framework/allure2#583]
#### I'm submitting a ... 
  - [ ] bug report
  - [X] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
I have one test which I run in one browser with one retry - it means if it fails on first attempt then I will run it again in new browser with new session id. It turns out these tests differ from each other only by the session id which I write in the parameters of each test. So I assume that one of these tests will be written to the other in the retry field. But it doesn't, how I understand because two tests have different values in parameters.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
I the result i have two xml files with the following content:
```xml
<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1504042925278' stop='1504042930441'>
    <name>Suite</name>
    <title>Suite</title>
    <test-cases>
        <test-case start='1504042925278' status='failed' stop='1504042930440'>
            <name>Test</name>
            <title>Test</title>
            <labels/>
            <parameters>
                <parameter kind='argument' name='sessionId' value='12345'/>
            </parameters>
            <steps/>
            <failure>
                <message>Error</message>
                <stack-trace>stack-trace</stack-trace>
            </failure>
            <description type='markdown'>* some-info-1</description>
        </test-case>
    </test-cases>
</ns2:test-suite>
```
and
```xml
<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1504042916774' stop='1504042925260'>
    <name>Suite</name>
    <title>Suite</title>
    <test-cases>
        <test-case start='1504042916776' status='failed' stop='1504042925258'>
            <name>Test</name>
            <title>Test</title>
            <labels/>
            <parameters>
                <parameter kind='argument' name='sessionId' value='56789'/>
            </parameters>
            <steps/>
            <failure>
                <message>Error</message>
                <stack-trace>stack-trace</stack-trace>
            </failure>
            <description type='markdown'>* some-info-2</description>
        </test-case>
    </test-cases>
</ns2:test-suite>
```

In the report it looks like as 2 completely different tests:
![allure report 2017-08-30 08-24-43](https://user-images.githubusercontent.com/5900697/29856608-b9e10b68-8d5c-11e7-9a07-63ca88d887bd.png)

#### What is the expected behavior?
I expected that I can specify which of parameters should participate in determining the identity of the test.

| Allure version | 2.3.3 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-js-commons@1.3.0 |
| Generate report using | allure-npm@2.3.3 |

**Comment by DudaGod** [comment]
@just-boris @baev guys hello, can you say something about this?

**Comment by just-boris** [comment]
+1 from me.
I also have tests with retries and sometimes I am puzzled trying to understand retry detection logic. Any pointer in documentation regarding retry detection would be helpful. 
Something like: "If your test has the same name and parameters and bla-bla-bla it will be considered as retry of another one."

**Comment by DudaGod** [comment]
Yeah, this information should be in documentation. But it would be really cool if `addParameter` method has new API. Something like this:
```js
test.addParameter('argument', {key: 'sessionId', value: '12345', useInId: false});
test.addParameter('argument', {key: 'browser', value: 'firefox', useInId: true});
```
In the result tests with equal name and browser but with different sessionId will be displayed in the list of retries.

So it will give me opportunity to control retries behaviour.

**Comment by baev** [comment]
duplicate https://github.com/allure-framework/allure2/issues/342
