### ISSUE TITLE
Orphaned test still displayed and counts for run duration.

### ISSUE THREAD

**Issue by gavrilfb** [allure-framework/allure2#584]
#### I'm submitting a ... 
  - [x] bug report

#### What is the current behavior?
Orphaned test still displayed and counts for run duration.
![firefox_2017-08-30_16-10-56](https://user-images.githubusercontent.com/29943195/29866052-60ae7e8c-8da1-11e7-959f-c95fd901c51c.png)

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
1. Create a test suite that consist of a test that fail and a test that pass
2. Run the suite
2. Remove the failed test from your code
3. Run the suite again

#### What is the expected behavior?
The failed test is not included in the last run duration.
I don't know what will be best behaviour for the orphaned test, though.

#### Please tell us about your environment:

| Allure version | 2.3.4 |
|----|----|
| Test framework | testng@6.11 |
| Allure adaptor | allure-testng@2.0-BETA16 |
| Generate report using | allure-jenkins-plugin@2.22 |

**Comment by baev** [comment]
seems like you need to clear your results folder before second run

**Comment by gavrilfb** [comment]
Would it affects the history features for Jenkins?

> Allure since version 2 supports history for tests in the report [Learn more about History plugin]. At the every report generation during the build Jenkins Allure Plugin will try to access working directory of the previous build and copy contents of allure-report\history folder to the current report contents. At the moment history entry for test case stores information about up to 5 previous results.

PS: I forgot to attach the screenshot of the Timeline in the main post. Done that now.

**Comment by baev** [comment]
Allure stores history information to `allure-report/history` folder. Then allure-jenkins plugin copies such folder to `allure-results/history` of the next launch. 

All you need is clean Jenkins workspace between launches. That will solve your problem
