### ISSUE TITLE
Wrong success rate for parameterized tests

### ISSUE THREAD

**Issue by aiannucci** [allure-framework/allure2#585]
#### I'm submitting a ... 
  - [X] bug report

#### What is the current behavior?

Parameterized test are being totalized as single test for the sucess rate count.
Check attached image, a parameterized test has run only once for each parameter (as history shows), but it shows up as 2 of 2 in sucess rate.

#### Please tell us about your environment:

| Allure version | 2.3.4 |
| --- | --- |
| Test framework | junit@4.12 |
| Allure adaptor | allure-junit4@2.0-BETA16 |
| Generate report using | allure-jenkins@2.22 |

![image](https://user-images.githubusercontent.com/4360246/29887879-43d15cb4-8d95-11e7-9935-69f652862700.png)

**Comment by baev** [comment]
> but it shows up as 2 of 2 in sucess rate.

Everything is seems to be right, current run included to success rate (current is passed + previous is passed = 2 of 2 are passed)
