### ISSUE TITLE
Line wrapping of error message is removed after click on "Show trace" toggle

### ISSUE THREAD

**Issue by skyoker** [allure-framework/allure2#588]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Line wrapping is removed after click on "Show trace" toggle if stack trace text doesn't fit view width.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
https://ci.qameta.io/job/allure2/job/master/Demo_Report/index.html#categories/57b32020e228ce747f455e8a7480696d/e30ed2d326b7a910/ (Suites > Search tests > Page loading test)
![screen shot 2017-09-04 at 1 17 32 pm](https://user-images.githubusercontent.com/14233513/30022357-b43837de-9173-11e7-9204-3dc8d42b863d.png)

![screen shot 2017-09-04 at 1 17 55 pm](https://user-images.githubusercontent.com/14233513/30022358-b43b2282-9173-11e7-954e-b17b064073e3.png)

#### What is the expected behavior?
Error message and stack trace have line wrapping

#### Please tell us about your environment:

| Allure version | 2.3.4 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.0-BETA11 |
| Generate report using | allure-maven@2.18 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
BTW that is feature, not a bug
