### ISSUE TITLE
[.TRX Format] - No StackTrace or ErrorInfo in case of test failure

### ISSUE THREAD

**Issue by arpit-nagar** [allure-framework/allure2#596]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report

#### What is the current behavior?
I am using Allure in Jenkins. I am having test suite in .net which produce output as .trx format.
I am able to view report. 
Currently I am facing issue in failure test cases. My trx file has stackTrace and errorInfo while Allure report do not have any stackTrace or error.

*This is not a jenkins plugin bug. It is a issue in allure trx parsing.* so I am posting it here.

#### What is the expected behavior?
In Allure report Failure test cases should have error log or stack Trace.

#### What is the motivation / use case for changing the behavior?
It is a must have requirement without stackTrace for failure info there is no use of a test report.

#### Please tell us about your environment:

| Allure version | Latest in jenkins |
| --- | --- |
| Test framework | .net core 2.0.0 |
| Jenkins | 2.70 |
| Allure Commandline | 2.3.5 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

Please find attached trx and Allure report for same.
[allure-report.zip](https://github.com/allure-framework/allure2/files/1292179/allure-report.zip)
[TestResults.trx](https://github.com/allure-framework/allure2/files/1292180/TestResults.txt) (update extension .txt to .trx)

**Comment by arpit-nagar** [comment]
relates to #424

**Comment by arpit-nagar** [comment]
Any updates on this ??

**Comment by baev** [comment]
@arpit-nagar our team are busy at the moment, feel free to send us pull request with fixes. All you need is parse few more nodes in TRX file. You can find code that parses TRX files here
https://github.com/allure-framework/allure2/blob/master/plugins/trx-plugin/src/main/java/io/qameta/allure/trx/TrxPlugin.java

**Comment by arpit-nagar** [comment]
Thanks @baev for your time. Really appreciated. 👍 
Will wait for release.

**Comment by baev** [comment]
2.4.0 already available

**Comment by arpit-nagar** [comment]
Thanks @baev
