### ISSUE TITLE
Description does not display in report

### ISSUE THREAD

**Issue by timmitomas** [allure-framework/allure2#599]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report

#### 
![allurebug](https://user-images.githubusercontent.com/15175428/30643861-28ca35aa-9e19-11e7-933c-6bec6020a2a8.png)

#### Please tell us about your environment:

| Allure version | 2.3.5 |
| --- | --- |
| Junit framework | Junit@4.12 |
| Allure adaptor | allure-junit4@2.0-BETA18 |
| Generate report using | allure-maven@2.0.1 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
duplicate https://github.com/allure-framework/allure-java/issues/114
