### ISSUE TITLE
Can't generate allure report data

### ISSUE THREAD

**Issue by slipwalker** [allure-framework/allure2#602]
I've gotten this error during Allure report generation stage. This error happens only when I run the tests through the Grid (grid hub located on the same machine where build server is, its url mentioned in the stack trace error below). Any thoughts/suggestions on this one? Why this happens? Report is generated via Allure Maven plugin.

```
21-Sep-2017 13:45:03 | [INFO] Try to finding out allure 2.3.5
-- | --
21-Sep-2017 13:45:03 | [INFO] Downloading allure commandline...
21-Sep-2017 13:45:03 | [INFO] Proxy is not specified.
21-Sep-2017 13:45:04 | [INFO] Downloading allure commandline complete
21-Sep-2017 13:45:04 | [INFO] Generate Allure report (aggregate) with version 2.3.5
21-Sep-2017 13:45:04 | [INFO] Generate Allure report to /somemypath/ui-test/target/allure-results/allure-report
21-Sep-2017 13:45:04 | [INFO] Found results directory /somemypath/ui-test/target/allure-results
21-Sep-2017 13:45:04 | [INFO] Can't find information about categories.
21-Sep-2017 13:45:04 | [INFO] Generate report to /somemypath/ui-test/target/allure-results/allure-report
21-Sep-2017 13:45:04 | Please use CMSClassUnloadingEnabled in place of CMSPermGenSweepingEnabled in the future
21-Sep-2017 13:45:04 | Error: JMX connector server communication error: service:jmx:rmi://ip-10-2-1-90.ec2.internal:9121
21-Sep-2017 13:45:04 | [ERROR] Can't generate allure report data
21-Sep-2017 13:45:04 | org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
21-Sep-2017 13:45:04 | at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
21-Sep-2017 13:45:04 | at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
21-Sep-2017 13:45:04 | at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
21-Sep-2017 13:45:04 | at io.qameta.allure.maven.AllureCommandline.execute(AllureCommandline.java:79)
21-Sep-2017 13:45:04 | at io.qameta.allure.maven.AllureCommandline.generateReport(AllureCommandline.java:49)
21-Sep-2017 13:45:04 | at io.qameta.allure.maven.AllureGenerateMojo.generateReport(AllureGenerateMojo.java:189)
21-Sep-2017 13:45:04 | at io.qameta.allure.maven.AllureGenerateMojo.executeReport(AllureGenerateMojo.java:128)
21-Sep-2017 13:45:04 | at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
21-Sep-2017 13:45:04 | at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:219)
21-Sep-2017 13:45:04 | at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:319)
21-Sep-2017 13:45:04 | at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:135)
21-Sep-2017 13:45:04 | at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:175)
21-Sep-2017 13:45:04 | at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:138)
21-Sep-2017 13:45:04 | at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
21-Sep-2017 13:45:04 | at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
21-Sep-2017 13:45:04 | at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
21-Sep-2017 13:45:04 | at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
21-Sep-2017 13:45:04 | at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
21-Sep-2017 13:45:04 | at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
21-Sep-2017 13:45:04 | at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
21-Sep-2017 13:45:04 | at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
21-Sep-2017 13:45:04 | at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
21-Sep-2017 13:45:04 | at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
21-Sep-2017 13:45:04 | at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
21-Sep-2017 13:45:04 | at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
21-Sep-2017 13:45:04 | at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
21-Sep-2017 13:45:04 | at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
21-Sep-2017 13:45:04 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21-Sep-2017 13:45:04 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21-Sep-2017 13:45:04 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21-Sep-2017 13:45:04 | at java.lang.reflect.Method.invoke(Method.java:498)
21-Sep-2017 13:45:04 | at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
21-Sep-2017 13:45:04 | at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
21-Sep-2017 13:45:04 | at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
21-Sep-2017 13:45:04 | at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
21-Sep-2017 13:45:04 | [INFO] ------------------------------------------------------------------------
21-Sep-2017 13:45:04 | [INFO] BUILD FAILURE
21-Sep-2017 13:45:04 | [INFO] ------------------------------------------------------------------------
21-Sep-2017 13:45:04 | [INFO] Total time: 6.931 s
21-Sep-2017 13:45:04 | [INFO] Finished at: 2017-09-21T13:45:04+00:00
21-Sep-2017 13:45:05 | [INFO] Final Memory: 55M/1121M

```

**Comment by slipwalker** [comment]
Also, sometimes for my ordinary working build I get the following error during Allure report generation:

```

22-Sep-2017 04:24:15 | [INFO] Generate Allure report (aggregate) with version 2.3.5
-- | --
22-Sep-2017 04:24:15 | [INFO] Generate Allure report to /somemypath/ui-test/target/allure-results/allure-report
22-Sep-2017 04:24:15 | [INFO] Found results directory /somemypath/ui-test/target/allure-results
22-Sep-2017 04:24:16 | [INFO] Can't find information about categories.
22-Sep-2017 04:24:16 | [INFO] Generate report to /somemypath/ui-test/target/allure-results/allure-report
22-Sep-2017 04:25:16 | [ERROR] Can't generate allure report data
-- | --
22-Sep-2017 04:25:16 | org.apache.commons.exec.ExecuteException: Process exited with an error: 143 (Exit value: 143)
22-Sep-2017 04:25:16 | at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
22-Sep-2017 04:25:16 | at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
22-Sep-2017 04:25:16 | at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
22-Sep-2017 04:25:16 | at io.qameta.allure.maven.AllureCommandline.execute(AllureCommandline.java:79)
22-Sep-2017 04:25:16 | at io.qameta.allure.maven.AllureCommandline.generateReport(AllureCommandline.java:49)
22-Sep-2017 04:25:16 | at io.qameta.allure.maven.AllureGenerateMojo.generateReport(AllureGenerateMojo.java:189)
22-Sep-2017 04:25:16 | at io.qameta.allure.maven.AllureGenerateMojo.executeReport(AllureGenerateMojo.java:128)
22-Sep-2017 04:25:16 | at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
22-Sep-2017 04:25:16 | at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:219)
22-Sep-2017 04:25:16 | at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:319)
22-Sep-2017 04:25:16 | at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:135)
22-Sep-2017 04:25:16 | at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:175)
22-Sep-2017 04:25:16 | at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:138)
22-Sep-2017 04:25:16 | at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
22-Sep-2017 04:25:16 | at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
22-Sep-2017 04:25:16 | at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
22-Sep-2017 04:25:16 | at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
22-Sep-2017 04:25:16 | at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
22-Sep-2017 04:25:16 | at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
22-Sep-2017 04:25:16 | at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
22-Sep-2017 04:25:16 | at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
22-Sep-2017 04:25:16 | at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
22-Sep-2017 04:25:16 | at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
22-Sep-2017 04:25:16 | at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
22-Sep-2017 04:25:16 | at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
22-Sep-2017 04:25:16 | at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
22-Sep-2017 04:25:16 | at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
22-Sep-2017 04:25:16 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22-Sep-2017 04:25:16 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22-Sep-2017 04:25:16 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22-Sep-2017 04:25:16 | at java.lang.reflect.Method.invoke(Method.java:498)
22-Sep-2017 04:25:16 | at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
22-Sep-2017 04:25:16 | at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
22-Sep-2017 04:25:16 | at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
22-Sep-2017 04:25:16 | at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
22-Sep-2017 04:25:16 | [INFO] ------------------------------------------------------------------------
22-Sep-2017 04:25:16 | [INFO] BUILD FAILURE
22-Sep-2017 04:25:16 | [INFO] ------------------------------------------------------------------------
22-Sep-2017 04:25:16 | [INFO] Total time: 01:13 min
22-Sep-2017 04:25:16 | [INFO] Finished at: 2017-09-22T04:25:16+00:00
22-Sep-2017 04:25:16 | [INFO] Final Memory: 43M/406M
```

**Comment by baev** [comment]
@slipwalker could you please specify your allure-maven plugin version, maven version (result of `mvn -version` command)

**Comment by slipwalker** [comment]
@baev allure-maven plugin version is 2.8, maven version is 3.5.0

**Comment by rimmiw** [comment]
Hi, 
I have the same problem, I can get my report using command line allure open .... 
but nothing with maven built I got the error 

 ------------------------------------------------------------------------
[INFO] Building CLP-REST 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- allure-maven:2.8:report (default-cli) @ clprest ---
[INFO] Allure installation directory D:\Userfiles\rlamrani\Desktop\CLP_REGRESSION/.allure
[INFO] Try to finding out allure 2.5.0
[INFO] Downloading allure commandline...
[INFO] Proxy is not specified.
[INFO] Downloading allure commandline complete
[INFO] Generate Allure report (report) with version 2.5.0
[INFO] Generate Allure report to D:\Userfiles\rlamrani\Desktop\CLP_REGRESSION\target\site/allure-maven-plugin
[INFO] Found results directory D:\Userfiles\rlamrani\Desktop\CLP_REGRESSION\target\soapui-results
[INFO] Can't find information about categories.
 Can't find information about categories.
[INFO] Generate report to D:\Userfiles\rlamrani\Desktop\CLP_REGRESSION\target\site\allure-maven-plugin
Report successfully generated to D:\Userfiles\rlamrani\Desktop\CLP_REGRESSION\target\site\allure-maven-plugin
[INFO] Report generated successfully.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.895 s
[INFO] Finished at: 2018-01-26T15:54:57+01:00
[INFO] Final Memory: 22M/300M
[INFO] ------------------------------------------------------------------------

Please help! is it something wrong in my pom.xml

`<properties>
		
	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <chromedriver.version>2.53.0</chromedriver.version>
    <safaridriver.version>2.53.0</safaridriver.version>
    <mavensurefire.version>2.19</mavensurefire.version>
    <mavencompiler.version>3.5.1</mavencompiler.version>
    <mavensurefirereport.version>2.19</mavensurefirereport.version>
	<junit.version>4.12</junit.version>
    <allure.version>1.4.23</allure.version>
    <aspectj.version>1.8.9</aspectj.version>
    <alluremaven.version>2.0.1</alluremaven.version>
	<soapuimaven.version>5.3.0</soapuimaven.version>
    <mavenantrun.version>1.8</mavenantrun.version>
    <timestamp>${maven.build.timestamp}</timestamp>
    <maven.build.timestamp.format>yyyy_MM_dd_hh_mm_a</maven.build.timestamp.format>
    <release.number>16-21</release.number>
	<soapui.results.directory>soapui-results</soapui.results.directory>
	</properties>
	
<dependencies>
		
		
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>

		
<dependency>
    <groupId>io.qameta.allure</groupId>
    <artifactId>allure-junit4</artifactId>
    <version>2.0-BETA17</version>
    <scope>test</scope>
</dependency>


<dependency>
    <groupId>ru.yandex.qatools.allure</groupId>
    <artifactId>allure-junit-adaptor</artifactId>
    <version>1.5.4</version>
    <scope>test</scope>
</dependency>

	
		
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.16</version>
		</dependency>
	
		
		<dependency>
			<groupId>net.sourceforge.jexcelapi</groupId>
			<artifactId>jxl</artifactId>
			<version>2.6</version>
		</dependency>
		
		<dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjweaver</artifactId>
            <version>${aspectj.version}</version>
        </dependency>
	
	</dependencies>
	<repositories>
    <repository>
        <id>smartbear-sweden-repository</id>
        <url>http://smartbearsoftware.com/repository/maven2/</url>
    </repository>
	<repository>
          <id>central</id>
          <url>https://repo1.maven.org/maven2</url>
          <releases>
            <enabled>true</enabled>
          </releases>
        </repository>
	</repositories>
	
	<pluginRepositories>
    <pluginRepository>
        <id>smartbear-sweden-plugin-repository</id>
        <url>http://smartbearsoftware.com/repository/maven2/</url>
    </pluginRepository>
	<pluginRepository>
          <id>central</id>
          <url>https://repo1.maven.org/maven2</url>
          <releases>
            <enabled>true</enabled>
          </releases>
        </pluginRepository>
	</pluginRepositories>
	
	
	
	<build>
	
		<plugins>
		
			<plugin>
				<groupId>com.smartbear.soapui</groupId>
				<artifactId>soapui-maven-plugin</artifactId> 
				
				<version>5.3.0</version>
				
				
				<executions>
					<execution>
						<id>test-report1</id>				
						<phase>test</phase>
						<goals>						
							<goal>test</goal>								
						</goals>
						<configuration>
							<projectFile>${project.basedir}/src/test/clprest.xml</projectFile>
							<junitReport>true</junitReport>
							<exportAll>false</exportAll>
							<printReport>true</printReport>
							<testFailIgnore>true</testFailIgnore>
							<outputFolder>target/${soapui.results.directory}</outputFolder>
														
							
						<soapuiProperties>
							<property>
								<name>soapui.https.protocols</name>
								<value>TLSv1.2,SSLv3</value>
							</property>
						</soapuiProperties>		
				<properties>
                    <property>
                        <name>listener</name>
                        <value>io.qameta.allure.junit4.AllureJunit4</value>
                    </property>
                </properties>						
						</configuration>
						
					</execution>					
				</executions>
				
			</plugin>
			
			   
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
			
			<plugin>
				<groupId>io.qameta.allure</groupId>
				<artifactId>allure-maven</artifactId>
				<version>2.8</version>
				<configuration>
					<reportVersion>2.5.0</reportVersion>
					<resultsDirectory>${soapui.results.directory}</resultsDirectory>
					<failReportIfEmpty>true</failReportIfEmpty>
				</configuration>
				<executions>
					<execution>
						<id>allure-report</id>				
						<phase>prepare-package</phase>
						<goals>						
							<goal>report</goal>								
						</goals>
					</execution>					
				</executions>
			</plugin>
			
			
			
			
			
			
		</plugins>	
		
	</build>
			
		`

**Comment by rimmiw** [comment]
The soapui project executed generate XML file with JUnit format, Allure support the XML JUnit format, why it's works using command line but with maven I have empty report ? 
Please help !!! thanks a lot
PS ; sorry for my English

**Comment by uterator** [comment]
This problem blocks the report generation, we can't use Allure.
@baev, is there any workround or solution for this?

`[INFO] Generating "Allure" report    --- allure-maven:2.8
[INFO] Allure installation directory /Users/builder/appium/.allure
[INFO] Try to finding out allure 2.7.0
[INFO] Generate Allure report (aggregate) with version 2.7.0
[INFO] Generate Allure report to /Users/builder/appium/report
[INFO] Found results directory /Users/builder/appium/target/allure-results
[INFO] Generate report to /Users/builder/appium/report
[ERROR] Can't generate allure report data
org.apache.commons.exec.ExecuteException: Process exited with an error: 143 (Exit value: 143)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:153)
    at io.qameta.allure.maven.AllureCommandline.execute (AllureCommandline.java:79)
    at io.qameta.allure.maven.AllureCommandline.generateReport (AllureCommandline.java:49)
    at io.qameta.allure.maven.AllureGenerateMojo.generateReport (AllureGenerateMojo.java:189)
    at io.qameta.allure.maven.AllureGenerateMojo.executeReport (AllureGenerateMojo.java:128)
    at org.apache.maven.reporting.AbstractMavenReport.generate (AbstractMavenReport.java:255)
    at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument (ReportDocumentRenderer.java:219)
    at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule (DefaultSiteRenderer.java:319)
    at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render (DefaultSiteRenderer.java:135)
    at org.apache.maven.plugins.site.SiteMojo.renderLocale (SiteMojo.java:175)
    at org.apache.maven.plugins.site.SiteMojo.execute (SiteMojo.java:138)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:02 min
[INFO] Finished at: 2018-08-09T16:31:45-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project prod: Error during page generation: Error rendering Maven report: Could not generate the report: Can't generate allure report data: Process exited with an error: 143 (Exit value: 143) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more infor`

**Comment by 123dev** [comment]
Any update on this? we have the same issue.
Thanks

**Comment by uterator** [comment]
Seems the error can be avoided if delete the target/surefire-reports/TEST-Testsuite.xml file. But I am not sure what impact it will have.
@baev, is it safe to delete it? 
Just we want to be sure we are not losing any data in reports by deleting that file.

Thanks

**Comment by baev** [comment]
I guess this one closed via https://github.com/allure-framework/allure-maven/issues/59

**Comment by dipudan** [comment]
Using a later version of allure-maven version resolved this issue.
