### ISSUE TITLE
Show duration change at history tab

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [allure-framework/allure2#604]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Only test case start timestamp with TC status is present on History tab

#### What is the expected behavior?
Add an duration for TC run as well. It'll also would be nice to add some traction arrows to Duration entry(arrows on the screenshot are for illustration only)
![2017-09-22_18-46-51](https://user-images.githubusercontent.com/9446141/30753829-305750e4-9fc9-11e7-93de-ebf3a612a0f6.png)

#### What is the motivation / use case for changing the behavior?
Faster traction for test cases that have slowed down during execution period.

#### Please tell us about your environment:

| Allure version | 2.3.5 |
| --- | --- |
| Test framework | testng@6.10 |
| Allure adaptor | allure-testng@2.0-BETA17 |
| Generate report using | allure-maven@2.18 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by simple-elf** [comment]
Same for retries tab please

**Comment by 4ekki** [comment]
@baev , is it going to be supported?

**Comment by dremdem** [comment]
@baev 
Hello! 
Could you please point me, where I can find the duration history in the history tab?
I suppose it's implemented already.

**Comment by baev** [comment]
@dremdem, this is a long time ago closed issue. Could you please create a [discussion thread](https://github.com/orgs/allure-framework/discussions) so we can discuss the feature request & better understand the need? Thanks
