### ISSUE TITLE
Pie chart is displayed incorrectly in Chrome 61 under Linux

### ISSUE THREAD

**Issue by smecsia** [allure-framework/allure2#605]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
When you open the Allure report generated by Allure CLI 2.3.5 in Chrome 61.0.3163.91 under Linux, only the top half of the pie chart is displayed.

#### What is the expected behavior?
The whole pie chart should be displayed on the screen.

#### Please tell us about your environment:
| - | version |
|---|---|
| Allure | 2.3.5 |
| Chrome | 61.0.3163.91 |
| Linux | Ubuntu 16.04.3 LTS |
| Generate report using | allure-cli@2.3.5 |

**Comment by danalbu** [comment]
Windows with Chrome 61 also reproduces
