### ISSUE TITLE
First Step Duration Bug

### ISSUE THREAD

**Issue by Richard-Cao** [allure-framework/allure2#607]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
The first step duration always show **0ms**

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
![image](https://user-images.githubusercontent.com/5953992/30848839-ed48e724-a2d2-11e7-8e3a-6cf1a647503a.png)

#### What is the expected behavior?
Should show correct time.

#### Please tell us about your environment:

| Allure version | 2.3.5 |
| --- | --- |
| Test framework | cucumber@2.4.0 |
| Allure adaptor | allure-cucumber@0.5.8 |
| Generate report using | allure-cucumber@0.5.8 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
@Richard-Cao In our demo the first step has correct duration https://ci.qameta.io/job/allure2/job/master/Demo_Report/index.html#suites/1bbdddb8b139ac506f125d271028f72a/2182923014f6916f/

BTW this maybe an issue in Allure Cucumber, so this is good point to start the work if you decide to help us maintain Allure Cucumber integration
