### ISSUE TITLE
Exception during report generation

### ISSUE THREAD

**Issue by kouratoras** [allure-framework/allure2#609]
I have an issue while trying to generate a report.

#### Steps to reproduce

1. I am generating the .xml file from Codeception using [allure-codeception](https://github.com/allure-framework/allure-codeception).
2. I am running the allure generate command to produce the report

#### What I see
An exception:
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "1.50642981892E+12"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
```

The XML file line that includes this string is:
```
<alr:test-suite xmlns:alr="urn:model.allure.qatools.yandex.ru" start="1.50642981892E+12" stop="1.5064299142E+12" version="1.4.0">
```

#### What I expect to see

The message that the report is created.

#### Environment

| Allure version | 2.3.5 |
| --- | --- |
| Test framework | Codeception@2.3.5 |
| Allure adaptor | allure-codeception@1.2.4 |
| Generate report using | allure-command-line-tool@2.3.5 |

**Comment by baev** [comment]
Allure doesn't support `1.50642981892E+12` notation for timestamps. Moved to https://github.com/allure-framework/allure-codeception/issues/36
