### ISSUE TITLE
Allure 2.35 isn't showing report for Chrome browser

### ISSUE THREAD

**Issue by Github248** [allure-framework/allure2#614]
We're using the latest Allure Command line 2.35 and Allure maven 2.5 versions. We run the same tests on cross browsers. Firefox, Chrome.... We're seeing the test results run on Firefox and smallview tests on Chrome browser fine but test results run on Chrome browser for largeview are missing in the report generated by Allure. Can you please suggest ?

We're using xml file configuration to execute the tests. Please see a sample configuration below.

	<test name="LV_Chrome">
		<parameter name="browser" value="chrome" />
		<parameter name="device_view" value="desktop" />
		<parameter name="version" value="latest" />
		<parameter name="platform" value="macOS 10.12" />
		<groups>
			<run>
				<include name="high" />
				<include name="lv" />
				<exclude name="sv" />
			</run>
		</groups>

		<classes>

			<class name="com.xxx.xxx.xxx.classname" />
		</classes>
	</test>

**Comment by just-boris** [comment]
Have you seen this?
https://stackoverflow.com/questions/23997449/allure-report-nothing-shown-in-chrome

**Comment by Github248** [comment]
That solution didn't fix the issue. Seeing results only for Firefox and Chrome smallview

**Comment by baev** [comment]
@Github248 you need to add view size as parameter to fix the issue
