### ISSUE TITLE
Allure report creation issue for Maven-TestNG selenium project

### ISSUE THREAD

**Issue by savtambe** [allure-framework/allure2#616]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.0-BETA11 |
| Generate report using | allure-maven@2.18 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by savtambe** [comment]
Hi @baev,
With below cloned project from git, i am able to generate the allure reports.
https://github.com/allure-examples/allure-testng-example

When i am creating new maven project with TestNG with same pom i am getting below error.

[WARNING] Results directory for module projectname tests not found.

[WARNING] Allure report was skipped because there is no results directories found

Is any other configuration required apart from pom?

**Comment by eroshenkoam** [comment]
You getting this error because you misconfigure  something. 
Can your copy your pom.xml here?

**Comment by savtambe** [comment]
Sure eroshenkoam,

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ru.yandex.qatools.allure</groupId>
        <artifactId>allure-examples-parent</artifactId>
        <version>1.0</version>
    </parent>

    <groupId>io.qameta.allure</groupId>
    <artifactId>allure-testng-example</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <java.version>1.8</java.version>
        <aspectj.version>1.8.10</aspectj.version>
    </properties>

    <name>Allure TestNG Example</name>
    <description>Allure TestNG Example</description>

    <dependencies>
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-testng</artifactId>
            <version>2.0-BETA14</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <version>1.3</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.21</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <testFailureIgnore>true</testFailureIgnore>
                    <argLine>
                        -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                    </argLine>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>

    <reporting>
        <excludeDefaults>true</excludeDefaults>
        <plugins>
            <plugin>
                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-maven</artifactId>
                <version>2.8</version>
            </plugin>
        </plugins>
    </reporting>

</project>

**Comment by eroshenkoam** [comment]
It looks pretty good. How did you run your tests?

**Comment by savtambe** [comment]
POM right click run as Maven build - clean test site.

**Comment by eroshenkoam** [comment]
Just split it into two commands: 
* `clean test` - after that you will see 'target/allure-results' directory under your project
* `site` - generate Allure report

**Comment by savtambe** [comment]
Sure eroshenkoam, will try and get back to you.

**Comment by savtambe** [comment]
Hi eroshenkoam,
Still facing the same issue.

**Comment by eroshenkoam** [comment]
Did you see `target/allure-results` directory after `clean test`?

**Comment by eroshenkoam** [comment]
Oh, you need to put this file into test resources directory: 
https://github.com/allure-examples/allure-testng-example/blob/master/src/test/resources/allure.properties

**Comment by savtambe** [comment]
it's already there, still facing the issue.

**Comment by baev** [comment]
BTW that seems to be configuration issue, please use our Gitter/Stackoverflow for such type of questions

**Comment by totalqa9** [comment]
Hi,

Please find the pom.xml configuration available in this link. It will be helpful
http://total-qa.com/advanced-selenium/allure-reporting/
Thanks,
total-qa.com
