### ISSUE TITLE
No categories from categories.json is displayed in report when retries are exist

### ISSUE THREAD

**Issue by undron** [allure-framework/allure2#617]
#### I'm submitting a ... 
- [x] bug report

#### What is the current behavior?
1. Create report with few tests retries
1. Add categories.json to result folder with category that match any or all retries
1. Generate report

Standard category is displayed in Categories tab

#### What is the expected behavior?
Category from categories.json should be displayed

#### Please tell us about your environment:

| Allure version | 2.3.5 |
| --- | --- |
| Test framework | NUntit 3.7.1 |
| Allure adaptor | - |
| Generate report using | command line tool |

#### Other information 
Minimum report in the attachment
[AllureResults.zip](https://github.com/allure-framework/allure2/files/1358276/AllureResults.zip)

**Comment by baev** [comment]
What is the point of seeing retries on categories tab?

**Comment by undron** [comment]
I agree that retries should not been seen on this tab.
But if test has any retries, it should be displayed in this tab acording categories.json, isn't it?
For exemple, test has no reties:
![goes_to_cat](https://user-images.githubusercontent.com/1076685/31328095-d67170b2-acdb-11e7-80da-c32b08421d2d.png)
And if it has:
![does_not_goes_to_cat](https://user-images.githubusercontent.com/1076685/31328101-df4c0f58-acdb-11e7-92e2-8b4c95aabdea.png)

**Comment by undron** [comment]
In fact, we do 3 retries on the any faled or broken test, so for now Category tab is useless for us.

**Comment by rovner** [comment]
@undron Try to add "flaky": true to categories.json

**Comment by undron** [comment]
@rovner It's works, thank you!
But now I should add two almost the same sections:
```  {
    "name": "Проблемы тестового окружения",
    "messageRegex": ".*StatusCode: InternalServerError.*",
    "matchedStatuses": [
      "broken",
      "failed"
    ],
    "flaky": true
  },
  {
    "name": "Проблемы тестового окружения",
    "messageRegex": ".*StatusCode: InternalServerError.*",
    "matchedStatuses": [
      "broken",
      "failed"
    ]
  },
```
Is any idea how to simplify this?

**Comment by Agentbars** [comment]
Hi
Will this issue be fixed somehow? Or is it normal behavior?

**Comment by eslepakurov** [comment]
Hi
The same issue
flaky: true - doesn't help though

Here is an example of categories.json. Are any mistakes out there?
Thank you.

`[
  {
    "name": "Вообще не запускались. Были проигнорированны!",
    "matchedStatuses": [
      "SKIPPED"
    ]
  },
  {
    "name": "Ошибки автотестов. Обратитесь к команде автотестирования для исправлений.",
    "matchedStatuses": [
      "BROKEN"
    ]
  },
  {
    "name": "Завершились успешно.",
    "matchedStatuses": [
      "PASSED"
    ]
  },
]`

**Comment by ryparker** [comment]
Same issue here, except it applies to any custom categories. None of my custom categories are appearing on the report.

categories.json:

```JSON
[
  {
    "name": "Snapshot Failures",
    "description": "Snapshots that have changed.",
    "messageRegex": "snapshot"
  },
  {
    "name": "Schema violations",
    "description": "Schema checks that have failed.",
    "messageRegex": "schema"
  }
]
```

<img width="1200" alt="Screen Shot 2020-07-08 at 4 30 29 PM" src="https://user-images.githubusercontent.com/17558268/86972332-65e42000-c138-11ea-95fa-69992fdc8bec.png">
