### ISSUE TITLE
Allure Report with Bamboo throws Runtime Exception

### ISSUE THREAD

**Issue by ankit-ojha** [allure-framework/allure2#620]
I am trying to integrate Allure Reports with Bamboo (locally). I have setup bamboo, linked to a project and installed allure bamboo plugin. Tests are executing correctly. I have read all the documents available on allure website regarding Bamboo Plugin

I am getting
omething went wrong with Allure Report generation. Here are some details:
java.lang.RuntimeException: Failed to find Allure executable by name Allure 1.4
at io.qameta.allure.bamboo.AllureBuildCompleteAction.lambda$execute$4(AllureBuildCompleteAction.java:87)
at java.util.Optional.orElseThrow(Unknown Source)
I also tried Allure 2.3.1 as stated on the documentation but no luck.

**Comment by eroshenkoam** [comment]
https://github.com/allure-framework/allure-bamboo/issues/35
