### ISSUE TITLE
Allure doesn't parse *.xml files which contains collection tag with any symbol (space, tab, etc)

### ISSUE THREAD

**Issue by eroshenkoam** [allure-framework/allure2#629]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Minimal xml for issue reproduce is: 
```
<?xml version="1.0" encoding="UTF-8"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1507555789637" stop="1507555789647">
	<name>Test Suite</name>
	<test-cases>
		<test-case start="1507555789637" stop="1507555789637" status="pending">
			<name>Test Suite</name>
			<labels>
			</labels>
                 </test-case>
        </test-cases>
</test-suite>
```

#### What is the expected behavior?

Report is generated

#### What is the motivation / use case for changing the behavior?

I like Allure report, so it will be nice to generate it :)

#### Please tell us about your environment:

| Allure version | 2.4.0 |
| --- | --- |
| Test framework | allure1 |
| Allure adaptor | any |
| Generate report using | command line |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
https://github.com/FasterXML/jackson-dataformat-xml/issues/124
