### ISSUE TITLE
Annotation @Link not working as intended

### ISSUE THREAD

**Issue by gavrilfb** [allure-framework/allure2#635]
#### I'm submitting a ... 
  - [x] bug report

#### What is the current behavior?
`@Link` not directed to specified url
![firefox_2017-10-12_10-22-41](https://user-images.githubusercontent.com/29943195/31478114-408b88da-af38-11e7-95f9-06d69d599a4e.png)

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Add `@Link("https://example.org")`
Run test and generate report

#### What is the expected behavior?
Links working as intended

#### Please tell us about your environment:

| Allure version | 2.4.1 |
| --- | --- |
| Test framework | testng@6.11 |
| Allure adaptor | allure-testng@2.0-BETA18 |

**Comment by gavrilfb** [comment]
The link have no href value `<a class="link" href="" target="_blank">https://example.org</a>`

**Comment by eroshenkoam** [comment]
You need to specify name and url like this: 
```
@Link(name="Example", url="https://example.org")
```

**Comment by gavrilfb** [comment]
Ok, it works now. Thank you.

PS: I think the documentions for `@Link` should be corrected / added then at https://docs.qameta.io/allure/latest
