### ISSUE TITLE
No data on the overview tab when generating the report from xunit

### ISSUE THREAD

**Issue by nikolayLevashkin** [allure-framework/allure2#640]
Hi.
After the start  xunit tests I get the xml  (>xunit.console.exe "Test.dll" -xml "report.xml")

xml version 2 https://xunit.github.io/docs/format-xml-v2.html

`<?xml version="1.0" encoding="utf-8"?>
<assemblies timestamp="10/17/2017 15:37:18">
  <assembly name="C:\Visual Studio 2015\Projects\WebRegistrationTest\NoMoneyAutoban\bin\Debug\NoMoneyAutoban.DLL" 
			environment="32-bit .NET 4.0.30319.42000 [collection-per-class, parallel (4 threads)]" 
			test-framework="xUnit.net 2.3.0.3820" 
			run-date="2017-10-17" run-time="15:37:18" 
			config-file="C:\Visual Studio 2015\Projects\WebRegistrationTest\packages\xunit.runner.console.2.3.0\tools\net452\xunit.console.x86.exe.Config" 
			total="2" passed="1" failed="1" skipped="0" time="0.117" errors="0">
    <errors />
    <collection total="2" passed="1" failed="1" skipped="0" name="Test collection for NoMoneyAutoban.TestBanNoMoney" time="0.027">
      <test name="NoMoAutoban.NoMoney.BanNoMoneyTest" type="Autoban.NoMoney" method="NoMoneyTest" time="0.025453" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[Assert.True() Failure\r\nExpected: True\r\nActual:   False]]></message>
          <stack-trace><![CDATA[   at NoMoneyAutoban.TestBanNoMoney.BanNoMoneyTestFalse() in C:\Visual Studio 2015\Projects\WebRegistrationTest\NoMoneyAutoban\TestBanNoMoney.cs:line 16]]></stack-trace>
        </failure>
      </test>
      <test name="NoMoneyAutoban.TestBanNoMoney.BanNoMoneyTestTrue" type="NoMoneyAutoban.TestBanNoMoney" method="BanNoMoneyTestTrue" time="0.0015885" result="Pass" />
    </collection>
  </assembly>
</assemblies>`

Then generate the report(>allure serve "/PathFolderToReportXml")
Open the report in Chrome
On the overview tab there is no data (date, trend, environment).
![allure](https://user-images.githubusercontent.com/32871270/31703633-2cea19f6-b3e6-11e7-873d-110696e3ca81.PNG)

| Allure version |2.4.1 |
| Test framework | xUnit 2.3.0 |
| Generate report using | allure-commandline v2.4.1 |

**Comment by baev** [comment]
See https://stackoverflow.com/a/46222758/3915166

**Comment by pmoura** [comment]
Same issue using Allure 2.14.0. Generating a report for a xUnit.net v2 XML file display "unknown - unknown (Unknown)". the `run-date`, `run-time`, and `time` attributes of the `assembly` element seem to be ignored.

**Comment by baev** [comment]
The official integration for XUnit is now available 

https://github.com/allure-framework/allure-csharp
https://allurereport.org/docs/xunit/
Try it via Allure Start https://allurereport.org/start/
