### ISSUE TITLE
Add ability to attach clickable links into scenario

### ISSUE THREAD

**Issue by igogorek** [allure-framework/allure2#644]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the expected behavior?
I would like to have an ability to attach clickable links to report. So that it would be an \<a> element in report html and attached url could be opened by just clicking on it.  

I would remove folding of attaches for this type, because it seems unnecessary but that's not very important.
 
It would be also great if url's inside step text and attach label also be clickable. But it would not be practical for very long url's and is in my opinion optional.
#### What is the motivation / use case for changing the behavior? 
I attach clickable links to report by attaching html, containing just <a> element for that link (which is not rendered in allure 2 currently).
It's not very practical.

#### Please tell us about your environment:

| Allure version | 2.4.1 |
| --- | --- |
| Test framework | pytest@3.2.3 |
| Allure adaptor | allure-pytest@2.2.3b1 |
| Generate report using | allure-commandline@2.4.1 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by sseliverstov** [comment]
You can use @allure.link decorator

some examples here:
https://github.com/allure-framework/allure-python/blob/master/allure-pytest/test/links/function_links_test.py

**Comment by igogorek** [comment]
That decorator allows attaching link to test. But i'm talking about links inside steps. Example would be - you prepared data for certain page state, you attach link to that page. In the steps tree i want to click on that link to open, instead of copy pasting it.

**Comment by sseliverstov** [comment]
Ok.
How about use attachment with list of urls and "text/uri-list" mime type?

**Comment by sseliverstov** [comment]
Example: https://ci.qameta.io/job/allure2/job/master/Demo_Report/index.html#suites/1bbdddb8b139ac506f125d271028f72a/37ef118ef19056e3/

**Comment by igogorek** [comment]
Tried it. Yes it works well enough.
```python
    with allure.step(u'Аттачим список урлов'):
        allure.attach('https://www.yandex.ru/\nhttps://google.com/', u'Список урлов', 
                               allure.attachment_type.URI_LIST)
```
Looks the same as text attachment but links are clickable
![2017-10-26_17-13-06](https://user-images.githubusercontent.com/4035219/32057853-1e0a3d12-ba71-11e7-96c9-ea0dbef33e9f.png)
And even long url looks nice, which was my biggest concern.
Accept unicode and invalid urls without raising an error on report generation. Which is also good.
So it's good enough for me. And only need one additional line in allure-python code.
Should i make a pull request or will you add it yourself?

**Comment by sseliverstov** [comment]
PR) tnx!

**Comment by baev** [comment]
please create a separate issue in allure-python for future discussions

**Comment by baev** [comment]
https://github.com/allure-framework/allure-python/pull/168
