### ISSUE TITLE
how to customize allure report and sort by date?

### ISSUE THREAD

**Issue by PraneshAnandhan** [allure-framework/allure2#646]
Hi,

I am currently looking into the framework Allure for Jenkins.

In Allure report is it possible to check historical report(timeline of changes between a lot of reports) and can be sort by date/time?

Is it possible?

**Comment by psprogis** [comment]
Hi,

What do you mean by "timeline of changes" ? You always have revision numbers and can find out what commits were done between time A and time B. Or if you are talking about tests history between time A and time B - you can take a look on a history trend, or open report as of time A and report as of time B and compare them: total number of tests, failed tests, pending tests, etc.

**Comment by baev** [comment]
closed as stale
