### ISSUE TITLE
Allure distributions not available on Maven site

### ISSUE THREAD

**Issue by rgudla** [allure-framework/allure2#647]
Contents in https://dl.bintray.com/qameta/maven/io/qameta/allure/ are identical to http://repo1.maven.org/maven2/io/qameta/allure/.

I couldn't find the contents of https://dl.bintray.com/qameta/generic/io/qameta/allure/ in Maven site.

Any plans to make the releases available in `Maven` as well instead of just `bintray`?

**Comment by baev** [comment]
All java artefacts are available on Maven Central. Generic package contains our binaries (command line and plugins) that should not be uploaded to Maven
