### ISSUE TITLE
"allure.link.issue.pattern" links are not working inside the report.

### ISSUE THREAD

**Issue by tlytvyn** [allure-framework/allure2#653]
I am working with latest allure maven plugin 2.9 and I have allure.properties file( in the root folder of the project ) which is copied correctly to allure-results folder when I am performing mvn allure:report

It's content:
"#Mon Oct 30 15:05:26 EET 2017
allure.link.issue.pattern=https\://jira.com/bugs/{}"

Also in pom.xml there is a line:
<propertiesFilePath>allure.properties</propertiesFilePath>

I am putting @Issue annotation and when I am clicking on it inside a report it is opening current report page instead of opening a jira.com link.

**Comment by baev** [comment]
> I have allure.properties file( in the root folder of the project ) which is copied correctly to allure-results folder

place allure.properties file to your test resources (`src/test/resources` by default). No more need to copy it to results directory

**Comment by tlytvyn** [comment]
@baev Thanks man, issue fixed) That works for me now
