### ISSUE TITLE
Allow attachements in test fixtures

### ISSUE THREAD

**Issue by marx-freedom** [allure-framework/allure2#66]
Greetings.
It would be great to have an ability to create attachments in test fixtures.

**Comment by baev** [comment]
Hi. Actually you can create attachments and steps in fixtures. But old Allure adaptors isn't support this. New TestNg and PyTest adaptors is pretty much ready, so stay turned.

**Comment by marx-freedom** [comment]
Thanks. Is there any plans to support it in JUnit adapter?

**Comment by baev** [comment]
> Is there any plans to support it in JUnit adapter?

Yep, right next after TestNG. For JUnit 4 it is only possible via custom runner or using AspectJ. I guess we will provide AspectJ implementation. Also we created an issue for JUnit 5 https://github.com/junit-team/junit5/issues/618 to support that

**Comment by baev** [comment]
Closing this one as fixed. You can watch the status of new adaptors in the related tickets:

https://github.com/allure-framework/allure2/issues/110
https://github.com/allure-framework/allure2/issues/109

**Comment by hollmaro** [comment]
@baev Hello! 
Can you tell exact in what allure-testNG adaptor (version) is an ability to add the attachment to fixtures?
As I know allure-testng 2.7.0 is the latest version.
Thank you!

**Comment by baev** [comment]
@hollmaro the same way as you add attachments in test. 

PS do not post questions in closed issues use our Gitter chat or StackOverflow (tag `allure`)
