### ISSUE TITLE
Report name keeps unchanged when specified in environment.xml file

### ISSUE THREAD

**Issue by gtuveri** [allure-framework/allure2#660]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

Even if using a custom environment specification file (as shown in https://github.com/allure-framework/allure1/wiki/environment), the report name keeps the "UNKNOWN" name in Overview page. 

#### Please tell us about your environment:

| Allure version | 2.4.1 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.0-BETA11 |
| Generate report using | allure-maven@2.18 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by Nirlaksh** [comment]
I am also facing same issue
Any update on this issue?

**Comment by dean403** [comment]
Any update on this issue?

**Comment by baev** [comment]
You can specify the report name via [executor.json](https://allurereport.org/docs/how-it-works-executor-file/) file or by using  the `--name` CLI option
