### ISSUE TITLE
Junit4 - Report's body stays empty when we use Timeout @Rule for tests

### ISSUE THREAD

**Issue by VDzhevalov** [allure-framework/allure2#669]
#### I'm submitting a ... 
  - [ ] bug report

#### Environment:
| Allure version | 2.4.1 |
| Test framework | junit@4.11 |
| Allure adaptor | allure-junit@2.0-BETA19 |
| Generate report using | allure-gradle@2.4 |

[//]: # (
When we use 
@Rule Timeout ...
or
@Test (timeout = xxxx) 

The report's body do not contain any informatiin about teststeps.)

**Comment by skalozubov** [comment]
The same issue is reproduced for us with TestNG using test time-out. Generated report has no steps. All other things like Features, Stories, test setup, test teardown, attachments are here.

Sample testng.xml when the issue **is** reproduced:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="SuiteName" verbose="1" configfailurepolicy="continue" time-out="300000">
    <test name="SampleName">
        <classes>
            <class name="com.example.LoginTest"/>
        </classes>
    </test>
</suite>
```
Sample testng.xml when the issue **is not** reproduced:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="SuiteName" verbose="1" configfailurepolicy="continue">
    <test name="SampleName">
        <classes>
            <class name="com.example.LoginTest"/>
        </classes>
    </test>
</suite>
```

Env:
```
testng:6.11
allure-gradle:2.4
allure {
    version = '2.3.5'
    autoconfigure = true
    configuration = "compile"
}
```
