### ISSUE TITLE
Define steps manually

### ISSUE THREAD

**Issue by marcuskaufmann** [allure-framework/allure2#671]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Having code like this

```
@Test
@Step("TRegister")
public void test()
{
    step("Goto homepage");
    //code

    step("Assure not logged in status");
    //code

    ...
}

@Step("\"{stepName}\" step")
public void step(String stepName)
{
}
```
This yields in a report that looks like that:
![chrome_2017-11-16_18-10-44](https://user-images.githubusercontent.com/16191117/32905508-7120cb26-cafa-11e7-86ab-da2f8b54f063.png)

#### What is the expected behavior?
But I want to have it to look like that:
https://ci.qameta.io/job/allure2/job/master/Demo_Report/index.html#suites/fd187460706bbe14b8a84cc98c3fb991/1063eec919e2a469/
![chrome_2017-11-16_18-26-11](https://user-images.githubusercontent.com/16191117/32905908-a84cd922-cafb-11e7-84fb-9507a53e77f4.png)

The icons indicate a passed/fail behaviour and timing seem to be correct.

#### What is the motivation / use case for changing the behavior?
If I would split my test case in many functions and annotate them correctly I would get that but the test case wouldn't be readable anymore. I work on top of an high level api that reduces the code needed for testing to a few lines. So I would have to wrap (in average) less then 3 lines in a function.
So it would be nice to define step during runtime so we could achieve the same behaviour as if it would be in annotatd functions.

#### Please tell us about your environment:

| Allure version | 2.4.1 |
| --- | --- |
| Test framework | JUnit@4.12 |
| Allure adaptor | allure-junit@2.0-BETA19 |
| Generate report using | allure-maven@2.9 |

**Comment by baranoff-ivan** [comment]
With Java 8 you could do something like that:
```java
@Test
@Step("TRegister")
public void test()
{
    step("Goto homepage", () -> {
        //code
    });


    step("Assure not logged in status", () -> {
        //code
    });

    ...
}

@Step("\"{stepName}\" step")
public void step(String stepName, Runnable actions) {
   actions.run();
}
```

**Comment by baev** [comment]
you can use `AllureLifecycle`:

```java

    public interface StepBody {
        void execute() throws Exception;
    }
    
    ...
    public static void step(final String name, final StepBody body)
        final String uuid = UUID.randomUUID().toString();
        final StepResult result = new StepResult()
                .withName(name);
        getLifecycle().startStep(uuid, result);
        try {
            body.execute();
            getLifecycle().updateStep(uuid, s -> s.withStatus(Status.PASSED));
        } catch (Exception e) {
            getLifecycle().updateStep(uuid, s -> s
                    .withStatus(getStatus(e).orElse(Status.BROKEN))
                    .withStatusDetails(getStatusDetails(e).orElse(null)));
            throw e;
        } finally {
            getLifecycle().stopStep(uuid);
        }
    }
```

**Comment by kishorejawalkar** [comment]
@baev Is it possible to use parameter(s) as value in the above step method?

For example like below:
```
@Step("Create {0} application.")
private void createApplication(String applicationType) {
   //code
}
```

**Comment by baev** [comment]
yep, see `io.qameta.allure.util.AspectUtils#getParameters`

**Comment by kishorejawalkar** [comment]
@baev not sure from where i get parameters MethodSignature & args to pass for getParameters method, please help me.
```
getParameters(final MethodSignature signature, final Object... args)
```

**Comment by baev** [comment]
this issue closed 5 years ago, please create a discussion instead https://github.com/allure-framework/allure2/discussions

**Comment by kishorejawalkar** [comment]
@baev created new discussion here https://github.com/allure-framework/allure2/discussions/1761
