### ISSUE TITLE
Steps annotation in the allure-junit.version 2.0-BETA19 does not work 

### ISSUE THREAD

**Issue by pavel-vlasov** [allure-framework/allure2#672]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
When adding Steps annotation on top of a method in allure-junit.version 2.0-BETA19 I get error message:
io.qameta.allure.aspects.StepsAspects.aspectOf()Lio/qameta/allure/aspects/StepsAspects
This error message is also visable in the report

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Add Steps annotation on top of a method

```
@Step("")
   public SelenideTest loop(String value){
       $(By.name("q")).setValue(value).pressEnter();
       return page(SelenideTest.class);
   }
```

#### What is the expected behavior?

No errors in the console and steps should show up in the report.

#### What is the motivation / use case for changing the behavior?

I can use steps again to see more details

#### Please tell us about your environment:

| Test framework | Junit@4.12 |
| Allure adaptor | allure-junit@2.0-BETA19 |
| Generate report using | allure-maven@2.8 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by symonk** [comment]
@pavel-vlasov I think this is an open issue, can you try with 2.0-BETA15, it should work

**Comment by baev** [comment]
fixed in last releases
