### ISSUE TITLE
junit 5 maven documintation

### ISSUE THREAD

**Issue by tnimni** [allure-framework/allure2#674]

**Comment by eroshenkoam** [comment]
I will make documentation at the end of the year :) 
But you can use this example for now: 
https://github.com/allure-examples/allure-junit5-example

**Comment by tnimni** [comment]
@eroshenkoam i have already created the documentation, if you can approve the pull request on allure-docs i'll appreciate it

**Comment by baev** [comment]
@tnimni sry, totally forgot about your pull request 

@eroshenkoam https://github.com/allure-framework/allure-docs/pull/81

**Comment by baev** [comment]
fixed via https://github.com/allure-framework/allure-docs/pull/81
