### ISSUE TITLE
Failure message is shared across different failures

### ISSUE THREAD

**Issue by vladoriginal** [allure-framework/allure2#678]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
When we have the py.test, that reports several failures, the same failure is shared in every failed step.

![image](https://user-images.githubusercontent.com/11050189/33174332-a2b29b60-d068-11e7-9b5a-06b17a7e8452.png)

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Smaller example generated today.
```xml
<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1511449869460" stop="1511449869508">
  <name>test_failures</name>
  <labels/>
  <test-cases>
    <test-case start="1511449869460" status="broken" stop="1511449869508">
      <name>test_locations_about</name>
      <failure>
        <message>Failed: Just fail the step</message>
        <stack-trace>fail_post = None

    def test_locations_about(fail_post):
        with pytest.allure.step('first step'):
&gt;           pytest.fail('Just fail the step')
E           Failed: Just fail the step

Projects\Locations\test_failures.py:5: Failed</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="29072-MainThread"/>
        <label name="host" value="123"/>
      </labels>
      <steps>
        <step start="1511449869462" status="failed" stop="1511449869462">
          <name>first step</name>
          <title>first step</title>
          <attachments/>
          <steps/>
        </step>
        <step start="1511449869508" status="failed" stop="1511449869508">
          <name>cleanup</name>
          <title>cleanup</title>
          <attachments/>
          <steps/>
        </step>
      </steps>
    </test-case>
  </test-cases>
</ns0:test-suite>

```

#### What is the expected behavior?
Each failed step has its own failure description.
I don't know which of the failures is better to show as general failure.

#### What is the motivation / use case for changing the behavior?
Test with retries could have serveral failures.
Test could produce one failure on a run and then another failure on a teardown.

#### Please tell us about your environment:

| Allure version | 2.4.1 |
| --- | --- |
| Test framework | py.test |
| Allure adaptor | pytest_allure_adaptor-1.7.9 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
You are using the first version of allure pytest, that uses allure1 model. Allure1 model only supports one error message per result. Upgrade to allure-pytest@2.2.4b1 , that will fix the problem

**Comment by vladoriginal** [comment]
Great thanks for clarification!
