### ISSUE TITLE
History, bypassing CI Server

### ISSUE THREAD

**Issue by twixdouble** [allure-framework/allure2#679]
Could you please give some how-to about making History work bypassing CI Server.
I'm using allure-nose but I think question is general.

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

Thank you very much.

**Comment by baev** [comment]
Allure stores history information to `allure-report/history` folder during report generation. So you need to copy such folder from previous launch into your allure-results before you generate the report.

Related issues:

#697 - ability to specify path for history storage
#347 - ability to configure number of history items

**Comment by PavelGloba** [comment]
@baev It doesn't work via command line without CI plugins or I'm doing something wrong:

1. Run tests
2. Generate reports: 
allure generate /opt/myproject/qwe-common/target/surefire-reports /opt/myproject/qwe-monitoring/target/surefire-reports /opt/myproject/qwe-logic/target/surefire-reports
3. Run tests again
4. Run allure generate again
5. Get an error:

`Target directory /opt/myproject/allure-report for the report is already in use, add a '--clean' option to overwrite`

I'm getting this error even if I leave only allure-report/history folder.  If I run generate with --clean option, allure overwrites everything including history. Is it possible to generate new reports and update history trend via cli?
