### ISSUE TITLE
History won't be generated

### ISSUE THREAD

**Issue by johnmondeen** [allure-framework/allure2#682]
_I am using: protractor, jasmine-allure-reporter, allure-commandline_

---
I had the problem, that no history would be generated over multiple testsuite executions.
After understanding the purpose of the history-feature (see https://stackoverflow.com/questions/47514696/what-exactly-are-history-and-retries-meant-to-mean-in-allure/47533045#47533045), more research and lots of trying out different things, **I found this solution**:

Before a new testsuite execution, the "history"-folder from "allure-report"-folder is supposed to be copied into the "allure-results"-folder. This way, allure will generate the right history from the saved "history"-folder.

**My fix**:
Execute the test via .bat and copy the folder beforehand:
```batch
if [[ -e ./allure-report/history ]]; then
  if [[ -e ./allure-results/history ]]; then
    rm -rf ./allure-results/history
  fi
  mv ./allure-report/history ./allure-results/history
fi
protractor conf.js
allure generate -c
```

---

Is there a better way to do this?
Shouldn't this happen by default?

**Comment by baev** [comment]
yeah, thats how it works at the moment. BTW we are going to implement allure config that will allow you to specify history folder via commandline:

```bash
$ allure generate --history /my/local/history
```

or using yaml configuration file

```yml
# allure.yml
history: /my/local/history
other.configs...
```

and then such config will be used during report generation 

```bash
$ allure generate --config my/allure/config 
```

**Comment by johnmondeen** [comment]
### I have found an issue with this solution. See the following scenario:
_(Say we have two testuites, I'll call A and B, and a testcase, I'll call X.)_

1) Execute X in A
  --> A listed, has no history (as expected)
2) Execute X in B
  --> B listed, has no history (as expected)
  --> X from 1) now in history of A (**not expected?!**)
3) Execute X in B again
  --> B listed, has history --> X from 2) (as expected)
  --> X from 1) and X from 2) now in history of A (**not expected?!**)

---
Looking into the files, I found, that the doubled history-entries have different _uid_ s, but their time-stamps are the same.

---
**How do you generate a proper history, when not continuing the execution of a testsuite, but running the same testcase in a different testsuite?**

-------------
Also: Why will the history only store up to five testcases? Can one somehow change that number?

**Comment by baev** [comment]
> Why will the history only store up to five testcases? Can one somehow change that number?

There is an issue https://github.com/allure-framework/allure2/issues/347

**Comment by baev** [comment]
https://github.com/allure-framework/allure2/issues/697

**Comment by baev** [comment]
> I have found an issue with this solution. See the following scenario:

@johnmondeen please create a separate issue. Also provide sample project to reproduce the problem
