### ISSUE TITLE
Allure2 Not Showing Severity Levels or DisplayNames

### ISSUE THREAD

**Issue by aljones15** [allure-framework/allure2#683]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Despite having DisplayName and Severity Decorators on all tests neither show. Also the Report has the Title Unknown.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
https://stackoverflow.com/questions/47603605/allure-results-not-showing-displayname

#### What is the expected behavior?
I believe the Allure Decorators, Steps, and Severity Levels should be in the report.

#### What is the motivation / use case for changing the behavior?
What's the point of Allure if you can't provide rich meta-data to make the reports more informative?

#### Please tell us about your environment:

| Allure version | ?? |
| --- | --- |
| Test framework | junit 4.12 |
| Allure adaptor | allure-junit4@2.0-BETA19 |
| Generate report using | allure-maven@2.9 |

#### Other information 
I am using Intellij Idea, but running normal man commands doesn't help either.
[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by eroshenkoam** [comment]
Please use the latest version of allure adapter: 
https://github.com/allure-framework/allure-java/releases/tag/2.0-BETA21

**Comment by aljones15** [comment]
you mean allure-junit4 or that I am missing a dependency?

**Comment by eroshenkoam** [comment]
@aljones15 yes, I fixed @DisplayName under test class in allure-junit4 2.0-BETA20

**Comment by eroshenkoam** [comment]
@aljones15 If you will have problems with that just reopen this issue.

**Comment by aljones15** [comment]
ok cool thevereity is also not showing I think the issue might be something else, but I am running it right now.

**Comment by eroshenkoam** [comment]
2 minutes please, I will check it

**Comment by aljones15** [comment]
just finished a basic run in which each test has a different severity, display name, and Story.
allure serve ./target/surefire-reports/ 
nothing shows up. is there a different command? I've also noticed none of this stuff seems to be in the report xml. is it written to the report xml?

**Comment by aljones15** [comment]
oh my bad looks like I needed to call allure serve on allure-results that might cause issues in aws though.
