### ISSUE TITLE
Category for tests marked with Issue annotation

### ISSUE THREAD

**Issue by Dmitriy85** [allure-framework/allure2#685]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
When I open categories there is no category fir the tests which have @Issue annotation.

#### What is the expected behavior?
When I open categories section in report I would like to see all tests which have @Issue annotation. 

#### What is the motivation / use case for changing the behavior?
This feature can reduce the time to split tests which a failed due to known issues and tests which are failing by unknown ones. Also it can save a lot of time for the analyzing results.

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | testng@6.8.5 |
| Allure adaptor | allure-testng@2.0-BETA21 |
| Generate report using | allure-maven@2.9 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by aleksandr-kotlyar** [comment]
+1 for `allure-pytest` adaptor. Would be nice to have.

**Comment by baev** [comment]
Closed as stale. Please create a GitHub discussion if the feature is still needed.
