### ISSUE TITLE
Show error message on history tab

### ISSUE THREAD

**Issue by rovner** [allure-framework/allure2#688]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
There are no error messages on history tab
![2017-12-13_11-40-06](https://user-images.githubusercontent.com/9945237/33929474-b07d4fe6-dffa-11e7-8b99-66cfb882f32d.png)
while retries tab has
![2017-12-13_11-39-54](https://user-images.githubusercontent.com/9945237/33929489-ba5d7964-dffa-11e7-9c7e-51e971b2c309.png)

#### What is the expected behavior?
History tab contains error messages

#### What is the motivation / use case for changing the behavior?
It is important to know was previous runs fails with the same error or another

#### Please tell us about your environment:

| Allure version | 2.4.1 |
| ----- | ---- |

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
Closed as stale. Please create a GitHub discussion if the feature is still needed.
