### ISSUE TITLE
Timeline support  filter testcases by given Min-Max range

### ISSUE THREAD

**Issue by wuhuizuo** [allure-framework/allure2#692]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Timeline only support filter testcases above the given time cost.

#### What is the expected behavior?
Timeline support filter testcases above the given time cost1 and  under time cost2

#### What is the motivation / use case for changing the behavior?

Testers want to optimilize the test performance by static the testcase time cost.
He/She want static testcases by the time cost as follow:
- above 1 hour
- 30min ~ 1hour
- 15min ~ 30min
- 5min ~ 15min
- 1min ~ 5min
- under 1min

#### Please tell us about your environment:

Allure 2.x

**Comment by baev** [comment]
Closed as stale. Please create a GitHub discussion if the feature is still needed.
