### ISSUE TITLE
Show retries on timeline

### ISSUE THREAD

**Issue by rovner** [allure-framework/allure2#693]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
First test runs are not displayes on timeline
![2017-12-14_17-18-33](https://user-images.githubusercontent.com/9945237/33996902-ab56dca4-e0f3-11e7-87b9-fafbb20929b1.png)
Such a gaps could be confusing

#### What is the expected behavior?
Display retries with faded color
![2017-12-14_17-21-50](https://user-images.githubusercontent.com/9945237/33996998-00f0a708-e0f4-11e7-99df-03a87b6f3d38.png)
Or introduce switcher to show/hide retries on a timeline

#### Please tell us about your environment:

| Allure version | 2.4.1 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by simple-elf** [comment]
@rovner how you rerun failed tests? Surefire plugin option `rerunFailingTestsCount`?
I have same issue with this parameter.
First run is without retries:
![image](https://user-images.githubusercontent.com/668395/34297003-43f7d60e-e737-11e7-8655-597bafb24f6b.png)
Second run with `rerunFailingTestsCount=2`:
![image](https://user-images.githubusercontent.com/668395/34297036-71c072b2-e737-11e7-9b89-e24f0a1674fb.png)
By documentation 
> ... executes all test classes and re-runs failed tests afterwards.
So first it runs all tests in one class, and then rerun all failed test in that class

**Comment by simple-elf** [comment]
And with parallel and retries in surefire
```
<parallel>classes</parallel>
<threadCount>2</threadCount>
<forkCount>2</forkCount>
```
timeline looks like this
![image](https://user-images.githubusercontent.com/668395/34348574-806e7dba-ea2d-11e7-9120-312129a7678b.png)

**Comment by biski** [comment]
We run tests in loop for e.g. 8h and now, after migrating to allure2, we see only first run of each test. It is major invconvenience to us because we can't read  the timelime and learn when our environment starts to slow down or when the tests are failed. Could you add some parameter or change it to display all tests (with retries) as default behaviour?

**Comment by MatthewKr** [comment]
We also run our set of tests in loop for 72 hours to check stability of test environment, check memory leaks and deadlocks etc. In Allure 1.4 we could see all runs of each test on timeline tab. In Allure 2 it is not possible. Please do it ASAP.

**Comment by piotrekjaromin** [comment]
In my team, we use allure 1.4. This functionality for us is one of the basic. We launch dozens of iterations of tests every night and on weekends. It helps us to illustrate what has happened to the environment, during the tests. Without it, we are unable to update to the latest version. Please, could you fix it?
