### ISSUE TITLE
Allure Overview for matrix job shows 404

### ISSUE THREAD

**Issue by dimkin-eu** [allure-framework/allure2#702]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Overview pane shows 404 + some js errors

#### Please tell us about your environment:
Note older version of allure + new jenkins 
| Allure version | 2.4.0 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.0-BETA16 |
|allure jenkins  | 2.25.1 |

#### Other information 
```
app.js:24 jQuery.Deferred exception: Cannot read property 'total' of undefined TypeError: Cannot read property 'total' of undefined
    at https://qa-jenkins/job/blabla/119/allure/app.js:37:132264
    at Array.map (<anonymous>)
    at e.value (https://qa-jenkins/job/blabla/119/allure/app.js:37:132151)
    at e.value (https://qa-jenkins/job/blabla/119/allure/app.js:37:132362)
    at e.i (https://qa-jenkins/job/blabla/119/allure/app.js:1:3389)
    at a (https://qa-jenkins/job/blabla/119/allure/app.js:1:3599)
    at https://qa-jenkins/job/blabla/119/allure/app.js:1:3704
    at Function.x.each.x.forEach (https://qa-jenkins/job/blabla/119/allure/app.js:1:77230)
    at o (https://qa-jenkins/job/blabla/119/allure/app.js:1:3655)
    at e.p (https://qa-jenkins/job/blabla/119/allure/app.js:1:4066) undefined
```
```
app.js:37 Uncaught TypeError: Cannot read property 'total' of undefined
    at app.js:37
    at Array.map (<anonymous>)
    at e.value (app.js:37)
    at e.value (app.js:37)
    at app.js:24
(anonymous) @ app.js:37
value @ app.js:37
value @ app.js:37
(anonymous) @ app.js:24
```

![image](https://user-images.githubusercontent.com/7899764/34149655-736920ae-e4ae-11e7-8e3a-c55052b8e71f.png)

**Comment by vbragin** [comment]
@dimkin-eu This problem is a result of downgrading of allure cl version from 2.5.0.
The solution is to use cl 2.5.0

**Comment by vbragin** [comment]
@dimkin-eu Or you can remove all builds created with 2.5.0 and later builds and execute the job with 2.4.0 once again.

**Comment by AntonioEspinosa** [comment]
> @dimkin-eu Or you can remove all builds created with 2.5.0 and later builds and execute the job with 2.4.0 once again.

had the same issue running 2.13.3 but clearing the logs helped me go to the jenkins job folder jobs/yourjob/buils/
once in there delete all the builds folders after that restart your jenkins server like brew services restart jenkins and run your build again thumbs up for this reply thanks!
