### ISSUE TITLE
Random `Duration trend` color 

### ISSUE THREAD

**Issue by dimkin-eu** [allure-framework/allure2#707]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Duration trend color

#### What is the expected behavior?
Change bar color as build state - passed/failed or same color shema as regular trend has, with percentage of green/yellow/red tests

#### What is the motivation / use case for changing the behavior?
Currently not clear, why passed builds could have red Duration trend, but for analysis this could be helpful

#### Please tell us about your environment:

| Allure version | 2.5.0 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.0-BETA16 |

#### Other information 
![image](https://user-images.githubusercontent.com/7899764/34207441-225d7864-e593-11e7-96a3-272d5965f826.png)

**Comment by baev** [comment]
Closed as stale. Please create a GitHub discussion if the feature is still needed.
