### ISSUE TITLE
Pop-up flickers on a trend

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [allure-framework/allure2#708]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Pop-up on a trend flickers when moving the cursor up and down

![2017-12-20_16-14-54](https://user-images.githubusercontent.com/9446141/34208903-305158f6-e5a1-11e7-873e-322c05f86839.gif)

#### Please tell us about your environment:

Sample demo report Allure 2 https://ci.qameta.io/job/allure2/job/master/Demo_Report/index.html#graph
Chrome latest

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by symonk** [comment]
this is a common problem throughout, if you position the mouse on a number of tool tips it flickers like crazy, I will investigate this soon.  flaky tool tip for example, tooltip_bottom appears to add 2x <divs> and remove them insanely fast

**Comment by skhomuti** [comment]
This issue is fixed in #866
