### ISSUE TITLE
[BUG] Expanded and after hidden categories expand another time, when clicking on item

### ISSUE THREAD

**Issue by simple-elf** [allure-framework/allure2#709]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report

#### What is the current behavior?
Expanded and after hidden categories expand another time, when clicking on item
Works on Categories, Suites, Behavors and Packages tab.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
[VIDEO](https://monosnap.com/file/Gw5ppanFxj4sJLJlGB9yMup5G71S16) from [demo report on allure site](https://ci.qameta.io/job/allure2/job/master/Demo_Report/index.html)

#### What is the expected behavior?
Expanded and after hidden category don't expand one more time, then clickin on item in another category, until we click on this category again.

#### What is the motivation / use case for changing the behavior?
For example, I readin allure report of 300 tests using packages tab. I filtering result by status (only failed).
I open first category with failed test, Clicking on failed test to see error message on right panel.
Then I hide this category (unexpande), and going to another, click on it to see tests in category, and then clicking on test. It needed to filter test, that I allready seen and not seen yet.

#### Please tell us about your environment:

| Allure version | 2.4.1 (some older version still have this bug) |
| --- | --- |
| Browser | Chrome Desktop Windows 63.0.3239.84 (x64) - doesn't matter much |

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by simple-elf** [comment]
Looks like https://github.com/allure-framework/allure2/pull/639

**Comment by simple-elf** [comment]
Css class "node__expanded" applies not only for ".node" elements, but also to ".node__title". And then on restoreState() this categories also expanded. Also ".node__leaf" elements shouldn't have "node__expanded" class.

**Comment by simple-elf** [comment]
`.node__title` without class `.node__expanded` fixes like this
```
    restoreState() {
        this.$('[data-uid]').each((i, node) => {
            const el = this.$(node);
            const uid = el.data('uid');
            el.parent().toggleClass('node__expanded', this.state.has(uid)); // give class to parent
        });
        this.$('.node__title_active').parent('.node').toggleClass('node__expanded', true);
        this.$('.node__expanded').parent('.node').toggleClass('node__expanded', true);
    }
```

Also for last node (test method itself) we don't need to toggle class
```
    @on('click .node__title')
    onNodeClick(e) {
        const node = this.$(e.currentTarget);
        const uid = node.data('uid');
        this.changeState(uid, !this.state.has(uid));
        if (!node.parent().hasClass("node__leaf")) {
            node.parent().toggleClass('node__expanded');
        } else {
            node.parent().addClass('node__expanded');
        }
    }
```

But I can't find right way to fix all problems, because there is also some "database" for node states (`changeState` method)

**Comment by simple-elf** [comment]
All fixes should be in [TreeView.js](https://github.com/allure-framework/allure2/blob/master/allure-generator/src/main/javascript/components/tree/TreeView.js) file.

**Comment by simple-elf** [comment]
Summon @baev

**Comment by simple-elf** [comment]
Found some fun fact. If build allure-generator with `webpack --optimize-minimize` - then bug with giving class 'node__expanded' to wrong div ('.node__title') appers. But if build allure-generator without '--optimize-minimize` - then bug isn't appears.

**Comment by baranoff-ivan** [comment]
Duplicates #575

**Comment by simple-elf** [comment]
@baranoff-ivan ok, but i'm working on solution.
