### ISSUE TITLE
[Proposal] Excelsior Jet integration

### ISSUE THREAD

**Issue by etki** [allure-framework/allure2#712]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

Allure runs on top of JVM, which requires end-user to install it first; also, Allure execution has relatively short lifespan, which, i suppose, forces most of code to run in interpreter / c1 compiled level. While there is no mood killer in that, i believe that Allure can run much faster.

#### What is the expected behavior?

I've stumbled upon [Excelsior Jet](https://www.excelsiorjet.com/) software (which, i believe, is not the only of a kind). It claims to offer following benefits:

- AOT compilation
- Regular java execution for non-precompiled coed (which means that end users will still be able to develop and run their own java plugins)
- Single binary compilation
- Relatively small (relatively to jvm, i guess) binary size
- No fee for usage in OSS projects

While this is obviously huge change and yet-another-artifact-type support, this looks very friendly to end user (i regularly work with a full rainbow of programming languages, and adding several steps in pipeline just to install java is a common PITA), requires no money from supporting company and may dramatically speed up execution.

**Comment by baev** [comment]
Closed as stale. Please create a GitHub discussion if the feature is still needed.
