### ISSUE TITLE
Allure Report not generated If you execute around 1500 Testcase Suite,getting error eclipse heap memory insuficcient

### ISSUE THREAD

**Issue by vedantkhachne18** [allure-framework/allure2#716]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.0-BETA11 |
| Generate report using | allure-maven@2.18 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by vedantkhachne18** [comment]
Hi,
Please give me solution I have executed around 1500 testcase testsuite using maven but my allure report was not generated getting error eclipse heap memory insufficient, I have increase eclipse heap memory Max 30 GB but getting same error. If I run around 700 testsuite then it will work properly and generate allure report.
Please anyone help me.
Thanks in advanced!!!!

**Comment by cj-darius-lapunas** [comment]
Similar situation, we have >7000 test cases and it's running past 60GB of ram. Is there something we can do? We're using several attachments per test, but it doesn't look like reducing attachments helps.

**Comment by baev** [comment]
@cj-darius-lapunas, I suggest you open a new issue with all the details of your problem. Please ensure you're using the latest possible release of Allure since we have made some performance improvements lately. 

This issue is closed as stale.
