### ISSUE TITLE
Public test project using all Allure2 API and Demo report

### ISSUE THREAD

**Issue by netmajor** [allure-framework/allure2#722]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
No up to date demo report for Allure2
As I know from @symonk https://ci.qameta.io/job/allure2/job/master/Demo_Report/index.html is allure1 report

#### What is the expected behavior?
Public project with tests using all allure features, so users can compare demo report with code.
If new feature will new added, tests should be updated.

#### What is the motivation / use case for changing the behavior?
Now I see demo report but I don't know how to achieve that look.

#### Please tell us about your environment:

| Allure version | 2.5.0 |
| --- | --- |
| Test framework | mocha |

**Comment by symonk** [comment]
@netmajor https://ci.qameta.io/job/allure2/job/master/Demo_Report/index.html is an allure 2 report, I was referring to http://allure.qatools.ru/ when I said that looks like allure 1.

**Comment by baev** [comment]
Demo2 project: https://github.com/sskorol/allure2-testng-report , report: https://ci.qameta.io/job/allure2/job/master/Demo2_Report/ 

Also you can find many examples in https://github.com/allure-examples organization

**Comment by netmajor** [comment]
Unfortunately test project is not project using js test frameworks (mocha or jasmine) :/

**Comment by symonk** [comment]
@netmajor the end result is pretty much the same, the implementation obviously varies, here is a mocha example to aid with implementation => https://github.com/allure-examples/mocha-allure-example any questions and we are happy to help you

**Comment by netmajor** [comment]
I am implementing Allure API for wdio-allure-reporter. I need to compare output in allure-result when i use my implementation with original output to check if it works properly.

For example I see problem with Step API I start to implement in wdio-allure-reporter. It always creates nested steps but I run it like:
addStep('step' ()=>{});
addStep('step2',()=>{});
Maybe some errors in my implementation :/

**Comment by just-boris** [comment]
Tree structure represents the case when some steps were called from another step. A simple example in js

```js
const enterUsername = allure.createStep('enterUsername', () => /*implementation*/);
const enterPassword = allure.createStep('enterPassword', () => /*implementation*/);
const loginStep = allure.createStep('login', async () => {
   await enterUsername();
   await enterPassword();
});
```

It will produce you the following tree structure:

```
login
├──enterUsername
└──enterPassword
```
