### ISSUE TITLE
Allure2 should tell the difference between same Suite but run by other browsers

### ISSUE THREAD

**Issue by netmajor** [allure-framework/allure2#723]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
I am executing same tests but using two browsers using webdriverio. After tests I have in .allure-result two result files per browser, but allure generate report with only information for one test. What option should contains test result files that report show statistics for test per browser? I checked feature and environment but not work.
Maybe we need new feature ?

#### What is the expected behavior?
Report should tell the difference between same test run by two browsers

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | mocha@6.8 |
| Allure adaptor | wdio-allure-reporter |
| Generate report using | allure-commandline@2.5.0 |

**Comment by baev** [comment]
yeah, thats about https://github.com/allure-framework/allure2/issues/130

We should be able to enrich historyId key with some environment information. That is the issue I am working on at the moment

**Comment by baev** [comment]
closed as stale
