### ISSUE TITLE
Tip "Flaky test" is blinking when hover cursor from top/bottom to the bomb icon

### ISSUE THREAD

**Issue by aleksandr-kotlyar** [allure-framework/allure2#724]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report

#### Current behavior
Tip "Flaky test" is blinking when you move mouse cursor from the top or from the bottom to the 'bomb icon'.
Look on the GIF 
from the bottom: https://gyazo.com/34f8f55d5e005e8971703e202cc11a43
from the top: https://gyazo.com/fcc086bf7a1a0209ca1a59b3023bae82

#### Cases to reproduce
you need flaky test with bomb icon
CASE 1: move cursor to the bomb icon from the top
CASE 2: move cursor to the bomb icon from the bottom

#### Expected behavior
tip "Flaky test" should not blink

#### What is the motivation / use case for changing the behavior?
I think that nobody want to see epileptic report ;-) especially when their tests are flaky

#### Environment:

| Allure version | 2.5.0 |
| --- | --- |
| Test framework | junit@4.12 |
| Allure adaptor | allure-testng@2.0-BETA21 |
| Generate report using | allure-maven@2.21 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by symonk** [comment]
this is a more universal issue, a large majority of the generated ui flickers on hovering

**Comment by bop0hz** [comment]
Hi,
addition:
Test is flacky pops up everytime, when you hover the cursor right after test case name:
![screenshot from 2018-01-26 15 36 35](https://user-images.githubusercontent.com/690243/35440442-7880fe02-02b0-11e8-9a66-076677e4c8b8.png)

Allure 2.5.0

Thanks
