### ISSUE TITLE
attach block shifted in YaBro

### ISSUE THREAD

**Issue by ljql** [allure-framework/allure2#725]
```
$ allure --version
2.4.1
```
**browser:** YaBro=17.10.0.2052 (64-bit)

**case**:
1. Run pytest with allure (test code below):
```pytest --alluredir=allure mytest.py```
2. Generate report:
```allure generate allure/```
3. Start http-server to open report in YaBro\Chrome:
```http-server allure-report/```
4. Open test SUITES and expand the step with attach
_Expect:_ block with class="attachment-row" is in correct place
_Acltual:_ block is upper

**Screens:** https://yadi.sk/d/plkW7ehE3RXMpC
There are 3 screens: for YaBro, for Chrome=63 and FF=57

**Python code**
```
import pytest
import allure
import json

def attach(_name: str, _dict: dict):
    allure.attach(json.dumps(_dict, indent=4, sort_keys=True), _name)

@allure.step("{0}")
def attach_me(step_name, attach_name, dict):
    attach(attach_name, dict)

def test_test():
    dict = {"key1": "value1",
            "key2": "value2",
            "key3": "value3"}
    attach_me("Attach me", "ATTACH", dict)
```

```http-server``` was installed via
```npm install http-server -g```

**Comment by baev** [comment]
## Yandex
![yabro_allure_attach](https://user-images.githubusercontent.com/2149631/35044061-f5e87cca-fb9f-11e7-866d-4bd68f6abe86.jpg)

## Firefox
![ff_allure_attach](https://user-images.githubusercontent.com/2149631/35044063-f7c92652-fb9f-11e7-9d4c-dd7b70ba9bb5.jpg)

## Chrome 
![chrome_allure_attach](https://user-images.githubusercontent.com/2149631/35044065-f94dacaa-fb9f-11e7-96d3-1b410f7fa2d0.jpg)
