### ISSUE TITLE
Wrong test case page is shown when quickly clicking on tests

### ISSUE THREAD

**Issue by victor-homyakov** [allure-framework/allure2#729]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
When quickly clicking on two or more tests to show their test case page (https://docs.qameta.io/allure/#_test_case_page), requests for the previous not shown test case pages are not cancelled. Responses may arrive in any order depending on the backend speed. Therefore sometimes I see wrong test case page (not for last clicked test, but for some of previous ones).

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
1. User opens Allure with some test results, probably on a slow computer, to look at test case page for test T2
2. User occasionally clicks on the test T1 instead of T2
3. User instantly realizes their mistake and quickly clicks on the test T2 - there is a chance that Allure will show test case for T2 for a moment, and then replace it with the test case for T1 (the test user clicked first).

#### What is the expected behavior?
When user clicks on the next test, any pending requests for the previous ones should be cancelled/ignored.

#### What is the motivation / use case for changing the behavior?
See reproduction steps. There is a chance to see wrong test case when user clicks on test and previous requests are not finished yet (click on wrong test or slow network response).

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.0-BETA11 |
| Generate report using | allure-maven@2.18 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
closed as stale
