### ISSUE TITLE
Incorrect allure cucumber jvm plugin version specified in documentation

### ISSUE THREAD

**Issue by vvolverine** [allure-framework/allure2#731]
Documentation issue.
**Explanation**:
Official documentation that located by link below, in section Cucumber JVM
https://docs.qameta.io/allure/
asking to add next dependency to the project
```
    <dependency>
        <groupId>io.qameta.allure</groupId>
        <artifactId>allure-cucumber-jvm</artifactId>
        <version>LATEST_VERSION</version>
    </dependency>

```
Unfortunately this adapter utilize old version of cucumber(1.x) and this version doesn't work with new Cucumber JVM framework(version 2.x and upper).

Please modify documentation accordingly to support both version of Cucumber Framework(old, v1 and new v2.)

Right version that should be used with cucumber 2.x and up
```
<dependency>
    <groupId>io.qameta.allure</groupId>
    <artifactId>allure-cucumber2-jvm</artifactId>
    <version>2.0-BETA21</version>
</dependency>
```
Also plugin usage should be update from
`-Dcucumber.options="--plugin io.qameta.allure.cucumberjvm.AllureCucumberJvm"`
to
`-Dcucumber.options="--plugin io.qameta.allure.cucumber2jvm.AllureCucumber2Jvm"`

**Comment by baev** [comment]
fixed already
