### ISSUE TITLE
Failed step not expanded with errors

### ISSUE THREAD

**Issue by Quron** [allure-framework/allure2#732]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Failed step not expanded

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
![bda3af3112](https://user-images.githubusercontent.com/26869885/35474200-177ae720-039c-11e8-8628-d3d52ef9934d.png)

#### What is the expected behavior?
Failed step expanded with errors inside.
Its work on **allure 2.4.1**
![ce2ef7034c](https://user-images.githubusercontent.com/26869885/35474239-78bbcac2-039c-11e8-8105-ef64f6f11907.png)

#### Please tell us about your environment:

| Allure version | 2.5.0 |
| --- | --- |
| Test framework | pytest-3.3.2 |
| Allure adaptor | allure-pytest-2.3.1b1 |
| Generate report using | jenkins |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by Quron** [comment]
Its blocker for https://github.com/allure-framework/allure-python/pull/409

**Comment by baev** [comment]
already fixed
