### ISSUE TITLE
Environment on sidebar

### ISSUE THREAD

**Issue by maratori** [allure-framework/allure2#735]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

Now the environment widget is shown only on the overview page.

#### What is the expected behavior?

It would be great to have the same info on the left sidebar.

#### What is the motivation / use case for changing the behavior?

It is very useful to have a quick access to the environment info.
And it is even better to have it before your eyes always.

#### Implementation

The best place is left sidebar under navigation links.
It can be visible if sidebar is expanded. And it can be hidden if sidebar is collapsed.

#### Discussion

Please share your thoughts.
I could implement such functionality if people like this feature.

#### Draft

Below is just a draft to imagine how it can be. Style must be discussed.

![image](https://user-images.githubusercontent.com/16486128/35539652-8ccc5c66-0563-11e8-8747-4447bab47455.png)

#### Please tell us about your environment:

| Allure version | 2.5.0 |
| --- | --- |
| Test framework | junit@4 |
| Allure adaptor | allure-junit@2.0-BETA21 |
| Generate report using | allure-maven@2.9 |

**Comment by baev** [comment]
closed as stale
