### ISSUE TITLE
Allure report is counting before and after hooks in the # of tests for mocha webdriverio

### ISSUE THREAD

**Issue by himildesai** [allure-framework/allure2#737]
<img width="892" alt="screen shot 2018-01-30 at 3 37 24 pm" src="https://user-images.githubusercontent.com/3360150/35597476-81665bfe-05d3-11e8-9baa-a1e97981dd06.png">

**Comment by klamping** [comment]
This is probably better suited to be reported here: https://github.com/webdriverio/wdio-allure-reporter/issues
