### ISSUE TITLE
HistoryFileTest failed

### ISSUE THREAD

**Issue by sseliverstov** [allure-framework/allure2#74]
io.qameta.allure.history.HistoryFileTest > skipHistoryForTestCaseWithoutId FAILED
    java.lang.AssertionError at HistoryFileTest.java:57

**Comment by ehborisov** [comment]
issue is not reproducible on Ubuntu 16.04

**Comment by baev** [comment]
The issue is successfully reproduced on MacOS 10.12.3 and Windows 10
