### ISSUE TITLE
Add percentage to Status widget

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [allure-framework/allure2#742]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Status chart displays only percentage for passed test cases(in pie chart)

#### What is the expected behavior?
It'll be nice to display percentage for all statuses(for each status row)
![2018-02-05_13-49-48](https://user-images.githubusercontent.com/9446141/35801032-d91ce2f8-0a7b-11e8-8151-61b25b11bd55.png)

#### What is the motivation / use case for changing the behavior?
Having percentage added might be used as a short report of current run.

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.0-BETA11 |
| Generate report using | allure-maven@2.18 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by dalenguyen** [comment]
Do you know which file has the percentage number in the report folder? Thanks,

**Comment by baev** [comment]
closed as stale
