### ISSUE TITLE
After deleting allure-results and re running project - allure opens an empty web page 

### ISSUE THREAD

**Issue by saritanzu** [allure-framework/allure2#743]
#### I'm submitting a ... 
  - [ ] bug report

#### What is the current behavior?

Hi, yesterday I manually deleted from my projects folders all of the allure-results files. I re-run my project several times but when I init allure it opens an empty browser page, there are no errors in the command line. I noticed that by mistake I deleted the *xml file, I restored it and re run my project, still empty report. I tried reinstalling allure via brew command (I'm using mac) but it says that allure already install.

What can I do? any ideas? Im stuck without a reported
*I deleted all the allure- results file because I wanted 'a clean start' of data since all the failures that it showed were part of testing the test cases
Using webdriverio, chai, JS and node

#### Please tell us about your environment:
Webdriver io
| Allure version | 2.2.0 |
| --- | --- |
| Test framework | mocha |
| Allure adaptor | allure-testng@2.0-BETA11 | - do not know
| Generate report using | allure-npm |

**Comment by baev** [comment]
First pf all please do not spam your support request to all the places. Linked issue https://github.com/webdriverio/wdio-allure-reporter/issues/92

Use StackOverflow (tag allure) / our Gitter (you already posted the message to allure-core) for support requests.
