### ISSUE TITLE
Classname as a filename for sysoutput 

### ISSUE THREAD

**Issue by iskrich** [allure-framework/allure2#747]
Hi, I have one problem with attachment files in JUnit like reports
https://github.com/allure-framework/allure2/blob/11103d963551a5c68a34e30aac00acca434a04b6/plugins/junit-xml-plugin/src/main/java/io/qameta/allure/junitxml/JunitXmlPlugin.java#L101

From what I understand, JUnit plugin use classname of testcase, for searching file with potential system output or something else. But it can be difficult to resolve target file attachment, when several test cases use the same class.
Is there any way to resolve conflicts such this, with the use unique id for attachment?

**Comment by baev** [comment]
Nope, thats how JUnit-style XML report designed
