### ISSUE TITLE
Allure Report generation from (.TRX) files gives NullPointerException in Jenkins

### ISSUE THREAD

**Issue by premaram** [allure-framework/allure2#748]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Allure report generated from [,TRX] files give Null Pointer Exception after generating report.
at line t ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:308)

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
1. Set Up Allure command line in "Manage Jenkins"
2. Set the Post Build step to generate "Allure Report" from [.TRX files] output folder from VSTest

Below is the exception message from Jenkins
==============================
$ C:\allure-commandline\bin\allure.bat generate C:\Jenkins\workspace\Test_QA\TestOutput C:\Jenkins\workspace\Test_QA\TestOutput\history -c -o C:\Jenkins\workspace\Test_QA\allure-report
Report successfully generated to C:\Jenkins\workspace\Test_QA\allure-report
Allure report was successfully generated.
Creating artifact for the build.
Artifact was added to the build.
ERROR: Build step failed with exception
java.lang.NullPointerException
at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:308)
at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:223)
at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:735)
at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:676)
at hudson.model.Build$BuildExecution.post2(Build.java:186)
at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:621)
at hudson.model.Run.execute(Run.java:1760)
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
at hudson.model.ResourceController.execute(ResourceController.java:97)
at hudson.model.Executor.run(Executor.java:405)
Build step 'Allure Report' marked build as failure
Collecting metadata...
Metadata collection done.

#### What is the expected behavior?

The Jenkins build with Allure report generation should not throw any exception and should generate the report without any error
#### What is the motivation / use case for changing the behavior?
Handling exception in the Report generation code

#### Please tell us about your environment:

| Allure version | 2.6.0 |
| --- | --- |
| Generate report using | allure-TRXPlugin |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by premaram** [comment]
@baev @eroshenkoam Could you please look into this issue with TRX plugin?
@arpit-nagar Coud you share your experience with TRX files report generation?

**Comment by premaram** [comment]
Now with version 2.6, Allure Report generation results with UNSTABLE status...

C:\QA>exit 0 
[Fusion_TestHarness_QA] $ C:\allure-2.6.0\bin\allure.bat generate C:\QA\TestOutput-1 -c -o C:\_QA\allure-report
Report successfully generated to C:\QA\allure-report
Allure report was successfully generated.
Creating artifact for the build.
Artifact was added to the build.
Build step 'Allure Report' changed build result to UNSTABLE
Collecting metadata...
Metadata collection done.
Notifying upstream projects of job completion
[copy-to-slave] Copying 'TestOutput-1\*.trx', excluding nothing, from 'file:/C\QA/' on 'hudson.slaves.DumbSlave[Notebook]' to 'file:/var/lib/QA/' on the master.
Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
Triggering a new build of TestRail_Results_Reporting
Finished: UNSTABLE

**Comment by baev** [comment]
should be fixed by now
