### ISSUE TITLE
Suites page of Allure report from [.trx] files shows test cases and it is not grouped by Suites

### ISSUE THREAD

**Issue by premaram** [allure-framework/allure2#749]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [X] bug report
  - [X] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Source(@https://github.com/allure-framework/allure2/tree/master/plugins/trx-plugin/src)
Test Cases are showed as Test Suite. So, the count of test suites is same as the test cases count.

#### What is the expected behavior?
The test suite should be the test folder name which in this case is the (.TRX) File and the Test Cases should be the number of the test cases inside each such folder

#### What is the motivation / use case for changing the behavior?
Test Suite is the super set like Test folder which contains the Test cases.

#### Please tell us about your environment:

| Allure version | 2.6.0 |
| --- | --- |
Test framework | Microsoft VS test @5.0
| Generate report using | allure-TRXPlugin |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by abhinayabalaji** [comment]
Any update on this?
