### ISSUE TITLE
Allure swallows exception raised during failed attempt to create the result JSON file

### ISSUE THREAD

**Issue by kshepitko** [allure-framework/allure2#750]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

If Allure fails to create a JSON output file because of I/O problems with underlying file system, no error is being thrown, and no results JSON is generated.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Easy to reproduce with a Cucumber scenario, as in Cucumber test runner case Allure generates JSON file name from the feature name.

1. Create a Cucumber feature file with a feature description, which, being used as base for file name, will cause problems
For instance, create scenario with "Feature: this is a test of the following things: one, two, three" (note a colon in feature name)
2. Run feature with Cucumber JUnit test runner
3. io.qameta.allure.FileSystemResultsWriter fails on `Path file = outputDirectory.resolve(testResultName);`, since Windows won't allow you to create a file with a colon in the name
4. No errors anywhere, Allure test results just silently missing for this feature.

#### What is the expected behavior?

Exception is thrown and seen in test execution log.

#### What is the motivation / use case for changing the behavior?

It doesn't make any sense to swallow such errors, as it just hides the problem, and you need to debug the test execution to see what's wrong.

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | junit@4.12 |
| Allure adaptor | allure-cucumber-jvm@2.0-BETA18 |
| Generate report using | allure-maven@2.8 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
should be fixed in latest releases
