### ISSUE TITLE
Generate Allure report based on data from database

### ISSUE THREAD

**Issue by satish88** [allure-framework/allure2#757]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
 
  - [x ] feature request
 
#### What is the current behavior?
I can generate allure report from testng.xml but not from database objects

#### What is the expected behavior?
If we have test results stored in the database, it would be useful to make that database a source of allure report generator. It can show all executions reports as home page and then click on any execution fetch the report of all tests in that particular execution.

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.0-BETA11 |
| Generate report using | allure-maven@2.18 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by RedTea14** [comment]
I think this is a very useful feature. Any update on this?

**Comment by baev** [comment]
At the moment you have a possibility to create own reader (see https://docs.qameta.io/allure/#_allure_plugins_system for more details)

If you are looking for ready-to use solution, we can offer a few options for you:

* Allure Enterprise - our paid solution that stores all the results in database an provides analytics features and more - will be released in public soon, at the moment you can contact `qameta at yandex.ru` for demo
* Allure Hub - service that stores all the reports in S3 - planned to releases later this year

**Comment by jar145** [comment]
Has Allure Hub been released yet? I cannot seem to find any information about it. Thanks
