### ISSUE TITLE
Different Total Test Cases numbers on Overview and Behaviors tabs cause confusing situations

### ISSUE THREAD

**Issue by kovylin77** [allure-framework/allure2#760]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
- [x] feature request
- [ ] bug report
- [ ] support request

#### What is the current behavior?

Currently we have different **total** numbers at `Overview` tab and `Behaviors` when we mark some tests with 2 or more `@Feature` annotations, so total count at `Behaviors` tab is bigger than on `Overview`.

![image](https://user-images.githubusercontent.com/22563850/36947732-a2527d9c-1fd8-11e8-909b-0dd3a365afe0.png)

![image](https://user-images.githubusercontent.com/22563850/36947743-b4e5b67c-1fd8-11e8-9374-6b2e111b8c6c.png)

#### What is the expected behavior?

I want to have only one Total Test Cases counter on `Overview` tab or at least I want to have these two counter values to be equals to each other.

#### What is the motivation / use case for changing the behavior?
It causes unclear confusing situations, especially when someone from management without deep understanding why one counter is bigger than another looks into report.

#### Please tell us about your environment:

| Allure version | 2.6.0 |
| --- | --- |
| Test framework | testng@6.8 |
| Generate report using | allure-gradle@2.5 |

#### Other information 

Discussed this issue with @eroshenkoam on Selenium Camp '18 conference and he agreed that this issue definitely should be resolved.

**Comment by baev** [comment]
closed as stale
