### ISSUE TITLE
Generate Allure HTML report within tomcat

### ISSUE THREAD

**Issue by moshere** [allure-framework/allure2#764]
Hi,
I would like to generate Allure report from within Tomcat application.
How can I generate this files from pure java program?

thank you
Moshe

**Comment by baev** [comment]
I can recommend you to generate the report using commandline, store it somewhere (an example using S3), and then simply serve it using controller that streams content from file storage. 

Also you can use `allure-generator` dependency, but note that there is no stable API

**Comment by moshere** [comment]
Thank you

**Comment by baev** [comment]
@moshere can I close the issue?

**Comment by moshere** [comment]
Yes
