### ISSUE TITLE
The Environment should support attachments

### ISSUE THREAD

**Issue by jonozzz** [allure-framework/allure2#766]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [X] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Environment can only have string name/value pairs.

#### What is the expected behavior?
It should be possible to attach files (or any type of supported attachments) to Environment.

#### What is the motivation / use case for changing the behavior?
Sometimes it's useful to attach a full configuration file to describe the Environment the tests were run into.

#### Please tell us about your environment:

| Allure version | 2.6.0 |
| --- | --- |
| Test framework | pytest@3.5.0 |
| Allure adaptor | allure-python@latest |
| Generate report using | allure-maven@2.18 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
closed as stale
