### ISSUE TITLE
Failed scenario from Allure ScalaTest Adapter report xml dispalayed as passed in UI

### ISSUE THREAD

**Issue by SergeyGavrilin** [allure-framework/allure2#767]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

1.  I have a tests in ScalaTest like this:
`feature ("***")`
`scenario ("1 ***")`
`scenario ("2 ***")`
where scenario ("1 ***") always fail, and scenario ("2 ***") pass.

2.  Run it using sbt and generate xml report with Allure ScalaTest Adapter. In received xml report scenario ("1 ***") marked as failed, scenario ("2 ***") marked as passed.

3. Run 
`allure serve `
for allure-reports folder

Result: scenario ("1 ***") marked as passed in Suites list and all diagrams.

#### What is the expected behavior?
scenario ("1 ***") marked as failed in accordance with xml report.

#### What is the motivation / use case for changing the behavior?
This bug blocks using Allure ScalaTest Adapter (problem not repeated for Junit scala reporter)

#### Please tell us about your environment:

| Allure version | 2.6.0 [64bit] |
| --- | --- |
| Test framework | ScalaTest 3.0.5 |
| Allure adaptor | Allure ScalaTest Adapter 1.5.1 |
| Generate report using | sbt 0.13 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by vijayemmanuel** [comment]
Even I face the same issue. 
I use AllureReporter to generate the XML files. Strangely the XML file provides status as "passed" which is actually a failed testcase. 
This causes bad report visualization  created through Allure Report generator.
Following is the environment
Allure Adaptor for Scalatest (1.5.1)
Scalatest (3.0.4)
SBT(0.13.17)

**Comment by baev** [comment]
I can suggest you to use new Allure ScalaTest integration, the old one is not supported any more https://mvnrepository.com/artifact/io.qameta.allure/allure-scalatest

**Comment by vijayemmanuel** [comment]
Could let me know the Reporter class I need to use with the new Scalatest Adapter?
Previously it was   "ru.yandex.qatools.allure.scalatest.AllureReporter"

**Comment by baev** [comment]
`io.qameta.allure.scalatest.AllureScalatest`

https://github.com/allure-framework/allure-java/blob/master/allure-scalatest/src/main/scala/io/qameta/allure/scalatest/AllureScalatest.scala

**Comment by vijayemmanuel** [comment]
Thank you @baev. It works with the new reporter class. 
Hope you could update the  documentation in https://docs.qameta.io/allure/#_scalatest
