### ISSUE TITLE
Failed case run to terminate other case runs

### ISSUE THREAD

**Issue by reneliu2006** [allure-framework/allure2#768]
2018-03-28 16:13:14,623 INFO [core.BrowserEmulator] - Started BrowserEmulator
[ERROR] Tests run: 4, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 64.98 s <<< FAILURE! - in TestSuite
[ERROR] giftCard_Flow(cashier.ui_Flow_Test)  Time elapsed: 16.902 s  <<< FAILURE!
com.codeborne.selenide.ex.ElementShouldNot: 
Element should not exist {.comp-paginlist_loading}
Element: '<p class="comp-paginlist_loading">没有数据</p>'
	at cashier.ui_Flow_Test.giftCard_Flow(ui_Flow_Test.java:76)

[ERROR] giftCard_Flow(cashier.ui_Flow_Test)  Time elapsed: 16.905 s  <<< FAILURE!
io.qameta.allure.AllureResultsWriteException: Could not write Allure test result
Caused by: java.nio.channels.ClosedByInterruptException

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR] cashier.ui_Flow_Test.giftCard_Flow(cashier.ui_Flow_Test)
[ERROR]   Run 1: ui_Flow_Test.giftCard_Flow:76 Element should not exist {.comp-paginlist_loading}
Element: '<p class="comp-paginlist_loading">没有数据</p>'
[ERROR]   Run 2: ui_Flow_Test.giftCard_Flow » AllureResultsWrite Could not write Allure test re...
[INFO] 
[INFO] 
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[ERROR] There are test failures.

**Comment by baev** [comment]
fixed in latest allure versions
