### ISSUE TITLE
Report generator fails with exception if zulu timestamp

### ISSUE THREAD

**Issue by akranga** [allure-framework/allure2#769]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
JUnit Report generator fails with ParseException if it tries to process zulu timestamp: `timestamp="2018-03-28T15:04:55Z"`.

#### Steps to reprocue
1. Create this file
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="test_all.x" errors="0" failures="0" tests="29319784" hostname="tbd" time="2.03698" timestamp="2018-03-28T15:04:55Z">
    <system-out/>
    <system-err/>
  </testsuite>
</testsuites>
```
2. Try to generate report with CLI
3. See the error

#### What is the expected behavior?
JUnit report generator should detect Zulu time format and should use: `DateTimeFormatter.ISO_DATE_TIME`
#### What is the motivation / use case for changing the behavior?
Zulu (utc) timestamp is common widely used. Different of tools can (like Catch2 for C++) can export their test results into this format, which is well understood by Jenkins (for instance) however not respected by Allure.

#### Environment:
| Allure version | 2.6.0 |

**Comment by akranga** [comment]
I can create a PR if needed

**Comment by baev** [comment]
> I can create a PR if needed

sounds good to me

**Comment by akranga** [comment]
Is it possible if somebody would take a look at the PR #789? Happy to d follow ups if needed
