### ISSUE TITLE
Gherkin tables

### ISSUE THREAD

**Issue by sseliverstov** [allure-framework/allure2#77]

**Comment by ehborisov** [comment]
There is a cucumber json format reader plugin in Allure 2.

so given a feature like

Feature: Test allure English

  Scenario: Test multiply
    Given first digit 5
    And second digit 5
    When I multiply it
    Then sum is 10

  Scenario Outline: Two digits multiply
    Given first digit <first>
    And second digit <second>
    When I multiply it
    Then sum is <sum>

    Examples: 
      | first  | second | sum   |
      | 6      | 6      | 12    |
      | 5      | 10     | 15    |

you have just to add json output formatter option to cucumber

and then serving resulting .json report file gives you a separate test case in allure report for each row of the table:
![cucumber](https://cloud.githubusercontent.com/assets/8182975/22646823/5c8e8112-ec7f-11e6-8d85-781dfda3e997.png)
