### ISSUE TITLE
No stack trace without message attribute in JUnit xml file

### ISSUE THREAD

**Issue by VladimirMiller** [allure-framework/allure2#770]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

Allure report generated using JUnit XML plugin from a file without "message" attribute in "failure" tag does not provide any opportunities to expand stack trace.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

1. Generate report using JUnit XML plugin (allure generate xmlReportsFolder).
2. Open report.
3. Check block with stacktrace: 

![actual](https://user-images.githubusercontent.com/24372954/38089754-32ecdb60-3369-11e8-8182-a77e2f67c2e6.PNG)

XML example:
[TEST-withoutMessage.xml](https://github.com/allure-framework/allure2/files/1860110/TEST-without.Message.txt)

#### What is the expected behavior?
Some opportunity to see a stack trace. 

Something like this (without failure message ofc):  
![expected](https://user-images.githubusercontent.com/24372954/38089914-a185dc20-3369-11e8-97e6-bac0ecb1d0e4.PNG)

XML example:
[TEST-withMessage.xml](https://github.com/allure-framework/allure2/files/1860101/TEST-withMessage.txt)

#### What is the motivation / use case for changing the behavior?
This kind of XML reports is generated by instrumentation tests in Android. And it's not depending on how tests are written.

#### Please tell us about your environment:

| Allure version | 2.6.0 |
| --- | --- |
| Test framework | junit@4.12 |
| Allure adaptor | - |
| Generate report using | cmd |

#### Other information 
I guess that this bug may be fixed by adding some default value for a message field in JUnit plugin.

Generated json for failed test:
[allure-report/data/test-cases/failedTest.json](https://github.com/allure-framework/allure2/files/1860158/failedTest.txt)

**Comment by mkj28** [comment]
Seeing the same for GO.

**Comment by Vizo77** [comment]
The same problem!!!
