### ISSUE TITLE
NoSuchElementException in getCurrentStep() method during parallel run

### ISSUE THREAD

**Issue by nemec8g** [allure-framework/allure2#772]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [* ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
During parallel run about 50-70 threads using testNg mechanism i faced that sometimes method which annotated with @Step threw NoSuchElementException

`java.util.NoSuchElementException
at java.util.LinkedList.getFirst(LinkedList.java:244)
at io.qameta.allure.internal.AllureStorage.getCurrentStep(AllureStorage.java:37)
at io.qameta.allure.AllureLifecycle.startStep(AllureLifecycle.java:203)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:49)`

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Allure threw NoSuchElementException in
 `public Optional<String> getCurrentStep() { final LinkedList<String> uids = currentStepContext.get(); return uids.isEmpty() ? Optional.empty() : Optional.of(uids.getFirst());` 

so i think this method should be synchronized

#### Please tell us about your environment:

| Allure version | 2.4.1 |
| --- | --- |
| Test framework | testng@6.9.10 |
| Allure adaptor | allure-testng@2.6.0 |
| Generate report using | allure-gradle@2.5 |

#### Other information 
[//]:  # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by bwolfe** [comment]
Adding my vote for fixing this.  

I ran into this in the same place when running multiple threads based on selenide.

**Comment by bwolfe** [comment]
This ticket should be in the allure-java repo

**Comment by bolshanetsky** [comment]
I see this problem regularly.

**Comment by aTan-aka-Xellos** [comment]
Adding my vote for fixing this.

**Comment by ihorvantukh** [comment]
My vote for fixing this.

**Comment by baev** [comment]
The issue should be fixed in latest allure-java release.
