### ISSUE TITLE
Message and stack trace no more showing for steps

### ISSUE THREAD

**Issue by bool-rus** [allure-framework/allure2#774]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

1. go to the demo: https://ci.qameta.in/job/allure2/job/master/Demo2_Report/
2. go to the test-case "shouldFailOnAssertionSubStep" -> test body -> handle on error popup -> check if element is displayed
3. i can open the red arrow, but nothing happens

#### What is the expected behavior?
on step 3 i can review the error message and stack trace

#### Please tell us about your environment:
it's your demo:
https://ci.qameta.in/job/allure2/job/master/Demo2_Report/

#### Other information
check the commit f0ea3956ecdfd55f2dacbdffc025f7909816c280, it's probably cause

**Comment by MohamedAsan** [comment]
This commit https://github.com/allure-framework/allure2/commit/bdf05a88f92746a71c2f16a5f44edad5ecd018f2  could be the cause. It works with this commit https://github.com/allure-framework/allure2/commit/4578c6672d71b66b1650db639785afba381c7368
