### ISSUE TITLE
Annotation Description, "useJavaDoc=true" do not working

### ISSUE THREAD

**Issue by dm-test** [allure-framework/allure2#778]
#### I'm submitting a ... 
  - [*] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
The "use Java Doc=true" parameter does not work correctly. In allure-junit 4, allure-unit 5 adapters annotation with such parameter is ignored (javaDoc text is not displayed in html-report), in allure-testng adapter problems with javaDoc with Russian text (encoding!)

#### Please tell us about your environment:

| Allure version | 2.6.0 |
| --- | --- |
| Test framework | testng@6.14.2 |
| Allure adaptor | allure-testng@2.6.0 |
| Generate report using | allure-maven@2.9 |

| Allure version | 2.6.0 |
| --- | --- |
| Test framework | junit@4.12 |
| Allure adaptor | allure-junit4@2.6.0 |
| Generate report using | allure-maven@2.9 |

| Allure version | 2.6.0 |
| --- | --- |
| Test framework | junit-jupiter-engine@5.1.0 |
| Allure adaptor | allure-junit5@2.6.0 |
| Generate report using | allure-maven@2.9 |

**Comment by occupant23** [comment]
I use the same versions for jUnit as mentioned above and found that the annotation is not working at all at the moment. While the data of other annotations is visible in the JSON file the Description annotation in not included within the file.
