### ISSUE TITLE
allure generate duplicate result 

### ISSUE THREAD

**Issue by 8dspaces** [allure-framework/allure2#780]
i am using allure+testng+gradle to run my test 
test result will include four json file and one xml file after every run

i try to generate report based the result, it always generate duplicate result 
if i manually delete the xml file and generate again, it will works 

could you help check how should i fix this ?

include gradle config 

apply plugin: 'io.qameta.allure'

allure {
    version = '2.6.0'
    autoconfigure = true

    reportDir = file("$rootDir/target/allure-report")
    resultsDir = file("$rootDir/target/allure-results")

    useTestNG (){
        version = '2.6.0'
        spiOff = true

    }
}

test {

    useTestNG(){
        include "GoogleTest.*"
    }

}

[allure-results.zip](https://github.com/allure-framework/allure2/files/1922061/allure-results.zip)

**Comment by baev** [comment]
make sure you have no `allure-testng-adaptor` dependency, thats probably it.

**Comment by 8dspaces** [comment]
It's awesome, it works. it confuse me for several days, thanks so much @baev
