### ISSUE TITLE
trouble with opening attachments

### ISSUE THREAD

**Issue by taraska** [allure-framework/allure2#783]
[Description]
Hello guys, we use the allure in our project and right now have a big trouble. In the picture you can see our small plugin, but it works only with uncountable creation tree on a server side java. So when we use same attachments for our tests with same ids we can see the next logic: "i try open attachment in middle of test body, but it opens in a head of content." I think that many companyes can use same attachments in one test. Can you fix it? Thx 
![bug](https://user-images.githubusercontent.com/12978941/39050743-26862b18-44af-11e8-80f4-4c8a7a4782a4.png)

**Comment by baev** [comment]
> So when we use same attachments for our tests with same ids

Attachment id should be unique in order to not get such trouble. How are you getting this?

**Comment by taraska** [comment]
We create an attachment by the package io.qameta.allure.model;
after we put it into a class StepResult by the same package (using method withAttachments())
i saw that the attachment of io.qameta.allure.entity has uid, maybe is it need add into class io.qameta.allure.model.Attachment too? Thx

**Comment by baev** [comment]
closed due to no response
