### ISSUE TITLE
Do it have a plan to support golang language?

### ISSUE THREAD

**Issue by shadow1163** [allure-framework/allure2#784]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the expected behavior?
Golang unit test need to run command "go test -v", its output just text format like this:
go test -v
=== RUN TestHello
--- PASS: TestHello (0.00s)
=== RUN ExampleHello
--- PASS: ExampleHello (0.00s)
PASS
ok  hello 0.006s

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.0-BETA11 |
| Generate report using | allure-maven@2.18 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
it would be awesome to add support for go testing package, but at the moment we have no clients that require it. So you can contribute such integration (that would be really appreciated) or consider sponsoring it

**Comment by Ubermensch01** [comment]
@baev, @shadow1163, check out our Allure adaptor for Golang on https://github.com/dailymotion/allure-go!

**Comment by shadow1163** [comment]
@Ubermensch01 I have tried to use module, appreciate your effort.

**Comment by Ubermensch01** [comment]
@shadow1163, we're actively working on getting the port up to par with other language ports and would appreciate you submitting issues too. :)

**Comment by baev** [comment]
https://github.com/ozontech/allure-go
