### ISSUE TITLE
Allure Report - showing failed test cases as passed in LINUX - Jenkins_Allure Plugin

### ISSUE THREAD

**Issue by senthilkumar369** [allure-framework/allure2#785]
Hi,

I ran my test using on Jenkins. Allure report got generated unfortunately it is showing failed test cases as passed also not showing stack trace of the steps. I am using Python Behave BDD.

Step 2 got failed but the test case showing as passed also not stack trace when i select the failed step (step2)

![image](https://user-images.githubusercontent.com/26564112/39345560-4081f7a2-4a3d-11e8-980c-093245e7a728.png)

**Comment by Nabawy90** [comment]
![screen shot 2018-05-01 at 13 39 02](https://user-images.githubusercontent.com/33811382/39473102-158281c4-4d45-11e8-9475-5c8994b75201.png)


I'm confirming this issue, I'm using Behave with Python as well but on a local Mac PC not linked to any CI

My environment is 


Allure version | 2.6.0
Test framework | behave 1.2.6
Python | 2.7

running & generation 

behave -f allure_behave.formatter:AllureFormatter -o ./allure_results/
allure serve-o ./allure_results/

This issue shall be linked to issue https://github.com/allure-framework/allure2/issues/787

**Comment by andreybehalf** [comment]
+1 
A deeper investigation shows that if the first step is broken/failed the json "summed" status will be marked properly but if steps other than the first one is marked broken/failed the "summed" status will be "passed".
I am attaching 2 JSON files that generated by the AllureFormatter. This 2 JSONs are for the same Scenario that I "forced" to fail. Once on the 1st step and the 2nd one on the 5th step.

1st JSON with **1st** failed step. Overall status is "broken".
`{
  "status": "broken",
  "name": "Customer with in review submitted payment, risk manually approve the payment, result - reaches payment confirmation page + paymentStatus=submmitted",
  "labels": [
    {
      "name": "tag",
      "value": "main_flows_priority-1"
    },
    {
      "name": "severity",
      "value": "normal"
    },
    {
      "name": "feature",
      "value": "BPI-2 customer submit payment"
    },
    {
      "name": "framework",
      "value": "behave"
    },
    {
      "name": "language",
      "value": "cpython2"
    }
  ],
  "stop": 1531309596336,
  "historyId": "54a52c317c9123e0286bca4bd2078089",
  "start": 1531309596327,
  "steps": [
    {
      "status": "broken",
      "start": 1531309596331,
      "stop": 1531309596331,
      "name": "Given vendor certified with payout method AC",
      "statusDetails": {
        "message": "\nYou can implement step definitions for undefined steps with these snippets:\n\n@given(u'vendor certified with payout method AC')\ndef step_impl(context):\n    raise NotImplementedError(u'STEP: Given vendor certified with payout method AC')\n\n"
      }
    },
    {
      "status": "skipped",
      "start": 1531309596336,
      "stop": 1531309596336,
      "name": "And customer ready for trx - approved with verified bank"
    },
    {
      "status": "skipped",
      "start": 1531309596336,
      "stop": 1531309596336,
      "name": "And potential transaction created"
    },
    {
      "status": "skipped",
      "start": 1531309596336,
      "stop": 1531309596336,
      "name": "And transaction expected checkpoint result is Review"
    },
    {
      "status": "skipped",
      "start": 1531309596336,
      "stop": 1531309596336,
      "name": "And transaction number 0 created by customer to vendor"
    },
    {
      "status": "skipped",
      "start": 1531309596336,
      "stop": 1531309596336,
      "name": "And transaction submitted by customer"
    },
    {
      "status": "skipped",
      "start": 1531309596336,
      "stop": 1531309596336,
      "name": "And transaction expected checkpoint result is Approved"
    },
    {
      "status": "skipped",
      "start": 1531309596336,
      "stop": 1531309596336,
      "name": "Then transaction has field Application_Status__c equal to Submitted"
    }
  ],
  "statusDetails": {
    "message": "\nYou can implement step definitions for undefined steps with these snippets:\n\n@given(u'vendor certified with payout method AC')\ndef step_impl(context):\n    raise NotImplementedError(u'STEP: Given vendor certified with payout method AC')\n\n"
  },
  "uuid": "d8182421-4c02-45ea-a8fa-d8978b46cd0e"
}`

2nd JSON with **7th** failed step. Overall status is "passed".
`{
  "status": "passed",
  "name": "Customer with in review submitted payment, risk manually approve the payment, result - reaches payment confirmation page + paymentStatus=submmitted",
  "labels": [
    {
      "name": "tag",
      "value": "main_flows_priority-1"
    },
    {
      "name": "severity",
      "value": "normal"
    },
    {
      "name": "feature",
      "value": "BPI-2 customer submit payment"
    },
    {
      "name": "framework",
      "value": "behave"
    },
    {
      "name": "language",
      "value": "cpython2"
    }
  ],
  "stop": 1531309826494,
  "historyId": "54a52c317c9123e0286bca4bd2078089",
  "start": 1531309656756,
  "steps": [
    {
      "status": "passed",
      "start": 1531309656759,
      "stop": 1531309772175,
      "name": "Given vendor certified with payout method ACH",
      "attachments": [
        {
          "source": "ba899f4a-9ab2-4b77-9047-3ac3f79354a4-attachment.txt",
          "type": "text/plain",
          "name": "Vendor Created In Scenario"
        }
      ]
    },
    {
      "status": "passed",
      "start": 1531309772176,
      "stop": 1531309809777,
      "name": "And customer ready for trx - approved with verified bank",
      "attachments": [
        {
          "source": "97b8407e-0cef-4f9c-920e-261cecfdd12f-attachment.txt",
          "type": "text/plain",
          "name": "Customer Created In Scenario"
        }
      ]
    },
    {
      "status": "passed",
      "start": 1531309809778,
      "stop": 1531309809779,
      "name": "And potential transaction created"
    },
    {
      "status": "passed",
      "start": 1531309809779,
      "stop": 1531309809925,
      "name": "And transaction expected checkpoint result is Review"
    },
    {
      "status": "passed",
      "start": 1531309809926,
      "stop": 1531309817416,
      "name": "And transaction number 0 created by customer to vendor"
    },
    {
      "status": "passed",
      "start": 1531309817417,
      "stop": 1531309826491,
      "name": "And transaction submitted by customer"
    },
    {
      "status": "broken",
      "start": 1531309826493,
      "stop": 1531309826493,
      "name": "And transaction expected checkpoint result is Approve",
      "statusDetails": {
        "message": "\nYou can implement step definitions for undefined steps with these snippets:\n\n@given(u'transaction expected checkpoint result is Approve')\ndef step_impl(context):\n    raise NotImplementedError(u'STEP: Given transaction expected checkpoint result is Approve')\n\n"
      }
    },
    {
      "status": "skipped",
      "start": 1531309826494,
      "stop": 1531309826494,
      "name": "Then transaction has field Application_Status__c equal to Submitted"
    }
  ],
  "uuid": "94c8fdc2-9013-460b-bc16-406d06d1ee29"
}`

**Comment by andreybehalf** [comment]
It is fixed in allure-behave==2.6.0
upgrade it

**Comment by sseliverstov** [comment]
@andreybehalf do you mean 2.5.0?

**Comment by andreybehalf** [comment]
Yes! Sorry :)

**Comment by subbro** [comment]
I am using allure-behave 2.8.18 and still find this issue of step being passed though failed/skipped in python
