### ISSUE TITLE
Is it possible set Feature via AllureListener?

### ISSUE THREAD

**Issue by shynkevich-alex** [allure-framework/allure2#788]
I run one test several times and I just change name of it and parameter.
Can I use AllureLifeSycle (AllureListener) to set Feature for test?

If yes how can I do it?

**Comment by baev** [comment]
Please use SO/our gitter chat for such type of questions.

PS

```java
Allure.getLifecycle().updateTestCase(tr -> tr.getLabels().add(new Label().setName("feature").setValue(someValue)));
```
