### ISSUE TITLE
Add documentation for Kotest support for Allure

### ISSUE THREAD

**Issue by sksamuel** [allure-framework/allure2#792]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

KotlinTest has provided allure support since version 3.0.0.
https://github.com/kotlintest/kotlintest/tree/master/kotlintest-extensions/kotlintest-extensions-allure

Allure has integration guides for the other frameworks supported and I would be happy to work with you to update the documentation for Allure for Kotlin.

**Comment by baev** [comment]
@sksamuel 👍 

The docs repo https://github.com/allure-framework/allure-docs . Provide a pull request and I'll happy to merge it!

**Comment by sksamuel** [comment]
Great, I'll write that up over the next several days.

**Comment by zaz600** [comment]
any news?

**Comment by sksamuel** [comment]
Only took me 2 years but here we go :joy: 
https://github.com/allure-framework/allure-docs/pull/125
