### ISSUE TITLE
Why allure2 did not have TestCaseId ?

### ISSUE THREAD

**Issue by lovesunshine** [allure-framework/allure2#793]
I want to add testCaseId into report, but I can not find this annotation in allure2. Can someone tell me
how to attach this to the report . Thank you !

environment:
Allure version: 2.6.0
Test framework: testng@6.14.3
Allure adaptor: allure-testng@2.6.0
Generate report using: allure-maven@2.9

**Comment by symonk** [comment]
@TmsLink("test-1")
@Issue("123")

**Comment by lovesunshine** [comment]
@symonk Thank you very much. I didn't understand the meaning of @tmslink and @issue thoroughly before. and now I got it and thank you.
