### ISSUE TITLE
gradle.properties version in master branch is 2.3-SNAPSHOT 

### ISSUE THREAD

**Issue by twigs** [allure-framework/allure2#797]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
the gradle.properties in the master branch list a version of 2.3-SNAPSHOT.
allure2 2.6.0 has been released 

#### What is the expected behavior?
the version in gradle.properties should be set to 2.6-SNAPSHOT or 2.7-SNAPSHOT not entirely sure which.

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
fixed via https://github.com/allure-framework/allure2/commit/53f8e5843d2fb696eb66650764a1a562ade21d5a
