### ISSUE TITLE
Bad SSL Cert for demo report

### ISSUE THREAD

**Issue by biltongza** [allure-framework/allure2#799]
I'm trying to have a look at the demo report from the docs linked in https://docs.qameta.io/allure/, but the link there points to https://ci.qameta.in/job/allure2/job/master/Demo2_Report/ where the SSL cert for that site is only valid for ci.qameta.io. Firefox let me add an exception but my company's firewall is blocking it.

**Comment by baev** [comment]
demo is now located at https://demo.qameta.io/allure/
