### ISSUE TITLE
Feature request: Configuration for date display is MM/DD/YYYY

### ISSUE THREAD

**Issue by osmolyar** [allure-framework/allure2#801]
#### I'm submitting a ... 
  - [ ] bug report
  - [ x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
-Current behavior:  Date in DD/MM/YYYY

#### What is the expected behavior?
-Would like to have a configuration flag to allow date in MM/DD/YYYY

#### What is the motivation / use case for changing the behavior?
-Standard US date format

#### Please tell us about your environment:

| Allure version | 3.6.0 |
| --- | --- |
| Test framework | webdriverio|
| Allure adaptor | |
| Generate report using | Allure Jenkins plugin |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by aljcalandra** [comment]
As another user I'd prefer ISO 8601 standard.

**Comment by just-boris** [comment]
FYI, the code `new Intl.DateTimeFormat().format(new Date())` prints the current date with respect to user's OS settings. Works in all browsers starting from IE11.

This can be a good point to submit a pull-request.

**Comment by osmolyar** [comment]
@just-boris , are you suggesting making this modification in the allure2 code base and making a pull request?  (If so could you please help point to the general area to look in?)

**Comment by just-boris** [comment]
Oh, well, the change was actually very small (thanks the proper code structure), so I have submitted a change myself: #808
