### ISSUE TITLE
Feature request:  Option to not automatically delete old results in allure-reports with Allure Jenkins plugin

### ISSUE THREAD

**Issue by osmolyar** [allure-framework/allure2#802]
#### Current behavior
-No option to not delete prior results in report directory with Allure Jenkins plugin

#### What is the expected behavior?
-Would like to have option to overwrite when rerunning but not automatically clean all files in allure-reports directory when running Jenkins Allure plugin

#### What is the motivation / use case for changing the behavior?
-My tests don't run when triggered by Jenkins for some reason, so currently running them via batch scripts after each Jenkins build; Allure reports are also generated by Batch script.   However each Jenkins run automatically deletes all reports hence the Allure links hosted by Jenkins are empty, even though run on the same build generates an Allure report.  Looking for a way to link up the generated Allure reports to be hosted in Jenkins.

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.0-BETA11 |
| Generate report using | allure-maven@2.18 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by AlexanderPoleschuk** [comment]
What's the point of this issue?
What do you mean by saying "prior results in report directory"?
Your results should be stored in "target folder" of the project and allure has nothing to manage this folder.
If you use 'mvn clean test' command, then you delete the results of previous run using 'clean' parameter.

**Comment by symonk** [comment]
the jenkins plugin will correlate history data for you, when running locally the problem is mvn clean will wipe out the /target directory, and even if it doesn't you won't be generating any history data there.

**Comment by baev** [comment]
not an issue
