### ISSUE TITLE
allure cannot generate report if path contains folder with whitespaces

### ISSUE THREAD

**Issue by Sup3rGeo** [allure-framework/allure2#806]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Allure fails to generate report if path to results folder contains whitespaces

![image](https://user-images.githubusercontent.com/20566367/41491862-f63b2e78-70d1-11e8-8bc2-42687840262e.png)

#### Please tell us about your environment:

| Allure version | 2.6.0 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
Could you please specify the full command you running
