### ISSUE TITLE
Cant debug in IntelliJ with Allure2 and aspectj in my pom.xml

### ISSUE THREAD

**Issue by breinjhel** [allure-framework/allure2#809]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Not sure if this is where I should post this but right now when I try to debug my code using IntelliJ with Allure and aspectj enabled Im getting 'this is not available' in debugger window when I try to evaluate a piece of code. If I remove the aspectj related stuff in pom.xml then debugging works fine

#### What is the expected behavior?
I should be able to debug even with Allure and aspectj in pom.xml

#### Please tell us about your environment:

| Allure version | 2.6.0 |
| --- | --- |
| Test framework | junit@4.12 |
| Allure adaptor | allure-junit4@2.6.0 |
| Generate report using | allure-maven@2.6.0 |
| AspectJ version | 1.9.1 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by breinjhel** [comment]
This is the part in pom.xml I had to comment out so that I can debug in intellij

`<?xml version="1.0" encoding="UTF-8"?>
<plugin>
   <artifactId>maven-failsafe-plugin</artifactId>
   <version>2.18</version>
   <configuration>
      <systemProperties>
         <property>
            <name>allure.results.directory</name>
            <value>${project.build.directory}/allure-results</value>
         </property>
         <property>
            <name>allure.link.issue.pattern</name>
            <value>https://example.org/issue/{}</value>
         </property>
      </systemProperties>
      <argLine>-javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"</argLine>
      <properties>
         <property>
            <name>listener</name>
            <value>io.qameta.allure.junit4.AllureJunit4</value>
         </property>
      </properties>
      <includes>
         <include>**/*Test.java</include>
         <include>**/When*.java</include>
         <include>**/*Section.java</include>
      </includes>
      <excludes>
         <exclude>**/*IntegrationTest.java</exclude>
      </excludes>
      <reuseForks>true</reuseForks>
      <systemPropertyVariables>
         <geb.build.reportsDir>target/test-reports/geb</geb.build.reportsDir>
      </systemPropertyVariables>
   </configuration>
   <dependencies>
      <dependency>
         <groupId>org.aspectj</groupId>
         <artifactId>aspectjweaver</artifactId>
         <version>${aspectj.version}</version>
      </dependency>
   </dependencies>
   <executions>
      <execution>
         <goals>
            <goal>integration-test</goal>
            <goal>verify</goal>
         </goals>
      </execution>
   </executions>
</plugin>`

**Comment by breinjhel** [comment]
This happens only when debugging inside the @Step methods

**Comment by simple-elf** [comment]
@breinjhel this happen, because then you run junit tests from IntelliJ IDEA allure junit4 listener is not connected.
But with testng there is no such problem.

My solution is maven profile, that active ONLY then you run test localy from IntelliJ IDEA
`https://github.com/simple-elf/selenoid-video-allure/blob/master/junit4/pom.xml`
```
<profiles>
        <profile>
            <id>junit4-aspect</id>
            <activation>
                <!--https://stackoverflow.com/questions/24760387/activate-certain-maven-profile-in-intellij-idea-only-->
                <property>
                    <name>idea.maven.embedder.version</name>
                </property>
                <!--<property><name>idea.version</name></property>-->
            </activation>
            <dependencies>
                <dependency>
                    <groupId>io.qameta.allure</groupId>
                    <artifactId>allure-junit4-aspect</artifactId>
                    <version>${allure.version}</version>
                    <scope>test</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>io.qameta.allure</groupId>
                            <artifactId>allure-junit4</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>com.google.guava</groupId>
                            <artifactId>guava</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
            </dependencies>
        </profile>
    </profiles>
```

**Comment by breinjhel** [comment]
@simple-elf I tried doing that but still cant debug/evaluate codes in intellij. Im using the intellij test runner though i run it from intellij not maven so maybe thats why ?

**Comment by breinjhel** [comment]
@simple-elf And also can I ask what allure-junit4-aspect is for? Wont the report generate without that just fine?

**Comment by baev** [comment]
closing because this is not an Allure issue
