### ISSUE TITLE
Documentation site returns with a 404 error.

### ISSUE THREAD

**Issue by number33** [allure-framework/allure2#812]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
The readme has a link to a documentation page https://docs.qameta.io/allure/2.0/, however the page is returning with a 404 error.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Go to https://docs.qameta.io/allure/2.0/

#### What is the expected behavior?
Page should load and display documenation

#### What is the motivation / use case for changing the behavior?
I would like to know more about trends graph and how to interpret it.

#### Please tell us about your environment:
Chrome and FF.

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.0-BETA11 |
| Generate report using | allure-maven@2.18 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
@number33 docs are moved to https://docs.qameta.io/allure/

PS redirect added
