### ISSUE TITLE
Allure for Bamboo plugin shows test case count mismatch

### ISSUE THREAD

**Issue by ranjithantham** [allure-framework/allure2#814]
Hi,
we are using same test case for multiple users to execute. when we do this allure plugin in bamboo shows incorrect match. we are executing the same test for multiple testng suites for multiple users
Ex: Test1 is the test case we are running this for multiple users say user1 and user2. so technically we are expecting 2 test cases in the allure reports in bamboo. but it showing as 1 testcase.  can we know how to fix this and how it's extracting and what fields it's considering while plugin extracting the multiple xml files from target/allure-results  - please need help on this.

**Comment by baev** [comment]
probably you got your test cases merged to retries (open test case page and navigate to `retries` tab). In order to fix the problem you need to add parameters (user in your case) to test case.

**Comment by ranjithantham** [comment]
Thanks you very much for your response. please can you tell me exactly what kind of parameter do i need to add at my test case level.  is it annotation !example of my test case below.  much appreciated your help on this - Thanks

  @Test(enabled = true)
   public void Test()

**Comment by ranjithantham** [comment]
you mean to say pass user as parameters in the Test Method - we are using role parameter from testng xml file. please can you help us - this is real blocker for us - looking forward to your reply - Thanks a lot.

**Comment by ranjithantham** [comment]
never mind - i got to know how to use parameters in the test case . it's now i am able to see the count match for different users - thanks for great input and help.
