### ISSUE TITLE
"Set up" and "Tear down" blocks are not displayed if slash used in test parameters

### ISSUE THREAD

**Issue by grmmvv** [allure-framework/allure2#824]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report

#### What is the current behavior?
"Set up" and "Tear down" blocks are not displayed if slash used in test parameters.

#### Reproduction
```python
import allure
import pytest

@pytest.fixture
def fixture(request):
    @allure.step('Fixture tear down')
    def fin():
        pass
    with allure.step('Fixture setup'):
        pass
    request.addfinalizer(fin)

@pytest.mark.parametrize('arg', ['foo/bar'])
def test_allure_error(arg, fixture):
    with allure.step('Test step'):
        pass
```

#### Please tell us about your environment:

| Allure version | 2.7.0 |
| --- | --- |
| Python | 2.7.15 |
| Test framework | pytest@3.6.4 |
| Allure adaptor | allure-pytest@2.5.0 |
| Generate report using | allure-commandline@2.7.0 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by sseliverstov** [comment]
moved to python repo https://github.com/allure-framework/allure-python/issues/290
