### ISSUE TITLE
Skipped test cases doesn't show under feature-story in Behaviours section

### ISSUE THREAD

**Issue by NikolaZavadska** [allure-framework/allure2#827]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
- when I have a suite with skipped test in and I used feature and story function, then skipped test doesn't show under the feature/story in Behaviour page in Allure.
- it shows as test without these two behaviour categories

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
testcase:

```js
describe('Test suite 1', () => {
    it.skip('skipped testcase', () => {
        reporter.feature('Cool feature 1');
        reporter.story('As a user I want to do this cool stuff');
    });
    it('There is title Sharktower on the login page', () => {
        reporter.feature('Cool feature 1');
        reporter.story('As a user I want to do this another cool stuff');
        page.login();
        page.title.should.equal('Cool feature');
    });
});
```

first testcase will skip and second will fail
- when I generate report and go to behaviour section I can see failed categorised test under the 'Cool feature' feature but the skipped test appears outside the feature category
#### What is the expected behavior?
- when I generate report and go to behaviour section I can see failed and skipped categorised test under the 'Cool feature' feature
#### What is the motivation / use case for changing the behavior?
- I want to see to which category the skipped tests belongs

#### Please tell us about your environment:

| Allure version | 2.7.0 |
| --- | --- |
| Test framework | webdriverio ^4.12.0 |
| Allure adaptor | allure-testng@2.0-BETA11 |
| Generate report using | wdio-allure-reporter ^0.6.3 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
The problem is that labels are not added because test not getting executed. I guess you can use `this.skip()` in test body instead of `it.skip`.

@BorisOsipov correct me if I wrong

**Comment by BorisOsipov** [comment]
@baev 
you're right. It's not allure issue.

**Comment by baev** [comment]
@NikolaZavadska you can refactor your test like this:

```js
it('skipped testcase', () => {
  reporter.feature('Cool feature 1');
  reporter.story('As a user I want to do this cool stuff');
  this.skip();
});
```
