### ISSUE TITLE
When there is more then 1 skipped test in suite Allure doesn't detect it

### ISSUE THREAD

**Issue by NikolaZavadska** [allure-framework/allure2#829]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
- when I have two skipped tests in one suite, then just first test from the suite appears in the report

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
describe('Suite 1', () => {
        it.skip('Test 1');
        it.skip('Test 2');
    });
Report shows just 1 test (Test 1)

#### What is the expected behavior?
- I'm expecting to see 2 skipped tests in report (Test 1 and Test 2)

#### What is the motivation / use case for changing the behavior?
- I want to know number of skipped tests. In this case I'm not getting correct result.

#### Please tell us about your environment:

| Allure version | 2.7.0 |
| --- | --- |
| Test framework | webdriverio ^4.12.0 |
| Allure adaptor |  |
| Generate report using | wdio-allure-reporter ^0.6.3 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
@BorisOsipov maybe you can help with this issue?

**Comment by BorisOsipov** [comment]
It is fixed in https://github.com/webdriverio-boneyard/wdio-allure-reporter/pull/127

@NikolaZavadska updates to 0.7.0 version.

**Comment by baev** [comment]
thanks @BorisOsipov
