### ISSUE TITLE
Allure reports calculate number of executed tests wrongly

### ISSUE THREAD

**Issue by kantarogit** [allure-framework/allure2#834]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)
**Description:**
When generating allure report for TestNG tests, the report counts up to twice as many tests as actually executed.

**Setup:**
1) test project has a parent project with the following configuration
(See Other information about correct versions of the plugins/depencancies used):

![image](https://user-images.githubusercontent.com/24574892/45098539-7d5db680-b125-11e8-960d-f5e2048953ab.png)

![image](https://user-images.githubusercontent.com/24574892/45098409-37a0ee00-b125-11e8-82ce-f4f7e3b0e913.png)

**Steps to reproduce:**
1) run tests with 
`mvn clean test` 
tests are organized as following:
- suite 1
2 passed
2 failed

- suite 2
1 before method failed
5 skipped

that returns (in my example) those numbers:

**_Tests run: 10, Failures: 3, Errors: 0, Skipped: 5_**

2) generate reports with `mvn allure:report `

**Expected result**
Allure report with correct number of tests executed

**Actual result:**
![image](https://user-images.githubusercontent.com/24574892/45098029-74b8b080-b124-11e8-868d-14eda97fb6d8.png)

Total - 19 tests
Failed - 5
Skipped - 10

#### Other information 

| used dependancies/plugins | version |
| --- | --- |
| Test framework | testng@6.11 |
| Allure adaptor | allure-testng@2.7.0 |
| Generate report using | allure-maven@2.9 |
| Maven surefire plugin | maven-surefire-plugin@2.19.1|

**Comment by baev** [comment]
@kantarogit could you please provide content of your `allure-results` folder?

**Comment by kantarogit** [comment]
@baev 
here it is:
![image](https://user-images.githubusercontent.com/24574892/45301021-47974400-b510-11e8-92d9-2cbd7f7adc35.png)

the content of the testsuite.xml is as following:
![image](https://user-images.githubusercontent.com/24574892/45301118-80cfb400-b510-11e8-8cce-480136af243b.png) 

(which is correct)

**Comment by baev** [comment]
the problem is that you configured both Allrue1 and Allure2 adaptors. Remove allure-testng-adaptor dependency from the project in order to fix the problem

**Comment by kantarogit** [comment]
issue solved...
there was a allure1 dependency in other project referenced through my parent project...
thanks @baev
