### ISSUE TITLE
Allure history

### ISSUE THREAD

**Issue by DmitriiTunikov** [allure-framework/allure2#835]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
Здравствуйте. Получаю историю тестов с помощью перекидывания директории history к вновь полученным результатам, при этом в отчете график trends строится верно, но нет возможности кликать на него, чтобы перейти к предыдущей сборке тестов. У вас в демо версии битые ссылки открываются по клику на предыдущие сборки. Не очень понятно, поддерживается ли история в таком формате, в котором это описано в документации. Заранее спасибо.

#### Please tell us about your environment:

| Allure version | 2.7.0 |
| --- | --- |
| Test framework | testng@last ver |
| Allure adaptor | allure-testng@last version |
| Generate report using | allure-maven@2.20.1 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by AlexanderPoleschuk** [comment]
История поддерживается для плагинов CI(Jenkins, Bamboo, TeamCity).
Для репортов, которые собраны при помощью AllureCLI история будет отображаться, но будет не кликабельна. У CLI просто нет информации о том, какой репорт считать предыдущим и как ссылаться на него.

**Comment by egorse** [comment]
@AlexanderPoleschuk есть ли планы поддерживать "регенерацию" истории через cli?

**Comment by baev** [comment]
да, в грядущей версии 3.0 планируется добавить возможность указать папку с историей даже при локальном запуске

всем выговор за русский язык в тикетах 😞
