### ISSUE TITLE
Wrong number of tescases are shown in allure report

### ISSUE THREAD

**Issue by praneeth-Lemnisk** [allure-framework/allure2#842]
First, I ran 10 test cases and everything is fine but in the next run, I am running only 9 out of those 10 test cases which i previously ran. But allure report is still showing 10 test cases in total.

Below are the plugins I am using in my project.
![allure-plugins](https://user-images.githubusercontent.com/43127642/45862204-5393c900-bd8e-11e8-9315-80a049e1aa05.png)
Is this a bug or is it something that I am doing wrong ??

**Comment by eskignax** [comment]
Did you clean your allure-results folder before running the 2nd time ?

**Comment by praneeth-Lemnisk** [comment]
No, I haven't cleaned it beforehand. Cleaning means deleting right ?? I thought without the previous data how it will show the history part of the report  hence I left them in the same folder.

**Comment by eskignax** [comment]
Yes, cleaning mean deleting.

Notice the difference between allure-results and allure-report in the process of generating a report. Then check this on stackoverflow: https://stackoverflow.com/questions/50376630/allure-reports-to-see-historic-trends/.

**Comment by praneeth-Lemnisk** [comment]
Ok, I figured it out and everything is fine now. Thank you so much for your help.
