### ISSUE TITLE
HTTP 403 error on getting https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.4.1/allure-2.4.1.zip

### ISSUE THREAD

**Issue by yurydiahiliev** [allure-framework/allure2#843]
Hello, I'm trying to generate Allure report and receive 403 HTTP error on URL https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.4.1/allure-2.4.1.zip
. Allure Reports 2.4.1

If I understand this zip archive should be enabled not forbidden

On Jenkins job results we receive following error:
Can't get https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.4.1/allure-2.4.1.zip to C:\jenkins\workspace\Arvi.Arvini2\ArviAutotests\Arvi.Arvini2.ErpSanity.Autotests\erp-sanity\build\allure-2.4.1.zip

**Comment by baev** [comment]
see https://github.com/allure-framework/allure2/issues/832#issuecomment-425643244
