### ISSUE TITLE
Timings Incorrect and Embedded Attachments not present when using Cucumber 4.x

### ISSUE THREAD

**Issue by james-bjss** [allure-framework/allure2#849]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Since Cucumber 4.x events consumed by the Allure formatter plugin are not received until after the test run.

This results in the step timings showing values of 0ms and means that embedded attachments are orphaned. I believe this is because filters like like allure-rest-assured rely on the currently executing step being set in the formatter plugin.

It is possible to use a formatter that implements the `ConcurrentEventListener `interface; however it may not be possible to determine the currently executing step for that thread. 

I have raised a related github issue on cucumber here to add this info in the events. In doing this it may also be possible to match these up after the run in conjunction with the timestamps.
https://github.com/cucumber/cucumber-jvm/issues/1491

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Will try to uplaod a demo at some point his evening.

#### What is the expected behavior?

Attachment should be embedded in steps.
Test timings should reflect actual execution times.

#### What is the motivation / use case for changing the behavior?

Want to use Cucmber 4.x parallel with Allure + Embedded attachments

#### Please tell us about your environment:

| Allure version | 2.7.0 |
| --- | --- |
| Allure-Restassured| 2.7.0 |
| Cucumber |4.0 - 4.10 |

#### Other information 
See: https://github.com/cucumber/cucumber-jvm/issues/1491

**Comment by james-bjss** [comment]
@baev  I am happy to try to to resolve this if we can agree a good approach. 
Have the team already started to look at Cucumber4?

**Comment by baev** [comment]
> Have the team already started to look at Cucumber4?

nope, as far as I know. Cucumber Integration is mostly maintained by the community

@letsrokk do we have any progress in this?

**Comment by james-bjss** [comment]
> > Have the team already started to look at Cucumber4?
> 
> nope, as far as I know. Cucumber Integration is mostly maintained by the community
> 
> @letsrokk do we have any progress in this?

I can confirm it *does* work with the current plugin (even when running parallel threads), it's the only the timings and embeddings that break, so if we can find a good way to fix that it should be usable.

**Comment by letsrokk** [comment]
@baev @james-bjss I haven't had a chance to look into what changes Cucumber 4.x brought in - yet.
But I do want to upgrade to 4.x in my projects mainly because new built in support for parallel execution. 

That is a good news, that current plugin works with Cucumber 4.x, but I suspect that we will need a new adapter which implements `ConcurrentEventListener ` to fully support new parallel execution feature. Let me have a look into this

@baev can you please confirm if new upcoming Allure 3 will support current adapters (`allure-java` adapters)?

**Comment by baev** [comment]
> can you please confirm if new upcoming Allure 3 will support current adapters (`allure-java` adapters)

yep.

**Comment by baev** [comment]
the only changes you should notice is changes introduced in https://github.com/allure-framework/allure-java/pull/249

we are getting rid of JAXB, and some pojos/methods are going to be deprecated

**Comment by letsrokk** [comment]
great, thanks

**Comment by james-bjss** [comment]
> @baev @james-bjss I haven't had a chance to look into what changes Cucumber 4.x brought in - yet.
> But I do want to upgrade to 4.x in my projects mainly because new built in support for parallel execution.
> 
> That is a good news, that current plugin works with Cucumber 4.x, but I suspect that we will need a new adapter which implements `ConcurrentEventListener ` to fully support new parallel execution feature. Let me have a look into this
> 
> @baev can you please confirm if new upcoming Allure 3 will support current adapters (`allure-java` adapters)? I was thinking of some small refactoring to reduce code duplication between current Cucumber adapters for different Cucumber major versions. Don't want to do it twice :)

Hi. Yes, but the problem is how do we map between the code that creates the attachment and the step that is passed form the event. I thought if cucumber passed the current threadId we could match this with the thread ID of the logger and the timing values it passed (incase thread is reused).

Unless there is another way to work this out? I know there are now `@BeforeSteps`  hooks that can receive a `Scenario` object perhaps we could store and match this? It wouldn't even need to be concurrent if we could work this out after.

**Comment by letsrokk** [comment]
According to [blog post](https://cucumber.io/blog/2018/09/24/announcing-cucumber-jvm-4-0-0) current version of adapter implements `EventListener`, and basically it receives a replay of events that happened during the execution of Scenario. Problem is, all attachments already happened when Allure saves Steps information.
That is why I suggest us to look into implementation of `ConcurrentEventListener`

**Comment by james-bjss** [comment]
> According to [blog post](https://cucumber.io/blog/2018/09/24/announcing-cucumber-jvm-4-0-0), because of the fact that current version of adapter implements `EventListener`, it basically receives a replay of events that happened during the execution of Scenario. Problem is, all attachments already happened when Allure saves Steps information.
> That is why I suggest us to look into implementation of `ConcurrentEventListener`

Hi, yes. But when the attachment is created and you attach it to the step, how do you know which step is the right one the code creating the attachment is executing in?

Thread1 -> Step1 - > Request Logger Creates an attachment
Thread2 -> Step1 -> Request Logger Creates an attachment

ConcurrentFormatter - Holds a reference to current executing Scenario & Steps List 
Thread1-Step1
Thread2 -Step1

How does the logger know which step to attach to if it doesnt know which thread it is in? Can this be done by getting hold of the Scenario?

**Comment by letsrokk** [comment]
It is managed by `AllureLifecycle`, and it should be thread safe. 

@baev can explain it better :)

**Comment by james-bjss** [comment]
> It is managed by `AllureLifecycle`, and it should be thread safe.
> 
> @baev can explain it better :)

OK. It's just that in the formatter I see things like this in the handleTestCaseStarted:
`java
        lifecycle.scheduleTestCase(result);
        lifecycle.startTestCase(getTestCaseUuid(event.testCase));`

It appears that this sets the current executing test. How would the logger know that this is the same test it belongs in if we have multiple tests running at the same time?

**Comment by baev** [comment]
Allure uses inheritable thread local in order to store current step/test context

**Comment by james-bjss** [comment]
> Allure uses inheritable thread local in order to store current step/test context

OK, I'm still not so sure (sorry) :) 
It's not so much about being threadsafe, it's just how you get the current executing step. Let my try to explain a different way. Or else you can help me understand why I am wrong :)

When we create attachments the following code is invoked in AllureLifeCycle
```java
    public String prepareAttachment(final String name, final String type, final String fileExtension) {
        final Optional<String> currentStep = storage.getCurrentStep();
```

If there are many tests running at the same time how do we know `getCurrentStep()` is the step for this thread? If this is set by the formatter on each threads threadlocal how would it know which one to set?

Scenario:
1. Start two tests at same time (Test A and Test B)
2. The tests both send started events to the formatter - 2x
3. The formatter needs to set the current active step. (if this is local to the running thread how does it know which thread)
4. Each RestAssured Attachment filter tries to get the current step 
         - How to tell which is the correct step for this thread? Is it something smart with the UID of the 
          scenario?

                    Concurrent Test Run      
                         |           |   
                  Test1Start   Test2Start   - 1
                         \          /
                       Event1    Event2     - 2
                            \      /
                    Allure Formatter         -3
             Receive Event (Single Instance)
                                 |
                lifecycle.setCurrentStep(Event1)
                lifecycle.setCurrentStep(Event2)
           

                      Thread1                    Thread2    -4
                  Restassured Filter        RestAssuredFilter
                       TestStep1                  TestStep2
                         |                           |
                CreateAttachment               CreateAttachment
          step=storage.getCurrentStep();  step=storage.getCurrentStep();                

                       step =???                  step=???

**Comment by baev** [comment]
Each thread has own id, so thread local in general is a map from thread id to some value. See https://docs.oracle.com/javase/8/docs/api/index.html?java/lang/InheritableThreadLocal.html

The idea behind listeners (aka adaptors) is that listeners run in same thread as the test do, so we can use thread locals to share context.

**Comment by baev** [comment]
support for Cucumber 4 was released
