### ISSUE TITLE
Features by stories does not show count of test cases

### ISSUE THREAD

**Issue by cjsaini** [allure-framework/allure2#859]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Feature By Stories on Dashboard does not show count of test cases under labels, instead it is always showing 1 (number of features under Epic)

<img width="1414" alt="screen shot 2018-11-09 at 10 09 40 am" src="https://user-images.githubusercontent.com/29964374/48294299-6acb6a80-e451-11e8-9328-01cedc48161a.png">

#### What is the expected behavior?
Expected behaviour is to have correct number of test cases under FEATURES BY STORIES widget as being shown in under SUITES on Dashboard

#### What is the motivation / use case for changing the behavior?
This way, we will be able to know actual number of test cases under each Epic displayed under FEATURES BY STORIES widget. Currently it shows number for Features under that Epic, but displaying number of test cases under Epic seems more meaningful.

#### Please tell us about your environment:

| Allure version | 2.7.0 |
| --- | --- |
| Test framework | testng@6.14.3 |
| Allure adaptor | allure-testng@2.0-BETA11 |
| Generate report using | allure jenkins plugin |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
The idea behind the widget is to have an answer for "how many stories are broken per feature" question. 

You probably need other one, that tests per epic/feature. For now you can use our plugin API to implement custom widget that fits your needs, or you can wait for Allure 3 release that will have possibility to add such widgets using configuration file
