### ISSUE TITLE
The input line is too long.

### ISSUE THREAD

**Issue by SureshGedela** [allure-framework/allure2#861]
I ran around 50 different test classes and when allure is trying to generate the report for all these 50 test classes it throws error.

[workspace] $ "C:\Program Files (x86)\Jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\Allure_2.7.0\bin\allure.bat" generate "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure1051245038278739955results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure1198028742925113484results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure1563013124874759315results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure1882694345674788591results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure1955073169269514036results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure2063172490262134191results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure2451197406121799032results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure2479806166862002306results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure2532201061810811226results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure2579336103235259088results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure26634498288506803results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure2795274377266800899results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure2836628872470898974results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure2851425369445017052results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure2904511517056729112results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure2910398599103237785results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure2993739939769684113results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure3034188645827881332results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure3200985616219755336results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure3277336320226525241results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure3307740178668818998results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure338525385843909664results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure3785672595442765978results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure3910534240127816025results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure3978844006312904102results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure4198002647392497711results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure4220960384358863211results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure4259757662743800630results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure4688016699277476235results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure5227920953571441130results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure5323005041861613346results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure5688387646710487205results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure6214743904059152317results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure6393735140085286522results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure6939822855025580515results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure7041410527149735349results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure7149424655283032057results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure7300032453254215842results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure731043902745581966results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure7843064309935394104results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure7908034933726806966results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure7921846546080725772results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure8003079336322639700results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure8007925306260895267results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure8209980593238213228results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure8250533892920308504results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure8287899877340690049results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure8456891208149711554results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure8552740609130788766results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure8823157490089211056results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure9049029171228189363results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure9169196151458935924results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure952231870942426392results" "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure992047004292578416results" -c -o "C:\Program Files (x86)\Jenkins\jobs\Stage - Run Tests - Smoke\workspace\allure-report"
The input line is too long.
The syntax of the command is incorrect.
FATAL: Can not generate Allure Report, exit code: 255
ru.yandex.qatools.allure.jenkins.exception.AllurePluginException: Can not generate Allure Report, exit code: 255
at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:296)
at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.access$000(AllureReportPublisher.java:61)
at ru.yandex.qatools.allure.jenkins.AllureReportPublisher$1.endBuild(AllureReportPublisher.java:266)
at hudson.matrix.MatrixBuild$MatrixBuildExecution.post2(MatrixBuild.java:424)
at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:627)
at hudson.model.Run.execute(Run.java:1762)
at hudson.matrix.MatrixBuild.run(MatrixBuild.java:314)
at hudson.model.ResourceController.execute(ResourceController.java:97)
at hudson.model.Executor.run(Executor.java:421)

**Comment by baev** [comment]
Could you please specify Allure version you are using?

**Comment by baev** [comment]
closed due to no response
