### ISSUE TITLE
Feature request: a way to disable step parameter auto-displaying in the report.

### ISSUE THREAD

**Issue by L-Evg** [allure-framework/allure2#863]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behaviour?
Allure 2 automatically displayed step methods parameter names and values in the report. That is nice and ok as long as the values are primitives or small-sized objects.

#### What is the expected behaviour?
It would be great to have a way to "say" to Allure "ignore.do not display this parameter's value in teh report.

#### What is the motivation / use case for changing the behaviour?
1. In case of huge collections, big-size objects (e.g. a huge JSON) etc - the report becomes less and less responsible
2. Data passed to a step method could be sensitive (passwords, names, CC numbers etc), so it should be not logged.

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | testng@6.9 |
| Allure adaptor | allure-testng@2.7.0 |
| Generate report using | allure-cli 2.5.0 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by QA-Rahul** [comment]
Is there any update on this? I am looking for some solution where I can hide some steps from allure report.

**Comment by baev** [comment]
As workaround I can suggest you a few options (speaking of Java tests):

1) create your own `CustomStep` annotation. (You can use default step aspect code as reference https://github.com/allure-framework/allure-java/blob/3f2d799a0129cef3b6282d8b10c897fe0dfb2efa/allure-java-commons/src/main/java/io/qameta/allure/aspects/StepsAspects.java )
2) use Allure Java API (`Allure.step()` methods) to create steps with only required params. See https://github.com/allure-framework/allure-java/pull/282 for the details

**Comment by firyx** [comment]
We needed this for Selenide with Allure.

I have created a custom Selenide extension in our framework,
but I have also created a Selenide PR (https://github.com/selenide/selenide/pull/948) to include this to Selenide itself.

**Comment by baev** [comment]
fixed via https://github.com/allure-framework/allure2/pull/1404

**Comment by BBSoftPro** [comment]
`@Steps()
void confirmPasscode(int seconds, passcode){
enterPasscode(passcode)
delay(second)
}`

in this case if I want to skip seconds cos I don't want to show it in the report steps. have any command this anotations to solve this ?

**Comment by baev** [comment]
Please ask a questions on [discussions](https://github.com/orgs/allure-framework/discussions)
