### ISSUE TITLE
Why do not unsuccessful auto tests appear in the Allure 2.8.1

### ISSUE THREAD

**Issue by VikaVika222** [allure-framework/allure2#868]
In version 2.8.1, only successful autotests are displayed in the autotest run reports.
 Allure  2.8.1
 testNgVersion = '6.14.3'
  selenideVersion = '5.0.1'
Jenkins+Gradle 
![image](https://user-images.githubusercontent.com/45560210/49370286-ca413100-f704-11e8-9dfa-e2b650da7bd5.png)

**Comment by baev** [comment]
closed due to no response
