### ISSUE TITLE
AllureLifecycle for tests launched via intelliJ  "Could not add attachment: no test is running"

### ISSUE THREAD

**Issue by Fanch-** [allure-framework/allure2#872]
#### I'm submitting a ... 
  - [ ] bug report

#### What is the current behavior?

```

2018-12-19 12:12:06 ERROR AllureLifecycle:563 - Could not add attachment: no test is running
2018-12-19 12:12:08 ERROR AllureLifecycle:414 - Could not start step: no test case running
2018-12-19 12:12:08 ERROR AllureLifecycle:470 - Could not update step: step with uuid 9cb0199b-f0db-45cc-97f9-2e2cc396633a not found
2018-12-19 12:12:08 ERROR AllureLifecycle:504 - Could not stop step: step with uuid 9cb0199b-f0db-45cc-97f9-2e2cc396633a not found
```

Using maven command to launch the tests, I have not this issue, but using intelliJ run/debug conf (for local tests) I have the previous logs.

So the console output is flooded by AllureLifecycle logs

#### What is the expected behavior?

With an allure previous version (2.7.0), we didn't have it.

#### Please tell us about your environment:

| Allure version | 2.8.1 |
| --- | --- |
| Test framework | junit@4.12 |
| aspectj version | 1.8.10 |

#### Other information 

        <allure.version>2.8.1</allure.version>
        <aspectj.version>1.8.10</aspectj.version>
        <maven-surefire-plugin.version>2.20.1</maven-surefire-plugin.version>
        <plugin-listener>io.qameta.allure.junit4.AllureJunit4</plugin-listener>

        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-junit4</artifactId>
            <version>${allure.version}</version>
        </dependency>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjweaver</artifactId>
            <version>${aspectj.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>2.17</version>
                <configuration>
                    <configLocation>google_checks.xml</configLocation>
                    <includeTestSourceDirectory>true</includeTestSourceDirectory>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire-plugin.version}</version>
                <configuration>
                    <systemPropertyVariables>
                        <allure.link.mylink.pattern>https://testrail-url?/cases/view/{}</allure.link.mylink.pattern>
                        <allure.link.issue.pattern>https://jira-url/{}</allure.link.issue.pattern>
                        <allure.link.tms.pattern>https://to.define/{}</allure.link.tms.pattern>
                        <allure.results.directory>${project.build.directory}/allure-results</allure.results.directory>
                    </systemPropertyVariables>
                    <argLine>
                        -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                    </argLine>
                    <properties>
                        <property>
                            <name>listener</name>
                            <value>
                                ${plugin-listener}
                            </value>
                        </property>
                    </properties>
                </configuration>
            </plugin>
        </plugins>
    </build>

**Comment by baev** [comment]
This logs means that you are trying to add steps and attachments when no test running (eg in set up/tear down methods that is not supported by allure-junit4 integration by now)

In order versions has no logging for such cases.

**Comment by Fanch-** [comment]
I mean it works using maven command line, it's when I launch a test with intelliJ that I get the error. 

![spectacle s30553](https://user-images.githubusercontent.com/7208988/50222660-dbd73980-0390-11e9-9a26-f578ca354a71.png)

Every steps during my test (so not linked to set up/tear down - Before/After) are throwing AllureLifecycle errors (everything works fine with mvn).

I guess with maven commandline, the plugin phase is correctly interpreted, the listener also, and with the IDE there is something wrong. The strange thing is that the attachments are still generated.

The behavior might be the same as before, logs in addition, it's just for local purpose have something to not show them could be great, otherwise we will still stay in 2.7.0 forever :(

**Comment by baev** [comment]
@Fanch- am I right that you have the same behaviour as in 2.7.0 but additional error logging is present?

The problem is that IDEA ignores maven-surefire configuration, so when you run tests using IDE Allure have no information about test start/stop event, and that causes the warnings. 

Attachments are generated because Allure can store the file you are trying to attach, but it can't find current execution context (AllureLifecycle stores information about current running tests in thread local storage) to add the link to the stored file.

Actually I think that having logs is a good idea - thats is a signal for you that something is wrong (like in this case, you have no listener configured when run your tests via IDE).

The problem is only exists for JUnit 4 projects since JUnit team decided to not add SPI support for listeners in 4.x versions (I even create a pull request with that change few years ago https://github.com/junit-team/junit4/pull/1122)

Also there is no possibility to configure listener for JUnit 4 in IDEA run build configuration (like for TestNG tests)

### Possible workarounds

* You can disable logging for AllureLifecycle class in your logger config (exact configuration depends on slf4j implementation you are using). After that the behaviour should be the same as in 2.7.0
* You can try to use `allure-junit4-aspect` module. This module is designed exactly for cases when you have no possibility to configure listener for JUnit 4. It uses aspects, so you need to configure AspectJ in your IDEA run build configuration (by adding aspectj-weaver agent to jvm args or using aspectj-compiler)

**Comment by Fanch-** [comment]
@baev Thank you for your answer.

With 2.7.0 I have just the logging errors when a step param is malformed, which is cool I agree `2018-12-20 11:54:50 ERROR NamingUtils:54 - Could not find parameter `

But I haven't the following errors during test :
```

2018-12-19 12:12:06 ERROR AllureLifecycle:563 - Could not add attachment: no test is running
2018-12-19 12:12:08 ERROR AllureLifecycle:414 - Could not start step: no test case running
2018-12-19 12:12:08 ERROR AllureLifecycle:470 - Could not update step: step with uuid 9cb0199b-f0db-45cc-97f9-2e2cc396633a not found
```

from 2.8.0

We have about 100 steps per test, which log a lot of errors.

But your answer is fine for me, we would have to use junit5 for allure 2.8.0 :+1:

**Comment by romainlouvet** [comment]
@Fanch- just add `log4j.logger.io.qameta.allure.AllureLifecycle = OFF` in your log4j.properties
bisous

**Comment by ogulcanarbc** [comment]
allure-junit-platform 2.13.0 working but 2.17.1 v not working this case, why?

**Comment by dzikuf** [comment]
> @Fanch- just add `log4j.logger.io.qameta.allure.AllureLifecycle = OFF` in your log4j.properties bisous

@romainlouvet in log4j2 this row does`t work. How to do in log4j2?

**Comment by david-m-globant** [comment]
for testng, this solve the title problem

```
<!-- required by Allure.addAttachment -->
<dependency>
	<groupId>io.qameta.allure</groupId>
	<artifactId>allure-plugin-api</artifactId>
	<version>${allure.version}</version>
</dependency>
<!-- required by Allure web view -->
<dependency>
	<groupId>io.qameta.allure</groupId>
	<artifactId>allure-testng</artifactId>
	<version>${allure.version}</version>
</dependency>
```
