### ISSUE TITLE
Microsoft Defender finds a virus in allure-2.8.1 -> app.js

### ISSUE THREAD

**Issue by danielbacara** [allure-framework/allure2#873]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
* When downloading the allure-2.8.1 from the allure releases page ](https://github.com/allure-framework/allure2/releases), microsoft windows defender finds a "Trojan:Win32/Spursint.F!cl" threat in the allure-commandline-2.8.1.zip -> allure-generator-2.8.1.jar->app.js
* Windows Defender automatically removes the allure-2.8.1.zip file

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
* Download [allure-2.8.1.zip ](https://dl.bintray.com/qameta/maven/io/qameta/allure/allure-commandline/2.8.1/allure-commandline-2.8.1.zip) from the release page of allure2 github
* Scan with Microsoft Windows Defender

#### What is the expected behavior?
* No threads found after a scan with Microsoft Windows Defender

#### What is the motivation / use case for changing the behavior?
Usage of Allure2 in a windows based environment with defender installed

#### Please tell us about your environment:

| Allure version | 2.8.1 |
| ---- | ------------- |
| OS  | Windows 10 |

#### Other information 
* It could be similar issue with a false positive as the following issue from google [material-design-lite](https://github.com/google/material-design-lite/issues/1754)
* You can submit it for anylysis to microsoft: https://www.microsoft.com/en-us/wdsi/filesubmission, so that it will become safe with the next update of windows defender.

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
* Status: Completed 
* Submitted by: ba**@gmail.com 
* Submitted: Dec 21, 2018 16:56:32 
* User Opinion: Incorrect detection 

## Analyst comments:

We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

Thank you for contacting Microsoft.

**Comment by baev** [comment]
@danielbacara could you please check that everything is ok now?

**Comment by danielbacara** [comment]
I checked and it is fixed. 

We can close this issue now 👍
