### ISSUE TITLE
Not latest test results in Jenkins Allure Report

### ISSUE THREAD

**Issue by ivanli1990** [allure-framework/allure2#874]
### Context
- **Jenkins version**: 2.46.3
- **Job type**: Pipeline

- **Allure plugin version**: 2.26.0
- **Allure commandline version**: 2.8.1

### Problem description

_Describe your problem in a meaningful way_:
- I used Jenkins Allure plugin to generate pytest testing results, and the pipeline is built periodically.
- The problem is the result in Jenkins Allure is not correct. Some pytest cases's results is not the latest running, but historical running. For example，I build the pipeline to run the case in 12.24, but some cases results in Jenkins Allure showed result in 12.21.  And When I view the suites.json's content，I find the time field in the case is wrong. And I also found the start time on Allure Overview is 12.21.
Why some cases not generate latest running result in Jenkins Allure?

### Logs & Traces
![image](https://user-images.githubusercontent.com/20061898/50389888-d8fe8f00-076a-11e9-9015-94459c0274a6.png)
![image](https://user-images.githubusercontent.com/20061898/50389876-ab194a80-076a-11e9-9cf0-92d83e3d2d5e.png)
![image](https://user-images.githubusercontent.com/20061898/50389899-fc293e80-076a-11e9-9419-c0dc78539e67.png)

_Please include any relevant log that could serve to better understand the source of your issue_

**Comment by baev** [comment]
You need to clean Jenkins workspace between runs.

**Comment by baev** [comment]
closed due to no response
