### ISSUE TITLE
Allure.zip file artifact takes inordinate amount of resources (>600GB disk, 32GB RAM) to transfer the artifact to Jenkins for archiving, and still hangs/crashes job

### ISSUE THREAD

**Issue by osmolyar** [allure-framework/allure2#877]
#### I'm submitting a ... 
  - [x] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

The Allure.zip file artifact takes an inordinate amount of time (several hours) and disk space (>600GB) to transfer the artifact to Jenkins for archiving when using the Allure plugin.   Even with this amount of resources, 99% of the time the Jenkins slave connection to the agent drops due to an OutOfMemory error, which I understand is due to running out of space when trying to transfer the contents of the zip file (according to https://stackoverflow.com/questions/23505098/jenkins-slaves-go-offline-or-hang-when-archiving-
artifacts).  We have also increased RAM on the Jenkins server to 32GB, and have set the heap sizes as follows

Jenkins: -Xrs -Xmx4096m 

Allure reporter: JAVA_ARGS: -Xmx512m -Xms512m 
DEFAULT_JVM_OPTS: -Xmx1G 

AT_HUB start-slave.bat for connection to Jenkins on qdvmwinselenium: -Xmx1024m -Xms1024m 

 This is seen with a suite of ~1000 tests, using wdio-cucumber-framework.  The issue is that the allure.zip file consists of ~76,000 1MB json files for this suite, with each json file listed in the response/request for each of the multiple POST/GET actions in each test step, as seen in the below image: 
![image](https://user-images.githubusercontent.com/15637471/50974821-1c226700-14ba-11e9-82bd-004a913ee817.png)

This information is absolutely of no apparent use for the passing items, as the response/request is only of interest if there is an error screenshot attachment, assertion error, or navigation error/stacktrace attached to that particular response.

Currently this handling of the zip file artifact is essentially blocking our organization's ability to use the Allure plugin, though it has been adopted by >7 scrum teams.  

It would be hugely beneficial if there was a setting (or default behavior) to eliminate all of these passing tiny json request/response files from the zip file, (or to handle them some other way such as concatenating into a single json file).

The same issue is discussed in the following threads, where people are resorting to shutting off archiving of the allure artifacts for this reason - which is not an approach we want to adopt.

https://stackoverflow.com/questions/46466590/how-to-totally-avoid-creating-jenkins-artifacts-after-each-build

https://stackoverflow.com/questions/45712514/allure-report-generation-and-display-speed-in-case-of-large-amount-of-tests-and?rq=1

This one contains the suggestion from allure devt "So the only way I can see to handle the problem - add an ability to hide all the passed tests from tabs (suites, behaviors, packages and timeline)" - this would be completely acceptable from our point of view.

https://stackoverflow.com/questions/23505098/jenkins-slaves-go-offline-or-hang-when-archiving-
artifacts": "Whenever Hudson master will run out of 
space, slaves will disconnect and will have to be restarted. 
You need to check Hudson master box and see how much space is allocated to the drive where hudson 
is running

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Run test suite with ~950 wdio-cucumber-reporter tests via Jenkins and Jenkins Allure plugin.

System resources:
600GB disk space
32GB RAM
heap sizes as follows

Jenkins: -Xrs -Xmx4096m 

Allure reporter: JAVA_ARGS: -Xmx512m -Xms512m 
DEFAULT_JVM_OPTS: -Xmx1G 

AT_HUB start-slave.bat for connection to Jenkins on qdvmwinselenium: -Xmx1024m -Xms1024m 

Jenkins build always hangs/fails at 'Generating artifacts for the build' step and the Agent connection to Jenkins drops with an OutOfMemory error.  Allure.zip file fails to be transferred to Jenkins server.

#### What is the expected behavior?

Allure.zip file should be successfully transferred to the Jenkins server and the Agent connection should not drop while trying to transfer the file.

#### What is the motivation / use case for changing the behavior?

This is currently blocking our organization's continued use of Allure with Jenkins.

#### Please tell us about your environment:
"wdio-cucumber-framework": "^1.1.0",
    "wdio-allure-reporter": "^0.7.0",

| --- | --- |
| Generate report using | allure-commandline 2.6.0 |
Allure Jenkins Plugin 2.27.0

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

The issue is that the allure.zip file consists of ~76,000 1MB json files for this suite, with each json file listed in the response/request for each of the multiple POST/GET actions in each test step

This information is absolutely of no apparent use for the passing POST/GEN actions, as the response/request is only of interest if there is an error screenshot attachment, assertion error, or navigation error/stacktrace attached to that particular response.

Currently this handling of the zip file artifact is essentially blocking our organization's ability to use the Allure plugin, though it has been adopted by >7 scrum teams.  

It would be hugely beneficial if there was a setting (or default behavior) to eliminate all of these passing json request/response files from the zip file, (or to handle them some other way such as concatenating into a single json file).

The same issue is discussed in the following threads, where people are resorting to shutting off archiving of the allure artifacts for this reason - which is not an approach we want to adopt.

https://stackoverflow.com/questions/46466590/how-to-totally-avoid-creating-jenkins-artifacts-after-each-build

https://stackoverflow.com/questions/45712514/allure-report-generation-and-display-speed-in-case-of-large-amount-of-tests-and?rq=1

This one contains the suggestion from allure devt "So the only way I can see to handle the problem - add an ability to hide all the passed tests from tabs (suites, behaviors, packages and timeline)" - this would be completely acceptable from our point of view.

https://stackoverflow.com/questions/23505098/jenkins-slaves-go-offline-or-hang-when-archiving-
artifacts": "Whenever Hudson master will run out of 
space, slaves will disconnect and will have to be restarted. 
You need to check Hudson master box and see how much space is allocated to the drive where hudson 
is running

**Comment by osmolyar** [comment]
As an update, even using a Jenkins machine with 192Gb of RAM, 28Gb page size, 972Gb disk space, the same failure occurs when transferring the artifact nearly 100% of the time.

**Comment by baev** [comment]
The easiest way to solve the problem is remove attachments from passed tests. We actually had this feature for old java adaptors, maybe this is a time to bring this feature to Allure 2 as well. 

Also during this issue I'd like to investigate attachments problem (I successfully generated reports for 200k+ tests, the main problem for such huge reports is laggy UI) but never tested it for huge amount of attachments.

**Comment by osmolyar** [comment]
Is there any setting we may possibly be missing?  This was previously working fine on the above mentioned machine, but now is not, even for fewer tests.

**Comment by osmolyar** [comment]
Also - just to clarify - the problem is not in generating the report - it is generated successfully on the Jenkins slave.  The problem is in transferring the artifact to the Jenkins host machine.  Were you able to also transfer the report for 200k+ tests to Jenkins via the plugin?

**Comment by BorisOsipov** [comment]
@osmolyar why just not disable reporting driver request\responses?

**Comment by BorisOsipov** [comment]
you can just attach screenshots on failed scenario step

**Comment by osmolyar** [comment]
How?

**Comment by baev** [comment]
```js
reporters: [['allure', {
        outputDir: 'allure-results',
        disableWebdriverStepsReporting: true, //this line
}]],
```

**Comment by osmolyar** [comment]
@baev , @BorisOsipov , thank you, that did the trick!  That is the option we were looking for.  So probably ok to close this item - though it would make sense to make this the default behavior.

**Comment by osmolyar** [comment]
@baev , @BorisOsipov , unfortunately I take it back.  It worked for the case with 160 cucumber scenarios, but not for the full suite (992 tests).   

The warnings about de-serializing classes as in #882 occur, followed by the agent crashing:
 SEVERE: [JNLP4-connect connection to qdselenium/172.17.105.119:54029] Reader thread killed by OutOfMemoryError
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Unknown Source)

This appears to argue for reopening #882 because perhaps the root cause was not the large number of json files in the .zip file.

**Comment by osmolyar** [comment]
Is there any heap file size we can change that would help this?  Is it the Jenkins heap size?

**Comment by baev** [comment]
> Is there any heap file size we can change that would help this?

looks like the problem is related to ulimit, not a heap size. Changing ulimit should help

**Comment by BorisOsipov** [comment]
@osmolyar sorry, but maybe just clear allure-results folder on jenkins and start from scratch without myriad of json files? It will help 100% :)

**Comment by osmolyar** [comment]
@BorisOsipov , thanks, but it is deleted with every build as a post-build action (and is empty and excluded from the P4 workspace, so no json files are transferred with the build).  (On a hopeful note the last two 'full suite' runs did successfully transfer the artifact, though it did fail once.)  Can confirm that it does not exist on the Jenkins slave now.

@baev , we have Jenkins running on a Windows 2012 server.   Is there a ulimit equivalent for windows?  (Had searched before, and did not find).
