### ISSUE TITLE
Unable to customize test name

### ISSUE THREAD

**Issue by Sanjay-Bhatta** [allure-framework/allure2#904]
Right now, my test name are reported as 'package_name.class_name'. As such the test are reported as 'com.abc.test1'. How can i customize that name in Allure report?

I want something like Test1

**Comment by baev** [comment]
@Sanjay-Bhatta our issue tracker is reserved to bugs and feature requests. Please use our community chat https://gitter.im/allure-framework/allure-core or StackOverflow(tag `allure`) for support questions
