### ISSUE TITLE
History of test limited to 5

### ISSUE THREAD

**Issue by tedrigofra** [allure-framework/allure2#906]
In the Allure report there are the tabs Overview, History and Retries.
When I click on History then I see only 5 previous test results, although Jenkins has many more builds with Allure reports.
Why is it only displaying 5 previous test results in the History tab? How can I see more in the History tab? Do I have to configure that somewhere?
I use the latest Allure versions and JUnit 5.4 and Maven and JDK 11.

**Comment by baev** [comment]
Duplicate of #347
