### ISSUE TITLE
allure generate command does not generate report with AllureFormatter for Behave

### ISSUE THREAD

**Issue by peter-kinzelman** [allure-framework/allure2#908]
**Describe the bug**
Generating test data with the [-f allure_behave.formatter:AllureFormatter](https://behave.readthedocs.io/en/latest/formatters.html?highlight=allure%20formatters#more-formatters) and then calling **allure generate {path_to_test_data}** produces a blank report. 

**To Reproduce**
Prequisites: [allure-behave](https://pypi.org/project/allure-behave/) is installed
1. Run a Behave test with the following parameters: -f allure_behave.formatter:AllureFormatter -o {some_path}
2. Go to installation directory of allure > cd /bin
3. Run command: **allure serve some_path**
4. Behave friendly report generated.
5. Run command: **allure generate some_path**
6. Report is successfully generated to /allure-report directory
7. Open index.html > BLANK REPORT

**Expected behavior**
A Behave friendly report generated (Scenario Steps, screenshots, etc included)

**Screenshots**
![screen shot 2019-03-06 at 10 42 56 am](https://user-images.githubusercontent.com/45794455/53893686-aa1f5780-3ffc-11e9-9e87-7b3da41d6e50.png)

**Environment (please complete the following information):**

| Allure version | 2.9.0 |
| --- | --- |
| Test framework | Allure Behave |
| Allure adaptor | allure-behave==2.5.4 |
| Generate report using | allure generate |

**Additional context**

**Comment by evangelos-ai** [comment]
Hi @peter-kinzelman , where are you creating the report ? on Jenkins or on local device ?

**Comment by peter-kinzelman** [comment]
@evangelos-ai on a local machine. Goal will be to generate the report from a docker container to a directory in CircleCI - which shouldn't make a difference I don't believe.

**Comment by baev** [comment]
@peter-kinzelman the problem is that you are opening report locally without using web server, for the details see https://stackoverflow.com/a/24002146/3915166

**Comment by peter-kinzelman** [comment]
@baev I don't want to use a webserver. 

1. I want to create a static HTML from `allure generate {path}` 
2. Open the index.html in the allure-report directory
3. Display report 

Am I missing something from that process? 

That same process works if i do `allure generate` with XML data

**Comment by peter-kinzelman** [comment]
This is now working in Chrome? 
Steps: 

- `allure generate to_some_path` 
-

**Comment by NowApoca** [comment]
Stills happening in ubuntu 20.04. I am running a battery of tests and running ```allure serve``` displays it correctly but when I try to run ```allure generate``` (Generating the file in the same project) and I try to open the index.html in firefox, it loads to the eternum as the image.

Am I doing something wrong?

**Comment by appaji-kumbhar-fortum** [comment]
I am facing same issue. @NowApoca any luck on ubuntu 20.04?

**Comment by panthangiswapna** [comment]
@peter-kinzelman I'm trying to view the HTML report using Allure in my local machine. However I'm not getting the allure HTML report generated while I run the below command (generated in the same folder path). I'm using Behave framework.

> **allure generate %allure_result_folder%**       **allure serve %allure_result_folder%**
Could you please help me in getting the HTML report generated!
Your help is much appreciated!

Thanks 
swapna
