### ISSUE TITLE
Tests aren't collecting historical data

### ISSUE THREAD

**Issue by KiT-Maverik** [allure-framework/allure2#923]
Can anybody advise how can I enable trends in allure reports? My tests aren't collecting historical data. All trend tabs show "There is nothing to show". I'm saving allure results in the same folder. But still, trends are dead. Can you advise me how can I fix this issue?
wdio+mocha+wdio-allure-reporter

**Comment by baev** [comment]
@KiT-Maverik Allure stores history information to allure-report/history folder during report generation. So you need to copy such folder from previous launch into your allure-results before you generate the report.

You can find additional information on Allure features here https://stackoverflow.com/a/46222758/3915166

**Comment by baev** [comment]
Also you can join our community in Gitter (https://gitter.im/allure-framework/allure-core) to ask questions about Allure
