### ISSUE TITLE
 I use maven plugin   excute  mvn allure:serve  , then give me a mistake .The question is    Downloading allure commandline...Proxy is not specified..  

### ISSUE THREAD

**Issue by huyifei2016** [allure-framework/allure2#924]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

| Allure version | 2.9.0 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.9.0 |
| Generate report using | allure-maven@2.18 |

**Additional context**

**Comment by baev** [comment]
@huyifei2016 could you please provide additional details on the problem you have?
