### ISSUE TITLE
The 'flaky' bomb icon is not received in the executed test list.

### ISSUE THREAD

**Issue by zzt-chun** [allure-framework/allure2#925]
`import time
import random
def test_0():
    time.sleep(random.randint(1, 3))
    if random.randint(1, 5) != 1:
        raise Exception('Broken!')`

![image](https://user-images.githubusercontent.com/44250961/55550922-17adc900-570c-11e9-8a31-ca95c751cd5a.png)

python 3.7.0
allure-pytest 2.6.1
pytest 4.3.1

**Comment by corinazaharia** [comment]
I'm having the same problem when I run the tests in Jenkins - how did you fix it?

**Comment by riddhik84** [comment]
I am having same issue. Any solution for this?

**Comment by techhemant** [comment]
Facing the same issue:
Using Allure allure-2.13.0

**Comment by zzt-chun** [comment]
There is a very stupid solution. After generating the report, use a script to modify the file that records the case names and delete the parts we don't want
