### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jiqialin** [allure-framework/allure2#930]
pluggy.manager.PluginValidationError: unknown hook 'pytest_namespace' in plugin <module 'allure.pytest_plugin' from 'E:\\Python\\Python36\\lib\\site-packages\\allure\\pytest_plugin.py'>

**Comment by sseliverstov** [comment]
Namespaces is deprecated in pytest. Try to import allure modules like this: `import allure.<some you want>` instead `import pytest.allure.<some you want>`

**Comment by VidyaCK** [comment]
I am also getting the same error after the installation of pytest-allure-adaptor using pip3. How can I resolve this?

**Comment by sibasishmohanta-ayla** [comment]
guys i installed pytest version 3.10.0 and it worked for me
