### ISSUE TITLE
gradle built allure-generator-2.11.0.jar prompt error "plugin 'net.researchgate.release' not found"

### ISSUE THREAD

**Issue by yuzhujiutian** [allure-framework/allure2#941]
**Describe the bug**
gradle built prompt plugin 'net.researchgate.release' not found.

What do I need to do to compile a new allure-generator-2.11.0.jar in the leatest source code dir “allure2\allure-generator” by gradle.bat?

**To Reproduce**
([reference \<How to customize allure report title and logo\>, answered by Suhas](https://stackoverflow.com/questions/48709263/how-to-customize-allure-report-title-and-logo))

1. Clone the repository- Link: https://github.com/allure-framework/allure2.git
2. Navigate to 'F:\helloc\aircraft\res\allure-commandline\allure2_v2.11.0_sourcecode\allure2\allure-generator\src\main\java\io\qameta\allure\summary'
3. Edit SummaryPlugin.Java file with any text editor
4. Search for setReportName("Allure Report"); and change to whatever name you want to give. Example setReportName("Automation Report")and save that file
5. Navigate to 'F:\helloc\aircraft\res\allure-commandline\allure2_v2.11.0_sourcecode\allure2\allure-generator'
6. Open command prompt (cmd) from this folder.Type gradle build and hit enter
`D:\winusr\gradle\gradle-5.4.1-bin\gradle-5.4.1\bin\gradle.bat build`
7.  Wait for few mins till it builds. See error as follows:
`F:\helloc\aircraft\res\allure-commandline\allure2_v2.11.0_sourcecode\allure2\allure-generator (master -> origin) (allure-generator@1.0.0)
λ D:\winusr\gradle\gradle-5.4.1-bin\gradle-5.4.1\bin\gradle.bat --stop
Stopping Daemon(s)
1 Daemon stopped
F:\helloc\aircraft\res\allure-commandline\allure2_v2.11.0_sourcecode\allure2\allure-generator (master -> origin) (allure-generator@1.0.0)
λ D:\winusr\gradle\gradle-5.4.1-bin\gradle-5.4.1\bin\gradle.bat build
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

\* Where:
Build file 'F:\helloc\aircraft\res\allure-commandline\allure2_v2.11.0_sourcecode\allure2\build.gradle.kts' line: 24

\* What went wrong:
Plugin [id: \'net.researchgate.release\', version: \'2.7.0\'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in \'org.gradle\' namespace)
- Plugin Repositories (could not resolve plugin artifact \'net.researchgate.release:net.researchgate.release.gradle.plugin:2.7.0\')
  Searched in the following repositories:
    Gradle Central Plugin Repository

\* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

\* Get more help at https://help.gradle.org

BUILD FAILED in 2m 17s

F:\helloc\aircraft\res\allure-commandline\allure2_v2.11.0_sourcecode\allure2\allure-generator (master -> origin) (allure-generator@1.0.0)
λ`

**Environment (please complete the following information):**

1. Allure version
![image](https://user-images.githubusercontent.com/386347/57175899-ee579880-6e83-11e9-8079-779fa94d5e8d.png)

2. gradle version
gradle-5.4.1-bin [download](https://downloads.gradle.org/distributions/gradle-5.4.1-bin.zip)

3. jdk version
jdk-12.0.1, [download](https://download.java.net/java/GA/jdk12.0.1/69cfe15208a647278a19ef0990eea691/12/GPL/openjdk-12.0.1_windows-x64_bin.zip)

4. os version
![image](https://user-images.githubusercontent.com/386347/57175906-0fb88480-6e84-11e9-9607-68dd1a74c970.png)

**Comment by kartnan** [comment]
If you have a ubuntu system, you can build this successfully. If not download a ubuntu vm probably 18.0 LTS version and run it in virtual box.

1. Download allure2 from git. Extract it.
2. Open the build.gradle.kts file in allure2 folder to check which gradle version you should be using.
3. Also check the java version. It should be oracle java jdk 8.
4. Then change the title name as given [here](https://stackoverflow.com/questions/48709263/how-to-customize-allure-report-title-and-logo)
5. run gradle build from inside the allure-generator folder.
6. Your build will finish successfully.
7. I did this with the latest version of allure, which is 2.17.3 as of now and customized the title.
8. I had installed gradle 7.2, oracle java jdk 8 u321 and the build completed successfully and I was able to change the report name.

Hope this helps anyone who might be in a similar situation.
