### ISSUE TITLE
allure reports generated by allure generate/open mode do not consume time

### ISSUE THREAD

**Issue by yuzhujiutian** [allure-framework/allure2#942]
**Describe the bug**
**_if allure reports generated by allure generate/open mode,_**
**_Q1_**. How to modify the default display language to the system language before performing allure open?
**_Q2_**. How to modify some configurations to make allure.step and allure.title display the length of time spent?

**_if allure reports generated by allure serve mode,_**
**_Q3_**. How to modify the specified allure report directory(not allure results dir) if the report is generated using the allure serve method?
currently, the allure report saved user's temp dir. e.g.
C:\Users\BRUUSER~1\AppData\Local\Temp\6883884507827514036\allure-report

**To Reproduce**

**Allure report generation method one**:
1. allure.bat generate
F:\helloc\aircraft\PIPENV_VENV_IN_PROJECT\aircraft-ZN10a0bq\Scripts\allure.bat.lnk generate F:\helloc\aircraft\autotestcase\allure_pytest_results -o F:\helloc\aircraft\autotestcase\allure_pytest_repords

2. allure.bat open
F:\helloc\aircraft\PIPENV_VENV_IN_PROJECT\aircraft-ZN10a0bq\Scripts\allure.bat.lnk open F:\helloc\aircraft\autotestcase\allure_pytest_repords

3. report screenshot
![image](https://user-images.githubusercontent.com/386347/57179394-13fa9700-6eb0-11e9-94c0-d14c789c56e8.png)

**Allure report generation method two**:
1. allure.bat serve
F:\helloc\aircraft\PIPENV_VENV_IN_PROJECT\aircraft-ZN10a0bq\Scripts\allure.bat.lnk serve F:\helloc\aircraft\autotestcase\allure_pytest_results -p 9090

2. report screenshot
![image](https://user-images.githubusercontent.com/386347/57179379-e31a6200-6eaf-11e9-92be-99c8f4bed7dc.png)

**Screenshots**
demo code
![image](https://user-images.githubusercontent.com/386347/57179401-2b398480-6eb0-11e9-866e-b321c2036cd4.png)

**Environment (please complete the following information):**

1. Allure version
![image](https://user-images.githubusercontent.com/386347/57175899-ee579880-6e83-11e9-8079-779fa94d5e8d.png)

2. gradle version
gradle-5.4.1-bin [download](https://downloads.gradle.org/distributions/gradle-5.4.1-bin.zip)

3. jdk version
jdk-12.0.1, [download](https://download.java.net/java/GA/jdk12.0.1/69cfe15208a647278a19ef0990eea691/12/GPL/openjdk-12.0.1_windows-x64_bin.zip)

4. os version
![image](https://user-images.githubusercontent.com/386347/57175906-0fb88480-6e84-11e9-9607-68dd1a74c970.png)

**Comment by baev** [comment]
Closed as stale. Please create a GitHub discussion if the feature is still needed.
