### ISSUE TITLE
Too many rules cause the title to display an exception in the allure report

### ISSUE THREAD

**Issue by zzt-chun** [allure-framework/allure2#950]
**Describe the bug**
Due to business needs, some cases require a lot of parameters, but the titile in allure shows poor reading and understanding.

**To Reproduce**

When I try to display too many parameters, the title is inconvenient to read, not what I want.
![image](https://user-images.githubusercontent.com/44250961/58394139-5741c300-8074-11e9-8fe9-30805d7eb5e6.png)

When I don't give a lot of parameters, the title in the allure report is what I want.
![image](https://user-images.githubusercontent.com/44250961/58394372-74c35c80-8075-11e9-866f-b9a7fcf52e06.png)

**Expected behavior**
What do I need to do to get what I want?

**Screenshots**

**Environment (please complete the following information):**

| Allure version | 2.9.0 |
| --- | --- |
| Test framework | pytest@4.3.0 |
| Allure adaptor | allure-pytest@2.6.1 |
| Generate report using | allure-serve@2.18 |

**Additional context**

**Comment by baev** [comment]
closed as stale
