### ISSUE TITLE
Add posibility to set report language before generating/serving it

### ISSUE THREAD

**Issue by SeleniumTestAB** [allure-framework/allure2#952]
**Is your feature request related to a problem? Please describe.**
As it is now, User must change language after report is generated/served and displayed. This leads to confusion from User because:
a) He/She might not know english (which is by default)
b) He/She might not see option to change the language to desired one
c) He/She might be frustrated because He/She needs to change language everytime when report got generated/served

All above scenarios can lead to problems if team wants to change reporting solution within organization (business Users might find this unattractive and decide to stick with outdated solution).

**Describe the solution you'd like**
Please, add a way to change default language from english to other that is available in your list of languages. For example polish.

**Describe alternatives you've considered**
I am not an expert in JS although i tried to make quick JS script to change the language but it did not work.

**Additional context**

**Comment by gengzongyuan** [comment]
Before the new function goes online, I realized the default language configuration by modifying the JS file. 
change allure2/allure-generator/src/main/javascript/utils/settingsFactory.js globalSettingsDefaults.language setting.
then build jar to replace allure/2.13.3/libexec/allure-generator-2.13.3.jar.

**Comment by baev** [comment]
Since [2.28.0](https://github.com/allure-framework/allure2/releases/tag/2.28.0), there is a new option `--lang` available:

```bash
$ allure generate --lang de path/to/allure-results
```

See https://github.com/allure-framework/allure2/pull/2476
