### ISSUE TITLE
duplicate test cases

### ISSUE THREAD

**Issue by krzprz** [allure-framework/allure2#953]
**Describe the bug**
Sometimes the same test case is listed twice in results.

**To Reproduce**
on the screen shots below there is an example of the same test listed twice. The difference is in parameter list. The problem reproduces if one parameter (I noticed it for Failing Environment and Skipped Environment in my case) has list with more than 1 input.
 
I can see in allure-report that there are 2 json *.*-result files for such test.  One file has empty paramter list and the other is filled. All parameters are filled in the same place and missing contents is connected only with those 2.

**Expected behavior**
test should be shown only once.

**Screenshots**
![image](https://user-images.githubusercontent.com/11803868/59201396-a4588580-8b9a-11e9-9231-a7bc7234dbea.png)

![image](https://user-images.githubusercontent.com/11803868/59201487-d7027e00-8b9a-11e9-8eb6-f15f4d2c5fb2.png)

![image](https://user-images.githubusercontent.com/11803868/59201525-ea154e00-8b9a-11e9-9083-d3f008c2b6f8.png)

**Environment (please complete the following information):**

| Allure version | 2.11.0 |
| --- | --- |
| Test framework | testng@6.9.8|
| Allure adaptor | allure-testng@2.11.0 |

**Additional context**

**Comment by fj11** [comment]
Hi, any update about this issue ?

**Comment by yanbo92** [comment]
any update?

**Comment by Spagliardin** [comment]
Hi, any update or possible solution?, I have this problem in angular

**Comment by baev** [comment]
Usually, the reason is that test parameters aren't specified correctly to Allure. See https://allurereport.org/docs/history-and-retries/ for the details. 

If you struggle to get it done, please create a support request in our [discussions](https://github.com/orgs/allure-framework/discussions)
