### ISSUE TITLE
TRX plugin doesn't parse timestamps correctly

### ISSUE THREAD

**Issue by Euphoric** [allure-framework/allure2#955]
**Describe the bug**
After creating an Allure2 report from a TRX file created through "dotnet test --logger:trx", the report generates, but all timestamps, test case start and end and duration, and whole test suite length are wrong.

**To Reproduce**
1. Grab any *.trx file
2. Generate an allure report from it
3. Open report
4. All times are wrong

**Expected behavior**
Tests have proper start, end and duration. Report has correct length.

**Environment (please complete the following information):**

| Allure version | 2.12.1 |
| --- | --- |
| Test framework | dotnet test with xUnit |
| Allure adaptor | allure-testng@2.12.1 |
| Generate report using | allure@2.12.1 |

**Comment by Euphoric** [comment]
I believe this bug can easily be reproduced by adding assert of time parsed in TRX test. It is only asserting test names and descriptions.

**Comment by baev** [comment]
fixed via #982
