### ISSUE TITLE
Allure keeps obsolete results

### ISSUE THREAD

**Issue by gicoprasico** [allure-framework/allure2#962]
**Describe the bug**
Allure report on Jenkins contains reports of removed or renamed test cases.

**To Reproduce**
1. Create a my.namespace.MyTest test case
2. Run a build in Jenkins + Allure Plugin
3. Check the report. It contains only one test case
4. Rename my.namespace.MyTest test case to my.newNamespace.MyTest
5. Run a build in Jenkins + Allure Plugin
6. Check the report. It contains the report for two test cases: 
- my.namespace.MyTest 
- my.newNamespace.MyTest

**Expected behavior**
Report should contain only test cases involved in build.

**Screenshots**
N/A

**Environment (please complete the following information):**
Windows 10 
| Allure version | 2.11.0 |
| --- | --- |
| Test framework | junit@4.12 |
| Allure adaptor | allure-junit4@2.11.0 |
| Generate report using | allure-maven@2.9 |

**Additional context**
N/A

**Comment by skhomuti** [comment]
Did you forget to clear the workspace?

**Comment by gicoprasico** [comment]
If I clear the workspace, then my history will gone. I would like to preserve the history results, but without test cases that are not in the project.

**Comment by baev** [comment]
> If I clear the workspace, then my history will gone

Nope, history is handled by Allure Jenkins plugin. In order to solve the issue please use Allure Jenkins plugin to generate report (by using Allure Report Publisher step instead of maven goal), then clear workspace before each build

See the docs https://docs.qameta.io/allure/#_jenkins
