### ISSUE TITLE
Add return value to step in report

### ISSUE THREAD

**Issue by amitwer** [allure-framework/allure2#963]
**Is your feature request related to a problem? Please describe.**
When reading the allure report, I sometimes have to debug just to see the value returned from a step. 
Having it printed in the report would be very helpful.

**Describe the solution you'd like**
Either: 
1. provide generic configuration to enable printing return values for all steps (I would be happy with a default=true, but this might cause some backwards compatibility issues)
Or:
2. Add to the step annotation a parameter that will print the return value to the report

**Comment by baev** [comment]
You can use `@Attachent` annotation together with `@Step`:

```java
@Step
@Attachment
String stepWithReturnValue() {
   return "Something"
}
```
