### ISSUE TITLE
"jQuery.Deferred exception" on Categories page, and categories page 404s.

### ISSUE THREAD

**Issue by dbak-invn** [allure-framework/allure2#965]
**Describe the bug**
When I attempt to navigate to the Categories tab, I get the following console warning, and a 404:

app.js:39 jQuery.Deferred exception: Cannot read property 'toLowerCase' of undefined TypeError: Cannot read property 'toLowerCase' of undefined
    at byName (http://10.8.128.72:58573/app.js:60:134376)
    at comparator_compare (http://10.8.128.72:58573/app.js:60:135002)
    at http://10.8.128.72:58573/app.js:60:135248
    at Array.sort (<anonymous>)
    at TreeCollection.value (http://10.8.128.72:58573/app.js:60:120682)
    at http://10.8.128.72:58573/app.js:60:120527
    at Array.map (<anonymous>)
    at TreeCollection.value (http://10.8.128.72:58573/app.js:60:120488)
    at TreeCollection.value (http://10.8.128.72:58573/app.js:60:120278)
    at TreeView.value (http://10.8.128.72:58573/app.js:60:137295) undefined

**To Reproduce**
I navigate to the Categories page and get this error and a 404.

This occurs whether or not I use a custom categories.json.

**Expected behavior**
The categories page should not 404.

**Screenshots**

**Environment (please complete the following information):**

| Allure version | 2.12.1|

Generating report using command line. `allure generate` and `allure open`

**Additional context**

**Comment by dbak-invn** [comment]
I found the issue; it was caused by a junit test case result like the following:

```
      <testcase classname="fake_classname" name="fake_name" time="0.0">
          <failure type="FAIL" >
            fake failure
          </failure>
      </testcase>
```
(this was generated using catch2)

And does not occur if there exists a `message` attribute in the failure tag.

I am not sure if this is invalid json, but it seems to me that categories should not break entirely if there is no message in a falure.

**Comment by baev** [comment]
<img width="1542" alt="Screenshot 2024-02-01 at 18 32 03" src="https://github.com/allure-framework/allure2/assets/2149631/b47fee3e-206e-4bdb-94dd-4f373219558b">

already fixed
