### ISSUE TITLE
Allure jira plugin - where do you enable plugin property? and set Jira Env variables?

### ISSUE THREAD

**Issue by akz786** [allure-framework/allure2#967]
**Pre-check**
- [ ] I'm aware that I can [edit the docs](https://github.com/allure-framework/allure-docs/) and submit a pull request

**Describe the improvement**

I'd like to report
- [x ] Unclear documentation
- [ ] A typo
- [x ] Missing documentation
- [ ] Other

**Description of the improvement / report**

The plugin can be installed easily so thats not an issue.

It is not clear where you need to set the following? 

where do you set the following? i.e. is it in JIRA, Jenkins or our test code?

**enable plugin - add env property ALLURE_JIRA_ENABLED=true**

and the same for below?

**setup Jira env variables:
ALLURE_JIRA_ENDPOINT=https://<jira>/jira/rest/
ALLURE_JIRA_USERNAME=<username>
ALLURE_JIRA_PASSWORD=<password>**

**Comment by ryparker** [comment]
All of those are set as environment variables that can be set in your `bash_profile`. To add environment variables to your bash profile you can open a terminal and type `export ALLURE_JIRA_ENABLED=true`

Here's a detailed tutorial which also explains how to do the same on Windows: https://www.twilio.com/blog/2017/01/how-to-set-environment-variables.html

**Comment by Ragul-Dhandapani** [comment]
Is there any option to provide the JIRA Issue Ticket in Jenkins inplace of mentioned in the "@Issue" tags in code. Hence, Once jenkins job is completed report can be published to JIRA with given ticket/issue ID in Jenkins.

**Comment by Ragul-Dhandapani** [comment]
Is there any option to provide the JIRA Issue Ticket in Jenkins inplace of mentioned in the "@Issue" tags in code. Hence, Once jenkins job is completed report can be published to JIRA with given ticket/issue ID in Jenkins.

**Comment by pkievit86** [comment]
I am using cucumber and I can add @issue=xxxx-4530 to the feature file and this is picked up.

**Comment by pkievit86** [comment]
on top, above Feature
