### ISSUE TITLE
endless allure2 report loading on firefox

### ISSUE THREAD

**Issue by frederic-boissiere** [allure-framework/allure2#968]
**Describe the bug**
When I try to open the index.html from the /target/site/allure-maven-plugin/index.html.
I've got an endless loading widgets on the "overview" page (see attachment.)
When I go to the "behaviours" page, I've got a 404 error page.
I've the same behaviour on IE-11.0.9600.19356 and Chrome-75.0.3770.142.

A few days ago, there was an update of Firefox on my laptop.
My new version is 68.0-Firefox Release-July 9, 2019. I guess the previous version was 67.0.
With the previous version of Firefox, there was no error when I opened the local allure web site from the local files.

Morevover, when I launch the server using `mvn allure:serve`, the report is correctly displayed.

**To Reproduce**
1. compile the maven project generating the allure report
2. Open the index.html file of <my_project>/target/site/allure-maven-plugin/ in firefox
3. See error

**Expected behavior**
I need to open the allure report from the generated files without using a running web server. In order to share it with my customer.

**Screenshots**
![allure_mainpage](https://user-images.githubusercontent.com/35914899/61360272-6841d000-a87e-11e9-87d9-67ce967d0630.png)
![allure_behaviors](https://user-images.githubusercontent.com/35914899/61360283-6d068400-a87e-11e9-95ea-597f29280677.png)
![allure_firefox_error](https://user-images.githubusercontent.com/35914899/61360352-932c2400-a87e-11e9-8efa-b17f5c701456.png)

**Environment (please complete the following information):**

| Allure version | 2.12.1 |
| --- | --- |
| Test framework | junit.jupiter@5.5.0 |
| Allure adaptor | allure-junit5@2.12.1 |
| Generate report using | allure-maven@2.18 |

**Additional context**
Below an extract of my pom.xml
></dependencies>
> ....
>       
>        <dependency>
>            <groupId>io.qameta.allure</groupId>
>           <artifactId>allure-junit5</artifactId>
>          <version>2.12.1</version>
>        </dependency>
> ...
> </dependencies>
>
>
>        <plugins>
>             
>             <plugin>
>                 <groupId>io.qameta.allure</groupId>
>                 <artifactId>allure-maven</artifactId>
>                 <version>2.10.0</version>
>                 <executions>
>                     <execution>
>                         <id>allure-site</id>
>                         <phase>verify</phase>
>                         <goals>
>                             <goal>report</goal>
>                         </goals>
>                     </execution>
>                 </executions>
>             </plugin>
>             <plugin>
>                 <groupId>org.springframework.boot</groupId>
>                 <artifactId>spring-boot-maven-plugin</artifactId>
>             </plugin>
>             <plugin>
>                 <groupId>org.apache.maven.plugins</groupId>
>                 <artifactId>maven-surefire-plugin</artifactId>
>                 <version>${maven-surefire-plugin.version}</version>
>                 <configuration>
>                     <properties>
>                         <property>
>                             <name>listener</name>
>                             <value>io.qameta.allure.junit5.AllureJunit5</value>
>                         </property>
>                     </properties>
>                     <includes>
>                         <include>**/*Test*.java</include>
>                     </includes>
>                     <systemProperties>
>                         <property>
>                             <name>allure.results.directory</name>
>                             <value>${project.basedir}/target/allure-results</value>
>                         </property>
>                         <property>
>                             <name>junit.jupiter.extensions.autodetection.enabled</name>
>                             <value>true</value>
>                         </property>
>                     </systemProperties>
>                     <reportFormat>plain</reportFormat>
>                 </configuration>
>           
> </plugin>

I also try to start chrome using this procedure, without success : 
> When opening the report from the local file, either open it in Firefox or launch Chrome with the >--allow-file-access-from-files flag. For other browsers, you need to enable cross-origin requests >to local files.

Thank you in advance.
Regards.

**Comment by e-avtonov** [comment]
@frederic-boissiere this can help with report opening in firefox 68:
https://stackoverflow.com/questions/56999411/firefox-68-local-files-now-treated-as-cross-origin-is-there-a-way-to-override

**Comment by frederic-boissiere** [comment]
@e-avtonov : Thank you for your fast answer ! Is it a workaround ? Could you update your implementation in order to fix it ?

**Comment by Arean82** [comment]
I generated the allure report as html , and ran in chrome after disabling security parameters temporarily
To generate Allure report as html, I used the command as per the format:
allure generate allure-results  allure-report-html

After this I created a batch file (windows) and placed it inside the report folder. To run the report I simply executed the batch file and the report opened in chrome.

the details of my batch file is below

`
TASKKILL /F /IM chrome.exe
set "Command="
SET mypath=%~dp0
echo %mypath:~0,-1%
for /f "tokens=2,*" %%A in ('reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome\shell\open\command" /ve 2^>nul') do set "Command=%%~B"
if not defined Command for /f "tokens=2,*" %%A in ('reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Clients\StartMenuInternet\Google Chrome\shell\open\command" /ve 2^>nul') do set "Command=%%~B"
if not defined Command echo Google Chrome was not found.
if defined Command start "Browser" "%Command%"  --allow-file-access-from-files --disable-web-security "%mypath:~0,-1%/index.html"
`


Hope this helps

**Comment by Arean82** [comment]
I generated the allure report as html , and ran in chrome after disabling security parameters temporarily To generate Allure report as html, I used the command as per the format: allure generate allure-results allure-report-html

After this I created a batch file (windows) and placed it inside the report folder. To run the report I simply executed the batch file and the report opened in chrome.

I used chrome v79 Also to run the report in firefox You can leverage this restriction by going to about:config url and then uncheck privacy.file_unique_origin boolean value.

However be aware that this only reverts to < 68 protection > mode I have shared my batch file .
`TASKKILL /F /IM chrome.exe
set "Command="
SET mypath=%~dp0
echo %mypath:~0,-1%
for /f "tokens=2,*" %%A in ('reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome\shell\open\command" /ve 2^>nul') do set "Command=%%~B"
if not defined Command for /f "tokens=2,*" %%A in ('reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Clients\StartMenuInternet\Google Chrome\shell\open\command" /ve 2^>nul') do set "Command=%%~B"
if not defined Command echo Google Chrome was not found.
'if defined Command start "Browser" "%Command%"  --allow-file-access-from-files --disable-web-security "%mypath:~0,-1%/index.html"`

**Comment by tavisca-pnayama** [comment]
When will this fix be available ?

**Comment by ruaeuk2** [comment]
> @frederic-boissiere this can help with report opening in firefox 68:
> https://stackoverflow.com/questions/56999411/firefox-68-local-files-now-treated-as-cross-origin-is-there-a-way-to-override

Big thanks, this reason help me!

**Comment by Bhargav704** [comment]
> > @frederic-boissiere this can help with report opening in firefox 68:
> > https://stackoverflow.com/questions/56999411/firefox-68-local-files-now-treated-as-cross-origin-is-there-a-way-to-override
> 
> Big thanks, this solution help me!



> @frederic-boissiere this can help with report opening in firefox 68:
> https://stackoverflow.com/questions/56999411/firefox-68-local-files-now-treated-as-cross-origin-is-there-a-way-to-override

Thanks it helps !!!

**Comment by nprasankumar** [comment]
All the link provided here as part of solutions seem to be temporary work around.  Disabling security in chrome or Firefox seems to be not a good. May I know if there is a plan to fix it?

**Comment by CraigRichards** [comment]
> All the links provided here as part of solutions seem to be temporary work around. Disabling security in chrome or Firefox seems to be not a good. May I know if there is a plan to fix it?

Unless I’m mistaken, your asking the Allure team to remove the CORS security feature from browsers. There is no fix other than work around. 

Browsers are just more secure than they used to be. 

I’m my teams everyone has a local IIS folder pointed to their generated report. A test execution will they update the report on TearDown.

**Comment by nprasankumar** [comment]
Junit5 reports produce static html reports and they are opening in chrome.  I was expecting similar behavior.

**Comment by baev** [comment]
there are only few options (at least that I know) to make it possible: 

1) embed everything into single html file. That will make reports unusable pretty much for everyone who has more than 1000 tests in run. So that could be an option but as opt-in feature
2) use JSONP files instead of JSON. We have in plan to add such support but it requires some deep code changes and only planned for Allure 3 as low priority feature.

for now, you only need such feature for local reports, so you have a few options:

1) use `allure` command line tool. It provides `allure open` and `allure serve` commands to open/serve reports 
2) for IDEA users there are `open in browser` feature (you can find it in context menu of html files) that will start web server for you

**Comment by Yuri-GG** [comment]
Is there any solution to see repot in Chrome by open index.html? I created report by running `allure generate` and disabled security in Chrome settings. But still has same issue.
![image](https://github.com/allure-framework/allure2/assets/51373885/7d95c2a2-afcd-4e93-906c-5fc9bfd99e18)
![image](https://github.com/allure-framework/allure2/assets/51373885/c22b629e-c4d9-4504-982b-470142c43934)
