### ISSUE TITLE
Troubles with build allure2 via Gradle (fix xctest screenshots)

### ISSUE THREAD

**Issue by slacklab** [allure-framework/allure2#981]
I try to apply fix xctest screenshoots from pull requests. 

And then do from root directory of a project 
./gradlew 
./gradlew build 

And get some errors: 
`/Users/i.sorokoletov/ios/allure2/allure-generator/src/main/java/io/qameta/allure/history/HistoryTrendItem.java:25: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlElement;
                                ^
warning: unknown enum constant XmlAccessType.FIELD
  reason: class file for javax.xml.bind.annotation.XmlAccessType not found
warning: unknown enum constant XmlAccessType.FIELD
warning: unknown enum constant XmlAccessType.FIELD
warning: unknown enum constant XmlAccessType.FIELD
warning: unknown enum constant XmlAccessType.FIELD
warning: unknown enum constant XmlAccessType.FIELD
warning: unknown enum constant XmlAccessType.FIELD
/Users/i.sorokoletov/ios/allure2/allure-generator/src/main/java/io/qameta/allure/history/HistoryTrendItem.java:38: error: cannot find symbol
    @XmlElement(required = true)
     ^
  symbol:   class XmlElement
  location: class HistoryTrendItem
/Users/i.sorokoletov/ios/allure2/allure-generator/src/main/java/io/qameta/allure/history/HistoryTrendItem.java:40: error: cannot find symbol
    @XmlElement(required = true, type = Long.class, nillable = true)
     ^
  symbol:   class XmlElement
  location: class HistoryTrendItem
/Users/i.sorokoletov/ios/allure2/allure-generator/src/main/java/io/qameta/allure/history/HistoryTrendItem.java:42: error: cannot find symbol
    @XmlElement(required = true)
     ^
  symbol:   class XmlElement
  location: class HistoryTrendItem
/Users/i.sorokoletov/ios/allure2/allure-generator/src/main/java/io/qameta/allure/history/HistoryTrendItem.java:44: error: cannot find symbol
    @XmlElement(required = true)
     ^
  symbol:   class XmlElement
  location: class HistoryTrendItem
5 errors
21 warnings`

`
./gradlew --v
Gradle 5.2.1
Build time:   2019-02-08 19:00:10 UTC
Revision:     f02764e074c32ee8851a4e1877dd1fea8ffb7183

Kotlin DSL:   1.1.3
Kotlin:       1.3.20
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          12.0.2 (AdoptOpenJDK 12.0.2+10)
OS:           Mac OS X 10.14.5 x86_64
`
How I can fix this problem and build allure2 ? 
Thanks for reply

**Comment by slacklab** [comment]
Solved: could rebuild project with java: 8.0.222.j9-adpt (over sdkman)

**Comment by baev** [comment]
currently you only can build the project using jdk 8

BTW the fix is released in 2.13.0
