### ISSUE TITLE
[iOS] Xctest: How set feature or story to test?

### ISSUE THREAD

**Issue by shynkevich-alex** [allure-framework/allure2#988]

**Comment by slacklab** [comment]
I can't find any info about this too. 
Suppose that all functionality contains at https://github.com/allure-framework/allure2/tree/56fce7a55aa0c7f28eec0904908e900dfffdc462/plugins/xctest-plugin/src/main/java/io/qameta/allure/xctest sources

And you can use

`XCTContext.runActivity(named: "Given: App launch") { _ in
            app.launch()
        }`
Please, share your contacts in profile. I want ask you for some questions about allure too.

**Comment by shynkevich-alex** [comment]
@slacklab thx, will try use it.
