### ISSUE TITLE
Allure Report is NaN% (ALLURE REPORT UNKNOWN Error) with nightwatch

### ISSUE THREAD

**Issue by sagg155** [allure-framework/allure2#994]
Issue
Context: - 
nightwatch npm version - 0.9.21
allure-commandline npm version -  2.9.0

Using the cmd **allure generate reports -c -o allure-reports** to generate allure reports but the report generated is as attached.
## Screen shot of Generated Report :-
![image](https://user-images.githubusercontent.com/12156593/63694360-e4431680-c833-11e9-8764-55e2eb0067fd.png)

**Comment by hendryang** [comment]
Assume ur XML results are stored here : **.../results/**
you can try this : `allure generate -c -o allure-reports results/* `

**Comment by Dhianesh19** [comment]
same error only shown

**Comment by Dhianesh19** [comment]
i am facing an issue while i am generate a allure report via jenkins and jenkins running in ubuntu server can anyone have a solution to solve the issue
![image (5)](https://github.com/allure-framework/allure2/assets/142984304/69a6cc9e-dadf-409d-9aa7-7098159b1073)
