### ISSUE TITLE
allure-results does not exists

### ISSUE THREAD

**Issue by arun05uvce** [allure-framework/allure2#998]
Results are not capturing and somehow its skipping the step. Even the folder allure-results is not created in the workspace.  But we have test results which are captured in .xml.

Below is the configuration screen: we have allure-commandline-2.12.0 installed in Jenkins server.

![image](https://user-images.githubusercontent.com/54798587/64104825-50160980-cd75-11e9-907d-145b468ddd6d.png)

**Console output:**
[Tosca_Publish_Results_E2E] $ D:\Programs\Allure\allure-commandline-2.12.0\bin\allure.bat generate -c -o D:\Programs\Jenkins\workspace\Tosca_Publish_Results_E2E\target\allure-report
**allure-results does not exists**
Report successfully generated to D:\Programs\Jenkins\workspace\Tosca_Publish_Results_E2E\target\allure-report
Allure report was successfully generated.
Creating artifact for the build.

**result_junit.xml generated as below:**
![image](https://user-images.githubusercontent.com/54798587/64105972-86548880-cd77-11e9-8735-aa02edc3ced9.png)

Could you please help to find why the results are not captured ?

Report :
![image](https://user-images.githubusercontent.com/54798587/64105809-34136780-cd77-11e9-9fd4-12320c3b3b5e.png)

**Comment by fescobar** [comment]
@arun05uvce your project should create the allure results files in the workspace. The plugin only read the results from the directories specified. Can you share your structure files in your Jenkins workspace?? what technology/adaptor/framework are you using?

**Comment by baev** [comment]
closed due to no response
